pkg/shipper/gcp.go
pkg/shipper/shipper_test.go
pkg/testutil/prometheus.go

Added shipper test that validates if shipper supports tsdb snapshots.

---

.gitignore
cmd/promlts/sidecar.go
kube/README.md
kube/envs.sh
kube/manifests/local/config.yaml
kube/manifests/local/deployment.yaml
kube/manifests/local/service.yaml
kube/run-local.sh

- Scripts to run minikube and use local cluster
- K8s manifest to deploy Prometheus scraping kubernetes itself.

 Added basics for promlts test setup on kubernetes.

---

README.md

Added build & go report badges.

---

cmd/promlts/main.go
cmd/promlts/query.go
cmd/promlts/sidecar.go
cmd/promlts/store.go

Just some cleanup to not use the global metric registry.

main: remove global metric registry

---

Gopkg.lock
Gopkg.toml
cmd/promlts/sidecar.go
cmd/promlts/sidecar_test.go
pkg/store/promproxy.go
pkg/store/promproxy_test.go
pkg/testutil/prometheus.go

Handle external labels from Prometheus server

---

Gopkg.lock
cmd/promlts/example.go
cmd/promlts/main.go
cmd/promlts/query.go
cmd/promlts/sidecar.go
cmd/promlts/store.go
pkg/okgroup/group.go
pkg/okgroup/group_test.go

Additionally rewrote flags to URL type when they need URL (:

Add all-in example command running 3 services in the same binary.

---

Makefile
cmd/thanos/example.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/sidecar.go
pkg/cluster/cluster.go
pkg/cluster/stores.go
pkg/query/querier.go
pkg/query/ui/ui.go
pkg/runutil/runutil.go
scripts/quickstart.sh
test/e2e/query_test.go

Had a bit of trouble deciding where which code should live. Ultimately decided to move `StoreSet` to `pkg/cluster`. It barely has anything cluster specific yet, but I expect this to change down the line.

cluster: back store set by cluster peer information

---

pkg/query/fanin.go
pkg/query/fanin_test.go
pkg/query/querier.go

Partially fills https://github.com/improbable-eng/thanos/issues/6

Implemented LabelValues.

---

Gopkg.lock
pkg/shipper/shipper.go
pkg/testutil/prometheus.go

@Bplotka 
Let's see if tests pass now without the sleep :) They do locally.

Fix wrong import, update deps

---

Dockerfile
Makefile

Added Thanos dockerfile.

---

Gopkg.lock
Gopkg.toml
cmd/thanos/example.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/shipper/gcp.go
pkg/store/gcs.go
pkg/store/gcs_test.go
scripts/quickstart.sh

@Bplotka 
The downloading of index files is working. The chunk reader is not yet implemented and tests are missing. But a first review round can't hurt.

Basic implementation of GCS store

---

cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

Added initial, optional DNS resolution for cluster peers.

---

cmd/thanos/example.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/cluster/advertise.go
pkg/cluster/cluster.go
test/e2e/spinup_test.go

Moved Joining Cluster into register functions and after label fetch inside sidecar.

---

pkg/cluster/cluster.go

cluster: deduce IP for API address.

---

Gopkg.lock
cmd/thanos/store.go
pkg/store/gcs.go
pkg/store/gcs_test.go
pkg/testutil/prometheus.go

Reverts improbable-eng/thanos#48

Revert "Fixes and e2e test for GCS store, fake block generator"

---

pkg/shipper/shipper.go
pkg/shipper/shipper_test.go

shipper: properly handle hard linking of block files

---

pkg/shipper/shipper.go

shipper: silence warning for temp dirs

---

Gopkg.lock
pkg/cluster/stores.go
pkg/query/fanin.go
pkg/query/promadapter.go
pkg/query/querier.go
pkg/query/querier_test.go
pkg/store/gcs.go
pkg/store/storepb/custom.go

Spotted a little bug. Figured I'd add some basics for testing and make the StoreInfo interface a bit convenience while I'm at it.
@Bplotka

Fix Querier LabelValues

---

pkg/query/fanin.go
pkg/store/gcs.go
pkg/store/gcs_test.go

Graceful shutdown and block filtering for store node

---

pkg/query/fanin.go

This only fixes the panic. I am pretty sure this is not expected to get zero lenght chunk from store `Series()` grpc method, so this should be an error.. Not sure what description for this error should be, though. Maybe just emptySet instead?

Zero chunks for chunkSeries should not raise panic.

---

pkg/store/gcs.go
pkg/store/gcs_test.go

Fixed issue with external label matchers inside store.

---

Gopkg.lock
pkg/query/api/v1.go
pkg/query/api/v1_test.go

query: compress response and encode streaming

---

cmd/thanos/query.go
pkg/query/api/v1.go
pkg/query/api/v1_test.go

Added latency metrics to query/query range on top of PromQL.

---

pkg/shipper/gcp.go
pkg/store/gcs.go

Added GCS operations metrics. Fixed not registered shipper metrics.

---

Makefile
cmd/thanos/rule.go
pkg/alert/alert.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

Discover Alertmanagers and send alert notifications

---

Gopkg.lock
cmd/thanos/example.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/cluster/stores.go
pkg/query/api/v1.go
pkg/query/api/v1_test.go
pkg/query/querier.go
pkg/query/querier_test.go
pkg/store/gcs.go
pkg/store/prometheus.go
pkg/tracing/context.go
pkg/tracing/gct.go
pkg/tracing/grpc.go
pkg/tracing/http.go
pkg/tracing/tracer.go

Added Tracing to thanos, backed up with Opentracing API + Google Cloud Tracing.

---

cmd/thanos/main.go
pkg/tracing/gct.go
pkg/tracing/tracer.go

Added optional debug name to tracing.

---

cmd/thanos/rule.go

Exposed TSDB block options for ruler.

---

pkg/query/querier.go

Made sure single error in query -> storeAPI communication does not fail whole request.

---

cmd/thanos/store.go
test/e2e/spinup_test.go

Added recovery interceptor for store gRPC requests.

---

Gopkg.lock
cmd/thanos/compact.go
cmd/thanos/main.go
pkg/compact/compact.go
pkg/compact/compact_test.go
pkg/objstore/gcs/gcs.go
pkg/store/bucket.go
test/e2e/query_test.go
test/e2e/rule_test.go

@Bplotka for a first review of the code. Will remove some excessive debug logging and add tests next.
It's currently running in a test bucket. It's not very fast due to being single-threaded. But that can easily be changed once we have confidence in it.

Add compactor command

---

cmd/thanos/main.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

Added recovery for all gRPC servers we have.

---

pkg/store/matchers.go

store: anchor regexp label matchers

---

pkg/store/bucket.go

Fixed one typo.

---

pkg/query/querier.go

Fixed typo for disabling deduplication.

---

README.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md

Those are obviously not fully complete, but describe the basic purpose and at least basic caveats for safe deployment.

Add component docs

---

cmd/thanos/rule.go
pkg/query/querier_test.go

Added default dedup param to ruler, added one test case to dedup.

---

cmd/thanos/rule.go

Added external labels to ruler shipper.

---

pkg/query/iter.go
pkg/query/querier_test.go

@Bplotka 
Not the fix for the original investigation, but this should make the deduping (if applied :)) more resilient.

query: improve deduplication and tests

---

cmd/thanos/store.go
pkg/store/bucket.go
pkg/store/cache.go

store: use simple LRU cache, add metrics, evict on size

---

README.md

Maybe we can lure some people into doing this with a pointer.

readme: add note about contributing backends

---

pkg/store/cache.go

I forgot adding of the size yesterday.
This also initialises both eviction series since it can take quite a while for the first eviction to occur and it can be a bit confusing for the series to not show up at all until then.

store: add missing increment of cache size metric

---

pkg/store/prometheus.go

Removed some things that are no longer needed and added a separate trace for re-encoding and responding the data.

store: add response trace, small fixes

---

test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

Improved e2e tests to avoid flaky builds.

---

Gopkg.lock
Gopkg.toml
cmd/thanos/compact.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/objstore/objstore.go
pkg/objstore/s3/s3.go
scripts/quickstart.sh

:wave: 
Using the minio-go client, implement the wonderful objstore.Bucket
interface.
This was relatively easy, and it appears to work fairly well. I'm
a touch uncertain about the work in GetRange, as the APIs with
gcs didn't quite map as well in that case.
Adding to my fear, I saw seemingly 100% failures of `store` `get_range,get` operations.
Although there were no logs, and everything seemed to work alright.
```
thanos_objstore_bucket_operation_failures_total{bucket="thanos",instance="localhost:19791",job="thanos-store",operation="get_range",prometheus="prom-1"} 50
thanos_objstore_bucket_operation_failures_total{bucket="thanos",instance="localhost:19791",job="thanos-store",operation="get_range",prometheus="prom-1"} | 183
~~~~
thanos_objstore_bucket_operations_total{bucket="thanos",instan …
```

objstore: implement s3 support

---

pkg/compact/compact_test.go

Tested compact min max deduction with mixed order of blocks.

---

pkg/compact/downsample/downsample.go
pkg/compact/downsample/downsample_test.go

downsample: handle staleness markers, add average chunk iterator

---

docs/getting_started.md

@Bplotka I thought a link to gotools repo would be beneficial too #203

Docs: link to gotools

---

Gopkg.lock
Gopkg.toml

Finally merged the pinned branch into upstream master.

vendor: repin prometheus/prometheus to master

---

docs/getting_started.md
kube/README.md

Addressed unresolved comments from https://github.com/improbable-eng/thanos/pull/196

docs: Some minor fixed in getting started docs.

---

cmd/thanos/query.go
pkg/store/proxy.go
pkg/store/proxy_test.go

A little useful generalisation.

store: get fanout stores with context

---

.circleci/config.yml
README.md

Added CircleCI for our CI build. It has additional options for building forked PRs with or without secrets. And it's way faster! 
Let me know what do you think @fabxc 
Also @GavinElder you wanted to see benefits of it (:
BTW: Yup - flakes happen as well ;p but maybe not so often.

CI: Added CircleCI config file.

---

Gopkg.lock

deps: Moved to the new dep format.

---

pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/compact/compact_test.go
pkg/compact/downsample/downsample_test.go
pkg/query/querier_test.go
pkg/shipper/shipper_test.go
pkg/store/bucket_test.go
pkg/store/prometheus_test.go
pkg/store/proxy_test.go
pkg/testutil/objstore.go
pkg/tracing/tracing_test.go

*: Added leaktest to all unit tests and fixed all found leaks

---

pkg/query/querier.go
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

query: Fixed wrong deduplication switch. Added tests.

---

.circleci/config.yml
Makefile

@Bplotka following from #228 I've made the changes to do a docker build and push for CircleCi.
Note, the "${DOCKER_USERNAME}" and "${DOCKER_PASSWORD}" environment variables need to be set for the config.yml
Successful build can be see here https://circleci.com/gh/monitoring-monkey/thanos/5 (the push image step failed because of the above).

Added docker image build and push

---

cmd/thanos/sidecar.go
pkg/reloader/reloader.go
pkg/reloader/reloader_test.go
pkg/runutil/runutil.go

reloader: Fixed reloader and added unit tests.

---

cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/data.go
pkg/cluster/delegate.go

This fixes reloader deadlock.
Depends on https://github.com/improbable-eng/thanos/pull/243

cluster+query: Refactored cluster package and put joins in run.Groups for commands.

---

Gopkg.lock
pkg/reloader/reloader.go

Thanks to https://github.com/go-fsnotify/fsnotify/issues/1

vendor: change fsnotify import path

---

cmd/thanos/compact.go
pkg/compact/compact.go
pkg/compact/compact_test.go

compactor: Fixed verifyIndex bug, comments and compact unit test.

---

cmd/thanos/bucket.go
cmd/thanos/downsample.go
pkg/compact/compact.go
pkg/compact/compact_test.go
pkg/shipper/shipper.go

Fixes my issue for https://github.com/improbable-eng/thanos/issues/246
We need that until potential TSDB feature request https://github.com/prometheus/tsdb/issues/309

compact: Added support for empty blocks.

---

pkg/compact/compact.go
pkg/store/proxy.go

compact+query: Added additional details to fetch series log and compact metrics

---

pkg/compact/compact_test.go

compact_test: Fixed broken compact test.

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/objstore/s3/s3.go

I wanted to use these to verify buckets to see why
my compaction was potentially failing, so I added
the s3 bits. Had to refactor a little bit but it
seemed fine.

Add s3 flags to bucket cmds

---

Gopkg.lock
Gopkg.toml

Wanted to push new dep format in separate PR (to the TSDB vendor update) but deps does not change anything when toml/lock is same. (:

deps: Upgraded to the newest TSDB + new dep format.

---

cmd/thanos/bucket.go

bucket: Fix output flag typo

---

cmd/thanos/bucket.go
pkg/block/block.go
pkg/objstore/client/factory.go
pkg/verifier/duplicated_compaction.go
pkg/verifier/index_issue_2_1_0.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/safe_delete.go
pkg/verifier/verify.go

verify: Added safe delete.

---

pkg/query/api/v1.go

Do not call querier.Select with nil arg

---

pkg/query/ui/ui.go

Fixes version info displaying in the webui

---

cmd/thanos/downsample.go
pkg/block/index.go

Fixes https://github.com/improbable-eng/thanos/issues/302

compact: Close OpenBlock properly.

---

pkg/store/bucket.go

store: With initial sync, no newBucketStore cache sync is needed.

---

pkg/query/api/v1.go

See this issue for reference : https://github.com/improbable-eng/thanos/issues/320

Omitting empty warnings in json responses

---

.circleci/config.yml
Makefile

make+CI: Fixed CI to actually test proper (local) image.

---

CHANGELOG.md
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go

Review and discussion here: https://github.com/improbable-eng/thanos/pull/350 (I merged accidently to the wrong branch)

store: Added debug log lines for block downsampling resolutions used for query.

---

.circleci/config.yml

CI: Fix for ext contributors.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/getting_started.md

templates: Added github templates for Issues and PRs as well as contributing guide.

---

Makefile
docs/storage.md
pkg/objstore/gcs/gcs.go
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/s3/s3.go

Fixes: https://github.com/improbable-eng/thanos/issues/290

store: Improved s3 range bug, other compatibility issues and tests.

---

cmd/thanos/main.go

Setup's `github.com/armon/go-metrics` Prometheus sink, so that we can expose metrics provided by `https://github.com/hashicorp/memberlist`
Right now I have to use global default registrer due to `go-metrics` not allowing to configure it. But I did a PR to fix it, which hopefully will get apporved: https://github.com/armon/go-metrics/pull/79
I've tested it looking at `/metrics` on thanos query and it adds following metrics:
```
query_memberlist_gossip{quantile="0.5"} 0.006785000208765268
query_memberlist_gossip{quantile="0.9"} 0.006837000139057636
query_memberlist_gossip{quantile="0.99"} 0.006837000139057636
query_memberlist_gossip_sum 0.36968300119042397
query_memberlist_gossip_count 53
query_memberlist_probeNode{quantile="0.5"} 0.6564480066299438 …
```

Add memberlist metrics to all components

---

docs/getting_started.md

Update so that its more explicit about adding cluster flags ... hopefully this means people can follow thru from the getting started, add cluster, expose store then add query.

docs: updating getting started

---

.circleci/config.yml
Makefile

Add CircleCI tag-triggered release publisher.
* Add tag latest make target.
* Add tarball publisher.
We'll have to activate a release to test this.

Add release publish

---

docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md

docs: Updated component flags.

---

.circleci/config.yml
Makefile

ci: Added missing github-release binary.

---

.circleci/config.yml
Gopkg.lock
cmd/thanos/bucket.go

Nil is handled everywhere and means that all blocks should be checked.

verify: Fixed case when id Matcher is not specified.

---

.circleci/config.yml
Gopkg.lock
Gopkg.toml

ci: Fixed CI

---

CONTRIBUTING.md

Add steps to build thanos project from source code.
- Tested in a new go enviroment
- [similar information](https://github.com/prometheus/prometheus#building-from-source) for prometheus project

Add steps to build Thanos project for contributors

---

pkg/cluster/cluster.go

Will help with https://github.com/improbable-eng/thanos/issues/426

cluster: Log error properly for failed refresh.

---

docs/components/sidecar.md

Updates duration options docs based on https://github.com/improbable-eng/thanos/pull/122#discussion_r197560509

sidecar: Update description of the duration options

---

docs/design.md

Typos and trailing newline

---

cmd/thanos/sidecar.go
docs/components/sidecar.md
pkg/reloader/reloader.go
pkg/reloader/reloader_test.go

reloader: Added support for multiple rule dirs.

---

docs/components/rule.md

docs: Typo

---

.gitignore
benchmark/Gopkg.lock
benchmark/Makefile
benchmark/cmd/thanosbench/resources.go

changes to make files to allow them to run correctly.
Builds locally when running make.

Updating Benchmark due to running make files

---

.circleci/config.yml

Make sure our CI builds catches missing imports.

---

docs/getting_started.md

Updates the `getting_started.md` to make it a little clearer in some places. 
You read it a few times and if it makes sense then it has worked ;)

Update getting_started.md Document

---

.circleci/config.yml

ci: Fixing cross build part2.

---

cmd/thanos/main.go
pkg/testutil/prometheus.go
pkg/tracing/gct.go
pkg/tracing/tracing.go

Fixes https://github.com/improbable-eng/thanos/issues/534

Fixed thanos rule tracing causing panic.

---

Makefile

Fixes https://github.com/improbable-eng/thanos/issues/519
PTAL @ebastos

make: Avoid doing errcheck as this is not necessary to build the code properly.

---

test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

e2e: Refactored e2e for more flexible tests.

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/flags.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
docs/components/bucket.md
docs/components/compact.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
pkg/objstore/client/factory.go
pkg/objstore/client/factory_test.go

Fixes https://github.com/improbable-eng/thanos/issues/539

objstore: Added support for passing YAML content through the flag.

---

Makefile
cmd/thanos/store.go
docs/components/store.md
pkg/objstore/objstore.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/s3/s3.go
pkg/query/storeset.go
pkg/store/bucket.go
pkg/store/proxy.go
pkg/testutil/prometheus.go
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go
test/e2e/store_gateway_test.go

* Added minio to test deps
* Added flag for store e2e to adjust sync interval
* Fixed s3 test config creation from env
* Added debug log for querier query
* Added thanos store gateway e2e
local make test + CI

Added store gateway e2e test.

---

test/e2e/spinup_test.go

Use ctx to close sub process properly, before test to be exited.
Fixes: #561 
@bwplotka

tests: add ctx to the minio spinup command

---

CHANGELOG.md

Summed up the changes made in the past 5 PRs to the changelog.

[file-sd-part-6] File SD to the changelog

---

cmd/thanos/compact.go

On an overloaded scrapers the amount of samples is enormous. Block size
on the 3d compaction level could be more than 30G, hence the next compaction
takes a big effort to download, compact and upload of hundreds Gb (hundreds of billions samples).
This could be essential at least for the undergoing development.
```
--debug.max-compaction-level=4  Maximum compaction level of presets, max is 4: 0=1h, 1=2h, 2=8h, 3=48h, 4=336h
```

compaction: add ability to set max compaction level

---

Gopkg.lock
Gopkg.toml

TODO for @sudhi-vm: Update this version maybe to something newer if needed?

swift: Unblocked make deps to make sure dep constraint points to correct repo.

---

CHANGELOG.md
docs/thanos_service_discovery.md

Documenting the changes in https://github.com/improbable-eng/thanos/pull/575

Documented DNS SD and added to the changelog

---

Gopkg.lock
Gopkg.toml
pkg/objstore/azure/azure.go
pkg/objstore/azure/helpers.go

* Upgrading to new azure-storage-blob-go version.
* Small changes in library functions

Migrate to new azure-storage-blob-go version

---

cmd/thanos/rule.go

Added a gauge vec to track loaded rules partitioned by group and file
Results on initial load 
```
thanos_rule_loaded_rules{file="/var/thanos/rules/etcd.conf",group="etcd"} 7
thanos_rule_loaded_rules{file="/var/thanos/rules/kafka.conf",group="kafka"} 3
thanos_rule_loaded_rules{file="/var/thanos/rules/ops.conf",group="ops"} 12
thanos_rule_loaded_rules{file="/var/thanos/rules/telco.conf",group="telco"} 70
thanos_rule_loaded_rules{file="/var/thanos/rules/thanos.conf",group="thanos"} 12
```
And after adding a new rule to the thanos group/file and hitting the reload endpoint
```
thanos_rule_loaded_rules{file="/var/thanos/rules/etcd.conf",group="etcd"} 7
thanos_rule_loaded_rules{file="/var/thanos/rules/kafka.conf",group="kafka"} 3
thanos_rule_loaded_rules{file="/var/thanos/rules/ops.conf",group= …
```

adds gauge vec for loaded rules

---

cmd/thanos/main.go
docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md

Added json log format so logs can be easily consumed by services like Elastic Stack.

.*: Add log format to the cli flags

---

benchmark/cmd/querier/main.go
benchmark/cmd/thanosbench/latency.go
benchmark/cmd/thanosbench/resources.go

PromQuerier now takes in a number of new arguments allowing for example to pass in basic auth if your prom is behind an auth system. 
Will now run multiple threads and pick randomly from the queries supplied.
Now run as either command line tool or as a server via flags.
- have ran against our internal systems

Update prom querier to be more generic

---

cmd/thanos/compact.go

Bugfix - thanos_compactor_retries_total was not registered
Built locally

compact: registering thanos_compactor_retries_total

---

Gopkg.lock
cmd/thanos/flags.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go

Added flag to disable gossip explicitly.

---

cmd/thanos/query.go
cmd/thanos/rule.go
pkg/discovery/dns/provider.go
pkg/discovery/dns/provider_test.go
pkg/discovery/dns/resolver.go
pkg/discovery/dns/resolver_test.go
pkg/extprom/extprom.go
pkg/extprom/extprom_test.go

dns: Fixed SRV lookup with different ports and metric consistency.

---

MAINTAINERS.md
docs/release_process.md
docs/storage.md

docs: Fixed pushing tag section for release process.

---

CHANGELOG.md
cmd/thanos/rule.go
docs/components/rule.md
docs/getting_started.md
docs/service_discovery.md
pkg/alert/alert.go
pkg/alert/alert_test.go

ruler: Handle multiple alertmanagers the same as Prometheus does.

---

cmd/thanos/query.go
pkg/query/storeset.go
pkg/store/proxy.go
pkg/ui/bindata.go
pkg/ui/query.go
pkg/ui/templates/query_menu.html
pkg/ui/templates/stores.html

Signed-off-by: Adrien Fillon <adrien.fillon@cdiscount.com>
* Pass the `query.StoreSet` to the UI
* Create a `storeStatuses` to track the status of stores
* New Web Page `Stores`
* Typo fix

query: add Stores UI page

---

docs/storage.md
pkg/objstore/client/factory.go
pkg/objstore/s3/s3.go
pkg/objstore/s3/s3_test.go

Fixes https://github.com/improbable-eng/thanos/issues/674

s3: Added more logs for config validates and explained edge case in doc.

---

.circleci/config.yml
CONTRIBUTING.md
Gopkg.lock
Gopkg.toml
Makefile
cmd/thanos/store.go
docs/components/store.md
docs/storage.md
pkg/objstore/client/factory.go
pkg/objstore/cos/cos.go
pkg/objstore/objtesting/foreach.go
scripts/bucketcfggen/main.go

The Tencent Cloud is a public cloud service provider in China.  [Tencent Cloud](https://intl.cloud.tencent.com/introduction). It provide the Object Storage named COS. 
Because our service integrates Tencent’s infrastructure, we want to back up our monitoring data in COS. This PR will implement the object store client for COS. Now it has been testing in our k8s cluster since two days ago, it seems to be ok now.
I would love to become the maintainer for the COS provider and keep development for Thanos.
I will update the documents later.

Object Storage: Support tencent cloud COS provider

---

docs/storage.md

Fix a few misspellings of "interface".

docs: fix typos in storage.md

---

Makefile
benchmark/cmd/thanosbench/resources.go
docs/release_process.md
pkg/objstore/s3/s3.go
pkg/store/prometheus.go
scripts/genflagdocs.sh

makefile: Pinned all tools; Added liche dep for markdown link check.

---

pkg/store/bucket_e2e_test.go

Fixes https://github.com/improbable-eng/thanos/issues/740

store: Fixed broken context passing leading to test never ending.

---

docs/getting_started.md

Thanks @improbable-ludwik for feedback and PTAL.

docs: Fixed getting started docs after feedback.

---

docs/components/query.md
docs/components/sidecar.md

Signed-off-by: Lukasz Jernas <lukasz.jernas@allegro.pl>

Fix some typos in documentation

---

docs/components/bucket.md
scripts/genflagdocs.sh

Add documentation for `thanos bucket inspect`

adding sub command docs for inspect

---

pkg/pool/pool.go
pkg/pool/pool_test.go

pool: Added tests for bytes pool.

---

tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar-lts.yaml
tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar.yaml
tutorials/kubernetes-demo/manifests/thanos-compactor.yaml
tutorials/kubernetes-demo/manifests/thanos-querier-no-us1.yaml
tutorials/kubernetes-demo/manifests/thanos-querier.yaml
tutorials/kubernetes-demo/manifests/thanos-ruler.yaml
tutorials/kubernetes-demo/manifests/thanos-store-gateway.yaml

k8s tutorial: Moved to proper Thanos version.

---

cmd/thanos/sidecar.go
pkg/shipper/shipper.go

Otherwise we can end up being in starvation. Reloader is trying to create config for Prometheus and
shipper fails before that because Prometheus is not up.

sidecar: Moved shipper flag check to run.group.

---

README.md

Update README.md with docker pull number. 

---

MAINTAINERS.md

Updated maintainers' page.

---

cmd/thanos/query.go
pkg/store/proxy.go
pkg/store/proxy_test.go

We have created an interface which takes context and returns errors, although actual implementation never does that.
So simplifying code :)

Simplify Thanos Query Get Stores

---

docs/getting_started.md

fixed a typo that obviously explained something wrong

fixed typo

---

docs/getting_started.md

Fix wrong link

---

examples/grafana/thanos-query.json

Fix y-axis unit to match the graph title
Visually verified in Grafana.

Change y-axis unit to rps for rps graph

---

docs/getting_started.md

refer to [comment](https://github.com/golang/go/issues/29278#issuecomment-447571410)
Add help info.
Make pass.

Add help about make failed

---

pkg/reloader/reloader.go
pkg/reloader/reloader_test.go

Fixed reloader tests to remove flakiness, simplified them.

---

docs/getting_started.md

Add more help.
For different version of `golang`, make pass.
Test many version of `golang`, unset GOPATH does not work for all case below `1.11.4`, so add more help info about it.

Add more help about make failed

---

test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go
test/e2e/store_gateway_test.go

e2e: Killed gossip e2e tests.

---

pkg/reloader/reloader_test.go

reloader: Minor fix to test - to improve for slow CI.

---

MAINTAINERS.md

Added a new maintainer to the list: @povilasv welcome!

---

docs/getting_started.md

To fix below issue:
$ make
which: no bzr in (/pkgs/go/bin:/pkgs/go_1.10/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
>> formatting code
No bzr binary found.
make: *** [check-bzr] Error 1
Add comment about `bzr` is a build requirement.

Add comment about bzr

---

Makefile

`go mod` has `verify` to check.
It works for current go mod.

use origin mod check

---

pkg/rule/rule.go
pkg/rule/rule_test.go

rule: Made thanos rules generatable; made generated struct Prometheus compatible.

---

pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/tsdb.go
pkg/store/tsdb_test.go

Fixes https://github.com/improbable-eng/thanos/issues/1038
CC @davtsur

ruler: Fixed Chunk's samples number overflowing Max Uint16.

---

.circleci/config.yml

ci: Env fixes.

---

pkg/store/cache_test.go

Add more tests for edge cases for the cache.
`go test -v`

store/cache: add more tests

---

Makefile
netlify.toml

website: Fixing netlify.

---

Makefile
website/layouts/_default/baseof.html

website: Added "founded by" footer.

---

pkg/store/proxy.go

How the code was before it could happen that we might receive some
series from the stream however by the time we'd send them back to the
reader, it would not read it any more since the deadline would have been
exceeded.
Properly use a `select` here to get out of the goroutine if the deadline
has been exceeded.

store/proxy: properly check if context has ended

---

Makefile
README.md
docs/contributing/how-to-contribute-to-docs.md
website/hugo.yaml

eh, more fixes (: 
cc @adrien-f

websited: Removed ghpages handling; fixed docs; and status badge.

---

README.md

- Fix readme grammar error
- not need test

website: Fixed docs

---

website/layouts/index.html
website/static/main.css

website: Sorted logo list, improved look on mobile devices.

---

docs/contributing/how-to-contribute-to-docs.md

Added requirements for company to add logo on thanos page.

feat: added requirements to add your logo docs

---

website/layouts/index.html

website: update padding around sponsors

website: update padding around sponsors

---

docs/components/rule.md

Fixed typos on rule.md file.
N/A

Ruler: fixing minor mistakes on rule.md

---

Makefile
scripts/genproto.sh

Fix https://github.com/improbable-eng/thanos/issues/1131

fix proto generation

---

cmd/thanos/sidecar.go

Fixed sidecar validating Prometheus check to be more clear.

---

docs/components/query.md

Basic wording correction.
Very basic change.

correct repeat wording in sentence in query.md

---

CHANGELOG.md

Cut 0.5.0-rc.0 release.

---

.circleci/config.yml
Makefile

Fixed promu release process.

---

Makefile

Fixing promu part3; Moving to master version.

---

CHANGELOG.md
docs/components/sidecar.md
docs/proposals/completed/201809_gossip-removal.md

docs: Improved sidecar docs.

---

website/data/sponsors.yml

Updated link to reference the meltwater engineering blog

Updated the website link to point to the engineering blog

---

CHANGELOG.md
VERSION

Cut release v0.5.0.

---

tutorials/kubernetes-demo/blockgen/main.go

Fix typo in demo

---

cmd/thanos/receive.go

This commit simplifies the setup of the receive Handler. The
`reloadReady` variable was not actually doing anything and adds some
complexity. We can add this back in once reloading is actually
implemented.
Remove some dead code in receive component setup.
cc @brancz @bwplotka @metalmatze

cmd/thanos/receive: eliminate unused code

---

cmd/thanos/downsample.go

That'll teach me to copy/paste :)

Correctly increment downsample metrics

---

MAINTAINERS.md
README.md
docs/release-process.md
scripts/websitepreprocess.sh
website/layouts/_default/baseof.html

Added @adrien-f  and @FUSAKLA as official triage persons! Thanks guys!
Also put @GiedriusS as next release shepherd as agreed offline.

Updated release process and maintainers docs with Triage role.

---

MAINTAINERS.md

Added jojohappy to triage.

---

docs/components/rule.md
docs/components/sidecar.md

fix some doc error

---

docs/proposals/approved/201812_thanos-remote-receive.md

Fix json in receive controller proposal.

docs/proposals: fix json

---

cmd/thanos/sidecar.go

Fixed missed static check issue.

---

docs/contributing/how-to-contribute-to-docs.md
website/data/adopters.yml
website/layouts/index.html
website/static/main.css

web: Moved internal naming to adopters.

---

scripts/websitepreprocess.sh
website/hugo.yaml

* Update website configuration and preprocess script for new org

website: migrate to new Github Org

---

.circleci/config.yml
.github/ISSUE_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
MAINTAINERS.md
README.md
benchmark/README.md
docs/components/rule.md
docs/getting-started.md
docs/integrations.md
docs/proposals/approved/201901-read-write-operations-bucket.md
docs/proposals/completed/201809_gossip-removal.md
docs/proposals/rejected/config.md
pkg/block/index.go
pkg/ui/templates/bucket.html
pkg/ui/templates/bucket_menu.html
pkg/ui/templates/query_menu.html
pkg/ui/templates/rule_menu.html

Further docs rename to new org; Improved docker login.

---

CHANGELOG.md

Add changelog entry for new S3 option and mark #1338 as a changed item
Signed-off-by: Lukasz Jernas <lukasz.jernas@allegro.pl>

Add changelog entry for S3 option

---

pkg/query/iter.go

Signed-off-by: ethan <guangming.wang@daocloud.io>
local test ok.

iter.go: error message typo correction

---

.gitignore
Makefile

Fixed makefile for OSX.

---

CONTRIBUTING.md

Update the slack channel for PR reviews to `#thanos-prs`.

Update slack channel

---

pkg/shipper/shipper.go
pkg/shipper/shipper_e2e_test.go
pkg/shipper/shipper_test.go

shipper: add meta version constant

---

pkg/receive/handler.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

handler.go: error message spell correction

---

benchmark/cmd/thanosbench/responsiveness.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

responsiveness.go: "intput" fix to input

---

.circleci/config.yml
CHANGELOG.md
Makefile

Adjusted Makefile; added important changelog item.

---

CONTRIBUTING.md

Small change to CONTRIBUTING.md to remove reference to a make target removed in https://github.com/thanos-io/thanos/pull/1422

update CONTRIBUTING.md to match make deps

---

docs/components/query.md
docs/contributing/how-to-contribute-to-docs.md

Incorrect rendering of bullet points. Adding a new line before them fixes the issue.
I also removed some trailing whitespaces.
I did a quick check on preview page and everything looks OK.

docs: Correct bullet points and remove trailing whitespaces

---

.circleci/config.yml
Makefile

Reduced memory for CI job.

---

docs/components/rule.md

fix typo in docs

---

pkg/compact/downsample/downsample.go
pkg/promclient/promclient.go
pkg/shipper/shipper.go
pkg/ui/rule.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
just fix typo words in codebase

Cleanup: fix some typos in code comment

---

docs/release-process.md

Updated schedule for releases.

---

pkg/reloader/reloader.go

Reloader: fix unclosed file

---

.circleci/config.yml
Makefile
README.md
go.sum
website/hugo.yaml
website/layouts/index.html

Added dockerhub images mirror for CI.

---

cmd/thanos/flags.go
docs/components/bucket.md
docs/components/check.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/storage.md
docs/tracing.md
pkg/tracing/client/factory.go
scripts/cfggen/main.go
scripts/genflagdocs.sh

Fixes: https://github.com/thanos-io/thanos/issues/1266

Added autogenerated docs for tracing.

---

pkg/tracing/stackdriver/tracer.go

Fixes: https://github.com/thanos-io/thanos/issues/1474

Fixed stackdriver tracer.

---

pkg/tracing/stackdriver/tracer.go

Fixes: https://github.com/thanos-io/thanos/issues/1474

Port "Fixed stackdriver tracer" to 0.7.0

---

.promu.yml
go.mod
go.sum

Pinned go-ieproxy for FreeBSD support.

---

.circleci/config.yml
.gitignore
Dockerfile.thanos-ci
Makefile

This should fix https://github.com/thanos-io/thanos/issues/1483
Also it should massively improve our CI time.

Baked required deps in docker image for CircleCI.

---

docs/getting-started.md
scripts/quickstart.sh

Resolves #1479 
Added port layout for running on single host
Not sure where to put it in the docs so if you think of any better place or form please comment.

docs: added standardized port layout

---

MAINTAINERS.md

:tada: 
/cc @thanos-io/thanos-maintainers

Add metalmatze to list of maintainers

---

docs/design.md

Update Compactor section in `design.md` to reflect it already does
down-sampling, and applies retention policies, and that is it no longer
a feature planned in the future.

Update Compactor documentation section in `design.md`

---

pkg/compact/downsample/downsample.go

fix potential call stack overflow by converting tail call.

---

CHANGELOG.md
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/flags.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
docs/components/bucket.md
docs/components/check.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
pkg/extflag/pathorcontent.go

This removes some complexity, plus it allows other projects to use this (e.g https://github.com/thanos-io/thanosbench)

Moved pathOrContent to separate package.

---

CHANGELOG.md

Updated CHANGELOG to mention v0.8.1

---

CHANGELOG.md

Updated CHANGELOG.

---

cmd/thanos/query.go
docs/components/query.md

it wasn't really obvious on how to disable it

doc on how to disable default partial response behaviour

---

docs/quick-tutorial.md

Fixed a small docs error.
Looked at the [rendered docs](https://github.com/CasualSuperman/thanos/blob/patch-1/docs/quick-tutorial.md) in my branch.

Remove duplicated sentence in docs

---

docs/storage.md
go.sum
pkg/compact/compact_e2e_test.go
pkg/objstore/client/factory.go
pkg/objstore/filesystem/filesystem.go
pkg/objstore/inmem/inmem.go
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/s3/s3.go
pkg/store/bucket_test.go
scripts/cfggen/main.go

Usa cases:
* See: https://github.com/observatorium/thanos-replicate/issues/7
* We want to have `sync` or `replicate` command
* We have improved shipper package that uses bucket store
* Local testing, demos

Added experimental filesystem bucket implementation

---

docs/proposals/201812_thanos-remote-receive.md

these questions are about merged PRs

remove irrelevant questions on remote-receive.md

---

MAINTAINERS.md

As agreed https://github.com/thanos-io/thanos/pull/1688#discussion_r340463729

docs: Maintainers - Added associated company.

---

pkg/server/grpc/grpc.go
pkg/tracing/grpc.go

Small clean up for tracing.

---

MAINTAINERS.md

Following the voting as per https://thanos.io/governance.md/#maintainers-team @squat is now part of the team (: 

Added Lucas to mantainers list.

---

pkg/ui/templates/stores.html

Fixes: https://github.com/thanos-io/thanos/issues/1601

query: Fixed labelset view for multi labels scenario.

---

docs/release-process.md
pkg/store/bucket_e2e_test.go

Moved release to Thursday; Cleanup tests.

---

docs/release-process.md

Due to KubeCon we need to delay the release to the next week ): It's already end of the week for most of us.

Moved 0.9.0 release to 26th of Nov

---

docs/components/compact.md

Delete broken link. The external_labels part has moved to docs/sidecar but no single section.

delete broken link

---

docs/components/sidecar.md

If not, sidecar could not get metadata.

add --web.enable-admin-api comment

---

tutorials/kubernetes-helm/README.md

Update image tag in doc. 0.3.2 is too old to use some cool new feature.
Test pass at local.

update image tag

---

tutorials/katacoda/thanos/1-globalview/courseBase.sh
tutorials/katacoda/thanos/1-globalview/step1.md
tutorials/katacoda/thanos/1-globalview/step2.md
tutorials/katacoda/thanos/1-globalview/step3.md

Add exteral url for prometheus instance to support all links work.
For now, many link in prometheus UI return 523(can not reach).

add external url

---

pkg/compact/compact.go

Just a quick fix for a typo I noticed while reading the source code.
Update the package import
N/A

Fix typo in package name

---

.github/stale.yaml
pkg/rule/rule_test.go

Proposing this as discussed on Thanos sync.
Closing Thanos issues after 90 days 

Enabled stale bot.

---

docs/components/query.md

- add support value
- remove duplicate link

add partial response strategy values

---

docs/getting-started.md

add deep dive talk

---

docs/service-discovery.md

Add an example for service discovery in kubernetes.

add kubernetes comment for service discovery

---

docs/getting-started.md

Adds intro talk from Kubecon CNCF event NA 2019.
xref: https://github.com/thanos-io/thanos/pull/1840#issuecomment-562060952

docs/gettingstarted.md: add intro talk

---

tutorials/katacoda/README.md

Updated process of developing Katacoda tutorials.

---

pkg/block/index.go
pkg/store/bucket.go

skip the error of unmarshal for index-cache file

---

pkg/compact/downsample/downsample.go

We had at least 5 questions about this on slack (: 

Added comment to non obvious downsampling aggregation.

---

.circleci/config.yml
CHANGELOG.md
Makefile
pkg/ui/rule.go
pkg/ui/static/js/alerts.js
pkg/ui/templates/alerts.html

Sync with the classic Prometheus UI alerts page. Enable to display the alerts counts and filter by alert state.

Update rule UI

---

pkg/ui/templates/bucket_menu.html
pkg/ui/templates/query_menu.html
pkg/ui/templates/rule_menu.html

Use thanos website in help link instead of github repo

Use thanos website in help link

---

pkg/block/block.go

arrange import packages.

---

.golangci.yml
Makefile

- move all golint config into file
- increase timeout time to 5m

move golint config to file

---

pkg/store/prometheus.go

pkg/store: add http header.

---

cmd/thanos/sidecar.go
pkg/promclient/promclient.go
pkg/promclient/promclient_e2e_test.go
pkg/store/tsdb_test.go

Add tsdb store test labelnames labelvalues

---

pkg/store/prometheus.go

Optimize the initialization of sync.Pool.

pkg/store: Optimize the initialization of sync.Pool.

---

scripts/genflagdocs.sh

fix error in MAC OS

---

docs/components/rule.md

Comment the alert rule config file format for beginners.

comment whole alert rule

---

Makefile

add go vet to lint

---

CHANGELOG.md
Makefile
examples/dashboards/compactor.json
mixin/thanos/dashboards/compactor.libsonnet

Updated CHANGELOG and dashboards after meta files synchronisations changes.

---

docs/proposals/201912_thanos_binary_index_header.md

Fixed whitespaces on binary header docs; addressed missing comment.

---

docs/release-process.md

Let's do RC of `v0.10.0` tomorrow.

docs/release-propose: add myself as shepherd

---

CHANGELOG.md

README: update before v0.10.0-rc.0

---

docs/release-process.md

Using YYYY-MM-DD should be less ambiguous regardless of where you live :)

Use RFC 3339 Date to be more readable

---

pkg/ui/static/js/graph.js
pkg/ui/templates/query_menu.html

persist settings in query UI

---

.github/stale.yml

do not mark bug label as stale

---

docs/release-process.md

Add one more step for metrics and a note that we should tag the merge
commit due to the reasons mentioned.

docs/release-process: add more steps

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/ruler.libsonnet

mixin/thanos: fix typo in alert name

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/querier.libsonnet

Pulls into the recent fix into `master`.

Fix revert metric name regression (#2005)

---

docs/components/sidecar.md

Add env comment

---

.circleci/config.yml
.promu.yml
Dockerfile.multi-stage
Dockerfile.thanos-ci

Use latest golang 1.13 docker image available

---

cmd/thanos/rule.go
cmd/thanos/sidecar.go
pkg/objstore/objstore.go
pkg/receive/config.go

The current prometheus/client-golang package already supported this method

Use gauge.SetToCurrentTime

---

MAINTAINERS.md

Welcome @yeya24 in the team! :tada: :muscle: 

Added Ben Ye to Triage.

---

cmd/thanos/query.go
docs/components/query.md

Revert "add flag max query samples"

---

CONTRIBUTING.md
README.md
SECURITY.md
docs/getting-started.md
docs/release-process.md
scripts/websitepreprocess.sh
website/layouts/_default/baseof.html

Fixes: https://github.com/thanos-io/thanos/issues/1389
Fixes: https://github.com/thanos-io/thanos/issues/2052

Improved documentation.

---

netlify.toml

This is required for GOLD CII Best practice badge: https://bestpractices.coreinfrastructure.org/en/projects/3048

Added security headers to our website.

---

CHANGELOG.md
cmd/thanos/rule.go

https://github.com/thanos-io/thanos/issues/2050
Fixes #2050

Pass prom registry to shipper from ruler.

---

.github/stale.yml

.github/stale.yml: fix a typo

---

netlify.toml

This commit cleans up some comments that were recently added to the
netlify.toml file.

netlify.toml: clean up comments

---

CONTRIBUTING.md

Added naming convention rule for components to CONTRIBUTING.md

---

cmd/thanos/main.go
docs/components/bucket.md
docs/components/check.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md

comment all log format

---

docs/proposals/201809_gossip-removal.md
docs/proposals/201909_thanos_sharding.md
docs/proposals/201912_thanos_binary_index_header.md

Fixed design doc statuses.

---

pkg/store/bucket.go

Especially for binary index-header we were not closing mmaped file handle.

Close index-header and block properly, even on error case.

---

MAINTAINERS.md

Signed-off-by: Dominic Green <dominicgreen1@gmail.com>
So long and thanks for all the fish ... 
Hopefully this gives some space for people that are more active on the project and can spend time making it even more amazing.

Removing myself as a maintainer :(

---

pkg/store/proxy.go

Fix segfault panic.

---

docs/proposals/202001_thanos_query_health_handling.md

Adds a document which proposes improving the healthiness handling of the
store nodes in Thanos Query.

Add proposal for improving Thanos Query healthiness handling

---

pkg/store/bucket_test.go
pkg/store/cache/inmemory.go

Fixes: https://github.com/thanos-io/thanos/issues/2147

Fixed Segfault when matching large number of postings + LRU.

---

.github/workflows/cross-build.yaml
.github/workflows/e2e.yaml
README.md
docs/contributing/how-to-change-go-version.md

Added badge for GH actions, trigger on push to master as well.

---

cmd/thanos/receive.go

This PR adds necessary logic to avoid any possible race condition that could happen an early failure.
* Makes sure gRPC server shuts down properly

receive: Avoid possible race condition caused by an early failure

---

pkg/query/querier.go

Add matchers, min and max time as span tags for data retrieval of the querier.
n/a as instrumentation
@bwplotka @squat @metalmatze @GiedriusS @povilasv

pkg/query: Add more detail to data retrieval tracing

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/query.libsonnet
mixin/thanos/alerts/receive.libsonnet
mixin/thanos/alerts/rule.libsonnet

This PR modifies alert a couple of alert severities.
cc @brancz 
* Update severities for Thanos Ruler alerts
* Update severities for Thanos Receiver alerts
* Update severities and the threshold for Thanos Querier alerts

mixin: Modify alert severities and thresholds

---

pkg/query/querier.go
scripts/quickstart.sh

This makes the tags added in #2184 actually work.
Started local jaeger this time and added the jaeger config to the quickstart script for next time :wink: .
@bwplotka @squat @metalmatze @GiedriusS @povilasv

pkg/query: Fix jaeger tags for query selects

---

docs/operating/troubleshooting.md
website/layouts/partials/_default/sidemenu.html

Added Operating doc section.

---

go.mod
go.sum

Removed dependency on Cortex fork; Moved to official one.

---

cmd/thanos/rule.go
pkg/alert/alert.go
pkg/cacheutil/memcached_client.go
pkg/receive/handler.go
pkg/store/bucket.go
pkg/store/prometheus.go
pkg/store/proxy.go
pkg/tracing/tracing.go

tracing: Simplified creation of spans.

---

tutorials/katacoda/thanos/1-globalview/courseBase.sh
tutorials/katacoda/thanos/1-globalview/step2.md

I think this was just a typo during the v0.11.0 release.

tutorials: fix typo in image version

---

scripts/quickstart.sh

- Remove duplicate log.level arg in quickstart.sh
- Not tested

.*: Remove duplicate log.level arg in quickstart.sh

---

Makefile

Use new go jsonnet formattter for jsonnet build pipeline, https://github.com/google/go-jsonnet/pull/388
cc @metalmatze @daixiang0 
* `make jsonnet-format`

make: Use new go jsonnet formatter

---

docs/sharding.md

Sharding: document supported relabel action and add store gateway backgroud

---

.gitignore

- Ignoring the OS-X Trash which can be randomly generated using the project

fix: Ignore the OS-X Trash

---

docs/sharding.md

docs/sharding.md: fix a typo

---

cmd/thanos/main.go

Crashing error messages now will print stacktrace.

---

CHANGELOG.md

Downsample: update changelog

---

examples/dashboards/compact.json
examples/dashboards/query.json
examples/dashboards/receive.json
examples/dashboards/rule.json
examples/dashboards/sidecar.json
examples/dashboards/store.json
mixin/thanos/dashboards/store.libsonnet
mixin/thanos/lib/thanos-grafana-builder/builder.libsonnet

thanos-mixin: clear units/axis

---

MAINTAINERS.md

Added Xiang to Triage Role.

---

MAINTAINERS.md

Added Kemal to Triage Role.

---

docs/sharding.md

Fixed the link to be a permalink as it was already outdated.
@thanos-io/thanos-maintainers @thanos-io/thanos-triage

docs/sharding.md: Replace example floating link with permalink

---

README.md

I think there are NOT enough badges, so added one more!

Added latest release badge.

---

docs/release-process.md

Proposing myself to shepherd the v0.12.0 release :))

docs/release: squat to release v0.12.0

---

CHANGELOG.md
pkg/store/proxy.go
pkg/store/proxy_test.go

When no stores are discovered, then timespan from 0 to 0 unixtime is reported.
Closes https://github.com/thanos-io/thanos/issues/1299.
n/a

pkg/store: Report no data if no stores discovered

---

pkg/block/fetcher.go

refine the code with package errgroup

block fetcher with errgroup

---

netlify.toml

Verification: Now on F12 network page we can see call to Google Analyitcs.

website: Enabled two scripts to fix Google analytics.

---

pkg/block/block.go
pkg/compact/compact.go
pkg/objstore/objstore.go
pkg/objstore/oss/oss.go
pkg/objstore/s3/s3.go

Fixes: https://github.com/thanos-io/thanos/issues/2322
Before tomorrows release (:

compact: Fixed minor logging issues.

---

docs/operating/troubleshooting.md

Compactor: Document reasons and solutions about overlaps

---

docs/contributing/coding-style-guide.md

docs: Fixed table formatting for coding style guide.

---

docs/contributing/coding-style-guide.md

docs: Added minor note to single rule.

---

examples/dashboards/store.json
mixin/thanos/dashboards/store.libsonnet

Fixes #2425
Signed-off-by: John Belmonte <john@neggie.net>
dashboard json files were regenerated with `make examples`
CI has coverage with `make check-examples`

store dashboard: fix gRPC streamed detail panels

---

docs/contributing/coding-style-guide.md

Found by Twitter friends!
https://twitter.com/golasgil/status/1249947397972733957

docs: Fixed typo in coding guide.

---

pkg/cacheutil/memcached_client.go

- Fixed memcached client metrics initialization

Fixed memcached client metrics initialization

---

cmd/thanos/compact.go
cmd/thanos/flags.go

Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>

cmd/thanos: clean gosimple S1039

---

CONTRIBUTING.md

Fixes #2458 
Signed-off-by: ranjithkumar007 <ranjith.dakshana2015@gmail.com>
Added DCO instructions in CONTRIBUTING.md
Verified locally using `make web-serve` and on [deploy preview](https://deploy-preview-2465--thanos-io.netlify.app/contributing/#pull-request-process)

docs: Update CONTRIBUTING.md with DCO

---

test/e2e/compact_test.go
test/e2e/e2ethanos/services.go

Related to: https://github.com/thanos-io/thanos/issues/2459

Added tests to reproduce #2459.

---

pkg/discovery/dns/provider.go

The DNS `Provider.Resolve()` takes an exclusive lock for the whole duration of the DNS resolution. If, for any reason, the DNS resolution is slow (ie. hits the timeout), the `Addresses()` will block for entire time of the resolution.
Notes to reviewer:
- Since `Resolve()` is currently goroutines safe I kept it safe (ie. multiple concurrent invocations of `Resolve()`), so I wrapped `resolverAddrs` metric update within the lock (`TxGaugeVec.ResetTx()` and `.With*()` is not goroutines safe).
Unit tests.

Do not lock DNS Provider.Address() while resolving addresses

---

cmd/thanos/compact.go

Signed-off-by: Johnathan Falk <johnathan.falk@gmail.com>
Changed documentation to better clarify option.

Compact: Update compact documentation to better clarify dedupeReplicaLabels.

---

.golangci.yml
Makefile
cmd/thanos/check_test.go
pkg/block/fetcher_test.go
pkg/query/api/v1_test.go
pkg/query/querier_test.go
pkg/receive/handler_test.go
pkg/receive/hashring_test.go
pkg/rule/api/v1_test.go
pkg/store/cache/inmemory_test.go
scripts/cfggen/main.go

Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>

add gofmt -s step to makefile and golangci

---

.github/stale.yml

Let's be more nicer on stale things (:

---

docs/proposals/202003_thanos_rules_federation.md

This adds the rules federation proposal.
* Adding a formal proposal for rules federation as per https://docs.google.com/document/d/12ou_YE54NPzBvzfAH-xkqmvyTu_L14_TYx5DhRxBOfU/edit#
TBD in the actual implementation.
cc @bwplotka

docs/proposals/202003_thanos_rules_federation: initial commit

---

pkg/query/api/v1.go
pkg/query/api/v1_test.go

Revert "Add deleteSeries skeleton to return bad request"

---

docs/release-process.md

13 is my lucky number :four_leaf_clover: 

Added Bartek as next release shepherd.

---

pkg/receive/multitsdb.go

Previously since the multi-tsdb work was merged, WAL replay was kicked off and the process marked as ready, but we need to wait for WAL replay to finish to be able to continue rollouts of other instances.
Ran tests
@bwplotka @squat @metalmatze @kakkoyun @krasi-georgiev

receive: Block WAL replay when starting receive component

---

docs/integrations.md

Thanks to G-Research as per: https://cloud-native.slack.com/archives/CL25937SP/p1588687640060200?thread_ts=1588167992.463800&cid=CL25937SP
Thanks @dgl for sharing!

docs: Added mention about thanos-remote-read integration.

---

.gitignore

Signed-off-by: Ranjith Kumar <ranjith.dakshana2015@gmail.com>
Add regex for e2e integration temp files to .gitignore
Verified using `git status`

Update gitignore with integration tests directory

---

cmd/thanos/main.go

Signed-off-by: Joel Bastos <kintoandar@gmail.com>
Minor typo fix on the reload function logline

Fix typo on reload function

---

tutorials/katacoda/thanos/1-globalview/step3.md

tutorials: Fix minor typos in globalview katacoda tutorial

---

pkg/ui/react-app/package.json
pkg/ui/react-app/yarn.lock

pkg/ui: bump jQuery to 3.5.0

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/receive.libsonnet

Add an alert on receive not performing uploads of data.
Wrote this rule based on data of a recent incident. So I checked whether it would have fired in that situation.
@bwplotka @krasi-georgiev @squat @metalmatze @kakkoyun

mixin: Alert on receive not uploading recent data

---

docs/storage.md

Typo in signature_version2
Visual

docs: fix signature_version2 vs signature-version2

---

CHANGELOG.md

Soft cut changelog on master to indicate new release being in progress.

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/alerts/receive.libsonnet
pkg/receive/handler.go

* Manually with ad-hoc queries against a running cluster.
cc @squat @brancz @metalmatze

mixin: Dynamically alert on forward request depending on replication factor

---

.circleci/config.yml
Dockerfile.thanos-ci

Fixed test job.

---

pkg/cacheutil/memcached_client.go

While running Cortex blocks storage at scale, we're seeing our traces flooded by MemcachedClient spans for queries hitting memcached tens of thousands of times. Such traces are quite useless and we can't even open them in the browser without freezing it. To temporarily overcome it, we had to stop propagating the tracing context to Thanos but this means we lost any Thanos spans.
The problem is that MemcachedClient spans are too low level to have single spans for every single operation. I suggest to remove spans from there.
N/A

Removed tracing spans from memcached client

---

pkg/shipper/shipper.go
pkg/shipper/shipper_e2e_test.go

Skip over already compacted blocks and do not check for their existence
if not needed i.e. appropriate flags have not been specified.
Closes #2686.
I moved one check a bit further up so that we would not do unnecessary existence checks.
Improved tests that fail without this change.

shipper: do not check for existence if not needed

---

CONTRIBUTING.md

Docs: fix Pull Request Process in CONTRIBUTING.md

---

CONTRIBUTING.md

CC : @bwplotka @povilasv :heart_eyes_cat:

Fixing Code of Conduct broken link in Contributing Documentation.

---

pkg/ui/react-app/yarn.lock

pkg/ui/react-app: bump websocket-extensions

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/alerts/rule.libsonnet

* Add `for` interval for `ThanosNoRuleEvaluations`
cc @brancz

mixin: Fix flappy ruler alert

---

scripts/quickstart.sh

Fixes #2588 
Added Thanos Rule in the `quickstart.sh`. Now users while running this script can also see the `thanos` rule in action! 

Added thanos rule component in the quickstart.sh

---

cmd/thanos/rule.go

Continue this pr https://github.com/thanos-io/thanos/pull/1857

Use original file name in rules loaded metric

---

go.sum
website/layouts/_default/single.html

Fixes #2512 
This PR aims to add TOC to `getting-started.md` page

Adding TOC on pages with more than 400 words

---

website/layouts/_default/baseof.html
website/static/main.css

I fixed visibility of Navbar hamburger menu icon by updating bootstrap,popperJS, and Jquery CDN to latest. Due to CSP issues, I used fontawesome icon instead in replace of bootstrap. With this, I was able to overcome CSP issues.
Works on local

Fixed navbar toggle icon to be visible

---

MAINTAINERS.md
docs/release-process.md

I also moved release date to next week as Kemal is PTO this week.

Added Kemal to Maintainer Role; Kemal is volunteering to be next release shepherd

---

CHANGELOG.md
tutorials/katacoda/thanos/1-globalview/courseBase.sh
tutorials/katacoda/thanos/1-globalview/step2.md
tutorials/katacoda/thanos/1-globalview/step3.md

Soft cut changelog on master to indicate v0.14.0 being in progress

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/alerts/receive.libsonnet

increase ThanosReceiveNoUpload time  check to 3h

---

docs/proposals/202005_version_documentation.md

@bwplotka @metalmatze Please I need your suggestions on this

Proposal: Building a versioning plugin for Thanos

---

go.mod
go.sum

Keep prometheus in sync with cortex.

Sync prometheus version with the one used by cortex

---

tutorials/katacoda/thanos/1-globalview/step1.md

Fixes #2690 
CC : @povilasv @bwplotka

Adding about external_labels in katacoda tutorial

---

cmd/thanos/downsample.go

Similar to https://github.com/thanos-io/thanos/pull/2895, we should inc the counter metric here.

Fix increment of thanos_compact_downsample_failures_total counter

---

examples/dashboards/overview.json
examples/dashboards/query.json
examples/dashboards/receive.json
examples/dashboards/rule.json
examples/dashboards/sidecar.json
examples/dashboards/store.json
mixin/dashboards/query.libsonnet
mixin/dashboards/receive.libsonnet
mixin/dashboards/rule.libsonnet
mixin/dashboards/sidecar.libsonnet
mixin/dashboards/store.libsonnet
mixin/lib/thanos-grafana-builder/grpc.libsonnet
mixin/lib/thanos-grafana-builder/http.libsonnet

* Separate Read/Write path dashboards for Receiver.
* Remove detailed panels.
* Clean up.
* Add screenshots.
* `make examples` and import Grafana.

mixin: Separate Read/Write path dashboards for receive

---

docs/release-process.md

Propose kakkoyun as next release shepherd

---

scripts/insecure_grpcurl_series.sh

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

fix the grpcurl script

---

Makefile

With the use of `Bingo`, we don't need to maintain these actions. So I'm removing them.
* Remove unnecessary Make actions

Makefile: Remove Jsonnet ci container

---

examples/dashboards/store.json
mixin/dashboards/store.libsonnet

* Add aggregation by operation to Store bucket dashboards

mixin: Improve Store Bucket operation boards

---

test/e2e/query_frontend_test.go

Fix the failed E2E query range test in master. Mentioned here https://github.com/thanos-io/thanos/pull/3012#issuecomment-672017260

Fix e2e query frontend range query split test

---

pkg/cacheutil/memcached_client.go

In addtition to `memcache: connect timeout to XXX.XXX.XXX.XXX:11211`, we have been seeing `read tcp XXX.XXX.XXX.XXX:59812->XXX.XXX.XXX.XXX:11211: i/o timeout`. This PR aims to address them.
* Handle network timeout errors.

memcached: Handle unexpected network timeout errors

---

docs/components/query-frontend.md
docs/components/store.md
scripts/cfggen/main.go

Add docs for query frontend

---

docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/design.md
docs/getting-started.md
docs/proposals/config.md
docs/proposals/gossip-removal.md
docs/storage.md

Added frontmatter to release 0.1.0 docs files inorder to make them viewable on website
Works on local machine

added frontmatter to release 0.1.0 docs

---

docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/design.md
docs/getting-started.md
docs/proposals/approved/201809_gossip-removal.md
docs/proposals/rejected/201807_store_instance_high_availability.md
docs/proposals/rejected/config.md
docs/release_process.md
docs/storage.md
docs/thanos_service_discovery.md
docs/troubleshooting/dev.md

Added frontmatter to release-0.2 docs inorder to make it viewable on website
Works on local

added frontmatter to release-0.2 docs

---

docs/proposals/approved/201809_gossip-removal.md
docs/proposals/rejected/201807_store_instance_high_availability.md
docs/proposals/rejected/config.md

Fixed duplicated title in release-0.2 proposal docs
Works on Local

Fixed duplicated title in release-0.2 proposal docs

---

docs/proposals/config.md
docs/proposals/gossip-removal.md

Fixed duplicated title in proposals
Works on local

Fixed duplicated title in release-0.1.0 proposal docs

---

docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/design.md
docs/getting-started.md
docs/proposals/approved/201809_gossip-removal.md
docs/proposals/approved/201812_thanos-remote-receive.md
docs/proposals/approved/201901-read-write-operations-bucket.md
docs/proposals/rejected/201807_store_instance_high_availability.md
docs/proposals/rejected/config.md
docs/release-process.md
docs/service-discovery.md
docs/storage.md
docs/troubleshooting/dev.md

Added frontmatter to release-0.3.1 docs
Works on local

added frontmatter to release-0.3.1 docs

---

website/layouts/_default/baseof.html
website/layouts/_default/single.html

added docsearch global meta tag and static class to help create configuration to fine tune daily crawl
Works on local

added docsearch global meta tag to aid in search crawling

---

docs/proposals/202003_thanos_rules_federation.md

Signed-off-by: Benjamin <benjamin@yunify.com>
- Correct incorrect rule type
N/A

docs: Incorrect rule type in thanos rules federation proposal

---

docs/proposals/202005_version_documentation.md

Added future work section in versioning proposal
Works on local

added future work to versioning proposal

---

cmd/thanos/compact.go
cmd/thanos/config.go
cmd/thanos/flags.go
cmd/thanos/main.go
cmd/thanos/query-frontend.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
cmd/thanos/tools.go
cmd/thanos/tools_bucket.go
cmd/thanos/tools_test.go
docs/components/sidecar.md
pkg/extflag/hidden.go
pkg/extflag/pathorcontent.go
pkg/extkingpin/app.go

Refactored cmd invokations for readability & reuse.

---

docs/community.md
docs/design.md
docs/getting-started.md
docs/governance.md
docs/integrations.md
docs/operating/binary-index-header.md
docs/operating/multi-tenancy.md
docs/operating/reverse-proxy.md
docs/operating/troubleshooting.md
docs/quick-tutorial.md
docs/release-process.md
docs/service-discovery.md
docs/sharding.md
docs/storage.md
docs/tracing.md
scripts/website/contentpreprocess.sh
website/hugo.yaml

This does not fix everything, for that we need proper script (in making). This should fix basics at least (tip).

Fixed tip links.

---

website/layouts/partials/versioning/version-picker.html

Renamed picker from Version to Docs
Works on local

Renamed picker from Version to Docs

---

pkg/block/fetcher_test.go
pkg/extprom/testing.go
pkg/reloader/reloader_test.go
pkg/rules/manager.go
pkg/rules/manager_test.go
pkg/testutil/testutil.go

Fixes https://github.com/thanos-io/thanos/issues/3083

Changed rule manager to avoid unreadable tmp rule file names; Attempted to fix reloader flakiness

---

docs/storage.md

Fixed incorrect heading level for AliYun OSS

docs: Fixed incorrect heading level for AliYun OSS

---

go.mod
go.sum
pkg/server/http/http.go

Add fgprof debug endpoint for Off-CPU time analysis.

Add fgprof profiler

---

docs/components/receive.md

It took long before I found proper url path

Add section about remote_write proper url path

---

website/layouts/index.html

Small grammar fixes to the website landing page.

layouts: small fixes to website index

---

website/layouts/_default/baseof.html

Fixed search to filter results based on the version content pages. 
Works on local

Fixed search to filter results based on the version content pages

---

CHANGELOG.md

* Fix broken link in the changelog.

Fix broken link in release notes

---

.github/stale.yml

I think we need to give more time for community to find time comment/contribute on interesting issues, let's extend staleness period a bit (: 

Extending GH issues staleness to kick in only after 2mo.

---

website/hugo.yaml

Added configuration to enable h1 - h4 tags in website
Works on local

Fixed TOC to contain h1 to h4 tags

---

MAINTAINERS.md

Add Prem as a maintainer

---

docs/release-process.md

I'm happy to shepherd the v0.17 release in November. 
Who is doing the Sep release? :grin:

Add metalmatze as v0.17 release shepherd

---

pkg/ui/react-app/src/thanos/pages/blocks/blocks.module.css

Signed-off-by: Daksh Sagar <daksh.sagar@yahoo.com>
Related to #3112 
Edit blocks.moudle.css to reduce vertical whitespace.
Verified it in the browser.

Block viewer: Reduce vertical whitespacing

---

README.md
website/layouts/index.html

I noticed GitHub repo's description still says "CNCF Sandbox project" rather than "CNCF Incubating project" - but I could not propose a change for it via PR.
This PR is only to raise that point, but while at it, I also found the note of "CNCF Incubation project" being used, which I thought would make more sense with "CNCF Incubating project" as used in CNCF website https://www.cncf.io/projects/.
`s/Incubation/Incubating/g`
Via Netlify build

doc: Correct CNCF project name

---

docs/proposals/201909_thanos_sharding.md
docs/proposals/config.md

Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>
Fixes typos in: 
1) docs/proposals/201909_thanos_sharding.md
2) docs/proposals/config.md

docs: Fixing typos in couple of files

---

website/layouts/_default/baseof.html

website: Changed download button to releases to be clearer.

---

docs/contributing/how-to-contribute-to-docs.md

Signed-off-by: Theunis Botha <tbotha95@gmail.com>
Fixed a typo in the `how-to-contribute-to-docs.md` documentation.
Tested by running the site locally.

Fixed a typo in the contribution docs

---

CHANGELOG.md

Added changelog separation.

---

docs/integrations.md

I only fixed a small typo error

(docs): fixed small error

---

MAINTAINERS.md
docs/contributing/community.md
docs/contributing/mentorship.md
scripts/website/contentpreprocess.sh

Added mentees onboarding docs; Improved Community and contribution docs.

---

docs/contributing/mentorship.md

This should fix the markdown linter error in CI.

Fix invalid link in mentorship.md

---

website/layouts/_default/baseof.html
website/layouts/_default/single.html
website/layouts/index.html
website/layouts/partials/searchConfig/docs.html
website/layouts/partials/searchConfig/index.html

Refactored search config to work efficiently on website and made search work on home page
Works on local

Refactored search config to work efficiently on website

---

docs/tracing.md

Fix misspelling of Lightstep in tracing docs

---

CONTRIBUTING.md
cmd/thanos/rule.go
docs/components/rule.md

[Ruler] Fix typo in docs

---

pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
pkg/ui/react-app/src/thanos/pages/blocks/TimeRange.tsx

Fixes #3242 
Change [number, number] to number[]
`yarn start` launches the dev server and all the tests pass

react-app: Fix incorrect argument type for react-slider's onChange prop

---

cmd/thanos/main.go
go.mod

Not sure about this part of code but I think we don't use memberlist anymore.

Cleanup unused memberlist metrics

---

pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/compact/compact_test.go

Cleanup some used by Cortex methods in compact.go

---

Dockerfile
Dockerfile.multi-stage
Makefile

Pin quay.io/prometheus/busybox docker image

---

docs/components/store.md

/cc @bwplotka
subsection 'External Label Partitioning' added to store doc that links to sharding doc

Add sub section 'External Label Partitioning' link to sharding doc

---

cmd/thanos/tools_bucket.go
docs/components/tools.md
pkg/verifier/duplicated_compaction.go
pkg/verifier/index_issue.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/safe_delete.go
pkg/verifier/verify.go

Refactored verifier for easier verifiers addition.

---

cmd/thanos/compact.go
pkg/block/block_test.go
pkg/block/metadata/meta.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/compact/compact_test.go
pkg/compact/planner.go
pkg/compact/planner_test.go
pkg/shipper/shipper_e2e_test.go

compact: Refactored compaction Planner for ability to extend planners. Added compatibility tests.

---

.github/FEATURE_REQUEST.md

Added a feature request template which I think covers the bases.
This should not affect the changelog, as it does not affect Thanos code.
Closes #3400 
Added FEATURE_REQUEST.md under .github

Add Feature request template

---

pkg/queryfrontend/request.go

bugfix: add label field to span log fields

---

pkg/logging/logger.go

Fix logging caller tag.
Running the e2e tests to see.

pkg/logging: Fix logging caller

---

docs/operating/cross-cluster-tls-communication.md

Line 23 - I think this is meant to be 'proxy based'
Simple spelling correction.
I didn't test it, but it probably works.

'Proxy bases' or 'proxy based'?

---

docs/contributing/community.md

docs: Moved Thanos Community meeting to be 13:00 UTC

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

Issues templates should be put to the `ISSUE_TEMPLATE` directory so that they can be selected when u open an issue.

Update issue templates to the template folder

---

CHANGELOG.md
cmd/thanos/store.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go

As disscussed: https://cloud-native.slack.com/archives/CL25937SP/p1605529810257900

store: Enabled postings compressions by default. Removed feature flag.

---

CHANGELOG.md

I made some changes for the changelog regarding the linting of it. I think, we don't have any lint checks for markdown, so this might be a good idea to add one.

Linting changes for changelog

---

tutorials/katacoda/thanos/2-lts/index.json

Nit Improvement in Finish file

---

pkg/store/bucket.go

Fix typo in error message

---

website/hugo.yaml

Website: Fix v0.17 docs link

---

scripts/website/contentpreprocess.sh
website/hugo.yaml

docs: Fixed rendering or raw HTML in our docs.

---

.gitpod.yml
CONTRIBUTING.md
README.md

Signed-off-by: Adam Domagalski <adadom@st.amu.edu.pl>
#3475 Add .gitpod config to spin up dev env on [GitPod](https://www.gitpod.io/), using existing one-node setup (see: [quickstart.sh](https://github.com/thanos-io/thanos/blob/b08c0ea62abfe4dcf1400da0e37598f0cd8fa8cf/scripts/quickstart.sh))

Add .gitpod

---

docs/components/receive.md
docs/components/sidecar.md
docs/storage.md

docs: Added storage docs for block layout. Explained external labels importance.

---

pkg/objstore/objstore.go

Fix error output in the log.
Details:
This pr is associated with an issue https://github.com/thanos-io/thanos/issues/3518
Review twice😸

pkg/objstore: make error msg more accurate.

---

docs/storage.md

- Fix supported clients markdown table syntax in `docs/storage.md`

docs: Fix supported clients table

---

test/e2e/receive_test.go

Signed-off-by: Chans321 <tsschand@gmail.com>

added e2e test for multitenancy resolves #3336

---

cmd/thanos/receive.go
pkg/receive/multitsdb.go

I was scared I see lot's of uploads every minute, but we do that for no uploads as well (:

receive: Clarified debug log message.

---

docs/operating/use-cases.md

issue: https://github.com/thanos-io/thanos/issues/3507
create a new page at docs/operating/use-cases.md and add the first case  about "Horizontal scaleable Prometheus with Thanos + Kvass"

docs: add operating/use-cases.md

---

docs/proposals/receive_split.md

Signed-off-by: Chans321 <tsschand@gmail.com>

Added proposal for receive split

---

docs/contributing/community.md

Signed-off-by: Ritesh Yadav <daydreamingguy941@gmail.com>
Added info about Thanos Contributor Office Hours to Thanos Website. Issue #3534

Updated Thanos Contributor office Hours in Community.md

---

MAINTAINERS.md

Change my role from triage to maintainer ^ ^

Add myself as maintainer

---

pkg/ui/react-app/src/pages/graph/ExpressionInput.test.tsx
pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx
pkg/ui/react-app/src/pages/graph/Panel.test.tsx
pkg/ui/react-app/src/pages/graph/Panel.tsx
pkg/ui/react-app/src/pages/graph/PanelList.tsx

Signed-off-by: Khyatisoneji <khyatisoneji5@gmail.com>

Changed "metrics autocomplete" with "autocomplete"

---

MAINTAINERS.md

MAINTAINERS.md: Update my company association

---

docs/contributing/mentorship.md

While I was part of the Community Bridge Mentorship, I found that working with an iterative process is really beneficial. Also having a small but working example helps in building up the project. I thought of adding this in the `mentorship` docs.
Suggestions are welcome :hugs:

Add a point of suggestion for Mentorship Doc

---

docs/components/query.md

docs: Fix typo in components/query.md

---

cmd/thanos/store.go
docs/components/store.md

The description of store is outdated and we support Aliyun OSS already.
Not sure if there is a good way to automate this if we support more Object storage in the future.

Chore: update store cmd description

---

tutorials/katacoda/thanos/2-lts/step1.md

Fix typo in katacoda/thanos/2-lts/step1.md

Fix typo in katacoda/thanos/2-lts/step1.md

---

docs/contributing/how-to-contribute-to-docs.md

Fix typo / grammatical issues in contribution doc for white noise section
Fixed a typo / grammar issue in white noise section of contribution doc
Ran the site locally

Fix typo / grammatical issues in contribution doc for white noise section

---

pkg/server/grpc/option.go

Just found this 2 artifacts while doing other things.

Lints: Remove UnixSocket not used and use right comment

---

CHANGELOG.md

Starting the v0.18 release process.

CHANGELOG.md: note that a release is in progress

---

docs/integrations.md
docs/quick-tutorial.md

Fixes [#3569](https://github.com/thanos-io/thanos/issues/3569) 
Made changes in some links of quick-tutorial.md and integragions.md file, to point them to the correct files.
I tested the website on localhost and the links now direct to the desired pages.

website: fixed broken links

---

cmd/thanos/compact.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/query_frontend.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
cmd/thanos/tools_bucket.go
docs/components/compact.md
docs/components/query-frontend.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/components/tools.md

Updated help messages with capitals and periods where needed (#3713).
Build and `thanos -h` to verify all messages conform to the same standard.

Update help messages with a consistent use of capitals and periods.

---

examples/dashboards/dashboards.md

Signed-off-by: Mert Acikportali <mertacikportali@gmail.com>
The `thanos-mixin` references in `examples/dashboards/dashboards.md` give 404s. 
Updating the references with the correct ones.

docs: update examples/dashboards/dashboards.md

---

docs/release-process.md
website/hugo.yaml

Fixed website and added new step for release process (tmp).

---

docs/quick-tutorial.md

Update Katacoda Official Link

---

pkg/ui/react-app/src/pages/graph/PanelList.tsx

Fixes a subissue `Fix button display when there is no panels` in #3541 .

Fix button display when there is no panels

---

pkg/ui/react-app/yarn.lock

Fix 2 lodash security issues:
* https://snyk.io/vuln/SNYK-JS-LODASH-1018905 fixed by https://github.com/lodash/lodash/commit/c4847ebe7d14540bb28a8b932a9ce1b9ecbfee1a
* https://snyk.io/vuln/SNYK-JS-LODASH-1040724 fixed by https://github.com/lodash/lodash/commit/3469357cff396a26c363f8c1b5a91dde28ba4b1c
From a quick look, I couldn't find usage of lodash in the UI code, it's probably only used at build time (not a JS expert though).
Tests should pass.

pkg/ui/react-app: update dependencies

---

docs/release-process.md
website/hugo.yaml

Fixed website, explained better release process.

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
examples/alerts/tests.yaml
mixin/alerts/sidecar.libsonnet
mixin/runbook.md

Fix alert label name regression introduce in https://github.com/thanos-io/thanos/pull/3204.
cc @hwoarang

Fix regression introduced in previous PR

---

pkg/api/query/v1.go
pkg/api/query/v1_test.go
pkg/ui/static/js/graph.js

Fixes: #3872 
- Fixed parseStep function.
- Fixed typo from the previous PR.
- Changed related test.
- New test case is able to simulate issue #3872. Now, this test case would fail without a fix introduced in this PR.

Fix parseStep bug introduced in PR #3740

---

pkg/api/query/v1.go
pkg/api/query/v1_test.go
pkg/ui/static/js/graph.js

* Fix bug introduced in PR #3740
* Minor change in test
Cherry picked: https://github.com/thanos-io/thanos/pull/3887

Cherry-pick from master: Fix parseStep bug introduced in PR #3740 (#3887)

---

pkg/compactv2/compactor_test.go
pkg/compactv2/modifiers.go

* rewrite delete should delete a series only if it matches all matchers in a deletion request
* add test case
Cherry pick of: https://github.com/thanos-io/thanos/pull/3886

Cherry-picked Tools: rewrite delete can delete series only if it matches all matchers (#3886)

---

docs/quick-tutorial.md

Fixes image and changed the headings so it does not look weird on the website.
How you tested it? How do you know it works? 
- Yes, locally and with sheer magic. 
Resolved issue #3909

Website: Fixes image and changed the headings

---

MAINTAINERS.md

:partying_face: :ice_cube: 
Quit a job and start a new one. 
I signed a contract. :smile: 
/cc @brancz

Update metalmatze's company

---

pkg/api/query/v1.go

Prometheus supports both GET and POST for querying exemplars. So add a new POST handler for it here.

Add POST method for exemplars API

---

docs/components/store.md

Signed-off-by: Saniya Arora <saniya.rishi@gmail.com>
Change is not relevant to the end user.
Updated the documentation for the Store gateway component, correcting the estimate disk space used by the precomputed index. Resolves #3045 according to the slack conversation mentioned.

Store Gateway Doc Update 

---

docs/components/store.md

Added an example on the full settings for the Thanos Store bucket cache.
Fixes #3666

website: improve documentation for bucket cache

---

docs/getting-started.md

Signed-off-by: Juraj Michalek <jmichalek@medallia.com>
Updated Talks section on website.

Website: update talk links

---

cmd/thanos/compact.go
cmd/thanos/tools_bucket.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go

Unfortunately, I deleted the original fork and resubmit the pr #3558 here.

Compact: Improve compact readability (from pr #3558)

---

CONTRIBUTING.md

Upstreamed changes from #3817 
Fixes #3876

Added more details about installing and running Thanos in the contributing.md file

---

pkg/ui/react-app/yarn.lock

* Upgrade and sync all patches
* `yarn test`

UI: Upgrade all frontend dependencies to patched versions

---

MAINTAINERS.md

Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>
Updated my GitHub username and company (this was due for long time)
https://github.com/prmsrswt is returning [404](https://http.cat/404)

Update Prem's GH username and company

---

pkg/promclient/promclient.go
pkg/targets/prometheus_test.go

Fix #4021.
Use the same way in pr #4013

Fix prometheus target tests with correct address

---

docs/release-process.md

docs: Add kube-thanos to the release process doc

---

pkg/block/fetcher.go

The go routine feeding work into the channel could get stuck when
there are more than 2*f.concurrency and more blocks left. Make sure
to completely drain the channel and report any error that occurred.
Signed-off-by: Holger Hans Peter Freyther <holger@freyther.de>

block: Avoid IgnoreDeletionMarkFilter deadlock on many errors

---

MAINTAINERS.md

Adds myself to the triage list. 🎉 🎉

Adds myself as triage member

---

examples/dashboards/query.json
mixin/dashboards/query.libsonnet

Fix query dashboards when frontend is deployed

---

pkg/api/query/v1.go

add & fix some missing comments in federated APIs

---

.muse/config.toml

Based on https://github.com/TomMD/thanos/blob/main/.muse/config.toml

Added Muse configuration to ignore certain issues.

---

CONTRIBUTING.md

GOBIN shouldn't be listed twice.

fix env variables described  in CONTRIBUTING.md

---

cmd/thanos/receive.go
pkg/logging/http.go
pkg/tracing/jaeger/config_yaml.go

Signed-off-by: someshkoli <kolisomesh27@gmail.com>
Minor fixes done during bug bash :raised_hands:

(bugbash) semgrep-sprinf-host-port fixes 

---

cmd/thanos/compact.go
cmd/thanos/tools_bucket.go
pkg/http/http.go
pkg/logging/options.go

Signed-off-by: someshkoli <kolisomesh27@gmail.com>
Removes unwanted err nil checks

(bugbash) fixes opt.semgrep.err-nil-chec 

---

pkg/logging/http.go

Fixes ST1005 : error strings should not be capitalized

(bugsbash)error strings should not be capitalized

---

pkg/reloader/reloader.go
pkg/rules/manager.go
pkg/shipper/shipper.go
pkg/testutil/e2eutil/copy.go
pkg/tls/options.go
scripts/copyright/copyright.go

Similar to #4160
P.S - Missed these changes in the earlier PR because they are not grouped together on muse.dev That PR is approved so opened a new one. Sorry for that.

(bugsbash) fixes potential file inclusion via variable

---

CHANGELOG.md

Corrected PR link for "Expose exemplars for `http_request_duration_seconds` histogram if tracing is enabled."
n/a

CHANGELOG: Correct issue link for exemplar PR

---

docs/components/store.md

Trivial fixup of incorrect command line parameter.
(trivial change)
Signed-off-by: Jens Erat <email@jenserat.de>
<sup>Jens Erat <jens.erat@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

docs: fix typo in components/store.md

---

.github/dependabot.yml

Fixed dependabot yml.

---

docs/proposals/202012_receive_split.md

Spelling and highlighting for more emphasis.

Updated receive-split proposal for spelling and nitpicks

---

website/static/main.css

Fixed indentation issue and added border
Closes #4209 
Run `make web-serve`

Website: Fix indentation issue

---

pkg/reloader/reloader_test.go

Signed-off-by: arcolife <archit.py@gmail.com>
as the title

label outer for loop breaks in switch cases

---

pkg/ui/react-app/src/thanos/pages/notFound/NotFound.tsx

Fixed incorrect homepage URL on 404 error page
Click Go back to home page

UI: fix incorrect URL on 404 error page

---

pkg/compact/downsample/downsample.go
pkg/compact/downsample/downsample_test.go

This pr exposes `downsampleRaw` for testing purpose.

Expose downsampleRaw for testing

---

pkg/api/query/v1.go
pkg/metadata/metadata.go
pkg/metadata/prometheus.go
pkg/metadata/proxy.go

Signed-off-by: KrishnaSindhur <krishnasindhur@gmail.com>
Add tracing for federated metadata API.
Closes #4132 
- make build
- make test-local

added tracing to matadata api

---

docs/release-process.md

Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>
cc @metalmatze

Nominate `metalmatze` and `onprem` as next release shepherds (for v0.21.0)

---

test/e2e/receive_test.go

Fix problem in CI https://github.com/thanos-io/thanos/runs/2715171646.

Fix E2E receive test

---

docs/components/compact.md

docs: fix concurrency flag

---

docs/contributing/mentorship.md

docs: Added section about Mentees Meetup and Retrospective.

---

docs/components/compact.md

Signed-off-by: Itaachime <sandeeppainuly16@gmail.com>
This PR resolves issue #3954 !

issue #3954 - resolves compactor broken page image

---

CHANGELOG.md
Dockerfile.multi-stage

Signed-off-by: Long Dai <long0dai@foxmail.com>
`apk upgrade` works like `apt upgrade`, it would upgrade OS version which goes against our purpose of ​​using a fixed image version, refer to [doc](https://wiki.alpinelinux.org/wiki/Upgrading_Alpine#Upgrade_Operating_System)

Build: do not upgrade alpine version

---

docs/release-process.md

As agreed on Slack, I will do the next release and @bwplotka will do the
one after.

docs: update release shepherds as agreed

---

CHANGELOG.md
pkg/ui/react-app/src/components/withStatusIndicator.tsx
pkg/ui/react-app/src/pages/graph/DataTable.tsx
pkg/ui/react-app/src/pages/graph/PanelList.tsx
pkg/ui/react-app/src/utils/index.ts
pkg/ui/react-app/yarn.lock

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>
fix #4372 
fix #4184

regenerate yarn.lock to fix codemirror

---

pkg/gate/gate.go
pkg/query/query_bench_test.go
pkg/store/bucket.go
pkg/store/bucket_test.go

Needed for future measurements. cc @spaparaju @ianbillett

querier: Added select benchmark

---

cmd/thanos/receive.go
cmd/thanos/rule.go

Fixes: https://github.com/thanos-io/thanos/issues/4396

receive: Add extra validation for tenant label name.

---

README.md

README.md: fix link to adopters file

---

MAINTAINERS.md

I'm stepping back from Thanos maintainers. Unfortunately I don't have time to follow Thanos dev and community, and I think it's just unfair keep wearing this hat.
Let me just say I ❤️  Thanos community and project! Vibrant, active, nice people. I learned a lot from all of you, thanks!

Stepping back from Thanos maintainers

---

MAINTAINERS.md

I have recently changed organizations, so here is the changeset to reflect that.

Update company for kakkoyun

---

cmd/thanos/tools_bucket.go
pkg/objstore/oss/oss.go
pkg/objstore/testing.go

Certain functions, for a particular set of arguments, have shorthands (helpers) that can be used instead.

Replaced function call with the helper function

---

pkg/promclient/promclient.go

Signed-off-by: songjiayang <songjiayang1@gmail.com>

Using prometheus'config to refactor ExternalLabels method

---

docs/proposals-accepted/202106-automated-per-endpoint-mTLS.md

Just a small nit in the proposal.
`Files` -> `files`  (case-sensitive)

proposal-accepted: correction in spelling

---

CONTRIBUTING.md

Signed-off-by: Hangzhi <1454678938@qq.com>
Fix some minor typos and add an alternative GOPROXY. This GOPROXY is for developers in mainland China who cannot connect the official ` https://proxy.golang.org `.

Fix typo and add a useful alternative GOPROXY

---

.bingo/prometheus.mod

Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
Cherry-picked https://github.com/thanos-io/thanos/pull/4453 partially to fix the build failure.

test: fix build failure with 'make install-deps'

---

CHANGELOG.md

This has just been added so it needs to be under the unreleased section.

CHANGELOG: fix changelog item

---

MAINTAINERS.md

Changed my workplace recently so update MAINTAINERS.md accordingly.

MAINTAINERS: fix my workplace

---

MAINTAINERS.md

Signed-off-by: Ian Billett <ibillett@redhat.com>
Add myself to triage team per email thread with `thanos-io@googlegroups.com`.
N/A

Add ianbillett to triage

---

docs/components/receive.md

Signed-off-by: yangyang <yangyang.chen01@sap.com>

docs: Fix wrong description in /docs/receive.md

---

examples/interactive/interactive_test.go
go.mod
go.sum

Added interactive Thanos e2e example.

---

.lift/config.toml

Signed-off-by: Abhishek357 <abhisheksinghchauhan357@gmail.com>
Added ignore rules for sonatype-lift bot to ignore vulnerabilities of transitive dependency because it is evaluating dependencies that are not even used. Example in this [PR](https://github.com/thanos-io/thanos/pull/4141) this bot flooded with misleading comments.

Added ignore rules

---

CONTRIBUTING.md

Signed-off-by: Ravi <jravi248@gmail.com>
Changed "... as suggested by the Pull Request template." to "... as suggested by the Issue template.", under the "Feedback / Issues" section.
Visual check

docs: Make a small correction in the Contributing guide

---

CONTRIBUTING.md

Fix formatting so that the CI would pass.
Fixes https://github.com/thanos-io/thanos/runs/3534070581

CONTRIBUTING: fix formatting

---

docs/storage.md

As PR #4654 , I am willing to help maintain Tencent COS client for Thanos.
cc @yeya24  @jojohappy
- Update `docs/storage.md`.

Docs: Add object storage maintainer

---

examples/interactive/interactive_test.go

Signed-off-by: metonymic-smokey <ahuja.aditi@gmail.com>
Added the word 'run' to the message in the interactive example.

Minor fix in interactive example

---

pkg/ui/react-app/package-lock.json
pkg/ui/react-app/package.json
pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx
pkg/ui/react-app/src/pages/graph/Graph.tsx
pkg/ui/react-app/src/pages/graph/GraphHelpers.ts
pkg/ui/react-app/src/pages/graph/Legend.tsx
pkg/ui/react-app/src/pages/graph/Panel.tsx
pkg/ui/react-app/src/pages/graph/TimeInput.tsx
pkg/ui/react-app/src/utils/index.ts
pkg/ui/react-app/tsconfig.json

Signed-off-by: Augustin Husson <augustin.husson@amadeus.com>
This PR is upgrading typescript to the last version. It's following the upgrade on Prometheus side: https://github.com/prometheus/prometheus/pull/9300
@onprem this is for you as well :).

upgrade typescript to v4 and fix some eslint warnings

---

docs/operating/modify-objstore-data.md

This pr adds an operation guide of using bucket rewrite tool.
It covers three use cases:
1. Delete series in the obj store
2. Relabel series labels in the obj store
3. Modify local Prometheus TSDB blocks

Add operation guide of bucket rewrite tool

---

cmd/thanos/rule.go
cmd/thanos/sidecar.go
pkg/alert/config.go
pkg/alert/config_test.go
pkg/httpconfig/config.go
pkg/httpconfig/config_test.go
pkg/httpconfig/http.go
pkg/store/prometheus.go
scripts/cfggen/main.go
test/e2e/e2ethanos/services.go
test/e2e/rule_test.go
test/e2e/rules_api_test.go

Rationatles:
* Query HTTP is not for query, it's literally HTTP generic config used by ruler.

Moved http configurations packages around [Refactor]

---

test/e2e/targets_api_test.go

Enabling test from https://github.com/thanos-io/thanos/issues/4069 again since the issue has probably been fixed in the meantime.
Wait on CI run.

E2E Tests: Enable targets API fanout test again

---

docs/proposals-done/201812-thanos-remote-receive.md

Fixed a typo in a reference to REPLICATION_FACTOR
Visual inspection

doc: fix simply typo in thanos receive doc

---

docs/design.md

... instead of its previous name, "master".
Changed `design.md` to link to Prometheus "main" branch (previously called "master").
I opened https://github.com/prometheus/prometheus/tree/main/tsdb/docs/format and can see its contents.

docs: Link to Prometheus "main" branch

---

docs/components/compact.md

* Proof-read the compactor docs and removed some common english mistakes to improve readability
I read it :)

docs: Proof-read compactor docs

---

MAINTAINERS.md

Signed-off-by: Jimmiehan <hanjinming@outlook.com>

Docs: Add myself as triage member

---

test/e2e/compatibility_test.go

* Pass the proper path to the binary in `e2e.NewCommand`
* Use the local `thanos:latest` Docker image to test whether the local
changes work
* Fix configuration generation
* Use `t.Log` for logging, not `fmt`
```
/bin/go test -test.v -timeout 999999s -run ^TestPromQLCompliance$ github.com/thanos-io/thanos/test/e2e
```
works

e2e: fix compliance test

---

examples/interactive/interactive_test.go
test/e2e/query_test.go

Minor fix to interactive test.

---

CHANGELOG.md
docs/components/rule.md
docs/proposals-accepted/202101-endpoint-discovery.md
docs/proposals-done/202005-scalable-rule-storage.md

Fix CI error https://github.com/thanos-io/thanos/runs/4302982378?check_suite_focus=true after the proposal is done.

Update links of scalable rule proposal

---

pkg/promclient/promclient.go
test/e2e/compact_test.go
test/e2e/query_test.go
test/e2e/receive_test.go
test/e2e/rule_test.go
test/e2e/store_gateway_test.go
test/e2e/tools_bucket_web_test.go

Try to add a test for https://github.com/thanos-io/thanos/issues/4549
but couldn't reproduce it :/

e2e: add downsampling testcase to compact_test

---

Makefile

Updated busybox image.

---

Makefile

Previous PR (https://github.com/thanos-io/thanos/pull/4957/files) unfortunately included incorrect SHAs (I copied the wrong lines :cry:). These ones are the correct ones - see from https://quay.io/repository/prometheus/busybox?tag=latest&tab=tags.
:eyes:

*: Correct BusyBox SHA

---

Makefile
docs/proposals-accepted/202108-more-granular-query-performance-metrics.md

1. exec `make docs` to fix CI broken `make check-docs`
1. CI

Fix CI broken `make check-docs`

---

docs/getting-started.md

Relates to https://github.com/thanos-io/thanos/issues/5021

Update docs for new/correct way of building Thanos

---

cmd/thanos/tools_bucket.go
pkg/component/component.go

chore: Use correct component name for bucket tools retention

---

pkg/ui/react-app/package-lock.json
pkg/ui/react-app/package.json

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

bump codemirror-promql to v0,19,0

---

MAINTAINERS.md

docs: Added Matej to Triage Team and Wiard to Core Maintainers.

---

mixin/README.md

Effectively reverts the change from https://github.com/thanos-io/thanos/pull/5107 since we have an alternative link to the resource.
.

Docs: Add mixin design doc again

---

pkg/ui/react-app/package-lock.json
pkg/ui/react-app/package.json
pkg/ui/react-app/src/pages/alerts/AlertContents.tsx
pkg/ui/react-app/src/pages/serviceDiscovery/Services.tsx
pkg/ui/react-app/src/pages/targets/ScrapePoolList.tsx

This new version allows us to remove unnecessary cast in the process
Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

bump kvsearch to v0.5.0 that support generic type

---

website/layouts/index.html

website: Add Ukraine support banner.

---

website/layouts/index.html
website/static/main.css

website: Fixing banner.

---

website/layouts/index.html

Changed wording to "Russia" from Putin, following discussions on Prometheus side: 
* https://github.com/prometheus/docs/pull/2110/files
* https://github.com/prometheus/docs/pull/2103#issuecomment-1086934207

webiste: Ukraine banner update

---

pkg/receive/handler.go
pkg/receive/writer.go

receive: Better error handling of remote write requests.

---

go.mod
pkg/targets/prometheus_test.go
pkg/targets/proxy_test.go
pkg/targets/targets.go

Attempted to repro https://github.com/thanos-io/thanos/issues/5257, but it was fixed in other point of time. Still useful to have more tests here.

Added target API tests (+goleak).

---

CHANGELOG.md

Reviewed and updated Changelog for 0.26-rc0

---

docs/contributing/community.md

We had obsolete information, let's update it (:

Updated information about our community call.

---

CONTRIBUTING.md

Signed-off-by: Wiard van Rij <wvanrij@roku.com>
Closes #5282

Adds more info about the formatting part.

---

cmd/thanos/receive.go
docs/components/receive.md
test/e2e/compatibility_test.go
test/e2e/e2ethanos/services.go
test/e2e/query_test.go
test/e2e/receive_test.go
test/e2e/rule_test.go

e2e: Refactored Receive Builder to be consistent with other helpers.

---

test/e2e/e2ethanos/services.go

e2e: Fixed exemplar support in receive helper.

---

docs/contributing/coding-style-guide.md

I think I've found a replacement for the dead link.

docs: fix link

---

pkg/cache/groupcache.go

Add a unsafe codec which uses the given byte slices directly to avoid
copying - we are doing ioutil.ReadAll() either way so there is no need
to copy anything.

cache: do not copy data in groupcache

---

pkg/alert/alert.go
pkg/alert/alert_test.go

Fixes https://github.com/thanos-io/thanos/issues/5351
Check if the alerts still have valid labels after relabeling.

Fix ruler send empty alerts

---

pkg/receive/multitsdb.go

Pruning Receiver tenants has a race condition caused by concurrently
removing items from the tenants map.
This commit addresses the issue by using a mutex to guard the tenants map.
Note: it might be a good idea to run unit tests with the `-race` flag in the CI.
Address race condition when pruning stale tenants.
```
go test ./pkg/receive/... -race -run TestMultiTSDBPrune -v
```

receive: Fix race condition when pruning tenants

---

docs/storage.md

Signed-off-by: Bishal Das <70086051+bishal7679@users.noreply.github.com>
Changelog entry format:
[#5485](https://github.com/thanos-io/thanos/pull/5486) Query
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

Typo fixed in storage.md file

---

pkg/api/status/v1.go

This commit replaces the copied TSDB status structs with direct
references from prometheus/prometheus.
Reference TSDB status structs from prometheus/prometheus.
Testing on local machine

Reuse upstream TSDB status structs

---

cmd/thanos/config.go
docs/components/sidecar.md

Fixes: #5462
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>

docs: Add Thanos sidecar Prometheus HTTP client config format

---

docs/release-process.md

Add myself as v0.28 shepherd and update the release date to next Monday.

add myself yeya24 to release shepherd for v0.28.0

---

MAINTAINERS.md

chore: Update my company info

---

MAINTAINERS.md

Update my company info

---

docs/operating/modify-objstore-data.md

FYI this was a little hard to figure out as there is no documentation. The deletion config is unmashalled into a slice of `metadata.DeletionRequest`s, which references `tombstones.Intervals` ([source](https://github.com/thanos-io/thanos/blob/78e923df76d0d79a43634027b0329f7e9c339a26/pkg/block/metadata/meta.go#L116)).
[Downstream issue](https://gitlab.com/gitlab-com/runbooks/-/merge_requests/5004)

Docs: Document how to delete an interval via `thanos tools bucket rewrite`

---

pkg/compact/compact.go

Add a log line to have the total time of a single run of compaction. The time duration includes blocks download, index verification, compaction, upload and finally mark source blocks as deletion.

chore: Log compaction run total time from block download

---

docs/components/receive.md
docs/components/store.md
docs/governance.md
docs/proposals-accepted/202206-active-series-limiting-hashring.md

Signed-off-by: Amin Cheloh <amincheloh@gmail.com>
Just fix typo in documents

docs: fix typos

---

CHANGELOG.md
go.mod
go.sum

- Bumps Prometheus to v2.39.1 to include [an important alerting fix](https://github.com/prometheus/prometheus/pull/11427).

*: Upgrade Prometheus to v2.39.1.

---

go.mod
go.sum

Fixes https://github.com/thanos-io/thanos/issues/5820

deps: Updated promql-engine to latest.

---

.github/stale.yml

Attempt to fix #5833 by trying removing some extra whitespaces etc., before diving deeper into config issues.
N/A

*: Clean up stale bot config file

---

.mdox.yaml
docs/blog/welcome.md
netlify.toml
website/layouts/_default/baseof.html
website/layouts/partials/versioning/banner.html
website/layouts/partials/versioning/version-picker.html

Added blog space on Thanos website.

---

scripts/quickstart.sh

*: Fix lint

---

go.mod
go.sum

Update objstore to latest version.
Fixes #5874
The Azure related changes have been verified.

Update objstore to latest commit

---

MAINTAINERS.md

Added Filip and Saswata to maintainers list after internal vote.

---

docs/contributing/community.md
docs/release-process.md

Added bwplotka as community meetings and release shepherd for December.

---

docs/components/store.md
docs/proposals-accepted/202012-receive-split.md
docs/proposals-accepted/202106-automated-per-endpoint-mTLS.md

Signed-off-by: Loong <loong.dai@intel.com>

docs: fix some typos

---

CONTRIBUTING.md

- Add a mention to WSL 2 as possible development environment.

*: Document development in WSL2

---

website/hugo.yaml
website/layouts/blog/list.html

Signed-off-by: Jatin <hyperbolicstech@gmail.com>
Fixed the blog list view, by replacing {{ .Content }} to {{ .Summary}} and also changed the summary length to 50.
Tested on local host.

fixed blog list view in website

---

go.mod
go.sum

This commit updates the Thanos PromQL engine to the latest version.

Update Thanos engine to latest version

---

pkg/query/querier.go

Do not call promgate directly but rather use our own wrapper that does everything we want - duration histogram, current in-flight calls, total calls.

query: reuse our own gate

---

docs/storage.md

* [ x ] Change is not relevant to the end user.

Update typo from `delete-mark.json` to `deletion-mark.json`

---

CHANGELOG.md
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go

Cherry picked https://github.com/thanos-io/thanos/pull/6086

cherry pick store gateway fix to release 0.30

---

README.md
docs/quick-tutorial.md

Signed-off-by: Jonah Kowall <jkowall@kowall.net>
I did not add a changelog for this simple update, but I can if you wish, just leave a comment. 
Feedback appreciated.
This PR fixes up the readme and the diagrams to be more clear and consise on the deployment models with and without Kubernetes. Also fixes up the remote write side of things. Source drawings with full edit are here for the images embedded:
https://docs.google.com/drawings/d/1AiMc1qAjASMbtqL6PNs0r9-ynGoZ9LIAtf0b9PjILxw/edit?usp=sharing
https://docs.google.com/drawings/d/1iimTbcicKXqz0FYtSfz04JmmVFLVO9BjAjEzBm5538w/edit?usp=sharing
View the Readme.md.
Context/discussion: https://cloud-native.slack.com/archives/CK5RSSC10/p1674215527890249?thread_ts=1674069893.558779&cid=CK5RSSC10

Updaing README with drawing fixes and minor wording clarification

---

CHANGELOG.md

This PR merges release branch v0.30 back to main, which includes some new changes for v0.30.2.
Also fixed some changelog entries.
Please merge the PR by using "Merge" commit

Merge release 0.30 to main

---

CHANGELOG.md

Add changelog entry for 5548

---

docs/components/receive.md

Document hashring algorithms

---

CHANGELOG.md
examples/dashboards/store.json
mixin/dashboards/store.libsonnet

Update store dashboard for summary to histogram changes.
* Followup to #6131
* Update changelog to note breaking changes.

Update mixin for new histograms

---

cmd/thanos/store.go
docs/components/store.md

https://github.com/thanos-io/thanos/pull/5773  introduced the modification
cc @wanjunlei

store: fix --no-cache-index-header flag

---

CHANGELOG.md
pkg/querysharding/analyzer.go
pkg/querysharding/analyzer_test.go

Fixes #6209
Added a test case for scalar function to not expect sharding

Disable scalar for vertical sharding

---

.circleci/config.yml

Upgrades orbs used in Circle CI builds to attempt to fix the Github RSA SSH key.

*: Bump Go and git-shallow-clone orbs

---

docs/contributing/mentorship.md

Update mentorship repo links, which cause docs check to fail in #6271

Update mentorship links

---

pkg/tracing/tracing.go

Signed-off-by: aimuz <mr.imuz@gmail.com>

fix: spelling errors DoInSpanWtihErr to DoInSpanWithErr

---

pkg/store/hintspb/custom.go
pkg/store/hintspb/custom_test.go

Fix a bug when merging `SeriesFetchedSizeSum`.

Fix series stats merge

---

MAINTAINERS.md

I've been recently offered to be part of the triage team in the project. I'm happy to accept it. 
This adds me to the triagers list.

Add `@douglascamata` to triagers

---

pkg/store/bucket_test.go

The test case was accidentally changed by me in https://github.com/thanos-io/thanos/pull/6325.

Fix postings test

---

docs/components/query.md

query.md: Added grpc_{client,server}_handled_total to metrics list

---

cmd/thanos/store.go

Follow up of https://github.com/thanos-io/thanos/pull/6441

Estimate block chunk and series size from metadata

---

pkg/store/bucket.go
pkg/store/bucket_test.go

This pr sets expanded posting cache when there is an empty posting group. Previously we don't cache that result, this results in a very low cache hit rate of expanded postings for such query.
```
if !pg.addAll && len(pg.addKeys) == 0 {
return nil, nil
}
```

Cache expanded postings when there is an empty posting group

---

docs/blog/2023-06-08-thanos-at-aiven.md

Fixing the blog on Aiven adoption

Fixing date and author for Aiven blog

---

docs/getting-started.md

I'm adding a blog post about how to use Thanos Ruler and Prometheus Rules, as an simple example to use with the rest of Prometheus Operator and Thanos components
Signed-off-by: Hélia Barroso helia_barroso@hotmail.com
* n/a

[FEAT] Add thanos ruler blog post

---

.mdox.validate.yaml

Ignore nginx.com in mdox link checks as it fails CI, as seen in #6482

Ignore nginx.com links in mdox

---

docs/quick-tutorial.md

Fixes issue https://github.com/thanos-io/thanos/issues/6492
Signed-off-by: Hélia Barroso [helia_barroso@hotmail.com](mailto:helia_barroso@hotmail.com)

[FIX] Documentation issue #6492

---

pkg/queryfrontend/queryinstant_codec.go
test/e2e/compatibility_test.go

chore: pkg imported more than once

---

CHANGELOG.md

Adds a CHANGELOG entry for #6474
* Add changelog entry for #6474

Add changelog for #6474

---

pkg/store/bucket.go

`r.stats.DataDownloadedSizeSum` needs lock for protection

Fix data downloaded size sum race when loading chunks

---

go.mod
go.sum

Update objstore and promql-engine deps to latest before release.

Update objstore and promql-engine to latest

---

scripts/quickstart.sh

Changelog entry format:
- [#6565](https://github.com/thanos-io/thanos/issues/6565) Thanos Repo tools

Bug fix in quickstart

---

pkg/store/postings.go

Store: fix ignored error in postings

---

pkg/store/bucket.go

Fixes concurrent update and iteration over s.blocks

store: fix race when iterating blocks

---

.mdox.validate.yaml
docs/tracing.md

docs: Update lightstep link

---

pkg/store/cache/memcached.go

Use the correct variable for timer.

Fix index fetch latency metric timer

---

CHANGELOG.md
cmd/thanos/query_frontend.go
pkg/queryfrontend/config.go

added tls config in downstream query

---

.mdox.validate.yaml
CHANGELOG.md

Ignore improbable.io links as improbable.io/blogs is 404

Add improbable.io to mdox ignore

---

pkg/block/indexheader/binary_reader.go

As mentioned in https://github.com/thanos-io/thanos/pull/6776#issuecomment-1749988440, let's try and see if RWLock helps with the lock contention issue.

Use RWLock for value symbols cache

---

go.mod
go.sum

Bump Prometheus version to pull https://github.com/prometheus/prometheus/pull/12955

Bump prometheus to latest main

---

pkg/api/query/v1.go

Fix a race where GetPrometheusEngine or GetThanosEngine is called twice at the same time from multiple HTTP requests. This fixes the race:
```
10:29:50 querier-query: ==================
10:29:50 querier-query: WARNING: DATA RACE
10:29:50 querier-query: Write at 0x00c0005fa0f8 by goroutine 285:
10:29:50 querier-query: github.com/thanos-io/thanos/pkg/api/query.(*QueryEngineFactory).GetPrometheusEngine()
10:29:50 querier-query: /go/src/github.com/thanos-io/thanos/pkg/api/query/v1.go:105 +0x1f9
10:29:50 querier-query: github.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).parseEngineParam()
10:29:50 querier-query: /go/src/github.com/thanos-io/thanos/pkg/api/query/v1.go:325 +0x109
10:29:50 querier-query: github.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).query()
10:29:50 querier-query: …
```

api/query: create engines once

---

pkg/store/cache/inmemory.go

From CPU profile of store gateway, inmemory index cache `get` method took about 13% of CPU time, while `CounterVec.WithLabelValues` took about 4% of CPU. Now we call `WithLabelValues` every time when we call `get` method and it can be expensive if we fetch a large amount of series/potings. 
This can be optimized by only update counter once at the end of `FetchMultiSeries` and `FetchMultiPostings` method. 
Existing tests should still pass. The change doesn't affect existing behavior.

Optimize inmemory index cache WithLabelValues call

---

pkg/receive/handler.go

There is a label name/value race in the current loop because `labelpb.ReAllocZLabelsStrings(&t.Labels, r.opts.Intern)` might be called which overwrites the original labels. At the same time, we might also be forwarding the same request through gRPC to other Receive nodes.
Fixes the following race:
<details>
<summary>Trace of the race</summary>
10:53:51 receive-1: WARNING: DATA RACE
10:53:51 receive-1: Read at 0x00c001097b90 by goroutine 361:
10:53:51 receive-1: github.com/thanos-io/thanos/pkg/store/labelpb.(*ZLabel).Size()
10:53:51 receive-1: /go/src/github.com/thanos-io/thanos/pkg/store/labelpb/label.go:273 +0x35
10:53:51 receive-1: github.com/thanos-io/thanos/pkg/store/storepb/prompb.(*TimeSeries).MarshalToSizedBuffer()
10:53:51 receive-1: …

receive/handler: fix label names/values race

---

pkg/queryfrontend/roundtrip_test.go

Fix the following race:
```
Read at 0x00c000614f98 by goroutine 521:
github.com/thanos-io/thanos/pkg/queryfrontend.TestRoundTripQueryCacheWithShardingMiddleware.func1()
/home/giedrius/dev/thanos/pkg/queryfrontend/roundtrip_test.go:612 +0x28e
testing.tRunner()
/usr/lib/go-1.21/src/testing/testing.go:1595 +0x238
testing.(*T).Run.func1()
/usr/lib/go-1.21/src/testing/testing.go:1648 +0x44
Previous write at 0x00c000614f98 by goroutine 532:
github.com/thanos-io/thanos/pkg/queryfrontend.promqlResultsWithFailures.func1()
/home/giedrius/dev/thanos/pkg/queryfrontend/roundtrip_test.go:917 +0x26f
net/http.HandlerFunc.ServeHTTP()
/usr/lib/go-1.21/src/net/http/server.go:2136 +0x47
net/http.serverHandler.ServeHTTP()
/usr/lib/go-1.21/src/net/http/server.go:2938 +0x2a1 …
```

queryfrontend: fix race condition in unit test

---

pkg/extkingpin/path_content_reloader_test.go

Fix race in the test by using an atomic value. The current variable is shared between goroutines.

extkingpin: fix race in test

---

pkg/promclient/promclient.go
pkg/store/bucket.go
pkg/store/labelpb/label.go

Labels are already sorted after unmarshalling from json or yaml

*: remove unnecessary label sorts

---

pkg/ui/react-app/src/thanos/pages/blocks/BlockDetails.tsx
pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx

Updated web ui to honor path prefix in API calls.
Pushed it to my env.

Honor pathPrefix in all api calls

---

.mdox.validate.yaml

https://github.com/thanos-io/thanos/actions/runs/6721963716/job/18268856498?pr=6867
The link is currently giving 503 response and caused docs check to fail. Update mdox config to ignore it.

Doc: mdox ignore 503 link

---

docs/getting-started.md

- Remove dead Banzai Cloud link as it looks like Banzai Cloud has migrated their site, and this article has been lost.

Doc: remove dead Banzai Cloud link

---

pkg/cacheutil/async_op.go
pkg/cacheutil/memcached_client.go
pkg/cacheutil/redis_client.go

Expose `NewAsyncOperationProcessor` so that it can be used in downstream projects

Expose asyncOperationProcessor

---

CONTRIBUTING.md

Removed gitpod script from the contribution.md
#6905

Removed the gitpod from the contribution.md

---

MAINTAINERS.md

Added myself to MAINTAINERS.md
:tada:

MAINTAINERS.md: add myself as maintainer

---

CHANGELOG.md
docs/storage.md
go.mod
go.sum

Cherry-Pick objstore bump for 0.33 release

Objstore: Bump Objstore for Azure Workload Identity support (#6891)

---

pkg/runutil/runutil.go

Fix comment on runtime/CloseWithErrCapture #5580

update runtime/CloseWithErrCapture comment

---

.mdox.validate.yaml

Twitter access throws 400 and it requires authentication now

Mdox ignore checking twitter urls

---

MAINTAINERS.md

Should be done in January last year...

Update MAINTAINERS.md (Bartek's company)

---

docs/components/rule.md

Changed the comment according to markdown format `docs/components/rule.md`

resolved issue #7024

---

docs/components/tools.md

Docs error introduced in [this](https://github.com/thanos-io/thanos/commit/6fd0ef88397887a4d6b9ee3db3b2197c254358c4#diff-89840bcebb29ac15c25fad738d4d95c327074e0559da78e4851b696d9533c267) commit
ran make docs to fix tools.md

docs: fix docs error

---

pkg/store/acceptance_test.go
pkg/store/proxy.go

* Add basic acceptance tests for proxy store
* Fix bug where invalid requests got ignored because of partial response strategy
* new acceptance tests for proxy store

Store: acceptance test for proxy store

---

CHANGELOG.md
docs/components/rule.md

Adds rendered doc changes from prior PR

Extended func support - doc update

---

pkg/query/remote_engine.go

Similar to https://github.com/thanos-io/thanos/pull/6957, we should copy labels from remote instant queries so that memory does not get overwritten when processing series in a central engine.

Copy labels from remote instant queries

---

test/e2e/query_frontend_test.go

Adding tests for explain/analyze with QFE. Will add fixes as separate PR.

e2e/query_frontend: add tests for explain/analyze

---

docs/getting-started.md

I'm adding a blog post about how to manage long term storage and querying with Thanos.
Signed-off-by: Hélia Barroso [helia_barroso@hotmail.com](mailto:helia_barroso@hotmail.com)

[FEAT] Adding blog post

---

CHANGELOG.md

* The pull request reference for the introduction of GOMEMLIMIT is incorrect.

fix(changelog): fix GOMEMLIMIT pull request reference

---

go.mod
go.sum

Bump promql-engine version to include samples counting.

go.mod: bump promql-engine

---

pkg/extkingpin/flags.go

Fix incorrect comments

---

CHANGELOG.md
pkg/logging/http.go

- Adding User Agent to HTTP Request

[CHORE] adding user agent

---

website/layouts/index.html

Added trademark line and URL which fixes #7104

web:added Trademark URL

---

test/e2e/compact_test.go
test/e2e/e2ethanos/services.go

Adding a minimal test case for issue #6775 - reproduces the panic in the compactor.

e2e/compact: add repro for issue #6775

---

internal/cortex/chunk/cache/redis_cache.go

level change

---

MAINTAINERS.md

Docs: update my affiliation

---

CHANGELOG.md

I am just adding a warn to the change log as per suggestion of @fpetkovski and @MichaHoffmann.

Appending warn to changelog about breaking change

---

pkg/receive/multitsdb.go
pkg/store/flushable.go
pkg/store/tsdb.go

Remove serverAsClient usage to reduce CPU usage.

receive: remove serverAsClient usage

---

.github/dependabot.yml

* Remove unused/broken `vendor` key.
* Increase Go PR limit from 5 to 20.
* Fixup yaml consistency.
`yamllint`

Fixup dependabot config

---

go.mod
go.sum

Bump objstore version

---

.bingo/minio.sum

This is minor change to remove mention of unused package.
There's a vulnerability https://nvd.nist.gov/vuln/detail/CVE-2024-38513 and our security scanner triggers on it.
Removing this does not affect anithing.

removed mention of unused pkg

---

MAINTAINERS.md

Thank you all for the last 5 years!

Remove metalmatze from Thanos maintainers

---

MAINTAINERS.md

I've been invited to be a triager on Thanos. I thankfully accept.

Add @harry671003 to triagers

---

docs/getting-started.md

docs: add saswatas youtube introduction to blog

---

CHANGELOG.md

Update CHANGELOG.md after #7614

---

docs/getting-started.md

* Added Thanos Blog by CloudRaft https://www.cloudraft.io/blog/scaling-prometheus-with-thanos

Added Scaling Prometheus with Thanos Blog from CloudRaft

---

.github/workflows/codeql-analysis.yml

https://github.com/github/codeql-action?tab=readme-ov-file#permissions needs this

Fix CodeQL checks on main

---

.mdox.validate.yaml
cmd/thanos/receive.go
docs/components/receive.md

receive: mark too-far-in-future flag as non-experimental

---

docs/blog/2023-11-20-life-of-a-sample-part-1.md

Added embedded style attribute in images that are rendered too big.
I have tested this locally running `make web-serve`.

Fix blog article img rendering for Life of a sample Part I

---

MAINTAINERS.md

I was invited by @fpetkovski  to become a Triager for Thanos, role that I would be pleased to accept.

Adding @pedro-stanaka as Triager

---

pkg/query/querier_test.go
pkg/store/proxy_merge.go
pkg/store/proxy_test.go
pkg/store/storepb/testutil/series.go
pkg/store/storepb/testutil/store_series_client.go

Reuse chunks map instead of creating a new one each time. This is a hot path and shows up in profiles.

store: reuse chunks map

---

pkg/receive/multitsdb.go

receive/multitsdb: defer unlock properly

---

go.mod
go.sum

Pull https://github.com/prometheus/prometheus/pull/15250

upgrade Prometheus to fix round function

---

.mdox.validate.yaml

docs: Add link to ignore

---

docs/components/receive.md
docs/components/sidecar.md
docs/components/store.md
docs/components/tools.md
docs/storage.md

docs: Fix formatting again

---

go.mod
go.sum

Update promql-engine for subquery fix

---

pkg/promclient/promclient.go

Sidecar: Ensure limit param is positive for compatibility with older Prometheus

---

cmd/thanos/receive.go
docs/components/receive.md

Close #8024
Unhide `tsdb.out-of-order.time-window` and `tsdb.out-of-order.cap-max` flags

receive: unhide tsdb.out-of-order.time-window and tsdb.out-of-order.cap-max

---

cmd/thanos/rule_test.go
go.mod
go.sum
pkg/receive/writer_test.go
pkg/store/labelpb/label_zlabel_test.go

I expect these releases to break certain label validations everywhere, PR to help catch them.

Bump common+client_golang to deal with utf-8

---

cmd/thanos/receive.go
docs/components/receive.md
test/e2e/distributed_query_test.go
test/e2e/e2ethanos/services.go
test/e2e/native_histograms_test.go
test/e2e/query_frontend_test.go
test/e2e/query_test.go
test/e2e/receive_test.go

e2e: use prom 3

---

CHANGELOG.md

- Fix markdown formatting in CHANGELOG.

Fix changelog markdown.

---

CHANGELOG.md
cmd/thanos/config.go
docs/components/sidecar.md

Sidecar: increase default prometheus timeout

---

CHANGELOG.md
cmd/thanos/tools_bucket.go
docs/components/tools.md

Adds min,max time, timeout and label selector via relabelling config to the `ls` command

tools: Extend bucket ls options

---

pkg/reloader/reloader_test.go

reloader: disable some flaky tests

---

test/e2e/tools_bucket_web_test.go

These are flaky hence disable them.

e2e: disable some more flaky tests

---

pkg/tracing/otlp/config_yaml.go
pkg/tracing/otlp/otlp.go

Optimize OTLP ClientType enumerate

---

.promu.yml

Signed-off-by: Ben Dronen <dronenb@users.noreply.github.com>

feat(promu): add darwin/arm64

---

docs/components/receive.md

Fix the docs after the most recent merge.

docs: fix receive page

---

pkg/api/query/v1.go

Fixes: #8257 
Currently we are calling `parseQueryAnalyzeParam` before executing the query, this will mean execution time at each operator, peak samples and total samples returned in UI are defaults based on just plan.
Tried out on local setup, should we add tests ?
range queries
instant queries
If query is not analyzable, appropriate "warning" is returned

query: fix query analyze to return appropriate results

---

docs/blog/welcome.md
docs/components/store.md

All GithubActions are failing due to minor changes such as :
- Fix the broken link to Prometheus Blog Page for updates
- New Flag docs

Resolve GitHub Actions Failure

---

test/e2e/rule_test.go
test/e2e/rules_api_test.go

Checking to see the validity of https://github.com/thanos-io/thanos/issues/8207
cc: @coleenquadros

e2e: Check rule group label works

---

test/e2e/receive_test.go

Add repro for https://github.com/thanos-io/thanos/issues/8224. Fix in follow up PRs.

e2e: add repro for 8224

---

cmd/thanos/query_frontend.go

Let's avoid using all the Cortex roundtripper machinery by using the downstream roundtripper directly and then close the body immediately as to not allocate any memory for the body of the response.

cmd/query_frontend: use original roundtripper + close immediately

---

scripts/quickstart.sh

Disables starting sidecar if user specified REMOTE_WRITE_ENABLED.
Based on the design online, running both these components simultaneously seems unintended: https://thanos.io/tip/thanos/quick-tutorial.md
Note: `seq 0 1 2` and `seq 0 2` are the same.
With REMOTE_WRITE_ENABLED
Without REMOTE_WRITE_ENABLED
Note: Some endpoints still seem misconfigured given the number of services with "0". This is still progress, though.

Don't start sidecar if REMOTE_WRITE_ENABLED env var present

---

MAINTAINERS.md
docs/components/store.md

Removing myself from the maintainers section.
I have verified this decision with myself 💔 
Thank you to the whole team for the journey and all the great experience and learning, I deeply appreciate all of it!

Remove @matej-g from maintainers

---

pkg/info/info.go

chore: fix comment typo
