thanos-io/thanos

docs/design.md

A first version of the overall design.
I also added a cost estimate at the bottom. Please don't quote me on it – especially the instance types are a completely wild guess. But since they account for a relatively small percentage, it might still be close. Resources for collecting Prometheus servers not included.

docs: add initial design overview

---

Makefile

Fixed goimports make target to exclude vendor properly.

---

cmd/promlts/sidecar.go
pkg/shipper/shipper.go
pkg/shipper/shipper_test.go
pkg/testutil/prometheus.go

The shipper is only concerned with detecting and passing directories or
files to a remote uploader. It's agnostic to TSDB itself so we can
simplify the unit test accordingly.
Fixes #20

Fix test flakes/errors

---

cmd/promlts/example.go
cmd/promlts/main.go
cmd/promlts/query.go
cmd/promlts/sidecar.go
cmd/promlts/store.go
pkg/query/fanin.go
pkg/query/querier.go
pkg/store/promproxy.go
pkg/store/storepb/rpc.pb.go
pkg/store/storepb/rpc.proto
pkg/store/storepb/types.pb.go

This adds an `Info` method to the store API to get meta information (right now just the store's labels).
We can now discover store nodes via a DNS lookup. Connections will then be instantiated and a store pool periodically queries the store's Info endpoint.

Add dynamic store node discovery

---

cmd/thanos/sidecar.go
pkg/shipper/gcp.go
pkg/shipper/shipper.go
pkg/shipper/shipper_test.go

This makes the shipper and remote components more aware of what they are
uploading. The Shipper now attaches a Thanos specific section to the
meta.json file where it attaches the external labels for the block.
The shipper now stages all files in a separate directory, making it less
vulnearable to other processes messing with the currently uploaded
files.
@Bplotka

shipper: make shipper aware of block layout

---

cmd/thanos/sidecar.go
pkg/cluster/cluster.go
pkg/cluster/stores.go
pkg/query/querier.go
pkg/store/promproxy.go

This actually fixes the races with pushing the metrics without external labels first, but actually it shows a shortcoming of exposing ext labels as unique attribute for store nodes. As it makes sense on sidecar, GCS store node does not necessary query data for same external labels.. also we maybe want to know which one is GCS store, which one is sidecar... so I guess, Peer.Label info for GCS store node needs to be some arbitrary value configured on startup?

Added labels to peer, added querying external labels as initial step in sidecar.

---

Gopkg.lock
pkg/block/block.go
pkg/shipper/shipper.go
pkg/shipper/shipper_test.go
pkg/store/gcs.go
pkg/store/gcs_test.go
pkg/testutil/objstore.go

This factors our the test bucket setup and deletes buckets more reliably.
I created `pkg/block` to interact with TSDB blocks. We have minimal custom additions in meta.json right now but that might become more over time.
This is being used in the shipper and now in the store as well.
The rest is correct handling of those meta.json files in `pkg/store`. It's a bit awkward to now also introduce `map[string]string` now as a representation for labels. But writing the 500th variant of `MarshalJSON` for labels is not much better as an alternative.
@Bplotka

Improve testing, handle block labels

---

Gopkg.lock
pkg/query/fanin.go
pkg/query/promadapter.go
pkg/query/querier.go
pkg/query/querier_test.go
pkg/store/gcs.go
pkg/store/storepb/custom.go

@Bplotka 
We are now doing all the merging ourselves. But nicely enough we know convert straight from `storepb` to `prometheus/prometheus/storage`. Thereby this package should now not have any deps onto `prometheus/tsdb` directly (just the chunks package).
The main reason is that we not only get overlapping chunks, but also get series set with no time ordering at all, which `prometheus/tsdb` mostly assumes. Later we will need to add more logic for merging series from HA pairs – so having it all here might be good after all.

Improve and test query fanin

---

cmd/thanos/store.go
pkg/store/gcs.go
pkg/store/gcs_test.go

This also fixes a wrong `defer Close()` call, which should've be called on the GCS object reader. At the same time, this is most likely what caused #66

Add basic store metrics, respect context in chunk reader

---

cmd/thanos/query.go
pkg/query/fanin.go
pkg/query/querier.go
pkg/query/querier_test.go

To be able to merge series from different replicas efficiently, we need
to align the sequentially in our series set so we can greedily grab them
until a new series is found.
To fully leverage the streaming API, we'd need to push this logic down
into the store servers, which could attach the (external) replica label
in the way we construct it here. For now this is sufficient without
adding API complexity.
@Bplotka 
This is just a very first step, but since it will get reasonably complex, it's probably a good idea to make multiple PRs.

query: add re-ordering of store input by replica labels

---

Gopkg.lock
Gopkg.toml
pkg/query/api/v1.go
pkg/query/querier.go
pkg/query/querier_test.go

@Bplotka 
Also contains the changes to the rules package in my dev branch so we can properly implement the rule component.

vendor: update TSDB and Prometheus

---

Gopkg.lock
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/rule.go
pkg/cluster/stores.go

This adds a command that queries a random query node to evaluate rules
and prints firing alerts to standard output.
@Bplotka After lots of struggle with the upstream package, here it goes :)
For now I just made query nodes expose their HTTP address as APIAddr in the gossip state. We might just want to make grpc/http address fields explicit in there eventually.

main: add initial rule evaluation command

---

cmd/thanos/rule.go
cmd/thanos/sidecar.go
pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/promproxy.go
pkg/store/tsdb.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

@Bplotka 
I'm writing an e2e test for the rule<>query interaction now but this code here is good for review already.

Expose data from rule component

---

Gopkg.lock
Gopkg.toml
cmd/thanos/store.go
pkg/block/index.go
pkg/query/iter.go
pkg/query/querier_test.go
pkg/store/gcs.go
pkg/store/gcs_test.go
pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/tsdb.go

I still need to adapt/add some tests and want to improve instrumentation. But generally the code is cleaned up now and things work fine in my manual testing. Everything still feels pretty fast.
Still without any caching at all `count(apiserver_request_count)` over 6h (5s scrape interval) returns in about 3 seconds and fetches a total of ~4700 series. For comparison, computing a rate over that bumps it to 5.4 seconds.
@Bplotka

 Fetch index information on demand

---

pkg/objstore/inmem/inmem.go
pkg/query/querier.go
pkg/store/bucket.go
pkg/store/matchers.go
pkg/store/posting_test.go
pkg/store/storepb/custom.go
test/e2e/spinup_test.go

Caching in next will be in  next PR.

Made sure posting preload does not load too much irrelevant bytes.

---

Gopkg.lock
pkg/store/bucket.go

Fix panic in index loading

---

cmd/thanos/main.go
cmd/thanos/store.go
pkg/store/bucket.go

This refactors the store a bit and adds a lot of stats and metrics. We might not need all of either in the long run but I wanted to go with exposing a lot so we have decent means of debugging.

Add metrics for bucket store

---

cmd/thanos/query.go
pkg/query/api/v1.go
pkg/query/api/v1_test.go
pkg/query/querier.go

Just some cleanup to align with how we are handling things elsewhere. Gets rid of some dependencies as well.

query: cleanup unused UI endpoints, remove option struct

---

cmd/thanos/rule.go
cmd/thanos/sidecar.go
pkg/shipper/shipper.go
pkg/shipper/shipper_test.go

@Bplotka 
We keep a simple local file in the data dir that we rebuild on every call to `Sync` it contains IDs of all blocks that we already uploaded and that exist locally.
I simplified the timestamp handling a bit. The gossip stuff still leaked into the shipper quite a bit. Now it's a simple function that tells us what the minimum timestamp we have is and up to which timestamp we have synced data (new but not used yet).
The connection to gossip then just happens in `main`.
I moved the test back to use actual GCS for now since I'm not quite confident enough that our in-mem and GCS implementations are equivalent (we just didn't really specify a lot of behavior).

Don't reupload blocks in shipper, simplify timestamps

---

cmd/thanos/compact.go
cmd/thanos/main.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/compact/compact.go
pkg/compact/compact_test.go
pkg/objstore/gcs/gcs.go
pkg/objstore/inmem/inmem.go
pkg/objstore/objstore.go
pkg/shipper/shipper.go
pkg/shipper/shipper_test.go
pkg/store/bucket.go
pkg/store/bucket_test.go
pkg/testutil/objstore.go

The bucket interface is simplified to the most granular operations. Everything else is handled via helpers in the objstore package. I also concolidated other packages' interface definitions to a single on there.
Since our bucket operations are now so precise, I figured it makes sense again to have an abstract metric wrapper. The actual operations should be a pretty straightforward 1:1 mapping for any object storage backend. Having a single metric makes it easier to share alerting rules and debugging advice etc.

*: simplify Bucket interface, migrate pkgs

---

pkg/alert/alert.go

Using the actual `cap()` of the slice requires very careful usage of it. Fixing it to an attribute is much safer.

alert: fix alert queue capacity

---

cmd/thanos/compact.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/alert/alert.go
pkg/cluster/cluster.go
pkg/cluster/stores.go
pkg/query/querier.go
pkg/query/querier_test.go
pkg/store/bucket.go
pkg/store/bucket_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

This adds timestamp-based filtering to the querier so it won't always hit the store node for rule evaluations and short-term queries. This does not include minimizing overlapping ranges between store and source nodes yet.
Fixes quite a few bugs along the way, hopefully including the very flaky (and correctly so) rule e2e test.
Removed some metrics in the cluster since we switched to non-blocking dialing a while ago, which made them mostly obsolete/useless.

store,cluster: handle timestamps properly

---

cmd/thanos/main.go
pkg/cluster/stores.go
pkg/store/bucket.go

Increased gRPC max msg size for client recv to the maximum possible (2GB)

---

pkg/store/bucket.go
pkg/store/bucket_test.go
pkg/store/storepb/custom.go

I addressed #154 upstream via https://github.com/prometheus/tsdb/pull/233.
Once it is merged there, these changes will automatically make use of it.
This potentially reduces requests to the object storage significantly.

store: skip postings preloading for unmatching blocks

---

Gopkg.lock
Gopkg.toml
pkg/store/bucket.go
pkg/store/bucket_test.go
pkg/store/storepb/custom.go

We managed to get all our upstream changes in the other day. So now we can pin our dependency back to master. A few other non-trivial changes have landed there. So for the next rollout we do we should keep an eye out for issues potentially related to that.

vendor: update prometheus/tsdb

---

Gopkg.lock
test/e2e/spinup_test.go

Upstream changed the flag library. 
PR for visibility. Will merge straight away to fix broken builds on other PRs.

test: fix Alertmanager flags

---

pkg/block/block.go
pkg/compact/downsample/downsample.go
pkg/compact/downsample/downsample_test.go

This implements, as discussed a special chunk type for aggregations. This prevents blow up of series count and index size on downsampling. It also makes subsequent handling of aggregated data easier, since for some queries we have to match and align different aggregates, e.g. sum and count to compute an average series.
This also addresses comments from the original PR #176 
All other work that was done for downsampling should be rebased onto this.
@Bplotka let me know whether you want to review it as the delta against #176 or whether I should file it against master.

Implement special aggregate chunk type for downsampling

---

README.md

With S3 API support virtually everything should be supported now.

Remove hints about unsupported object storages

---

pkg/compact/downsample/downsample.go
pkg/compact/downsample/downsample_test.go

These changes contain:
* Simplified the aggregate chunk serilization format – it was to complex for little benefit. Now we just  set the sub-chunk length to 0 if we want to signal an aggregate is omitted
* We don't omit chunks anymore for now regardless. Always generate all aggregates
* Ensure mint/maxt are set on aggregate-of-aggregate chunks
* Add AverageChunkIterator to combine sum/count chunks into a stream of averages
* Properly handle the Stale NaN signal samples
* Skip over samples that go back in time

downsample: fix various issues

---

cmd/thanos/downsample.go
cmd/thanos/main.go

This command simply looks at exisiting blocks and downsamples them. It's what I've been using for my tests. We might just fold it into the compact command but the glue code to tie into `pkg/compact/downsample` will stick around.

main: add downsample command

---

pkg/store/bucket.go
pkg/store/bucket_test.go

@Bplotka 
Definitely some tests missing overall – will add some later.

store: support serving downsampled data from bucket

---

docs/getting_started.md

We need `dep ensure` first to make sure we have right dependencies.
This should solve https://github.com/improbable-eng/thanos/issues/203 @V3ckt0r

docs: Recommend `go get` with `-d` flag to just download thanos.

---

Gopkg.lock

Raising this to fix build issue with `dep ensure` failing in CI build:
```
dep ensure
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/prometheus/prometheus: fatal: failed to unpack tree object 126770e81fa24752b30cbcde54cb96d95b243ea5
: exit status 128
```

updated hash for prometheus@queryparams

---

cmd/thanos/query.go
pkg/query/api/v1.go
pkg/query/api/v1_test.go
pkg/query/querier.go
pkg/query/querier_test.go

This is stil weird since Queryable should be a base not per request, but this is better than context hack we had.

query: Moved away from querier params passed by context.

---

cmd/thanos/bucket.go

@Bplotka a little POC of a command.
Standard, just print IDs:
```
./thanos bucket --gcs-bucket <name> ls
01BZ2KS2M97KET6BE8BBW6KJQJ
01BZ2MXPG9NXXB2VGWA4R5ABQ8
01BZ2P2AFMD5TWXXQ7F02QPKHB
01BZ2Q6ZJYT2R3N1ZM4P54XT7T
01BZ2RBJ2N2972QKSR56FJN27Z
01BZ2SG5Z1H6MN9EKCVG0CYE1Q
01C18S2S39ZQ4VK43SKVYBRKSR
...
```
Print JSON:
```
./thanos bucket --gcs-bucket h-te1-thanos ls -o json
{
"version": 1,
"ulid": "01BZ2KS2M97KET6BE8BBW6KJQJ",
"minTime": 1510840800000,
"maxTime": 1510842000000,
"stats": {
"numSamples": 2302468,
"numSeries": 134223,
"numChunks": 134223
},
"compaction": {
"level": 1,
"sources": [
"01BZ2KS2M97KET6BE8BBW6KJQJ"
]
},
"thanos": {
"labels": {
"monitor": "inframon",
"monitor_cluster": "h-te1",
"monitor_env": "testing"
}
}
}
{
"version": 1,
"ulid": "01BZ2MXPG9NXXB2VGWA4R5ABQ8", …
```

main: add bucket command

---

Gopkg.lock
cmd/thanos/sidecar.go
pkg/reloader/reloader.go

Triggering of config reloads is a common sidecar need for Prometheus in
various cluster schedulers. Additionally, substituting environment
variables in the configuration is not supported by Prometheus natively
but greatly simplifies deployments.
@Bplotka 
As discussed on IRC yesterday. I wasn't quite happy with existing packages as they did no hash-diff on the files aside from not supporting envvar substitution. They also had custom, k8s-centric logic on top.

sidecar: add config reloader

---

cmd/thanos/compact.go
cmd/thanos/store.go

For commands that support use of an S3 bucket (not all do), make the GCS
bucket flag optional.
Otherwise, Thanos fails to start because `--gcs.bucket` is not set.

Make GCS bucket optional where S3 bucket supported

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
pkg/compact/compact.go

This runs the verification procedure before and after we create new blocks from previous blocks. The compactor will block indefinitely and the downsample
run will terminate with an error.

compact/main: verify compacted and downsampled blocks

---

scripts/quickstart.sh

Without this flag, requests to `/-/reload` on the Prometheus instances
return a HTTP 403, which shows in the logs when running `quickstart.sh`:
level=error name=sidecar-1 ts=2018-03-06T23:00:20.548170907Z caller=reloader.go:71 component=reloader msg="triggering reload failed" err="received non-200 response: 403 Forbidden"
level=error name=sidecar-2 ts=2018-03-06T23:00:20.814485689Z caller=reloader.go:71 component=reloader msg="triggering reload failed" err="received non-200 response: 403 Forbidden"
level=error name=sidecar-3 ts=2018-03-06T23:00:21.06514265Z caller=reloader.go:71 component=reloader msg="triggering reload failed" err="received non-200 response: 403 Forbidden"

quickstart.sh: Enable web lifecycle URLs

---

pkg/objstore/s3/s3.go

`minio.Core` is a low-level primitive; as far as I can tell, we don't
need access to the low-level API so use `minio.Client` instead.
`minio.NewV4()` is used under the hood by `minio.NewCore()`, so there is
no change in functionality here.
From the documentation:
https://godoc.org/github.com/minio/minio-go#NewCore
> Returns new initialized a Core client, this CoreClient should be only
> used under special conditions such as need to access lower primitives
> and being able to use them to write your own wrappers.

objstore: Use high-level S3 API

---

cmd/thanos/compact.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

Passing credentials as command-line flags is not good security practice
as the credentials are visible to any other user on the system.
Using environment variables to pass credentials also has its problems,
but in lieu of using a configuration file, don't allow users to pass the
S3 secret key as a command-line flag.

Don't allow S3 secret key to be passed as a flag

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
pkg/compact/compact.go
pkg/compact/compact_test.go

This extends the compactor to consider downsample resolutions to the compaction grouping. With this it is safe to run the compactor against a bucket with data of different resolutions.
Furthermore #183 is likely to be cased by semantical races in the compactor. The PR drastically simplifies the logic and gets rid of any disk caching of meta.json files and just rebuilds groupings on demand. It is very unlikely that this has any noticable performance impact.

Simplify compactor and respect resolutions

---

cmd/thanos/compact.go
pkg/compact/compact.go

This adds a downsampling pass after all compaction work has been done.
By default the compactor will exit now after all compactions and
downsamplings completed, which makes deployment as a batch job easy.
The `--wait` flag restores previous behavior where the process keeps
running and waiting for new work.

main: downsample in compactor, exit on complete

---

cmd/thanos/main.go

The gokit logger expects key-value pairs. Previously, this line would
cause:
exiting=(MISSING)
...to appear in the logs.
It should now be:
msg="exiting"
...which is consistent with other log entries from Thanos.

Fix missing value in log entry

---

Gopkg.lock
Gopkg.toml
pkg/compact/compact_test.go

I think we should pin to some version. Maybe it's bit manual to adopt to new changes, but at least we will be able to track down what version of TSDB we use in given Thanos revision.
@fabxc PTAL

Pinned to fresh TSDB and updated deps.

---

cmd/thanos/compact.go
pkg/compact/compact.go
pkg/compact/compact_test.go

Fixes https://github.com/improbable-eng/thanos/issues/246

compact: Make sure sources are removed after compaction.

---

cmd/thanos/store.go

This comment is inaccurate; the store instance is currently run as a
single instance and does no coordination between peers to determine
which subset of data from the object store it should be responsible for
serving.
A single store instance is responsible for all of the data in a single
object store bucket.

store: Remove mention of hashing in comment

---

cmd/thanos/compact.go

Add a 1-hour compaction level for blocks using a block size smaller than
the 2-hour default used by Prometheus. For block sizes using the default
(or larger) block size, this compaction level will be ignored.
Relates to #263.

compact: Add a 1-hour compaction level

---

kube/manifests/prometheus-gcs.yaml
kube/manifests/prometheus.yaml

..To avoid having the thanos sidecar throw a `level=error ts=2018-04-08T13:07:32.559863231Z caller=reloader.go:72 component=reloader msg="triggering reload failed" err="received non-200 response: 403 Forbidden"`

Add web.enable-lifecycle to k8s samples

---

cmd/thanos/compact.go
pkg/compact/compact.go

I think this one is critical fix @fabxc
Before it, my removal of group dirs in local dir was simply not working (and err ignored), so I think I had all these compact overlaps because my compact planning was including ALL blocks (no matter what group O.o)

compact: Move downsampling and compact to sub dirs to avoid removal of potentially mounted dir.

---

cmd/thanos/compact.go

This comment is no longer accurate as of f30c0d5fb; we no longer compact
in the top-level directory.
/cc @Bplotka

compact: Remove outdated comment

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main.go
pkg/block/index.go
pkg/compact/compact.go
pkg/verifier/index_issue.go

compact: Added overlap check before and after compact. Added extra index check for outsiders.

---

cmd/thanos/compact.go
pkg/compact/compact.go
pkg/compact/compact_test.go
pkg/objstore/objstore.go
pkg/runutil/runutil.go

Currently, we have a similar issue as with prom 2.2.0 compaction.
< Critical fix >
For newly uploaded compacted blocks we need to assume strong consistency for object storage.
If not, we need to address it somehow with file locks or something like that. Basically, compaction is not safe to be planned without whole overview. (except fresh blocks - these can be safely excluded)
GCS has strong write-read consistency: https://cloud.google.com/storage/docs/consistency
S3 has weird consistency, but seems to be write-read for newly created objects:  https://codeburst.io/quick-explanation-of-the-s3-consistency-model-6c9f325e3f82

compact: Use sync-delay only for fresh blocks. Refactored halt, retry logic.

---

docs/getting_started.md

Minor doc fix: the example for running thanos query with deduplication has a non-existent flag.

Fix thanos query replica-label flag

---

pkg/query/api/v1.go

Documentation and even code comments suggest the deduplication feature is enabled by default, which is actually not the case. This change makes using Thanos querier as a standard Grafana datasource work as expected.

Enable deduplication by default in querier

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
docs/components/store.md
pkg/objstore/client/factory.go
pkg/objstore/s3/s3.go
pkg/objstore/s3/s3_test.go

Fixes #291 
This uses the builtin SetAppInfo from Minio to create "Minio (darwin; amd64) minio-go/4.0.9 Thanos/<version> (go1.10.1)" user agent string for requests.

Set custom user agent for S3 store client

---

cmd/thanos/sidecar.go
pkg/query/storeset.go

This PR makes the sidecar error out directly, when no external labels are configured, following @fabxc's suggestion in #266. In order to be able to alert on non-unique sets of external labels I chose to expose a metric that hashes the external labels and increments the time-series for each occurrence, that way an alert can fire, when there are any time-series that have their value >1.
The only trouble I'm having with the metric approach I took is that I can't immediately see which combination of external label is problematic, registering a metric with the external label pair is sadly not possible as the prometheus metrics registry will reject samples that have varying label sets.
Closes #266
@Bplotka @fabxc

External label uniqueness

---

cmd/thanos/store.go
pkg/block/block_test.go
pkg/shipper/shipper.go
pkg/store/bucket.go

This improves the startup time when most files are cached (we load using multiple concurrent workers).
Improves: https://github.com/improbable-eng/thanos/issues/309

store: Reuse sync block for initial sync block.

---

pkg/query/storeset.go
pkg/query/storeset_test.go
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

Problems:
- we were checking ext labels on old stores not new ones. As a result we were adding and deleting peer all the time for duplicates.
- we were blocking multiple store nodes use case, since they don't have ext labels.
Plus, added test. PTAL @brancz 

store: Fix storeset to check external label duplicates correctly and allow multiple store nodes.

---

pkg/objstore/s3/s3.go

This allows us to set a `ResponseHeaderTimeout` which avoids
cases where the client blocks forever when the S3 endpoint
takes connections but doesn't return anything.
Fixes #315

Use custom roundtripper in the minio client

---

Gopkg.lock
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

Makes all flag descriptions start capitalized and end with period (same
as in Prometheus). Some descriptions descriptions had other
typos/problems.

Make flag caps/punctuation consistent, fix some descriptions

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/objstore/client/factory.go

Replaces copy and pasted object store initialization with an already existing factory function.
Also makes sure that metrics are created whenever the object store instance is required.
Signed-off-by: Łukasz Jernaś <deejay1@srem.org>

Replace gcs/s3 bucket init code with factory

---

Makefile

I will manually remove `latest` and `master` tags from now on.
Basically it was really risky. In case of bug we were not able to properly tell what exactly commit is deployed. Also having "AlwaysPull` k8s policy and `master` leads to having rolled out different versions of thanos which is not safe.
Related to https://github.com/improbable-eng/thanos/issues/325 when we cannot tell what exactly commit it was running.

make: Turned default pushed image tag to branch-date-commit to avoid just "master" or "latest" images.

---

Gopkg.lock
Gopkg.toml
pkg/objstore/s3/s3.go

Enable support for SSE.
I've tested out this bit using my docker image, and it looks good:
```
level=info ts=2018-05-16T04:50:16.144065497Z caller=shipper.go:185 msg="upload new block" id=01CDJJRTXS20130C0QEMQ7T8GS
level=info ts=2018-05-16T04:50:26.61080944Z caller=shipper.go:185 msg="upload new block" id=01CDJSMJ5TFJXF82F7FVZXPM6H
level=info ts=2018-05-16T04:50:37.515684352Z caller=shipper.go:185 msg="upload new block" id=01CDK0G9DS7H7VXNK7BMBY1AZC
```
```
thanos bucket ls
```
```
01CDJJRTW9PDJAYKAZNWK8YG2J
01CDJJRTXS20130C0QEMQ7T8GS
01CDJSMJ490SKQPH9X5JGSE1HW
01CDJSMJ5TFJXF82F7FVZXPM6H
01CDK0G9CBNXT8C0VQ85RCPY4D
01CDK0G9DS7H7VXNK7BMBY1AZC
01CDK7C0M9BJCFDKFYFHBHQN8N
01CDK7C0NTP4EGK2YQDHMDGKGM
01CDKE7QW9AFP0T78WMQ28G73B
01CDKE7QXSXYCCCVXF27VNZKWN
level=info …
```

Update minio client and add support for s3 SSE encryption

---

pkg/reloader/reloader.go

The Thanos reloader ignores any directories inside the rules directory.
If the reloader looks at a symlink to a directory, it is not interpreted as
a directory, but as a symlink and thereby not ignored.
Instead of using `os.Lstat`, use `os.Stat` to follow symlinks before
checking if it is a directory.
//CC @fabxc

reloader: Use `os.Stat` instead of `os.Lstat`

---

CHANGELOG.md
CODE_OF_CONDUCT.md

docs: Added CHANGELOG & code of conduct before first release candidate.

---

docs/getting_started.md

PR #328 added object_stores.md in one commit and renamed it to
storage.md in another. But the reference to object_stores.md was not
updated to refer to storage.md. Fix that.

docs: Fix link to storage.md

---

docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
scripts/genflagdocs.sh

Adding basic documentation for `bucket.go` in `/docs/components/bucket.md`.

#270 add docs for the bucket component and its sub commands

---

cmd/thanos/query.go
pkg/query/storeset.go
pkg/query/storeset_test.go

Changes:
- gRPC dial is non-blocking, so we need to make intial Info call to make sure connection is ok for gossip.
- duplicates were wrongly handled
- log on every storeset change for better debugability

query: Made storeset more reliable and make it log on changes.

---

cmd/thanos/sidecar.go
pkg/shipper/shipper.go
pkg/shipper/shipper_e2e_test.go
pkg/shipper/shipper_test.go
pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/proxy.go

Fixes https://github.com/improbable-eng/thanos/issues/353
TL;DR: Because of bug inside shipper we were propagating wrong blocks time range that is accessible by sidecar. Query was then assuming that there is no need to ask this sidecar for data. This was only if there is NO TSDB block in the filesystem (first 2h)
PTAL @adamhosier 

sidecar: Fixed critical bug for datapoints not being accessible on query.

---

.circleci/config.yml
Makefile

This patch introduces target dependencies so that requirements are met for each of the build targets. In practical terms this means there is no need to explicitly run `make install-tools` or `make deps` as these targets will be run whevener it is needed. Also, as `make` tracks modification dates for the real targets, it will not re-run dependent targets if there were no changes - meaning, these changes should not impact day-to-day development of thanos.

Define dependencies for build targets

---

cmd/thanos/query.go
cmd/thanos/store.go
pkg/cluster/cluster.go

store: Tiny logging improvements.

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
pkg/block/block.go
pkg/block/index.go
pkg/compact/compact.go
pkg/compact/downsample/downsample.go
pkg/shipper/shipper.go
pkg/shipper/shipper_e2e_test.go
pkg/shipper/shipper_test.go
pkg/testutil/prometheus.go
pkg/verifier/duplicated_compaction.go
pkg/verifier/index_issue.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/verify.go

TSDB issue: https://github.com/prometheus/tsdb/issues/347
How we handle it?
- segregate this issue in special stat entry in verifier.
- auto-fix broken plan block before thanos compaction.
- adding repair job to run offline batch repair for indivdual blocks.
NOTE: At this point we have no power of fixing the bug when someone uses local compaction ):
Fixes https://github.com/improbable-eng/thanos/issues/354
PTAL @BenoitKnecht

block: Handle gracefully extra duplicated chunk produced by TSDB issue.

---

cmd/thanos/sidecar.go
pkg/store/prometheus.go

Fixes https://github.com/improbable-eng/thanos/issues/381
PTAL @dmitriy-lukyanchikov
CI only

sidecar: Handle empty series from Prometheus remote read.

---

cmd/thanos/rule.go
docs/components/rule.md

This change adds a new argument `external.query.url` that represents an externally accessible thanos query URL that is in turn used to populate the source/generatorURL for each alert.
Note: This field also powers the source button in Alertmanager.
Currently when the arg is not passed the empty URL will be concatenated with the query string and passed as the generatorURL for the alert. If required we can replicate the existing behaviour of omitting field when the URL is not present or supply a default value.
Before
After

rule: supply GeneratorURL in alerts

---

Makefile
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/sidecar_test.go
cmd/thanos/store.go
pkg/alert/alert.go
pkg/block/block.go
pkg/block/index.go
pkg/cluster/cluster.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/objstore/client/factory.go
pkg/objstore/gcs/gcs.go
pkg/objstore/inmem/inmem.go
pkg/objstore/objstore.go
pkg/objstore/s3/s3.go
pkg/runutil/runutil.go

Due to a high number of these issues, let's split the PR.
Thanks @asbjxrn for finding some not checked errors. This motivates us to fix all of these places. Some of them are serious, some not, but I think it is better to check all errors 100% time. (:
- Added errcheck makefile step
- Fixed some portion of not checked errors (mainly for bucket and commands)
- Added `runutil` helpers for closing functions.
CI, errcheck

*: Added errcheck and fixed not check errors [PART1].

---

docs/getting_started.md
examples/alerts/alerts.md

Adds example alerts for Thanos for running in Kubernetes environment.
This is not meant to be suited for all environments, this is just example that you can start with and adapt to your needs.
Here is how it looks rendered -> https://github.com/povilasv/thanos/blob/alert-examples/examples/alerts/alerts.md

Add Thanos alert examples

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/rule.go
pkg/compact/downsample/downsample.go
pkg/query/storeset.go
pkg/reloader/reloader.go

Misspelled words in the following files
```
modified:   cmd/thanos/compact.go
modified:   cmd/thanos/downsample.go
modified:   cmd/thanos/rule.go
modified:   pkg/compact/downsample/downsample.go
modified:   pkg/query/storeset.go
modified:   pkg/reloader/reloader.go
```
Document update

Update misspelled words reported by Go report card

---

.circleci/config.yml
.gitignore
.promu.yml
Makefile

* Split the test, build, and publish steps with CircleCI workflows.
* Fixup `promu` target so it can be used outside of make.
* Update git ignore list for promu use.
* Update promu crossbuild list to avoid 32-bit builds.
* Siplify publish step with workflow filter.
Tested promu crossbuild locally.

Split build/publish in CircleCI

---

.gitignore
scripts/quickstart.sh

Quickstart now uses `./thanos` rather than `thanos` as mac does not search path like in linux. Also, adding ignore for prom binary incase people copy it for running quickstart.
Ran locally.

update quickstart to work out of box with mac

---

Makefile

Depend only on promu, not crossbuild, as crossbuild does not work in
docker.

Fix tarball publish

---

examples/grafana/monitoring.md
examples/grafana/thanos-rule.json

Adds an example Grafana dashboard for Thanos Rule using the existing format

rule: add example grafana dashboard for rule

---

kube/manifests/prometheus-gcs.yaml
kube/manifests/prometheus.yaml

To fix the targetPort of k8s service for sidecar http metrics in [Example Kubernetes manifest](https://github.com/improbable-eng/thanos/blob/master/kube/manifests/prometheus.yaml) and [Example Kubernetes manifest with GCS upload](https://github.com/improbable-eng/thanos/blob/master/kube/manifests/prometheus-gcs.yaml)
The targets of Kubernetes SD contain the sidecar instance.

Fixed targetPort of k8s service for sidecar http metrics

---

Makefile

This is to make sure dep output stays always the same.

makefile: Pin  dep command to specific version.

---

Gopkg.lock
Gopkg.toml

It solves problem with [SETTINGS_HEADER_TABLE_SIZE](https://github.com/grpc/grpc-go/pull/2045), allowing to work
behind nginx https://www.nginx.com/blog/nginx-1-13-10-grpc/
Affected all thanos components are communicating over gRPC

update go-gprc package to 1.12.1

---

docs/components/rule.md
docs/design.md

Fixes https://github.com/improbable-eng/thanos/issues/416
Please double check my quick math here (:
PTAL @kamelkev @tonglil
Storing 100TB with 1.07 bytes/sample.
100 (TB) / 1.07 (bytes/sample) = 1.027580961×10¹⁴ samples.
We assume avg of 1mln time series, so 102758096.1 samples "available" for single series to fit into 100TB overall.
With 15s scrape interval (4 samples/min):
102758096.1 (samples) / 4 (samples/min) = 25689524.025 min = ~48.88 years
With 1s scrape interval (60 samples/min):
102758096.1 (samples) / 60 (samples/min) = 1712634.935 min = ~3.25 years
- Cost description
- Rule flag (sorry for the unrelated thing)
I used Calculator :eyes:

docs: Fixed Thanos cost description to include scrape interval.

---

cmd/thanos/flags.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go

Make thanos components available to make cluster communication over public networks.
Affected all components
For the initial step, it was added two additional cluster options:
* cluster.secret-key - AES key, which could be one of the AES-128, AES-192, or AES-256. Specified as a hexadecimal string
* cluster.network-type - predefined peers configurations to be able to work in a specified network type: local, lan or wan (lan by default)
Tested `secret-key` on the local environment\
cc @Bplotka @mattbostock

Add thanos cluster to be able to work in public networks

---

Makefile

To install dep without user's GOPATH, the tmp place is `/tmp/go`
use `make deps`

To install dep without user's GOPATH

---

docs/getting_started.md

Fix typo in getting_started.md
Changed `cluset.peers` to `cluster.peers` in Communication Between Components section.
This is a documentation change.

Fix typo in getting_started.md

---

.gitignore
Gopkg.lock
docs/storage.md
pkg/objstore/s3/s3.go

Support retrieving credentials from IAM instance profile, `~/.aws/credentials` and standard AWS environment variables
Fixes #209
Adds support for retrieving AWS credentials from sources other than just the command line, such as an instance profile or file. Backwards compatibility is maintained by using the static credentials if supplied from the command line.
Tested by using the branch in a CI environment and having automated tests ensure that the system works correctly, such as querying data or checking data is uploaded to S3.

Add support for retrieving AWS credentials from sources other than command line

---

pkg/compact/downsample/downsample.go
pkg/compact/downsample/downsample_test.go

To switch the `it.At()` position to read the current item in the `CounterSeriesIterator.Seek()` first. If not, it will skip the current item.
related #439

Fixed miss current sample when do to seek to specify timestamp

---

cmd/thanos/sidecar.go
docs/components/sidecar.md
pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/testutil/prometheus.go

Fixes https://github.com/improbable-eng/thanos/issues/478

sidecar: Add support for prometheus with --web.route-prefix.

---

pkg/store/proxy_test.go

Showcase of how state with external lset being the same for 2 peers is wrong.

query: Extend test cases to the case with the same external labels.

---

cmd/thanos/main.go

- adding in metrics for process
```
process_cpu_seconds_total 0.34
process_max_fds 1024
process_open_fds 19
process_resident_memory_bytes 2.822144e+07
process_start_time_seconds 1.53511609353e+09
process_virtual_memory_bytes 3.8580224e+07
```

Adding in process collector to all processes

---

.gitignore
Gopkg.lock
Gopkg.toml
Makefile

PTAL @vglafirov
- Pinned Prometheus to v2.3.2
- Added .dep-finished file to make sure we rerun dep on `make dep` when deps fail.
Tested on fresh empty dep repo (no vendor and empty .lock)

make & deps: Pinned Prometheus package, otherwise we can have broken master anytime.

---

Makefile
benchmark/cmd/thanosbench/resources.go
pkg/store/proxy_test.go
pkg/testutil/prometheus.go
test/e2e/query_test.go
test/e2e/spinup_test.go

Problems: Because of https://github.com/prometheus/prometheus/issues/4551 Thanos
e2e tests were not passing (98% time). This caused CI to be almost always red.
PTAL @povilasv @vglafirov 
- Added Makefile step to install pinned version of Golang binaries.
- Test e2e against pinned version fo Prometheus and alertmanager for reproducible builds.
- Additonally: make format.
- CI
- Local `make test`
- Local `GOCACHE=off go test -v ./test/e2e/...`

e2e: Run Query Simple e2e tests against pinned version of Prometheus.

---

CHANGELOG.md
cmd/thanos/bucket.go

Not sure if you would be happy with this, but maybe adding `-o wide`, with default printing make sense?
I tried something like:
```
thanos bucket ls -o  '{{.ULID}} {{.MinTime }} -- {{.MaxTime}} - Compact: {{.Compaction.Level}}, Downsample: {{.Thanos.Downsample}}, Source {{.Thanos.Source}}'
```
But couldn't figure out how to format dates nicely.
```
thanos bucket ls -o wide --s3.bucket=dev-sys-mon-prometheus-storage
```
```
01CMRNWKTDD87W80957X47YNH8 -- 2018-08-11 03:00 - 2018-08-13 03:00 Diff: 48h0m0s, Compaction: 3, Downsample: 300000, Source: compactor
01CMRP2RDN93TJF4AF7BKJ2W2D -- 2018-08-11 03:00 - 2018-08-13 03:00 Diff: 48h0m0s, Compaction: 3, Downsample: 300000, Source: compactor
01CMXTSBTZSP4TGYNZ9K74ZXJ7 -- 2018-08-13 03:00 - 2018-08-15 03:00 Diff: 48h0m0s, Compaction: 3, …
```

Add bucket ls -o wide

---

docs/proposals/gossip-removal.md

This is quite a major change, so please give us feedback!
Rendered view: https://github.com/improbable-eng/thanos/blob/gossip-remove-proposal/docs/proposals/gossip-removal.md
PTAL: @brancz @povilasv @fabxc @domgreen and others.
@mxinden @stuartnelson3 this may interest you.

proposal: Deprecate/Remove gossip clustering for Thanos.

---

cmd/thanos/compact.go

Fixes https://github.com/improbable-eng/thanos/issues/297
PTAL @drax68

compact: Add optional flag to disable downsampling.

---

cmd/thanos/compact.go
docs/components/compact.md
pkg/compact/compact.go
pkg/compact/retention.go
pkg/compact/retention_test.go

ref: #458 
Adds retention analog to the implemented global retention.
Any feedback welcome :-)
Small unit test and tested locally in a cluster using the parameters:
`--retention.res0=4d --retention.res1=8d`
```
level=info ts=2018-09-10T09:58:56.706891152Z caller=compact.go:141 msg="retention policy of raw samples is enabled" duration=96h0m0s
level=info ts=2018-09-10T09:58:56.707158971Z caller=compact.go:144 msg="retention policy of 5 min aggregated samples is enabled" duration=96h0m0s
level=info ts=2018-09-10T09:58:56.707404063Z caller=compact.go:234 msg="starting compact node"
level=info ts=2018-09-10T09:58:56.707904636Z caller=main.go:244 msg="Listening for metrics" address=0.0.0.0:10902
level=info ts=2018-09-10T09:58:56.708745619Z caller=compact.go:803 msg="start sync of metas" …
```

compact: add bucket retention by resolution

---

Gopkg.lock
Gopkg.toml
cmd/thanos/main.go
pkg/objstore/objstore.go
pkg/store/cache.go

Use the version recommended by the upstream maintainer until there is an
official release. There are a number of issues with the very old 0.8.0
verision.
Specifically for client_golang, master is considered stable enough to
rely on. Experiments are kept in branches.
[0]: https://github.com/prometheus/node_exporter/pull/1076

Bump Prometheus client_golang vendoring

---

docs/design.md

Link to tsdb-format is broke, adding relink to doc it's referencing
Update doc link to newer tsdb format link on prometheus/tsdb
Click da link and boom 🎉

Docs: design.md - Update Link for tsdb-format

---

docs/getting_started.md

Thanos now has a release, where the binary can be downloaded as is.

Update release info

---

pkg/block/index.go
pkg/compact/compact.go

Helps with https://github.com/improbable-eng/thanos/issues/431
But not fixes this - it will just halt with correct message, not panics.
Still the source of not sane index needs to be resolved (Prometheus).
PTAL @jojohappy @asbjxrn

Fixed panic while checking duplicated chunks in index file.

---

CHANGELOG.md
pkg/store/proxy.go
pkg/store/proxy_test.go

When we are calling many stores we need to ensure that if they all (more than 10) return an error we do not halt the as we cannot add more the the respCh in doing so we are eating into the number of queries we are allowing Thanos.
`respCh` should be one more than the number of stores we have ... this is so  we can push all error responses to the channel and also the final error if the series has no results.
Added a test.

Proxy Store should not lock when all clients error.

---

CHANGELOG.md
cmd/thanos/main.go

Greetings !
It took some time to found the culprit but I found it before the weekend !
Fix #463
* Add `thanos_` prefix to go-metrics metrics :smirk: 
* Disable runtime metrics collection of go-metrics since it's already taken care of by the official Prometheus client
```diff
1,7c1,8
< # HELP thanos_query_memberlist_gossip thanos_query_memberlist_gossip
< # TYPE thanos_query_memberlist_gossip summary
< thanos_query_memberlist_gossip{quantile="0.5"} 0.022954000160098076
< thanos_query_memberlist_gossip{quantile="0.9"} 0.02971700020134449
< thanos_query_memberlist_gossip{quantile="0.99"} 0.042089998722076416
< thanos_query_memberlist_gossip_sum 0.6567779900506139
< thanos_query_memberlist_gossip_count 30
\ No newline at end of file
---
> # HELP query_memberlist_gossip query_memberlist_gossip …
```

Add thanos prefix to go-metrics and disable duplicate runtime metrics (#463)

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
pkg/compact/compact.go

fixes: #470 
Related discussion: [comment](https://github.com/improbable-eng/thanos/issues/470#issuecomment-426691885)
Clean up the temporary directory before compactor beginning.

Fixed clean up old compact chunks when compact starts

---

cmd/thanos/rule.go
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

ref: https://github.com/improbable-eng/thanos/issues/492
The rule e2e test now runs 3 times with different service discovery options:
* only gossip
* only static flag configuration
* only file sd
The tests pass

[file-sd-part-5] Rule e2e test uses different service discovery options

---

cmd/thanos/rule.go
docs/components/rule.md
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

Adds the option to statically configure the queriers that ruler talks to via a command line flag.
Not exactly fileSD related, but it can be useful as a static alternative to gossip.
Validated in a following PR - (https://github.com/improbable-eng/thanos/pull/556)

[file-sd-part-4] Added flag for query addresses to ruler

---

cmd/thanos/query.go
cmd/thanos/rule.go
docs/components/rule.md
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

ref: https://github.com/improbable-eng/thanos/issues/492
Added file sd to ruler. You can specify files to watch via a command line flag. Then the ruler will load queriers' addresses from the files whenever the files are updated.
Tests in this PR: https://github.com/improbable-eng/thanos/pull/556

[file-sd-part-3] Added file sd to rule

---

Gopkg.lock
benchmark/cmd/thanosbench/resources.go
cmd/thanos/query.go
cmd/thanos/rule.go
docs/components/query.md
docs/components/rule.md
pkg/discovery/cache/cache.go
pkg/query/api/v1.go
pkg/store/proxy_test.go
test/e2e/query_test.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

ref: https://github.com/improbable-eng/thanos/issues/492
Added file sd to query. You can specify files to watch via a command line flag. Then the querier will load stores' addresses from the files whenever the files are updated.
We are reusing Prometheus' file sd.
Tested in a following PR that adds the different SD options to the tests - (https://github.com/improbable-eng/thanos/pull/554)

[file-sd-part-1] Added file sd to query

---

cmd/thanos/compact.go

Fixes #580 
Should now clean the down sample dir explicitly rather than root as root could be the volume mount.

do not clean root, instead explicitly clean downsample dir

---

CHANGELOG.md
cmd/thanos/query.go
kube/manifests/thanos-query.yaml

Add `/-/healthy` endpoint to Querier.
For a related discussion on this change, you can find [a similar discussion](https://github.com/prometheus/pushgateway/issues/105) on the Prometheus Push Gateway repository.
This endpoint implementation is naive and in the future, we could maybe add verification of gRPC peers or anything else.
```curl http://127.0.0.1:10902/-/healthy -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 10902 (#0)
> GET /-/healthy HTTP/1.1
> Host: 127.0.0.1:10902
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 12 Oct 2018 11:26:48 GMT
< Content-Length: 19
< Content-Type: text/plain; charset=utf-8
< 
Thanos is Healthy.
* Connection #0 to host 127.0.0.1 left intact
```

Add /-/healthy endpoint to Querier

---

cmd/thanos/query.go
cmd/thanos/rule.go
docs/components/query.md
docs/components/rule.md
test/e2e/spinup_test.go

@bwplotka proposed to make the file SD flags a bit less verbose.
Any thoughts on this format:
* `--store.sd-files`
* `--store.sd-interval`
Bare in mind we will also add dns lookup interval flag. It will look like that:
* `--store.sd-dns-interval`

Changed the file SD flags names

---

test/e2e/rule_test.go

I must have missed this in the last merge. Noticed it while working on dns sd, and thought it is worth a separate pr.

Fixed an e2e test not using the table test confs

---

cmd/thanos/compact.go

Max compaction level is using as a high bound to sub-slice original level set.
fixes https://github.com/improbable-eng/thanos/pull/578

compaction: fix edge case for compaction levels

---

docs/thanos_service_discovery.md

Format the markdown of JSON and YAML Discovery File snippets so they properly highlighted. In addition, there was an extra comma in after the array in the JSON sample, which would make the JSON file itself invalid.
The snippets are properly highlighted when previewing the modified markdown.

docs: Improve discovery file snippets

---

pkg/objstore/client/factory.go

This will convert the type to uppercase `S3` or `GCS`, so that people that have a config like still works:
```
type: s3
...
```
`make build` and then run `./thanos bucket ls` with config that has lowercase name.

pkg/objstore: Uppercase bucket type after reading config

---

docs/proposals/201807_store_instance_high_availability.md

The format of this proposal mirrors an existing draft proposal:
https://github.com/improbable-eng/thanos/pull/387
We should to arrive at consensus on the open issues described in the proposal (under the 'Open issues' section) before merging.
/cc @xjewer @fabxc @Bplotka

Add proposal for store instance high availability

---

pkg/objstore/client/factory.go
pkg/objstore/gcs/gcs.go
pkg/objstore/s3/s3.go
test/e2e/store_gateway_test.go

Related comments: [#467](https://github.com/improbable-eng/thanos/pull/467#discussion_r228696300)
The bucket operator metrics in each bucket are unnecessary, because we wrap the instance of bucket in the `metricBucket`, those seem to be duplicated. Let's remove the metrics and we can add again when support multiple buckets.
In Thanos Query UI, we can just find the `thanos_objstore_bucket_operations_total`, no `thanos_objstore_s3_bucket_operations_total` or `thanos_objstore_gcs_bucket_operations_total` etc..

Remove bucket operator metrics

---

pkg/reloader/reloader.go

SHA256 calculate sum even on empty input:
[227 176 196 66 152 252 28 20 154 ....]
in this case, even if ruleDirs hasn't been specified, it tries to reload prometheus.
For the case the --web.enable-lifecycle isn't enabled, the reloader gets into the infinity loop.
fixes: https://github.com/improbable-eng/thanos/pull/476
cc @bwplotka

sidecar: fix reloader to reload prometheus, when it shouldn't

---

kube/manifests/prometheus-gcs.yaml

and for consistency add -gcs suffix to service as well.
Without this the selector would point to non-existent prometheus pods

add correct app selector for prometheus traffic

---

.circleci/config.yml
CONTRIBUTING.md
Gopkg.lock
Gopkg.toml
cmd/thanos/store.go
docs/components/store.md
docs/getting_started.md
docs/storage.md
pkg/objstore/client/factory.go
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/swift/swift.go

This commit adds support for OpenStack swift storage.
- OpenStack Swift is a highly available, distributed object/blob store. This commit adds support to persist the metric data on Swift.
- Ensured `TestObjStore_AcceptanceTest_e2e` works for the swift storage. Verified that the test objects are getting created by going directly to swift while the tests were running.
- Tested with a local OpenStack swift installation.

Support OpenStack Swift object storage

---

pkg/objstore/s3/s3.go

S3 object store: set bucket-owner-full-control acl on upload
This is needed in environments where the sidecar is deployed in
one AWS account while the store bucket is owned by a different account
Without this ACL the storer cannot access data written
- set bucket-owner-full-control canned acl on S3 Upload
- Local test with multiple accounts

S3 object store: set bucket-owner-full-control acl on upload

---

Makefile

I added `v2.3.2` and `v2.4.3`. 
Possible enhancement could be automatically getting latest stable version of Prometheus so we don't have to add new versions manually.   
Tests are passing for all versions.

feat tests: Added newer versions of Prometheus and Minio to e2e tests

---

Makefile

Actually cd into the dependency's directory before invoking `git fetch`. Otherwise, the `git fetch` command operates on the Thanos working directory itself. Also: use consistent whitespace (tabs in Makefile, spaces in line continuation) and escaping.
Clone Thanos via SSH and run the tests from master in a Docker container, e.g. via
docker run --rm -it -v "$(pwd):/go/src/github.com/improbable-eng/thanos" golang:1.10
The build will fail when trying to git fetch dependencies, since it actually tries to fetch Thanos, but this will fail because of the missing SSH key.

Makefile: fix git fetch when dependencies are already present

---

CHANGELOG.md
cmd/thanos/rule.go
cmd/thanos/rule_test.go

fixes https://github.com/improbable-eng/thanos/issues/598
1. Added handling of scalar result or query node response when evaluating rules
I verified that it works with test rules loaded to the new version of rule node:
```yaml
groups:
- name: test
rules:
- record: scalar_rule
expr: 1
labels:
type: SCALAR
- record: vector_rule
expr: sum(topk(1,up)) by (instance)
labels:
type: VECTOR
```
and result from connected query node is:
I also added simple test to verify ability to decode scalar response.

fix rule: Fixed scalar result handling in rule node (#598)

---

CHANGELOG.md
test/e2e/spinup_test.go

e2e: Use `cluster-disable` flags in e2e tests, for non gossip tests.

---

CHANGELOG.md
cmd/thanos/rule.go
docs/components/rule.md
pkg/alert/alert.go
pkg/alert/alert_test.go

This allows to setup thanos ruler in HA and avoid duplicated alerts.

ruler: Add support for simple relabelling in form of label drop.

---

pkg/store/bucket.go

Debugging #335.
Potentially broken preloadPosting is missing some postings, because
of bad partitioning. Unit tests are there, but we might not get all edge cases?
If with this check we will have still panic - it can only mean races.
However, -race is not showing anything interesting on, even extended tests.
Would be nice to build testing tag with this and allow users to deploy it and test on setups that can repro store gateway panics.
PTAL @adrien-f 

Added additional check for lazy Postings.

---

CHANGELOG.md
cmd/thanos/rule.go
cmd/thanos/rule_test.go

Fixes https://github.com/improbable-eng/thanos/issues/680
Tested this code with docker image:
```
povilasv/thanos:fix-thanos-rule-alertmanager-dns-2018-12-13-99b00b0
```

Fix thanos rule alertmanager dns

---

pkg/objstore/s3/s3.go

Signed-off-by: Adrien Fillon <adrien.fillon@cdiscount.com>
I noticed an issue where a S3 multipart upload would fail with a `413 Entity Too Large` error. After investigating, I noticed we were not sending the size of the buffer/chunk/file/... to the minio-go library and that would cause the multipart upload to be a single part upload.
From what I've seen, the `Upload` method is only called with a `os.File` object : https://github.com/improbable-eng/thanos/blob/a09d41dd6534f28365eede43fd024fed3dcc0750/pkg/objstore/objstore.go#L80
I'm currently not satisfied with what I did but it works :shipit: ! I open this PR so we can figure out the best way to handle this. In case of real buffers, to compute their size I would need to duplicate it in memory from what I read.
* s3: Send correct file …

store/s3: try to guess size to enable multipart uploads

---

docs/storage.md

Properly specify the file format for embedmd blocks in docs/storage.yaml
This help make the document more user friendly with syntax highlilghting.

docs: Fix embedmd file format and syntax highlight

---

docs/proposals/201812_thanos-remote-receive.md

This adds a proposal for a new component to be added to Thanos to enable Prometheus servers replicate their time-series data via Prometheus' remote-write support. Take the motivation for this from the proposal.
Our concrete case is for analytics where customers have tight insight over what data is sent and it must be initiated by them, instead of us using something like [PushProx](https://github.com/RobustPerception/PushProx).
The RedHat Prometheus/monitoring team intends to do maintainership of this component as well as it's initial implementation. A working, but proof of concept state version of the proposal can be found [here](https://github.com/Go-SIP/thanos-receiver). Note this proof-of-concept, only has a minimal feature set working, to demonstrate the concept. Also the proposal …

proposals: Add proposal for a component for remote-write support

---

CHANGELOG.md
pkg/store/prometheus.go
pkg/store/prometheus_test.go

Fixes https://github.com/improbable-eng/thanos/issues/649
This fixes missing external label values in query HTTP API endpoit `/api/v1/label/<label_name/values>`.
Till now it only added label values returned from Prometheus instance and did not add it's own external labels.
@bwplotka If you could please take a look I'm not sure if Store node and Rule node uses the same code I verified it works only for Sidecar. Thanks in advance!
1. Store adds it's values of matching external label by name
1. De-duplicates resulting values because external labels can have same value as Prometheus labels.
1. Tests for external labels  
Tests are passing and it was tested on real-world Prometheus instance with sidecar and query pointing to it. All worked as …

Fixed store label values api to add also external label values

---

README.md
docs/proposals/approved/201809_gossip-removal.md
docs/proposals/approved/201901-read-write-operations-bucket.md

Main goals are:
* Support for eventual consistent object storages: https://github.com/improbable-eng/thanos/issues/298, https://github.com/improbable-eng/thanos/issues/377
* Avoid race condidtions on compaction and retention: https://github.com/improbable-eng/thanos/issues/564, https://github.com/improbable-eng/thanos/issues/271
* Handle partial uploads gracefully: https://github.com/improbable-eng/thanos/issues/377
CC @improbable-ludwik

Added proposal for Read-Write coordination-free bucket operation contract

---

kube/manifests/prometheus-gcs.yaml
kube/manifests/prometheus.yaml
kube/manifests/thanos-query.yaml
kube/manifests/thanos-store.yaml

Fix for #706 
Added service account for prometheus. 
Changed the thanos version.
Prometheus is able to scrape the metrics. 
Thanos query is not crashing anymore. 
~~~
kubectl get pod
NAME                            READY     STATUS    RESTARTS   AGE
prometheus-0                    2/2       Running   1          16m
prometheus-1                    2/2       Running   1          16m
thanos-query-7c6f6f5f77-dzbtp   1/1       Running   0          12m
thanos-query-7c6f6f5f77-kztfx   1/1       Running   0          12m
kubectl logs prometheus-0 prometheus
level=info ts=2019-01-03T16:28:53.110868076Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"
level=info ts=2019-01-03T16:28:53.110930676Z caller=main.go:216 …

prometheus service account and thanos version fix

---

CHANGELOG.md
docs/storage.md
pkg/objstore/s3/s3.go
pkg/objstore/s3/s3_test.go

Fixes https://github.com/improbable-eng/thanos/issues/708
Fixed potential nil pointer panic - fixed wrong casting handling.
CC @druss17
CC @improbable-ludwik @ianbillett

s3: Moved bucket-owner-full-control to be optional behind the flag.

---

examples/grafana/thanos-query.json

Some queries were incorrectly using rate() on non-counter metrics, this function was removed from the query
Deployed to Grafana instance

grafana: remove rate from non-counter metrics

---

pkg/store/prometheus.go
pkg/store/prometheus_test.go

split response into chunks no bigger than 2^16 to avoid overflowing XOR compression
Signed-off-by: Robert Sullivan <robert.j.sullivan@gmail.com>
In `prometheus.go` when building the response, create multiple `AggrChunk` structs each with a slice of samples not to exceed 2^16 number of samples. This is needed to not overflow the XOR encoding.
We added a test to `prometheus_test.go`, and we also shipped it to our environment where we were seeing the bug mentioned in issue #396. After pushing the changes, we saw a full 2 weeks of data in the same query that was previously cutting off the more recent week of data.

sidecar: fix issue #396: split response into chunks no bigger than 2^16 samples

---

docs/storage.md
pkg/objstore/swift/swift.go
scripts/bucketcfggen/main.go

This time I've created a proper fix for the SWIFT object store example in the documentation.
Made swiftConfig public and added proper config in the helper tool.
Executed make docs and the example is now created properly.

Fix documentation for SWIFT objectstore.

---

CHANGELOG.md
docs/storage.md
pkg/objstore/s3/s3.go
pkg/objstore/s3/s3_test.go

This adds a new option in the s3 object storage config that provides the ability to ignore TLS verification errors for testing and/or debugging purposes.
We are running Thanos with this patch against our internal s3 compatible storage system (Dell EMC ECS) as well against Minio server with a self-signed certificate.
We are using Thanos with an s3 compatible storage service and, for various reasons, we are limited to a self-signed certificate in our testing environment. Plain HTTP is not an option either (so the `insecure` options does not work for us). This option allows us to proceed with our Thanos testing and evaluation.

s3: insecure skip verify option

---

Makefile
docs/getting_started.md

Just a small change to fix the docs link for supported Prometheus versions after https://github.com/improbable-eng/thanos/commit/7d30beb3ac98e6ab3bdeebdee01430f6671922ad

fix docs link for supported Prometheus versions

---

CHANGELOG.md
pkg/store/proxy.go
pkg/store/proxy_test.go

This fixes potential race condition. Thanks to @jojohappy who highlighted the problem in this PR: https://github.com/improbable-eng/thanos/pull/744
Sorry for getting duplicate PR, but found other race conditions as well (what if sending stream gives err!) and this fixes CI and edge cases for users so it's quite urgent.
Particular race conditions and known issues this PR fixed:
* Start stream series set sending to buffered chamber before we are even reading. When one of store returns err and want to send warn it is blocked forever. (@jojohappy finding)
* When error happens while stream.recv on start stream we were warning only despite our partial response disable flag.
* When client stream is broken we end response channel reader loop. This means that if stores sends us data and channel is …

proxy: Make sure there is no race condition between sender and recv of resp channel

---

CONTRIBUTING.md
Makefile
scripts/genproto.sh
scripts/installprotoc.sh

We have a shortcut of `make proto` to generates golang files from Thanos proto files. But if people have not installed the standard protocol buffer implementation from https://github.com/google/protobuf, the command will be failed. 
This PR will fix the bug for downloading the `protoc` binary and pinning the version at `3.4.0` we specified.
To run `make proto` locally.

Fixed make proto

---

cmd/thanos/query.go
cmd/thanos/rule.go
docs/components/query.md
docs/components/rule.md
pkg/ui/query.go
pkg/ui/rule.go
pkg/ui/ui.go
pkg/ui/ui_test.go

The UI links are prefixed with a value of "X-Forwarded-Prefix" header.
This fixes https://github.com/improbable-eng/thanos/issues/364 in a more dynamic way in comparison to static options used by `prometheus`.
For example, this header [is used in Spring](https://github.com/spring-projects/spring-framework/blob/a9a38fe67e5750d8cd71e68273462bd1e8f2a60a/spring-web/src/main/java/org/springframework/web/filter/ForwardedHeaderFilter.java#L44) Java framework.
Support of "X-Forwarded-Prefix" allows to expose `thanos query` on a sub-path behind `Traefik` kubernetes ingress controller or any other reverse proxy by simply stripping of the sub-path, without a need to parse and rewrite response header and body.
The http.Header.Get() returns empty string if a header is not set. Therefore, such value …

query, rule: add path prefix support

---

Gopkg.lock
Gopkg.toml
pkg/shipper/shipper_e2e_test.go

This will hopefully make sure dependantbot is not trolling us (: 
The problem: Go dep expects toml file `version` in `0.16.0` not `v0.16.0`... -.-  

Fixed toml file versions; Upgraded cloud.google.com/go

---

cmd/thanos/store.go
docs/components/store.md
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go

Added a command-line argument to thanos store for the number of goroutines to use when syncing blocks from a store.  This should limit the amount of memory used at peak when starting up the process, especially the first time when there won't be `index.cache.json` files on disk already.
Added debug statements to validate number of goroutines created during development and blocks being loaded.

Add flag for thanos-store block sync concurrency

---

pkg/store/cache.go
pkg/store/cache_test.go

Related to #651. An initial attempt to fix this because I am always nervous that some person could unintentionally make our Thanos Store instance hang even if the index cache is quite big :( 
`thanos_store_index_cache_items_overflowed_total` metric added which shows how many times we have tried to add an item to the cache which was simply too big according to the `--index-cache-size` parameter. `ensureFits()` now returns false when we cannot possibly ensure that the passed slice could fit into the cache. The original problem still exists in some form that `setPostings` or `setSeries` could block for a longer time if there are a lot of small items in the cache however at least it shouldn't dead-lock.
Wrote unit tests for it and they pass. It is kind of hard to reproduce this unfortunately …

LRU cache ensureFits() tweaks WRT deadlocking

---

CHANGELOG.md
Makefile
pkg/promclient/promclient.go
pkg/promclient/promclient_e2e_test.go
pkg/store/bucket_e2e_test.go
pkg/testutil/prometheus.go

Required for https://github.com/improbable-eng/thanos/pull/731
Important follow up on this is https://github.com/improbable-eng/thanos/issues/758

[sync part3] promclient: Added method for Prometheus snapshot.

---

cmd/thanos/rule.go

Fixes #799 
This checks if either `--query` or `--query.sd-files` flag has been given, when `--cluster.disable` flag is set.
Tested with different combinations of above mentioned flags. Also `make test`

ruler: require either --query or --query.sd-files when gossip is disabled

---

cmd/thanos/rule.go
cmd/thanos/rule_test.go

Fixes #800 
Uses prometheus' LabelName verification to check if labels provided via `--label` fit the guidelines
`make test` and tested various unsupported label names like `-`.

rule: add verification for labels provided via --label

---

Gopkg.lock
cmd/thanos/bucket.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
pkg/promclient/promclient.go
pkg/shipper/shipper.go
pkg/shipper/shipper_e2e_test.go
pkg/testutil/prometheus.go

Added shipper capability to sync compacted blocks once.
Changes:
* Use shipper metrics properly.
* Do not add compacted blocks to `uploaded` arr in thanos shipper meta if they are not uploaded.
* Added flag for syncing compacted blocks once.
* Enable working on different work dir.
* Enable using snapshot API to avoid race conditions.
* Ignore empty blocks.

Added shipper capability to sync compacted blocks once.

---

tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar-lts.yaml
tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar.yaml
tutorials/kubernetes-demo/manifests/thanos-compactor.yaml
tutorials/kubernetes-demo/manifests/thanos-gateway.yaml
tutorials/kubernetes-demo/manifests/thanos-querier-no-us1.yaml
tutorials/kubernetes-demo/manifests/thanos-querier.yaml
tutorials/kubernetes-demo/manifests/thanos-ruler.yaml

Signed-off-by: David Calvert <davidcalvertfr@gmail.com>
Updated kubernetes-demo manifests to use improbable/thanos:v0.3.0 docker image instead of the rc.
Based on image tag available here : 
https://hub.docker.com/r/improbable/thanos/tags

kubernetes-demo: manifests to use improbable/thanos:v0.3.0

---

pkg/reloader/reloader.go
pkg/reloader/reloader_test.go

Fixes #760 
- add test to verify behavior difference between watches of symlinked files versus symlinked directories
- add symlink resolution to rule directories if necessary
- `go test`

reloader: add support for watching symlinked directories of rules

---

examples/grafana/thanos-compact.json

Changed series name in Compact Grafana Example dashboard, Operations/s panel:
From : `sum(rate(thanos_compact_garbage_collections_total{...`
To : `sum(rate(thanos_compact_garbage_collection_total{...`
(Removed 's' in collection).
The series appears in Grafana.

Examples: Grafana: Compact: Fixed typo in Compact GC series Operations/s

---

pkg/store/bucket.go
pkg/store/bucket_e2e_test.go

Needed to refactor logic to add "posting groups".
Some debug in progress, but overall showing the direction (: 
Fixes: https://github.com/improbable-eng/thanos/issues/834

store: Added missing matcher logic for negative matchers.

---

CHANGELOG.md
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go

Fixes https://github.com/improbable-eng/thanos/issues/833

store: Fixed intersect matching when one matcher filters out all series.

---

Dockerfile.multi-stage
Makefile

This makes it easy to build a thanos image without a proper dev env set up.
Also allows to build images using quay.io or docker hub services.

Add a multi-stage Dockerfile

---

benchmark/cmd/thanosbench/resources.go
cmd/thanos/rule.go
pkg/query/api/v1.go
pkg/query/api/v1_test.go
pkg/rule/api/v1.go
pkg/rule/api/v1_test.go

Adding 2 new API end points for the rule component : 
1. "api/vi/rules"
2. "api/vi/alerts" 
1. Added 2 end points (based on prometheus rules end point) 
2. Changed a few functions in the query API to be accessible and reused them in a new rule API class.
Its also an option to add a common class for shared code of  rule and query components, but I wasn't sure this is necessary. 
1. Tested query and rule components locally 
2. Added unitest for rule/alerts end points

Rule component: Adding new API end point for rules and alerts in 

---

pkg/store/cache.go
pkg/store/cache_test.go

Potpourri of fixes to the cache:
* Do not forget to increase the c.current metric with relevant labels when
adding items to the cache. Without this the metric `thanos_store_index_cache_items` is unavailable.
* Properly adjust c.curSize when adding items to the cache.
* Switch the order of operands in a check to avoid a *potential* uint64 overflow and thus not removing enough items to satisfy our size constraints.
Without these last two fixes essentially the metric `thanos_store_index_cache_items_evicted_total` is always zero together with `thanos_store_index_cache_items_overflowed_total` (most of the time). This is because we never enter the loop, and we never increase c.curSize before this.
Verification:
* New smoke tests pass which check if curSize is properly adjusted.

store/cache: fix broken metric and current index cache size handling

---

docs/components/sidecar.md

Make it more clear what the Prometheus command line flags should be for sidecar use.

Include example Prometheus command line

---

pkg/block/index.go
pkg/compact/compact_e2e_test.go

It is possible that Prometheus will produce time series with duplicate
labels. E.g.: a{b="2",b="2"} 1
Where such metric is pushed to Prometheus either wittingly or
unwittingly, the compact process will stall because the check will not
pass. For example:
{"caller":"main.go:181","err":"error executing compaction: compaction failed: compaction: gather index issues for block /data/compact/0@{monitor=\"monitor\",replica=\"repl\"}/01D34EDQMSQ29RHAC47XGKHGC7: out-of-order label set {__name__=\"foo\",exported_job=\"vv\",host=\"172_16_226_56\",host=\"172_16_226_56\",region=\"lt\",subtask_index=\"5\",task_attempt_id=\"32e4b047bb768583ff57c709be3b1046\",task_attempt_num=\"8\",task_id=\"688c028a219ff3372f3eecb0ee5811f9\",task_name=\"Source:_foo\",tenant=\"abc\",tier=\"cooltier\",tm_id=\"53b2ed987b08f4 …

compact: relax index label checking

---

cmd/thanos/compact.go
docs/components/compact.md
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go

Add a flag to the `compact` command to allow for fetching of the block metadata in parallel.
Tested by running `thanos compact` with `--log.level=debug` to see that it fetches the metadata much quicker when concurrency is added.

compact: add concurrency to meta sync

---

pkg/discovery/dns/resolver.go
pkg/discovery/dns/resolver_test.go

This adds an A lookup after the SRV lookups in order to resolve https://github.com/improbable-eng/thanos/issues/752.
I made ran the query with `--store` set to a random SRV record (i.e., not something running a store node) then immediately killed the process.  During close down, we see what address the querier was attempting to use for the store node.
On master:
```
martin@swift:~/go/src/github.com/improbable-eng/thanos$ ./thanos query --store=dnssrv+_xmpp-server._tcp.google.com.
level=info ts=2019-02-23T10:17:17.886702366Z caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=192.168.0.14:10901
level=info ts=2019-02-23T10:17:17.891416133Z caller=flags.go:105 msg="QueryAPI address that will be propagated through gossip" address=192.168.0.14:10902 …
```

querier: do A lookups after SRV lookups for store discovery

---

pkg/compact/compact.go
pkg/compact/compact_e2e_test.go

During the Thanos group compactor, in the case when the Prometheus compactor has found that the resulting block would have no data, delete the source blocks (after checking they are indeed empty) and exit early.  Introduce a sentinel error to mark this case, to force the caller (bucket compactor) to continue compacting the rest of that group.  
It is necessary to handle the empty compaction case separately because the later parts of the group compactor result in an error if we attempt to continue.
Note that the Prometheus compactor uses the empty ULID for the "block with no samples" case:
```
// When resulting Block has 0 samples
//  * No block is written.
//  * The source dirs are marked Deletable.
//  * Returns empty ulid.ULID{}.
Compact(dest string, dirs []string, open []*Block) …
```

Compact: skip compaction for blocks with no samples

---

.circleci/config.yml
CHANGELOG.md

Updated changelog to make sure the important change with index-cache-size is known.

---

CHANGELOG.md
pkg/objstore/objstore.go

Convert lastSuccessfullUploadTime into a GaugeVec with one dimension:
bucket, which makes client_golang *not* make that metric unless at least
one value has appeared.
This is better for users since Grafana will show that last upload has
been 49+ years ago instead of N/A when no uploads had happened before.
Fixes #886.

objstore: do not set last successful time metric before 1st upload

---

pkg/store/bucket.go

Debugs: https://github.com/improbable-eng/thanos/issues/874
TODO in next PRs: 
* Test gRPC panic recovery... it seems to not work. 
* Add logging interceptors. At least for error logging.
CC @mjd95 @GiedriusS 

Added safeguard against 847. Make sure debug stats are always printed, even on error.

---

pkg/block/block.go
pkg/shipper/shipper.go

Fixes https://github.com/improbable-eng/thanos/issues/934
CC @SuperQ 

sidecar: Handle intermediate restarts of sidecar gracefully.

---

examples/grafana/thanos-query.json

Avoid hard coding app and thanos query, use the template parameters.
Manually verified in Grafana

examples: Use $labelvalue and $labelselector rather than hard coding app and thanos-query

---

pkg/query/api/v1.go

Signed-off-by: Joseph Lee <joseph.t.lee@outlook.com>
The Prometheus support POST method for `query/query_range` endpoints, and Grafana support POST method for Prometheus too. 
When do complex query with multi label values from Grafana used GET method such as `count(node_load{instance=~"11\\.11\\.11\\.11|\\8\\.8\\.8\\.8"}) `  that label `instance` have much more IP  will failed, but if support POST method in Thanos Query, the query will work.
I have test it in my daily environment and production environment.

query: support POST method for query/query_range endpoints

---

cmd/thanos/query.go

fixes: #830 
Update the addresses from file SD by using DNS SD resolver when file SD is updated if necessary at once.
PTAL @GiedriusS @R4scal

Fixed lag between file-sd and dns-sd

---

CHANGELOG.md
CONTRIBUTING.md
MAINTAINERS.md
README.md
benchmark/README.md
docs/components/bucket.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/design.md
docs/getting_started.md
docs/proposals/approved/201809_gossip-removal.md
docs/proposals/approved/201901-read-write-operations-bucket.md
docs/proposals/rejected/201807_store_instance_high_availability.md
docs/proposals/rejected/config.md
docs/release_process.md
docs/service_discovery.md
docs/storage.md
scripts/genflagdocs.sh

Delete all duplicate blank in docs.

Remove some white noise

---

docs/storage.md
pkg/objstore/s3/s3.go

`minio.Client` has a `TraceOn` method which will be
called when one set the `traceon: true` in the bucket config.
This was a feature request here
https://github.com/improbable-eng/thanos/issues/530
1. Started a `minio` server locally and created a bucket called `test1`
2.  Created `store.yml` file (no `traceon`)
```
type: S3
config:
bucket: "test1"
endpoint: "localhost:9000"
access_key: "1NRJ8U7TDIKNAJOSG03Q"
insecure: true
signature_version2: false
encrypt_sse: false
secret_key: "gUFrMkH2PySW5SunGQ3hizixNMwenYu31yZdot+m"
put_user_metadata: {}
http_config:
idle_conn_timeout: 1s
insecure_skip_verify: true
```
3.  Run `./thanos bucket ls --log.level=debug --objstore.config-file=store.yml`
Output: 
```
level=info ts=2019-03-18T22:21:58.554021848Z caller=factory.go:39 msg="loading bucket …
```

objstore.s3: add trace functionality

---

pkg/objstore/azure/helpers.go

Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>

Fix panic when Azure error does not match pattern

---

pkg/reloader/reloader.go

This addresses an issue found in the Prometheus Operator, which reuses
this reloader sidecar, but which then also has a second sidecar which
may trigger rule-based reloads while the config sidecar is in the middle
of writing out its config (in a non-atomic way):
https://github.com/coreos/prometheus-operator/issues/2501
I didn't add a test for this because it's hard to catch the original
problem to begin with, but it has happened.
Signed-off-by: Julius Volz <julius.volz@gmail.com>

Make config reloader file writes atomic

---

CHANGELOG.md
pkg/verifier/overlapped_blocks.go

Fixes #908 
According to https://github.com/prometheus/tsdb/blob/master/db.go#L778 `OverlappingBlocks()` requires a sorted Slice by MinTime.
Verify no longer shows overlapping blocks, that overlap by `0s`. `make test` passes

Bucket: verify sort metas by MinTime before overlap check

---

cmd/thanos/sidecar.go

resolves https://github.com/improbable-eng/thanos/issues/952
Add info log with external labels of prometheus once successfully loaded

feat sidecar: added info log about successful load of external labels

---

cmd/thanos/compact.go
pkg/block/index.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go

This PR attempts to address https://github.com/improbable-eng/thanos/issues/888
* Added --debug.accept-malformed-index that will ignore errors caused by Prometheus Issue https://github.com/prometheus/prometheus/pull/5372
* Log at warn level when out of order labels are seen, the Status struct keeps track of how many of these errors are present in a TSDB block
I've run this code with and without the added CLI option against my Prometheus TSDB blocks known to exhibit this condition.  The condition is flagged appropriately.  New compacted blocks are built.

compact: accept malformed index

---

cmd/thanos/query.go
docs/components/query.md
pkg/query/storeset.go
pkg/store/proxy.go
pkg/store/proxy_test.go

Improves handling of timed out data/
Adds `--store.response-timeout` in order to have a timeout on a single stream operation.
Some times GRPC streams get stuck and don't send any data for long periods of time
E.G. Simple GRPC Store API, which just sleeps.
Right now the only option to time them out in GRPC is to set `context.WithTimeout()`
The issue is that it is a global timeout,
if we set it to 10s, we won't ever get results from Thanos Store (backed by object store)
if we set it to 120s, we will always be waiting 120s for the HTTP queries to finish, which is :/
As we will be waiting for the slowest one to finish
This fix adds a timeout per single data receive operation
Ref: https://github.com/improbable-eng/thanos/pull/928
Thanos Query will log if timeout was reached:
``` …
```

query: Add store.response-timeout

---

docs/storage.md
go.mod
pkg/objstore/gcs/gcs.go

Add `service_account` as multi line string to GCS config.
I've tested that the binary locally starts without any connections errors.
We need this change so that we can have one unified way of configuring the Thanos object storage. Additionally it will make the Prometheus Operator's life easier to manage those components (sidecar).
/cc @bwplotka @brancz @s-urbaniak

config: Add possibility to inline ServiceAccount into GCS config

---

pkg/store/proxy.go

It doesn't make sense to advertise that a Thanos Query node has data
since the beginning of the time and till the end of time if it only has
nodes which have specific time ranges of data.
Change it accordingly by checking each time range of each node and
setting it to the min/max values.
Calling these functions is fine as the values are cached and `TimeRange()` functions are protected by mutexes.

store/proxy: set {Min,Max}Time accordingly to the nodes

---

.promu.yml

Removed `{{repoPath}}/vendor/` from .promu so that version info correctly populates after transition to go mods.
Build info is now correctly populated:
```
thanos, version 0.3.2-master (branch: master, revision: 57a58a75254d60be5fdb74cb63ceff829318117c)
build user:       jdfalk@mm1
build date:       20190328-15:08:32
go version:       go1.12.1
```

*:Fix version info after change to go mods.

---

Makefile

On one of my mac OS machines the `find . -type f ...` expands to *a lot*
of files, and then all of them are passed as parameters to `goimports`.
Unfortunately, it seems like that hits the default limits of ARG_MAX
i.e. the maximum amount of bytes that can be allocated for the
parameters of a single command line.
Fix this by only passing the directories. `goimports` already descends
to all child directories and checks all of the files. Also, it properly
checks only the Go files as implemented here:
https://github.com/golang/tools/blob/master/cmd/goimports/goimports.go#L64
Verified that no changes are made with this patch by running `make format`.
The part to exclude `./vendor` is kind of moot now since we use Go modules but
I still left it since it seems used in some parts. Also, perhaps …

Makefile: fix mac OS build

---

Makefile

China firewall does not like our CI check it causes flakes - excluding.

makefile: Excluded tencent doc check.

---

CHANGELOG.md
cmd/thanos/query.go
docs/components/query.md
pkg/query/storeset.go
pkg/query/storeset_test.go
pkg/ui/bindata.go
pkg/ui/query.go
pkg/ui/templates/stores.html

Signed-off-by: Adrien Fillon <adrien.fillon@cdiscount.com>
* Cleanup unhealthy stores from UI view after 5m
* Keep stores metadata between health states
* Sort stores types in UI

query: cleanup store statuses as they come and go

---

cmd/thanos/compact.go
docs/components/compact.md
pkg/compact/compact.go

This adds an concurrency parameter to the compact command which controls how many groups are compacted in parallel.
Builds on https://github.com/improbable-eng/thanos/pull/898
Ran the compactor against a test bucket.

Compact: group concurrency 

---

CHANGELOG.md
cmd/thanos/query.go
cmd/thanos/rule.go
go.mod
go.sum
pkg/discovery/dns/miekgdns/lookup.go
pkg/discovery/dns/miekgdns/resolver.go
pkg/discovery/dns/provider.go
pkg/discovery/dns/provider_test.go
pkg/discovery/dns/resolver.go
pkg/discovery/dns/resolver_test.go

Fixes: https://github.com/improbable-eng/thanos/issues/1015

dns: Added miekgdns resolver as a hidden option to query and ruler.

---

cmd/thanos/query.go
docs/components/query.md

Subqueries allows request with no [specified resolution](https://prometheus.io/blog/2019/01/28/subquery-support/).
Set it up and allow to configure default evaluation interval.
Fixes https://github.com/improbable-eng/thanos/issues/1023

query: set default evaluation interval

---

CHANGELOG.md
cmd/thanos/compact.go
pkg/block/block.go
pkg/block/index.go
pkg/block/metadata/meta.go
pkg/compact/compact.go
pkg/compact/downsample/streamed_block_writer.go
pkg/objstore/objstore.go
pkg/store/bucket.go

Add few steps during compaction:
1. Process all index cache in old blocks made by compactor until this version,
updates meta.
2. Calculate index cache during group compaction.
3. Calculate index cache during downsampling.
Store downloads index cache from object storage or process it if doesn't exist.
covers first step of #942
cc @bwplotka

store+compactor: process index cache during compaction

---

pkg/objstore/gcs/gcs.go

*Urgent fix*
Without this that option was unusable.

gcs: Fixed scopes for inline ServiceAccount option.

---

docs/storage.md

After struggling to get permissions correct with Thanos sidecar + GCS storage, this PR updates the storage docs to reflect that GCS permissions should be set on the project level, not the bucket level. It also details some steps to troubleshoot the GCS policies.
Checked that the Markdown looks clean and meaningful

storage docs: add detail about GCS policies and testing

---

pkg/compact/compact.go

Follow on from https://github.com/improbable-eng/thanos/pull/1010
https://github.com/improbable-eng/thanos/pull/1010 added group-level concurrency to compaction.  It used an `errGroup` to manage the concurrency, which errors out all the concurrent tasks as soon as one fails, which can mean wasted resources and partial uploads.
This PR changes the behaviour so that once an error is encountered, we wait before all the active goroutines finish before erroring out the compaction.

compact:  group concurrency improvements

---

cmd/thanos/receive.go

Add flag to configure retention on receive component.
Modified min/max block size, to produce small blocks and watched blocks out of retention to be deleted. Same as #1011, this should have e2e tests. I'll look into that as a follow up. I've thought about adding min/max block duration as hidden flags for testing purposes, but I think I'd prefer to just produce old blocks for upload and retention scenarios in e2e tests.
@bwplotka @domgreen @GiedriusS @povilasv

receive: Add retention flag for local tsdb storage

---

CHANGELOG.md
go.sum
pkg/query/api/v1.go
pkg/query/querier.go
pkg/store/bucket.go
pkg/store/prometheus.go
pkg/store/proxy.go
pkg/store/proxy_test.go
pkg/store/tsdb.go

Implements: #702 
Add `/api/v1/labels` api to thanos query. 
Run `curl <query url>/api/v1/labels` to fetch all of labels in Prometheus. Noticed that the api is added in Prometheus 2.6.

querier: Add /api/v1/labels support

---

cmd/thanos/flags.go
cmd/thanos/rule.go
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md

Since 0.4.0 is last release with gossip available, let's disable it so people will be aware of this.
+ changed small label inconsistency.

Disabled gossip by default.

---

cmd/thanos/bucket.go
pkg/block/index.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/safe_delete.go

Detected and worked around in #953 this PR introduces code into the repair function that should repair affected TSDB blocks.
* When repairing index issues be sure to sort the label sets

bucket verify: repair out of order labels

---

pkg/store/cache.go

* Initialise all metrics to zero
* Correctly register overflow metric

store: Initialise and correctly register all index cache metrics.

---

CHANGELOG.md
pkg/block/index.go
pkg/compact/downsample/downsample.go
pkg/compact/downsample/downsample_test.go
pkg/compact/downsample/streamed_block_writer.go
pkg/runutil/runutil.go
pkg/runutil/runutil_test.go
pkg/testutil/prometheus.go

Fixes https://github.com/improbable-eng/thanos/issues/1065
Root cause:
* runutil defered capture error function was not returning error properly so unit tests were passing, even though there was bug
* streamed block write index cache requires index file which was not closed (saved) properly yet. Closers need to be closed to perform this.
PTAL @xjewer @shivas
@shivas included your PR https://github.com/improbable-eng/thanos/pull/1068/files here.

 Fixed Downsampling process; Fixed `runutil.CloseAndCaptureErr`

---

CHANGELOG.md
docs/storage.md
pkg/objstore/s3/s3.go

Minio is able to autodetect the region for cloud providers like AWS but the logic fails with Scaleway Object Storage solution.
Related issue on Minio: https://github.com/minio/mc/issues/2570
Independently of this issue, I think it's preferable for users to have the possibility to define the region explicitly rather than depends on code that is hard to test with all S3-compatible tools (e.g., https://github.com/minio/minio-go/blob/93e12e097cf3aec86c28ceeb7a960a29b2302a3a/pkg/s3utils/utils.go#L99)
Expose an optional `region` attribute in bucket configuration file. The change is backward compatible. When the region is not defined, the code still depends on Minio client to deduce the region.  
Manually tested after having created a bucket on Scaleway Object Storage …

objstore: Expose S3 region attribute

---

CHANGELOG.md
Makefile

Fixed bug:
- fetching go-bindata failed.
- change the repo of go-bindata to github.com/go-bindata/go-bindata,
because old repo has been archived.
- pin the `go-bindata` as v3.3.1.
When I run `make assets` in golang container, it would be failed with follow message:
```console
>> deleting asset file
>> writing assets
go: finding github.com/jteeuwen/go-bindata/... latest
go get github.com/jteeuwen/go-bindata/...: no matching versions for query "latest"
Makefile:94: recipe for target 'assets' failed
make: *** [assets] Error 1
```
On the other hand, the `github.com/jteeuwen/go-bindata` had been archived, use `github.com/go-bindata/go-bindata` now.
Run `make assets`.

Fixed fetching go-bindata failed

---

.gitignore
Makefile
README.md
go.mod
go.sum
netlify.toml
scripts/websitepreprocess.sh
website/hugo.yaml
website/layouts/_default/baseof.html
website/layouts/shortcodes/embedcode.html

cc @adrien-f 
Also updated hugo version.

website: Moved to netlify.

---

CHANGELOG.md

Just got the error when starting release v0.4.0:
`Error parsing commandline arguments: unknown long flag '--sync-delay'`
A note in the CHANGELOG would be nice :-)

Add note to CHANGELOG: Renamed flag --sync-delay to --consistency-delay

---

CONTRIBUTING.md
Makefile
docs/getting-started.md
go.mod
go.sum

After bumping the Prometheus version to 2.8.1 in #1009, `bzr` should no longer a build requirement. (This was addressed in https://github.com/prometheus/prometheus/pull/5378). As such, it doesn't make much sense to keep it as a requirement in the `Makefile` anymore :) 
The only remaining package with a dependency that required `bzr` was `github.com/improbable-eng/thanos/pkg/cluster` because it depended on v0.1.0 of `github.com/hashicorp/memberlist`. I've bumped this dependency to v0.1.3 which no longer has a dependency that needs `bzr`.
For historical reference, the `bzr` dependency was previously discussed in #868 and #948 
I have verified that Thanos builds successfully still on MacOS. I could use someone to test a Linux build if they feel inclined, though. (Make sure you clean out your …

Remove references to 'bzr' as it is no longer required

---

CHANGELOG.md
pkg/query/api/v1.go
pkg/query/api/v1_test.go

As compact.ResolutionLevel{Raw,5m,1h} says the resolution levels are
expressed in milliseconds. Currently, parseDownsamplingParam() calls
parseDuration() and friends which express this value in nanoseconds.
Thus, we need to divide the value by 1000*1000 to have them in
milliseconds.
Add test cases to check all of this.

query/api: properly pass downsampling param

---

pkg/store/cache/cache.go
pkg/store/cache/cache_test.go

1. When an item is successfully updated, metrics and cache size tracking added the new version of the item but did not remove the old version of the item.
For example, with a fresh cache, if you set the same item `m` times with each version having entry size `n`, the cache would think it had `m` items with current size `m*n` instead of `1` item with current size `n`.
If you then emptied the cache by evicting every item (only one), the cache would think it had `m-1` items with current size `(m-1)*n`, instead of `0` items with current size `0`.
This would allow the cache to get stuck in an eviction loop which persists even after the cache has been emptied.
2. When an item is unsuccessfully updated in the cache because the new version is too big, the old version was left in the cache.
If an …

store/cache: drop updates to existing items and dedupe get/set methods

---

README.md

Also this was merged directly accidently, sorry for that: https://github.com/improbable-eng/thanos/commit/1977ac9fe83ffeb0cedf1cf123bced3fe996bc70
That's is when you use Github UI to fix docs for laziness.

Updated README.md - typo fix.

---

CHANGELOG.md
pkg/query/api/v1.go
pkg/query/api/v1_test.go

If I am not wrong downsampling on master is broken for 2days.
This reverts commit 7a767eff3c7ecf55acbdc9d15a505207b2a0a7a2.
See: https://github.com/improbable-eng/thanos/pull/1144#issuecomment-493263066
Reason: 
* It has to be in in milisecond but we already do that underneath in Querier: https://github.com/improbable-eng/thanos/blob/3b9afb435215e761ecd34b3ccfd69d9946f6f725/pkg/query/querier.go#L58
* Conversion does not make sense here as time.Duration is unit agnostic type, so we should do conversion in the moment of transformation to `int64` only.
Tests are nice but they are assuming no-one converts resolution in further stack. Let's revert this and fix the getFor as it's done here: https://github.com/improbable-eng/thanos/pull/1146

Revert "query/api: properly pass downsampling param (#1144)"

---

.circleci/config.yml
CHANGELOG.md
Dockerfile.multi-stage

This is to mitigate potential memory allocation latency bugs: https://github.com/prometheus/prometheus/issues/5524

Moved CI to build Thanos with golang 1.12.5

---

pkg/promclient/promclient.go
pkg/query/api/v1.go

https://github.com/improbable-eng/thanos/issues/1129
The actual Querier response has more fields:
https://github.com/improbable-eng/thanos/blob/master/pkg/query/api/v1.go#L80:6
https://github.com/improbable-eng/thanos/blob/master/pkg/query/api/v1.go#L588

Thanos Rule: Add more context to errors

---

Makefile

```
sylvain@ubuntu-1604-dev:~/gopath/src/github.com/improbable-eng/thanos[master]$ time make docker-multi-stage DOCKER_IMAGE_NAME=quay.io/sylr/thanos:test
...
...
real    6m58.813s
user    0m0.372s
sys     0m0.352s
```
```
sylvain@ubuntu-1604-dev:~/gopath/src/github.com/improbable-eng/thanos[goproxy]$ time make docker-multi-stage DOCKER_IMAGE_NAME=quay.io/sylr/thanos:test
...
...
real    2m10.127s
user    0m0.376s
sys     0m0.268s
```

Use go proxy to fasten building at first build (useful for docker & ci)

---

docs/design.md

There was a small typo where 100k was referenced which was suppose to be 10k operations per the cost mentioned in regards to GCS 
Check GCS pricing documentation: https://cloud.google.com/storage/pricing#operations-pricing

design.md typo on GCS Operation Pricing

---

pkg/query/storeset.go

When we change the external labels after store has already joined into storesets that will makes the external labels duplicated.
Check duplicate external labels before checking whether the store is exist or not.
Run unit test which has passed.
/assign @bwplotka 
/cc @GiedriusS

query: Check duplicate external labels for all stores include existed store

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
pkg/block/block.go
pkg/block/index.go
pkg/promclient/promclient.go
pkg/store/prometheus.go
test/e2e/rule_test.go

fixes issue #1160 
replaced usages of json.NewDecoder Decode, with ioutil.ReadAll/File and json.Unmarshal
been running in production for a few days, memory graphs appear marginally better fixes

store,compact,sidecar: replace all usage of json.Decoder with json.Unmarshal

---

cmd/thanos/sidecar.go
pkg/promclient/promclient.go
pkg/promclient/promclient_e2e_test.go

The version check would check the prometheus version and if > 2.2.0
would query the flags endpoint to do some extra validation.
Remove this for just checking the flags endpoints and if it responds do
the validation; otherwise log the failure, but continue the startup.
Signed-off-by: Miek Gieben <miek@miek.nl>

promclient: drop version check

---

cmd/thanos/downsample.go

`json.Unmarshal` expects a pointer as the second argument. Fix it by
adding a missing '&'.
Fixes #1181.

thanos/downsample: pass pointer-to-struct to Unmarshal

---

docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
docs/contributing/how-to-contribute-to-docs.md
docs/getting-started.md
docs/storage.md
go.sum
scripts/websitepreprocess.sh

- Up to now, all the relative links were replaced in the `scripts/websitepreprocess.sh` by generating the URL for the website to correctly parse the links, that always added the `/docs/` dir in the path, which did not work for some of them (e.g. Makefile link below) as they were located outside of that directory. 
- Added small doc note on how to run the website locally, let me know if that is useful? Saves a small amount of time for not needing to go look at the Makefile :)
- Some other small cleanups.
- The `go.sum` change was automatic when I ran `go mod vendor`, but can remove it if you are getting a different result. 🤷‍♀ 
Tested all the links and they resolve both in markdown on github and by running the website locally. 
As a side note/question, there are some tools out there that …

 scripts/websitepreprocess.sh,docs/*: Fix broken links

---

CHANGELOG.md
docs/storage.md
pkg/objstore/swift/swift.go
pkg/objstore/swift/swift_test.go

As described in https://github.com/improbable-eng/thanos/issues/1117

add cross domain scoping

---

go.mod
pkg/receive/hashring.go
pkg/receive/hashring_test.go

This PR adds a basic hashring type to the receive package. The hashring does not implement consistent hashing because today we do not care about needing to shift data around between scale-up/scale-down. The current plan is that at every scale event we flush all data, write it to block storage, and start again.
Going forward, a PR will embed a Hashring into the Handler struct so that when handling requests, the Handler can decide if it needs to handle the request itself or forward it to another host.
Forwarding functionality will be added in a follow up.
Unit testing of hashring.
cc @metalmatze @brancz

pkg/receive: basic hashring support

---

cmd/thanos/compact.go
pkg/compact/compact.go
pkg/compact/compact_test.go

We observed thanos compactor was exiting on upload errors. Previously, a new 
error was created from all worker errors so the custom type was not propagated.
This introduces `go-multierror` to preserve the error types.
If all errors returned are retriable, it is safe to retry the compaction.
Since the compactor may still return a single error this logic is preserved.
(Happy to refactor out the duplicated logic with individual error checks.)
Tests are passing and I'll run this change with real workloads shortly.

Propagate retriable/haltable errors from compactor

---

cmd/thanos/receive.go
pkg/receive/handler.go

Currently, the receive component blocks indefinitely when the Thanos
process is interrupted because the given context is not actually used
to stop the server.
* This change adjusts the receive Handler struct to quit on context done.
* Remove unused quit chan
* start the receive component;
* send SIGINT
* verify that before the change the process does not exit
* verify that after fix process does exit

pkg/receive: remove deadlock on interrupt

---

cmd/thanos/bucket.go
docs/components/bucket.md

thanos bucket inspect --help
```
-l, --selector=<name>="<value>" ...
Selects blocks based on label, e.g. '-l key1="value1" -l key2="value2"'. All key value pairs must match.
```
must be:
```
-l, --selector=<name>=\"<value>\" ...
Selects blocks based on label, e.g. '-l key1=\"value1\" -l key2=\"value2\"'. All key value pairs must match.
```
I also updated the docs.
* add backslashes to bucket inspect help message
* add backslashes to bucket inspect docs

bucket: inspect help message

---

cmd/thanos/compact.go
cmd/thanos/downsample.go

When `compact` goes into its downsampling step, no app metrics are reported, which makes our dashboard look a bit bare for several hours (sometimes days if we have a backlog). Adding a couple of metrics means we can alert if no compactions or downsamples have happened in x period.
This is a little less clean than I'd like due to the two callers of `downsampleBucket` having slightly different contexts, however I think it's a reasonable compromise. Let me know what you think!
The metrics are labelled in the same way as compact metrics for ease of comparison.
Add `thanos_compact_downsample_total` and `thanos_compact_downsample_failures_total` downsampling metrics.
Tests are passing, will run with real workloads.

Add downsampling metrics

---

docs/getting-started.md

Don't think go depends on git anymore and even if it does the error
message would point in the right direction so no need to mention it
explicitly.
The tutorial is not GCS specific so no need to mention it at the
begining.
The go mod checksum error is already solved in the most recent golang
versions and  has enough google results how to resolve so no need to
mention it here.

Docs update

---

CHANGELOG.md
cmd/thanos/check.go
cmd/thanos/check_test.go
cmd/thanos/main.go
cmd/thanos/testdata/rules-files/invalid-rules-data.yaml
cmd/thanos/testdata/rules-files/invalid-unknown-field.yaml
cmd/thanos/testdata/rules-files/invalid-yaml-format.yaml
cmd/thanos/testdata/rules-files/valid.yaml
docs/components/check.md
scripts/genflagdocs.sh

Resolves #1096 
This adds `thanos check rules` command to check Prometheus rules.
We cannot use the `promtool check rules` since Thanos-rule allows the additional field `partial_response_strategy`
Tested it on different types of invalid rule files even valid. Works fine.

feat: added thanos check rules command

---

docs/components/check.md

:roll_eyes: sorry, forgotten from copy-pasting

docs: fix typo in check rules cmd docs

---

pkg/discovery/dns/provider.go

Add `thanos_querier_store_apis_dns_provider_results` / `thanos_ruler_query_apis_dns_provider_results` metrics.
`count(dns_provider_results)` tells us how many addresses have been
configured through flags and file-SD, while `sum(dns_provider_results)`
gives us the number of endpoints actually produced from these addresses.
Ran `thanos query --store=localhost:10901`, navigated to `localhost:10902/metrics` and found the entry:
```
thanos_querier_store_apis_dns_provider_results{addr="localhost:10901"} 1
```

Query/Ruler: Add metric for number of endpoints resolved for each configured address.

---

pkg/receive/handler.go

The thanos receive component instruments its handler with some metrics
but these metrics are currently never registered.
Register the receive handler metrics with the given registerer during creation. 
Scrape the receive component's /metrics endpoint to verify that the handler metrics are now present.

pkg/receive: register handler metrics

---

pkg/receive/handler.go

As per the discussion in
https://github.com/improbable-eng/thanos/pull/1261#issuecomment-503561741,
let's add a metric to track the total number of requests handled by the
receive component.
Add a `thanos_http_requests_total` metric to the receive component.
* start thanos receive
* make a request against the receive endpoint; and
* verify that the counter is increased

pkg/receive: add requests counter metric

---

CHANGELOG.md
docs/storage.md
pkg/objstore/azure/azure.go
pkg/objstore/azure/azure_test.go
pkg/objstore/azure/helpers.go

Closes #1252 
Changelog entry:
* [#1253](https://github.com/improbable-eng/thanos/pull/1253) Add support for specifying a maximum amount of retries when using Azure Blob storage (default: no retries).
- Add field to Azure configuration to allow for specifying "maxretries".
- This retry value is used when creating a pipeline (most operations do this for things like stat'ing the bucket) and when downloading the bucket's context.
_(Note: the Azure library does not currently support retries for uploads or for deletions)._
All tests pass. Verified `query`, `store`, `bucket inspect`, `bucket ls` commands all work.

Add Support for retries when using Azure Blob Storage

---

cmd/thanos/receive.go
docs/proposals/approved/201812_thanos-remote-receive.md
pkg/receive/handler.go
pkg/receive/hashring.go
test/e2e/query_test.go
test/e2e/receive_test.go
test/e2e/spinup_test.go

This commit adds a new replication feature to the Thanos receiver.
By default, replication is turned off, however, when replication is
enabled (replication factor >=2), the target node for a time series will
replicate the time series to the other nodes concurrently and
synchronously. If the replication to >= (rf+1)/2 nodes fails, the
original write request is failed.
* add optional replication to the Thanos receive component
* add e2e tests to exercise replication
* e2e tests
* manual testing to ensure replicated metrics appear in querier
* checking new metrics to ensure replication errors don't increase in regular operation
cc @brancz @bwplotka @metalmatze

receive: Replication

---

docs/proposals/approved/201812_thanos-remote-receive.md

This commit makes a small fix to the spelling of `REPLICATION_FACTOR`
as suggested by bwplotka in
https://github.com/improbable-eng/thanos/pull/1270#discussion_r296797981.
cc @bwplotka :)

docs/proposals: fix replication factor spelling

---

README.md
docs/integrations.md

I am happy to add more information about the integration, but I believe if something is missing it  should be added to the original documentation of Geras.
* add link to integrations.md from the main README.md
* start integrations.md doc

docs: add integration docs

---

pkg/store/cache/cache.go
pkg/store/cache/cache_test.go

This affects adding new items to the cache:
1. It removes the max iterations restriction.  See https://github.com/improbable-eng/thanos/issues/1257#issuecomment-503824210 for reasoning.
2. If the item is small enough to fit but doesn't fit even after the cache has been emptied, the cache is reset to recover from an internal accounting error (this should never occur).
Updated tests.
Please let me know if you'd like a CHANGELOG entry.
Fixes #1257

store/cache: remove iteration limit and reset on internal inconsistency

---

pkg/receive/handler.go

If the replication factor is 1, we can skip the replicate() function
call and directly forward the requests. Replicating to 1 endpoint
still exhibits correct behavior but requires another func call and mem.
Additionally, doing this cleanup means that when a node fails to
store a time series locally, the returned error message is about the
local store rather than about failing to replicate to 1 endpoint.

pkg/receive: optimize when replication factor is 1

---

pkg/ui/ui.go

* use `template.Funcs` to overwrite prefix rendering function to avoid concurrent map writes
Run `go run github.com/improbable-eng/thanos/cmd/thanos query`
And then concurrently HTTP GET "http://0.0.0.0:10902/graph" 1000 times
Before change:
It panics with concurrent map writes.
After change:
No longer panics.

Fixes #1272: fix map concurrent writes when rendering html templates in ui

---

pkg/query/iter.go
pkg/query/querier.go
pkg/query/querier_test.go

Fixes the problem with `sum` and inflated values as outlined here: https://github.com/improbable-eng/thanos/issues/922.
The problem was the following: `sum` selects the last value of each time series in each window and adds the different dimensions up however our code asks for the downsampled sum value which is equal to all samples added up in either a 5m or 1h window, and adding those up, obviously, results in an inflated value. The practical result was that as if we applied `sum_over_time(...[5m])` on top. So the fix is to ask for the last sample in each window in the case of `sum` instead of the aggregated value.
Also adds an E2E test for a typical setup of one Sidecar connected + one or more
Thanos Store nodes. Tests and shows how the whole thing with `sum` really works.
Testing: …

query/querier: fix sum() inflated values problem

---

docs/getting-started.md

While running make I noticed the following error message:
......
building binaries /root/work/bin
thanos
github.com/prometheus/tsdb/goversion/root/work/pkg/mod/github.com/prometheus/tsdb@v0.8.0/goversion/init.go:17:9: undefined: _SoftwareRequiresGOVERSION1_12
......
The requirements in place are 1.10+
After running it with go 1.12.6 (https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz), make succeeded as expected
......
building binaries /root/work/bin
thanos
/root/work/src/github.com/improbable-eng/thanos
[root@8a40500422c4 thanos]# ./thanos --version
thanos, version 0.5.0-master (branch: master, revision: 11d77980618b1df4753eb96006188ea535f3f8a7)
build user:       root@8a40500422c4
build date:       20190626-16:31:59
go version:       go1.12.6
......

Update golang version in requirements

---

CHANGELOG.md
cmd/thanos/bucket.go
docs/components/bucket.md
pkg/runutil/runutil.go
pkg/ui/bucket.go
pkg/ui/static/js/bucket.js
pkg/ui/templates/bucket.html
pkg/ui/templates/bucket_menu.html
scripts/genflagdocs.sh

Exposes a web interface for the state of Thanos buckets just like `pprof web`.
This is an early preview, the code is rough on the edges and could use some
review. See the screenshots for some examples.
**What works?**
- Can display the timeline of blocks per shard
- Can print error messages if any
- Reloads data from remote storage every 30m
- Reloads browser slightly smarter than that
**TODOS**
- Some download code is duplicated from `ls -o json`; refactor as needed
- Some web code is duplicated from query UI; refactor as needed
- Do we need any of the route prefix?
- Unfortunately learned a bit late that the JS libraries cannot be vendored. That sucks :(
- The tooltip is pretty basic and can contain a lot more useful info.
- Allow some kind of filtering and other bells and whistles to …

Add web UI to display the state of Thanos bucket

---

CHANGELOG.md
go.mod
pkg/query/storeset.go
pkg/query/storeset_test.go
pkg/store/prometheus.go
pkg/store/prompb/remote.pb.go
pkg/store/proxy.go
pkg/store/proxy_test.go
pkg/store/storepb/custom.go
pkg/store/storepb/rpc.pb.go
pkg/store/storepb/rpc.proto
pkg/store/storepb/types.pb.go
pkg/store/tsdb.go
pkg/ui/templates/stores.html
scripts/quickstart.sh
test/e2e/rule_test.go

This PR adds that the Info gRPC service now exposes potentially multiple label-sets. For all store types except `proxy` this doesn't change anything for now, it just adds the currently single label-set as the only entry in the list of label-sets. The `proxy` type, from now exposes it's stores' labels merged with its configured selector.
I'd like to ask that the `proxy.go` changes are particularly carefully reviewed.
Adapted all tests and see them passing.
@squat @bwplotka @GiedriusS @povilasv @domgreen

*: Allow exposing multiple label-sets

---

pkg/component/component.go
pkg/prober/prober.go
pkg/prober/prober_test.go

This PR adds prober package/component which will unify readiness and health checks of all thanos components.
For more info please refer to the PR https://github.com/improbable-eng/thanos/pull/656

feat: added prober package to generalize readiness probes

---

pkg/receive/config.go
pkg/receive/hashring.go

Currently, it is possible for the hashring configuration update channel
to be closed before the hashring config watcher has completely stopped.
This means that the config watcher can attempt to write on a closed
chan. This commit fixes that by closing the chan only after the config
watcher will never write again to the chan. This also prevents further
errors of this type by changing the ownership of the chan so that the
goroutine writing to the chan is the one closing it.
This commit also ensures that a closed hashring config chan does not
trigger a new hashring to be sent on the update chan.
cc @bwplotka @brancz

pkg/receive: ensure hashring chan closes after ctx

---

pkg/prober/prober.go

AFAICT there was an idea to use a general RWMutex componentMtx but then
it was removed in favor of two separate RWMutexes for the readiness and
healthiness probes.
Remove it from the struct to unblock the build.

prober: remove unused componentMtx

---

cmd/thanos/sidecar.go

Addresses https://github.com/improbable-eng/thanos/issues/1239 by adding a step that will force a wait on external labels before starting the shipper (when upload is enabled).
Note that the case of `len(m.Labels())` is already checked in the sidecar when it initially syncs with Prom.  However, we don't currently hard-fail if `len(m.Labels())==0`as we retry indefinitely.  With this PR, we would now hard-fail in that case (after 2 minutes).

sidecar:  wait on ext labels before uploading

---

pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/proxy.go
pkg/store/proxy_test.go
pkg/store/tsdb.go

Addresses https://github.com/improbable-eng/thanos/issues/1305

Make it clear, explicit, and fail early on query with just external labels.

---

pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/proxy.go
pkg/store/proxy_test.go
pkg/store/tsdb.go

Merging it into `master`. I think @bwplotka accidentally merged it into a wrong branch which has a similar name to `master`. Original PR: https://github.com/improbable-eng/thanos/pull/1310

Make it clear, explicit, and fail early on query with just external labels

---

CHANGELOG.md

Adds an entry to the CHANGELOG for the fix added in #1311, since I overlooked that initially :sweat_smile: 
N/A

add CHANGELOG entry for PR #1311

---

cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

Remove the code `runutil.CloseWithLogOnErr(logger, l, "store gRPC listener")`, because when the grpc server is stopped, the listener who grpc server served will be closed too.
Send SIGHUP to the thanos components, such as query, store, sidecar. No warning log appeared like this:
`level=warn ts=2019-07-12T04:20:03.867228785Z caller=runutil.go:108 component=sidecar msg="detected close error" err="store gRPC listener: close tcp 0.0.0.0:10901: use of closed network connection"`

Remove duplicate closing grpc listener

---

pkg/query/api/v1.go
pkg/query/api/v1_test.go

Prometheus' /series end-point returns an empty array no matter what: if
there were results or not. We need to follow the same principle in
Thanos as well because our users depend on it.
The same fix has been applied as here:
https://github.com/prometheus/prometheus/blob/fef150f1b5e48652ec6779e2129ae9a0cf13db8a/web/api/v1/api.go#L506
Tests have been updated to account for this difference and plus one test
has been added just for this case.
Closes #1325.

api/series: return an empty array iff no results

---

CHANGELOG.md
VERSION

Brings everything from the 0.6.0 tag into master + appropriate VERSION
value. Also, remove some unneeded whitespace from CHANGELOG.md.

CHANGELOG/VERSION: bring 0.6.0 into master

---

CHANGELOG.md
pkg/query/storeset.go
pkg/query/storeset_test.go

Fixes https://github.com/improbable-eng/thanos/issues/1337
cc @PsychoSid

querier: Allows single store in case of duplicates. Drop others.

---

docs/design.md

Fix a couple of typos in the design doc

---

pkg/promclient/promclient.go

Move suggestion about admin API to appropriate place

---

docs/components/store.md

Removing this after gossip removal, also, is there anything that needs to be added?
Updated doc removing cluster argument for Store.
Just a doc change

Remove deprecated option from example

---

katacoda.yaml

Katacoda added the possibility to define an attribute in katacoda.yaml to determine the location of the katacoda scenarios in the git repo.
We have tested with your repo, and worked fine. 
We will be happy to help if you have questions building the scenarios.
Signed-off-by: Gabriela S. Soria <soria.gaby@gmail.com>
Added `katacoda.yaml ` file setting the property 
`scenario_root : tutorials/katacoda
`
We have tested cloning using the forked repository inside https://katacoda.com

Added katacoda.yaml file to determine the location of the katacoda scenarios in the git repo.

---

docs/storage.md
pkg/objstore/s3/s3.go
pkg/objstore/s3/s3_test.go

Some S3 compatible setups may have a different limit for maximum
file size in multipart uploads, so allow for overriding it.
Signed-off-by: Lukasz Jernas <lukasz.jernas@allegro.pl>
* [ENHANCEMENT] Allow for setting minimal part size for S3 multipart uploads
Added `part_size` parameter to S3 YAML config file in bytes to allow for setting different multipart part size for chunk upload.
Added a config test and tested in a real world scenario.

Multipart features

---

CHANGELOG.md
cmd/thanos/compact.go
cmd/thanos/main.go
tutorials/kubernetes-demo/manifests/thanos-compactor.yaml

Used new Prober package in the Thanos compact to provide `/-/healthy` and `/-/ready` endpoints
I also added new `defatltHTTPListener` which registers the prober. I'm leaving the old `metricHTTPListenGroup` with `TODO` to remove it once all components are migrated to the new one to avoid touching different components in this PR.
Also I switched to using `component.Component` instead of passing the string from the main. 
It felt weird to have somewhere string and somewhere the component interface.
Tested it and works as expected, also exposes metrics about Prober status 
```
thanos_prober_healthy{component="compact"} 1
thanos_prober_ready{component="compact"} 1
```

feat compact: added readiness Prober

---

pkg/receive/handler.go

Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

receiver: avoid race of hashring

---

CHANGELOG.md
pkg/receive/config.go

This PR adds new metrics to monitor hash-rings.
It exposes the number of nodes and the number of tenants per hash-rings.
* Adds two new metrics to receive `thanos_receive_hashring_nodes` and `thanos_receive_hashring_tenants`.
By using make test and manual testing against receive API, it seems like the previous behavior kept intact.

receive: Hash-ring metrics

---

pkg/receive/handler.go

Ensure we log unexpected errors in the Thanos receive component.
This commit also ensures we properly count errors in the
thanos_receive_forward_requests_total metrics.
cc @brancz @metalmatze

pkg/receive/handler.go: log errors

---

pkg/receive/config.go

This PR attempts to store the most recent config md5 checksum, and when it happens as metrics to catch any inconsistencies between current and desired state. The same strategy is used by [prometheus/alertmanager#coodinator](https://github.com/prometheus/alertmanager/blob/master/config/coordinator.go).
* Exposes 3 new metrics: `thanos_receive_config_hash`, `thanos_receive_config_last_reload_successful` and `thanos_receive_config_last_reload_success_timestamp_seconds`.
`make test`, `make lint`, `make build` and manual verification of the metrics.

receive: Store the most recent config hash and timestamp as metrics

---

Makefile

The command `make build` fails when `$GOPATH` contains multiple paths separated by `:`:
Example:
```
$ echo $GOPATH
/go:/opt/rh/go-toolset/root/usr/share/gocode
$ make build
Makefile:99: *** target pattern contains no `%'.  Stop.
```

Fix usage of $GOPATH in Makefile

---

pkg/block/index.go
pkg/store/bucket.go

This PR attempts to reduce the memory used by the store component when initializing the local cache during startup. It transforms the `map[uint32]string` into a `[]string`, accepting that there might be many, many empty elements in the slice. This also makes it so that there is no difference between a non-existing label and an empty label.
Testing showed a reduction from 4.0 GiB to 3.6 GiB when loading 3 GiB data from S3 (on an XPS 13 running Ubuntu 18.04).
I let the unit tests run, both with the original, my patched and and intentionally broken implementation to check if there are tests for the `lookupSymbol()` function at all.

store: use a slice instead of a map for storing the symbols in an index

---

cmd/thanos/compact.go
docs/components/compact.md

fix #1377
Do I have to remove the `debug` prefix of this flag?

unhide disable-downsampling flag in compactor

---

pkg/store/prometheus.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
just correct misspelled words in error message
just correct misspelled words in error message

prometheus.go: fix typos in error message

---

CHANGELOG.md
Makefile
docs/components/query.md
docs/contributing/how-to-contribute-to-docs.md
pkg/promclient/promclient_e2e_test.go
pkg/receive/handler.go
pkg/store/prompb/remote.pb.go
pkg/store/storepb/rpc.pb.go
pkg/store/storepb/rpc.proto
pkg/store/storepb/types.pb.go
tutorials/kubernetes-demo/manifests/prometheus-pv-0.yaml

Fixed some misspells, added couple of useful linters.

---

README.md
website/hugo.yaml
website/layouts/index.html

* Added a link to the quay.io Docker images to the homepage.
* Built website locally and confirmed it looks as expected.

Add link for Docker images to homepage

---

CHANGELOG.md
examples/grafana/thanos-query.json
pkg/extprom/http/instrument_server.go
pkg/query/api/v1.go
pkg/query/api/v1_test.go
pkg/receive/handler.go

This PR attempts to unify HTTP server instrumentation behavior across components and removes unnecessary metrics. Thanos Query and Receive now use common instrumentation middleware. 
PTAL #1420 for previous discussions.
* Thanos Query no longer exposes `thanos_query_api_instant_query_duration_seconds`, `thanos_query_api_range_query_duration_second` metrics.
* Thanos Receive no longer exposes `thanos_http_request_duration_seconds`, `thanos_http_requests_total`, `thanos_http_response_size_bytes`.
Local `make test` and run.

query/receive: Unify HTTP server instrumentation

---

cmd/thanos/main.go
go.mod
go.sum

Add uber-go/automaxprocs integration to automatically set maxprocs value according to cgroup limit or $GOMAXPROCS env variable
Run any thanos component with --log.level=debug in docker container with cpus limit or not empty env variable GOMAXPROCS and see debug log message from library which value has been set for golang maxprocs.

Add automaxprocs

---

CHANGELOG.md
pkg/query/iter.go
pkg/query/querier.go
pkg/query/querier_test.go
pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/store/proxy_test.go
pkg/store/storepb/custom.go
pkg/store/storepb/custom_test.go
pkg/store/storepb/rpc.pb.go
pkg/store/storepb/rpc.proto

Fixes: https://github.com/improbable-eng/thanos/issues/488

sidecar: Added support for streaming, chunked remote read.

---

cmd/thanos/compact.go
cmd/thanos/downsample.go

Use `block.DownloadMeta` method to download block meta.
Reduce some duplication.

cmd: reduce code duplication

---

cmd/thanos/query.go
docs/components/query.md
pkg/query/api/v1.go
pkg/query/api/v1_test.go

* [] Added `thanos query --query.instant.default.max_source_resolution` flag to set a default value for maxSourceResolution on instant queries (as are for example used by the `thanos rule` component)
* [] Added support for the max_source_resolution query parameter for `/api/v1/query`
We have configured our compactor with different retentions for different resolution levels:
```
thanos
compact
--log.level=debug
--data-dir=/var/thanos/store
--objstore.config-file=/s3/thanos.yaml
--retention.resolution-raw=7d
--retention.resolution-5m=30d
--retention.resolution-1h=180d
--wait
```
This causes a situation where the result of a `thanos rule` recording rule was
only taking the last 7-8 days of data into account, because instant queries were
always using a maxSourceResolution of 0 and therefore …

Support max source resolution for instant queries

---

CHANGELOG.md
cmd/thanos/compact.go
cmd/thanos/main.go
cmd/thanos/sidecar.go
pkg/prober/prober.go
tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar-lts.yaml
tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar.yaml

_Next PR in the from the series of adding readiness and liveness probes._
Added readiness and liveness prober to the thanos sidecar.
It follows the logic of setting the `promUp` metric so when it successfully fetches config of the Prometheus it becomes ready.
The question is should it take into account status of the GRPC interface also?
1.  started sidecar without running the Prometheus instance results in 
```
$ curl http://0.0.0.0:10902/-/ready
thanos sidecar is not ready. Reason: request flags against http://localhost:9090/api/v1/status/config: Get http://localhost:9090/api/v1/status/config: dial tcp 127.0.0.1:9090: connect: connection refused
``` 
2.  started the prometheus sidecar becomes ready
```
$ curl http://0.0.0.0:10902/-/ready …
```

feat sicedar: added readiness prober

---

CHANGELOG.md
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

This PR initializes gRPC server metrics as soon as server starts, to provide more reliable data for instrumentation.
* Initialize gRPC server metrics
* `make test | build | lint` and local test

*: Initialize gRPC server metrics

---

pkg/ui/templates/alerts.html
pkg/ui/templates/rules.html

[Bugfix]: User can not click the link of `expr` or `alert` to jump to Query ui in rule pages.
Visit the rule or alert page, and try to click the link of `expr` or `alert`.

Rule: Fixed wrong query url in rules and alerts pages

---

cmd/thanos/receive.go
scripts/quickstart.sh
test/e2e/spinup_test.go

Signed-off-by: Wing924 <weihe924stephen@gmail.com>
fixes #1497 

make label flag consistent in receive and rule

---

cmd/thanos/receive.go

Allow setting frequency at which TSDB blocks are created for the receive service.
Extracted tsdb minBlockDuration and maxBlockDuration used in receive service into flag that defaults to the current value of 2h.
Built and ran service locally to ensure that the flag takes effect as intended.

Allow setting TSDB block duration for receive service

---

docs/getting-started.md

@bwplotka 
Fixes invalid link causing CI to fail 
https://circleci.com/gh/thanos-io/thanos/4811?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

fix docs: fixed getting started link to release process

---

pkg/store/bucket.go

I experienced a slow drip of "key does not exist" errors, presumably due to compactions, then nearly all get_range requests began to fail with "pool exhausted" errors.
caller | err
-- | --
bucket.go:871 | rpc error: code = Aborted desc = fetch series for block 01DM8ACH11QQQESTY0VET5PXKS: preload chunks: read range for 1: get range reader: The specified key does not exist.
bucket.go:871 | rpc error: code = Aborted desc = fetch series for block 01DMA1C7D151KM6H1DGY498WWQ: preload chunks: read range for 6: allocate chunk bytes: pool exhausted
Return the byte slice to the pool on error paths.
N/A

store: fix chunk pool memory leak

---

CHANGELOG.md
pkg/block/block.go
pkg/store/bucket.go

fixes #1504
- store: delete block dir with missing `meta.json` on startup

fix store: handle invalid cache block dir

---

tutorials/katacoda/thanos/1-globalview/index.json
tutorials/katacoda/thanos/1-globalview/step3.md

fix typo of step 3 of  `Intro: Global View and seamless HA for Prometheus`  in katacoda

docs: fix typo of katacoda 1-globalview

---

CHANGELOG.md
go.mod
go.sum
pkg/block/block.go
pkg/block/block_test.go
pkg/compact/compact.go
pkg/compact/retention.go
pkg/objstore/inmem/inmem.go
pkg/objstore/objstore.go
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/shipper/shipper_e2e_test.go
pkg/verifier/safe_delete.go

Fixes https://github.com/thanos-io/thanos/issues/1331
Problem that we are fixing is explained in the linked issue.
Also the problem will be fully fixed once this is also done: https://github.com/thanos-io/thanos/pull/1394 This is because although major parts of Thanos for syncing blocks is resilient to partial uploads, there are some points when we don't handle it properly (crash e.g compactor)
cc @lx223 @metalmatze 

Fixed partial delete issues on compactor; Added Upload/Delete tests.

---

CHANGELOG.md
cmd/thanos/bucket.go
docs/components/bucket.md

Signed-off-by: Johnathan Falk <johnathan.falk@gmail.com>
Fixes #1532 
Added timeout flag to bucket inspect
Built and run

Add bucket inspect timeout flag

---

cmd/thanos/compact.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/sidecar.go
tutorials/kubernetes-demo/manifests/thanos-querier.yaml

This PR,
* Adds `/-/ready` endpoint for readiness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Uses `prober.Prober` for readiness and liveness endpoints.
* Changes ~`defaultHTTPListener`~ `scheduleHTTPServer` to consume an existing `http.Handler`
1. `make test`
2. Started `thanos query` and made a request to related endpoints.
```console
➜ curl http://0.0.0.0:10902/-/healthy
thanos query is healthy
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos query is not ready. Reason: thanos query is initializing
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos query is ready
```

query: Add readiness probe to query

---

CHANGELOG.md
cmd/thanos/main.go
cmd/thanos/rule.go
tutorials/kubernetes-demo/manifests/thanos-ruler.yaml

This PR,
* Adds `/-/healthy` endpoint for liveness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Adds `/-/healthy` endpoint for liveness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Uses `prober.Prober` for readiness and liveness endpoints.
1. `make test`
2. Started `thanos rule` and made a request to related endpoints.
```console
➜ curl http://0.0.0.0:10902/-/healthy
thanos rule is healthy%
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos rule is not ready. Reason: thanos rule is initializing
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos rule is ready%
```
3. Started `thanos rule` and visited `http://localhost:10902/rules` to check UI.

rule: Add liveness and readiness probe

---

pkg/objstore/azure/azure.go

closes #1466 
* [#1469] Prevent EOF errors in Azure objstore
Make Azure objstore's GetRange smarter by recognizing when the requested size will be greater than the remaining length of the file to be downloaded. This prevents EOF errors described in #1466 
Verified compaction, initial download, and querying the store node all work (tested against Azure Blob with ~400GB of data)

store: Prevent EOF errors in Azure objstore

---

CHANGELOG.md
cmd/thanos/compact.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/sidecar.go
go.mod

This PR,
* Adds `/-/healthy` endpoint for liveness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Adds `/-/healthy` endpoint for liveness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Uses `prober.Prober` for readiness and liveness endpoints.
1. `make test`
2. Started `thanos receive` and made a request to related endpoints.
```console
➜ curl http://0.0.0.0:10902/-/healthy
thanos receive is healthy%
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos receive is not ready. Reason: thanos receive is initializing
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos receive is ready%
```

receive: Add liveness and readiness probe

---

CHANGELOG.md
cmd/thanos/downsample.go
cmd/thanos/main.go

This PR,
* Adds `/-/healthy` endpoint for liveness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Adds `/-/healthy` endpoint for liveness checks.
* Adds `/-/ready` endpoint for readiness checks.
* Uses `prober.Prober` for readiness and liveness endpoints.
1. `make test`
2. Started `thanos downsample` and made a request to related endpoints.
```console
➜ curl http://0.0.0.0:10902/-/healthy
thanos downsample is healthy%
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos downsample is not ready. Reason: thanos downsample is initializing
```
```console
➜ curl http://0.0.0.0:10902/-/ready
thanos downsample is ready%
```

downsample: Add liveness and readiness probe

---

docs/service-discovery.md

- Add documentation about the `dnssrvnoa` option that was added in https://github.com/thanos-io/thanos/pull/865

query: document the dnssrvnoa option

---

CHANGELOG.md
cmd/thanos/main.go
cmd/thanos/store.go
tutorials/kubernetes-demo/manifests/thanos-store-gateway.yaml

Added the prober to yet another component. Store this time.
The store does the bucket initialization and sync synchronously, so the default http server will start up only once it is finished. Then it gets healthy(live) and once the gRPC server starts up the store gets also ready.
Personally I'd much rather see the liveness probe to answer right from the start during the bucket init since this way we leave the bucket sync duration to some initial back-off of an orchestrator. 
- added prober to the thanos store
Started it and verified it gets ready end healthy as expected.

feat store: added readiness and livenes prober

---

cmd/thanos/flags.go
docs/components/bucket.md
docs/components/check.md
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
pkg/shipper/shipper.go

Mostly minor type/grammar/punctuation fixes in components markdown files.
Signed-off-by: Callum Styan <callumstyan@gmail.com>

Fix typos, including 'fomrat' -> 'format' in tracing.config-file help text

---

docs/components/compact.md

Added a `Groups` section in `compact.md` explaining the importance for the `external_labels` to be both unique and persistent across different Prometheis.
I have recently had to deal with quite a large data loss incident. 
I believe that it happened because we had a compactor running while the `external_labels` of the Prometheis that produced blocks for it had as `replica` a value that had a hash appended to it. 
That hash changed when a Prometheus version restarted for some reason, since it was a hash generated on startup. No more blocks from the group generated by the now-dead replica arrived, and so the old blocks never became big enough for them to be downsampled, and eventually they were deleted because of the retention policy we had.
So I think it's quite important to explain how …

Adding doc explaining the importance of groups for compactor

---

docs/proposals/201809_gossip-removal.md
docs/proposals/201901-read-write-operations-bucket.md

The format of these files is wrong in thanos website.
See https://thanos.io/proposals/201809_gossip-removal.md/
Signed-off-by: dongwenjuan <dong.wenjuan@zte.com.cn>

Add blank line for list

---

cmd/thanos/bucket.go
cmd/thanos/downsample.go
pkg/compact/compact.go
pkg/compact/downsample/downsample.go

I wanted to add some metrics but actually I have realized that I don't need them in the middle. However, this has turned out into a nice refactoring PR. The following things were done:
* `UNTIL-COMP` column in `bucket inspect` has been renamed into `UNTIL-DOWN` because that is what it actually shows - time until the downsampling
* Some constants that were sprinkled all over the code were moved into one package

Refactor compactor constants, fix bucket column

---

pkg/testutil/prometheus.go
pkg/testutil/sysprocattr.go
pkg/testutil/sysprocattr_linux.go
test/e2e/spinup_test.go

The unguarded use of Linux-specific fields in `syscall.SysProcAttr` makes developing a little awkward on non-Linux systems. This change makes tests build and run on systems other than linux.
Extract configuration of `syscall.SysProcAttr` for prometheus and spinup_test to separate files with build flags (!linux/linux) so test code compiles on all platforms.
I was able to run tests on OSX

Make tests buildable on non-linux systems

---

Dockerfile.multi-stage
Dockerfile.thanos-ci
go.mod

bumping version of go to 1.13.1

---

pkg/receive/handler.go
test/e2e/receive_test.go

When the number of replication errors are below the error threshold,
the replication func should not return an error.
Fixes: #1508
e2e tests
cc @brancz @R4scal

pkg/receive: replication should succeed if length errs < threshold

---

pkg/store/bucket.go

This PR fixes #1580 
It fixes the immediate issue, but it could be worthy to discuss if pool.BytesPool is necessary at all or could be replaced by a simpler direct usage of sync.Pool
* Match store bytes pool size to size of chunks used by chunkByteReader.
* extract constant nested in method to package level
* change pool.BytesPool construction to use chunk size as smallest bucket size
The store does no longer exhaust its byte pool size on larger buckets

Set minimum buffer size of BytesPool to maxChunk size

---

cmd/thanos/receive.go

This commit fixes a panic caused by sending on the chan which is closed
too early. This chan was closed when the setup func returned, rather
than when the group's goroutine returned.
Fixes: #1594

cmd/thanos/receive: fix close chan panic

---

CHANGELOG.md
cmd/thanos/rule.go
cmd/thanos/rule_test.go

fixes #1564 
- fixed issue when Alertmanager URL contains `+` which can be for example in credentials 
- added tests which are passing
- tested to startup the rule with various URLs

fix rule: fixed issue with alertmanager URL containing +

---

Makefile
build-check-comments.sh
scripts/build-check-comments.sh

OS X fix for https://github.com/thanos-io/thanos/pull/1599
- OS X grep is different from Linux and original PR didn't work
- To avoid complex OS detection in Makefile, move to external script
- Also to avoid OS X specific grep/regex (it's complex enough!), use reliable Linux distro in Docker
People may not like the dependency on Docker, of course.
No CHANGELOG, Change is not relevant to the end user.
- Makefile (edit)
- build-check-comments.sh (add)
- Change is not relevant to the end user.
Question: should `build-check-comments.sh` live in `scripts` dir?
Manual tests on OS X and in Linux docker containers. Tested for overrides etc.
Tested adding bad comments to trigger the check. All seems to work.

OS X fix for `make check-comments`

---

cmd/thanos/receive.go

Avoid flushing the WAL twice when starting the receiver. Instead we wait for the hashring to be loaded which will force a WAL flush. When stopping the receiver we also stop the DB before flushing to avoid re-opening the DB unnecessarily.
Signed-off-by: Devin Trejo <dtrejo@palantir.com>
* [] I added CHANGELOG entry for this change.

receiver: Avoid flushing the WAL twice on startup

---

cmd/thanos/receive.go
pkg/receive/handler.go
pkg/tracing/http.go

This commit instruments the Thanos receive component's HTTP server with
the specified tracer. Specifically, it adds spans for each request
forwarded between receive nodes.
Change is not relevant to the end user.

pkg/receive: add tracing to forwarded requests

---

cmd/thanos/rule.go
docs/components/rule.md

keep same logic with prometheus resend delay configuration and EndsAt time

keep same logic with prometheus resend delay configuration

---

.github/PULL_REQUEST_TEMPLATE.md

- updated the PR template so the checkboxes are by default displayed as empty (it always irritated me :D) 
- added example changelog entry, as once discussed, to lower the release burden with formatting changelog.

chore: updated github PR template with changelog entry format

---

docs/proposals/201909_thanos_sharding.md

cc @jojohappy @mattrco @metalmatze

Proposal for Thanos Sharding.

---

pkg/receive/handler.go
pkg/receive/handler_test.go
pkg/receive/writer.go

This commit ensures that the `replicate` func does not falsely identify
a replication error as a conflict. If the number of conflict errors
during replication is less than the minimum replication threshold, then
replication cannot be said to have failed due to a conflict and the
request should be retried.
Fixes: #1615
xref: #1563
cc @brancz @dtrejod

pkg/receive: avoid false positive conflict err

---

CHANGELOG.md
cmd/thanos/compact.go
cmd/thanos/flags.go
cmd/thanos/store.go
docs/components/compact.md
docs/components/store.md
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/compact/compact_test.go
pkg/query/storeset.go
pkg/query/storeset_test.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go
test/e2e/spinup_test.go
test/e2e/store_gateway_test.go

Implement partial parts of proposal #1501 :
* Add relabel config into Thanos, store gateway and compactor are supported now.
* Selecting blocks to serve depends on the result of block labels relabeling.
* For store gateway, expose advertise labels after relabeling.
* Allow the duplicate external labels for store gateway components.
Note: pre-filter has been implemented before this PR.
TODO:
@bwplotka @brancz @povilasv @GiedriusS PTAL, thanks!

Store,Compactor: Thanos sharding

---

.circleci/config.yml
CHANGELOG.md
Makefile
cmd/thanos/sidecar.go
cmd/thanos/store.go
docs/components/sidecar.md
docs/components/store.md
pkg/store/prometheus.go
pkg/store/prometheus_test.go
pkg/testutil/prometheus.go

Rebased and with addressed comments of this: https://github.com/thanos-io/thanos/pull/1267
Fixes https://github.com/thanos-io/thanos/issues/1191
TODO:

Added min-time limitaiton for sidecar. This allows optionally storing longer retention time on Prometheus.

---

docs/components/sidecar.md

This adds a section to the sidecar docs about the experimental flag `--shipper.upload-compacted`.
We struggled to find a way to upload our historical Prometheus data to the object store and stumbled upon the issue #348 which mentions the flag.
A section with the name "Upload compacted blocks (EXPERIMENTAL)" was added to the docs for the sidecar component explaining how to upload already compacted blocks for migrating to a Thanos setup.

docs: Add section to sidecar docs for uploading compacted blocks

---

CHANGELOG.md
cmd/thanos/store.go
pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go
pkg/query/internal/test-storeset-pre-v0.8.0/storeset_test.go
pkg/query/storeset.go
pkg/query/storeset_test.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go

Current idea is to remove duplication for now as it's tricky to make it right and we aim to unblock v0.8.0. Ticket to consider it back: https://github.com/thanos-io/thanos/issues/1635
Changes:
* Cleaned up the code a bit.
* Ensured proper locks.
* thanos_store_nodes_grpc_connections is not per store type and external labels. thanos_store_node_info is marked as deprecated.
* Added (optional, but enabled by default) compatibility label to store GW Info method (`@thanos_compatibility_store_type" = "store"`. ) with flag to disable it. Store only adds it if there is any labelset to advertise.
* Disabled any strict deduplication in external labels detection; just warning!
* More tests; compatibility tests for query pre 0.8.0 and new store GW.
* Remove compatibility label if spotted.
Fixes …

Removed Querier duplicate labels checks & made sure store will be not blocked for older Queriers.

---

cmd/thanos/receive.go
pkg/receive/handler.go
pkg/receive/handler_test.go
pkg/receive/writer.go

This commit adds tests for the Thanos receive component's external HTTP
API. This rather large PR was motivated by fixing a regression that was
introduced in 19e59ef5369c2134ae3295bd29b86b05b82cb980, where returning
a MultiError threw off the error counting logic in the request
parallelization func, which could cause the wrong HTTP status code to be
returned. In order to protect against these regressions, we need
thorough testing of the external API.

pkg/receive: fix regression and add testing for receive external API to avoid future regressions

---

Makefile

ensure `make build` works when GOPATH is not set
- this gets me every single time;
- use `go env GOPATH` which also returns default;
* Change is not relevant to the end user.
- `Makefile`. This kind of fix is already in `thanosbench` repo. 
Manual tests:
- Go 1.13
- Explicitly set GOPATH;
- Empty GOPATH.

nit: ensure build works when GOPATH is not set

---

.circleci/config.yml
Makefile
cmd/thanos/bucket.go
docs/storage.md
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/s3/s3.go
scripts/cfggen/main.go

* Again, only for master/release builds and PRs from person with write-access to Thanos.

Added CI testing against S3 bucket.

---

cmd/thanos/flags.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

This commit cleans up a TODO in the flags.go file and eliminates the
regCommonServerFlags func, which added almost no additional utility
beyond calling regGRPCFlags and regHTTPAddrFlag.
low-priority cleanup.
cc @povilasv @bwplotka

cmd/thanos/flags: remove unhelpful flags helper

---

pkg/receive/tsdb.go
pkg/receive/tsdb_test.go

This commit ensures that we delete the WAL after it has been flushed to
a block. Flushing the WAL simply creates a block but does not remove the
WAL directory or its contents. This means that once the DB is re-opened,
new samples are added to the same WAL. Flushing the WAL again does not
result in blocks with overlapping time ranges because the flushing logic
guards against this
(https://github.com/prometheus/prometheus/blob/master/tsdb/db.go#L300).
Nevertheless, we should delete the WAL after flushing it to ensure that
flushed samples are not needlessly re-processed. Also, once multi-TSDB
support is added, holding old samples in the WAL could cause problems.
Ran thanos receive locally and ensured that after several starts and stops, …

pkg/receive: remove flushed WAL

---

CHANGELOG.md
cmd/thanos/sidecar.go
docs/components/sidecar.md

The current timeout while the Prometheus instance is starting up is a constant 10 minutes.
As reading the WAL can take a long time we would like to set a custom timeout value, so the Thanos sidecar container is not erroring out every 10 minutes.
I ran `make test` with the in-memory store tests.

Add a new prometheus.ready_timeout CLI option to the sidecar

---

cmd/thanos/main.go

This commit simplifies the registration of pprof HTTP endpoints. The
pprof.Index handler automatically takes care of delegating to the
correct handler for each profile depending on the request path:
https://golang.org/src/net/http/pprof/pprof.go?s=8862:9042#L260
The following profiles are handled:
https://golang.org/src/net/http/pprof/pprof.go?s=7565:8570#L248
Note that this also includes the `allocs` profile, which was previously
not explicitly added.
Built binary and verified all pprof endpoints continue to function.
cc @bwplotka

cmd/thanos/main.go: simplify pprof registration

---

pkg/store/bucket.go

Signed-off-by: Povilas Versockas <p.versockas@gmail.com>
Changes bucket functions to use `errgroup` instead of `run.Group` 
`run.Group` concurrently runs all of the goroutines, waits until the first actor exits, invokes the interrupt functions, and finally returns control to the caller only once all actors have returned. 
This makes it that if first goroutine returns `nil`, and other goroutine returns an error, we won't receive it, as it gets thrown away:
https://github.com/oklog/run/blob/master/group.go#L51-L53
On the other hand `errgroup` - blocks until all function calls from the Go method have returned, then returns the first non-nil error (if any) from them.
This will return us an error if any of the goroutines fail

Store: Refactor run group to errgroup

---

pkg/query/api/v1.go
pkg/query/querier.go

This will definitely helps with offset queries.
Same was done on https://github.com/cortexproject/cortex/pull/1012

querier: Actually use select Start,End params during select.

---

cmd/thanos/main_test.go

This small PR simply fixes an error message that confused me during a
review.

cmd/thanos/main_test.go: clarify backwards error

---

CHANGELOG.md
pkg/objstore/azure/azure.go
pkg/objstore/cos/cos.go
pkg/objstore/gcs/gcs.go
pkg/objstore/objstore.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/s3/s3.go
pkg/objstore/swift/swift.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go

Fixes: https://github.com/thanos-io/thanos/issues/1664

store: Filter blocks before loading it. Sort advertise labels; Added sharding e2e test.

---

cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/receive/handler.go

This commit gives the Thanos receive component the capability to use TLS
in both the remote-write client and server. This means that Thanos
receive can now authenticate all requests.
In order to accomplish this change, this commit abstracts the majority
of the logic of `defaultGRPCServerOpts` into a reusable func for gRPC
and HTTP servers and creates a similar func for TLS client
configurations.
cc @bwplotka @brancz, this is following our conversation yesterday about missing authn and encryption options for Thanos receive.

cmd/thanos/receive: remote-write client+server TLS

---

CHANGELOG.md
CONTRIBUTING.md
Makefile
docs/storage.md
go.mod
go.sum
pkg/objstore/client/factory.go
pkg/objstore/objtesting/foreach.go
pkg/objstore/oss/oss.go
scripts/cfggen/main.go

Open this PR as discussed in #1234 ， will update soon.

objstore : implement Aliyun OSS

---

CHANGELOG.md
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/flags.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
docs/components/compact.md
docs/components/query.md
docs/components/rule.md
docs/components/sidecar.md
docs/components/store.md
pkg/server/http.go
pkg/server/option.go

This PR adds a new CLI flag to components which serve HTTP, called `--http-grace-period`.
Also refactors existing code and introduces a new HTTP server package, to increase the clarity of the `run.Group` scheduling.
cc @bwplotka @FUSAKLA 
* Adds new `--http-grace-period` CLI flag to components which serve HTTP.
* Removes `scheduleHTTPServer` function and introduces a new package to handle HTTP serving.
* `make local-test`
* `./scripts/quickstart.sh`

.*: Add new http-grace-period flag

---

CHANGELOG.md
pkg/shipper/shipper.go
pkg/shipper/shipper_test.go

Fixes #1670
Signed-off-by: Olivier Biesmans <olivier.biesmans@blablacar.com>
Sidecar now uploads blocks with the lowest minTime first

Upload blocks with the lowest minTime first

---

pkg/objstore/s3/s3.go
pkg/query/api/v1.go
pkg/ui/static/js/graph.js
pkg/ui/static/js/graph_template.handlebar

Fixes #1463 
* Downsampling option in Querier UI is now reflected in the URL.

Fix downsampling option in querier URL

---

cmd/thanos/bucket.go
docs/components/bucket.md
pkg/ui/bucket.go

Currently, the bucket web command generates and registers metrics but
they are never actually exposed. This commit ensures that the metrics
are exposed and leverages the recently created server package for
consistency.
This cleanup also helps prepare for the upcoming changes for
https://github.com/thanos-io/thanos/issues/1657.
Changelog entry is already covered by #1680 
Launched bucket web component before and after change and ensured that metrics are exposed.

cmd/thanos/bucket: expose metrics

---

docs/governance.md

As per our discussion on Thanos Maintainer Sync we crafted first official Governance doc for Thanos project. Heavily based on Prometheus.
All maintainers, please read very carefully and review. Please approve *only* if you agree.
`Vote` for this change will be send next week (: Have a nice weekend!
@brancz @metalmatze @povilasv @domgreen @GiedriusS 

Added official Governance page for Thanos.

---

CHANGELOG.md
cmd/thanos/bucket.go
docs/components/bucket.md

While standardizing some flags, commit
9d4d0bf408ed86eaab371c8f0c52d7bb5fe6e164 accidentally added
a `--http-address` flag to the bucket web component that is never used.
However, rather than remove this new flag, this commit removes the
`--listen` flag that the component defines so that the component is in
line with the flags defined by other components.
cc @kakkoyun @bwplotka

cmd/thanos/bucket: remove unused flag

---

cmd/thanos/bucket.go
pkg/ui/bucket.go

This commit fixes a regression introduced in #1702, where the signature
of the bucketui.Register method was changed. The bug was caused because
one of the registered paths relied on the HTTP parameter variable
support from github.com/julienschmidt/httprouter, which the standard
library does not support. The fix is instead to implement the change
recommended in
https://github.com/thanos-io/thanos/pull/1702#discussion_r341269556.
Built and ran bucket web component and verified that the metrics and regular UI both work.

cmd/thanos/bucket: fix static fileserver

---

go.mod
pkg/receive/handler.go

The receive component currently has duplicate spans for requests handled
by its HTTP server. This is due to the fact that the server is
instrumented once using the global singleton tracer and then a second
time with the tracer configured via the CLI. This commit eliminates the
duplicate instrumentation via the global singleton in favor of the
explicit specified tracer, which is consistent with the practice of
other Thanos components.
Example of duplicate span:
Note that:
* both `/receive HTTP[server]` and `POST /api/v1/receive` represent the same operation; and that
* the span created by the global singleton, `POST /api/v1/receive` is erroneously setting the HTTP status code to `0`.

pkg/receive: eliminate duplicate tracing

---

pkg/store/bucket.go

- append to s.lset caused reallocs and overallocs
- this is now fixed by properly setting capacity on s.lset
- pprof shows "-316.22MB, 5.00% of 6322.82MB total" for sample data set and query I used
- Sample data generated with thanosbench using `realistic-k8s-1w-small` profile
- Query executed: `count({__name__=~".+"}) by (__name__)`
- Instrumented `BucketStore.Series` to dump heap profile at the start and end of the function call.
- Compared the profiles using pprof:
```
go tool pprof -sample_index=alloc_space -edgefraction=0 -lines -base heap-series-1-after-base.pb.gz  -http=:8080 heap-series-1-after-change.pb.gz
```
- PNG attached
- Heap profiles attached
[heap-series-1-after-base.pb.gz](https://github.com/thanos-io/thanos/files/3809061/heap-series-1-after-base.pb.gz) …

remove reallocs and overallocs for s.lset in bucket.go

---

cmd/thanos/receive.go

While debugging #1721, I found that when thanos receive bails, there is
a race in a select statement, where the non-returning branch may be
chosen. This branch will deadlock if selected twice because the channel
reader has already exited. The way to prevent this is by checking if
we need to exit on every loop.

cmd/thanos/receive: avoid deadlock

---

cmd/thanos/receive.go
pkg/receive/tsdb.go

Every time thanos receive is started, it has to replay the WAL three
times, namely:
1. open the TSDB;
2. close the TSDB; open the ReadOnly TSDB and Flush; and
3. open the TSDB
These WAL replays can take a very long time if the WAL has lots of data.
With the fix from #1654, the third time will be instantaneous because
the WAL will be empty. That still leaves two potentially long WAL
replays. We can cut this down to just one long replay if we do the
following operations instead:
1. with a closed TSDB, open the ReadOnly TSDB and Flush; and
2. open the TSDB
Now, the second step will be a fast replay because the WAL is empty,
leaving just one potentially expensive WAL replay.
This commit eliminates explicit opening of the writable TSDB during
startup, and instead opens it after flushing the …

cmd/thanos/receive: reduce WAL replays at startup

---

docs/components/rule.md

This addition to the documentation would have answered [this](https://cloud-native.slack.com/archives/CK5RSSC10/p1572959144493000) question that I raised on slack.
Added sentence to the documentation for `Ruler` component.
Not applicable.

Docs: Expand ruler recommended alerting docs

---

CHANGELOG.md
cmd/thanos/compact.go

Add a metric called thanos_compactor_iterations_total that is a counter
and will get increased by 1 every time an iteration gets executed
successfully. This is needed in case --wait is specified and then our
Compactor could die. We need to alert on such a case.
One thing would be to alert on a restart of the container however that
is not the most flexible thing - it might still be OK as long as it
successfully finishes its job in time. However, it is impossible to know
that exact part ATM.
Add this metric so that users could add alerts like:
```
rate(thanos_compactor_iterations_total[1d]) == 0
FOR 3d
```
There is `thanos_objstore_bucket_last_successful_upload_time` but still
that doesn't show if we were able to get through all …

compact: add metric thanos_compactor_iterations_total

---

cmd/thanos/query.go
pkg/compact/compact.go
pkg/extprom/http/instrument_server.go
pkg/objstore/objstore.go
pkg/server/grpc/grpc.go
pkg/store/bucket.go
pkg/store/gate.go

This PR changes existing bucket configurations to fix issues that observed with latency graphs.
For example, as you can observe there are large differences between mean and P50 latencies. 
* `thanos_compact_garbage_collection_duration_seconds_bucket`
* `thanos_compact_sync_meta_duration_seconds_bucket`
**This increases the number of buckets for most of the histograms. For certain metrics, it significantly affects cardinality. However, it's needed to properly instrument the components.**
Uses exponential buckets to provide more even distribution. (number of buckets, before and after)
* `grpc_server_handling_seconds_bucket` : 10 -> 15 (+exposes multiple labels)
* `http_request_duration_seconds_bucket` : 11 -> 17 (+exposes 3 labels, code, method, handler)
* …

*: Use exponential buckets for histogram metrics

---

CHANGELOG.md
cmd/thanos/bucket.go
docs/components/bucket.md
pkg/ui/bucket.go

* Added `--web.external-prefix` to `thanos bucket web` to support proxying on a subpath.
* Updated docs with current `thanos bucket web --help` output.
Built clean, worked as expected locally.

bucket: Add `--web.external-prefix` for proxying on a subpath

---

cmd/thanos/rule.go

Refactor the if loop checking whether the shipper is enabled or not to be easier to read.
`make test-local` runs fine.

cmd/thanos/rule: simplify if block

---

cmd/thanos/query.go
pkg/compact/compact.go
pkg/extprom/http/instrument_server.go
pkg/objstore/objstore.go
pkg/server/grpc/grpc.go
pkg/store/bucket.go
pkg/store/gate.go

This PR re-adjusts histogram buckets, as a follow-up to #1545.
Re-adjust smaller low latency buckets and limits maximum bucket size to default query timeout limit for read path.
* Refactor histogram buckets.
* `MINIO_ENABLED=1 ./scripts/quickstart.sh` and `curl /metrics`.

Re-adjust histogram buckets

---

CHANGELOG.md
cmd/thanos/bucket.go
docs/components/bucket.md
pkg/ui/bucket.go

Using the following build: quay.io/thanos/thanos:master-2019-11-20-af2a342b, I encountered 404s on static resources when trying to run the bucket web UI behind a Nginx proxy. 
- This PR fixes that by ensuring that the UI is handled at the provided external path.
- Added web.prefix-header to provide similar functionality available in the Query UI
I am running an internal build of this branch behind a Nginx proxy with no issues.
Fixes: https://github.com/thanos-io/thanos/issues/1349

Fix web.external-prefix 404s and add web.prefix-header for bucket web UI.

---

CHANGELOG.md
pkg/rule/api/v1.go
pkg/rule/api/v1_test.go
pkg/rule/rule.go
test/e2e/rule_test.go

Closes #1189 
Fixed the switch type in the `rules` handler because alerting rules are instances of `*rules.AlertingRule`, not `thanosrule.AlertingRule`. This is because the rules are returned from the Prometheus rule managers and have no notion of `PartialResponseStrategy`.
The `/api/v1/rules` and `/api/v1/alerts` endpoints are now covered by the end-to-end tests.

ruler: fix the /api/v1/rules endpoint

---

pkg/model/timeduration_test.go
pkg/objstore/oss/oss.go

Signed-off-by: Matt Layher <mdlayher@gmail.com>
Fix minor issues detected by staticcheck:
```
$ staticcheck ./...                                                                                                       
pkg/model/timeduration_test.go:35:21: don't use Yoda conditions (ST1017)                                                                            
pkg/objstore/oss/oss.go:66:9: assigning the result of this type assertion to a variable (switch r := r.(type)) could eliminate the following type as
sertions:                                                                                                                                          
/home/matt/src/github.com/thanos-io/thanos/pkg/objstore/oss/oss.go:68:11 …
```

pkg: fix staticcheck issues

---

test/e2e/spinup_test.go

When running the end-to-end tests locally, Alertmanager may fail to start if another instance of Alertmanager is already running. This is because both instances bind to the default clustering port (9094). Since e2e tests don't rely on Alertmanager clustering, we disable clustering by setting `--cluster.listen-address=""`.
End-to-end tests should pass as before.

test/e2e: start Alertmanager without clustering

---

CHANGELOG.md
cmd/thanos/rule.go
pkg/rule/api/v1.go
pkg/rule/api/v1_test.go
pkg/rule/rule.go
pkg/rule/rule_test.go
pkg/ui/rule.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

This change ensures that the /api/v1/rules endpoint returns the original path of the rule file instead of the path of the temporary file generated by Thanos ruler.
The mapping from the original rule filenames to the temporary filenames is stored in the `github.com/thanos-io/thanos/pkg/rule.Manager` struct. 
Added end-to-end tests.

pkg/rule: retain original path for rule files

---

CHANGELOG.md
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/prober/prober.go
pkg/prober/prober_test.go
pkg/server/http/http.go

This PR aims to simplify `prober` implementation by keeping its existing behaviour.
It also tries to simplify API and tries to use more idiomatic go naming for methods.
It also moves prober API touchpoints to `server/http` call sites to make the usage more explicit.
These changes are purely cosmetic and just to increase the maintainability of the package, you can ignore this PR, if you think the changes don't provide any value.
* Refactor `prober` and its usages for sake of simplicity.
Runs local test to ensure nothing changed, `make test-local`.

Simplify prober

---

CHANGELOG.md
pkg/rule/rule.go
pkg/rule/rule_test.go

Thanos didn't deal correctly with rule files that have the same name but live in different directories (eg `thanos rule --rule-file foo/rules.yml  --rule-file bar/rules.yml`). This is because the "transofrmed" files are stored in the same output directory and the filenames don't differ if the partial response strategy is the same.
Unit test added.

pkg/rule: support identical rule filenames in different directories

---

pkg/objstore/azure/azure.go
pkg/objstore/cos/cos.go
pkg/objstore/filesystem/filesystem.go
pkg/objstore/gcs/gcs.go
pkg/objstore/inmem/inmem.go
pkg/objstore/objstore.go
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/objstore/oss/oss.go
pkg/objstore/s3/s3.go
pkg/objstore/swift/swift.go

Adds a new method ObjectSize(context.Context, string) method to our
object storage interface which returns the size of the specified object
in uint64 without actually downloading all of it.
This is a pre-requisite to one check that we want to add (https://github.com/thanos-io/thanos/pull/1550).
Add a check to our E2E tests to see if it works.

objstore: add ObjectSize() implementation

---

docs/integrations.md
docs/release-process.md
scripts/websitepreprocess.sh

Fix: perl script was only changing first item in line. `/g` was missing.
Fixes: https://github.com/thanos-io/thanos/issues/1816

Updated release process; fixed links.

---

cmd/thanos/sidecar.go
docs/components/sidecar.md
docs/quick-tutorial.md

Promote sidecar shipper.upload-compacted flag to non hidden, non experimental state.

---

docs/components/sidecar.md

Make doc clear about compacted/uncompacted data to upload.

comment upload compacted or not

---

docs/service-discovery.md

This commit cleans up some of the language in the service discovery talk
for improved legibility.

docs/service-discovery.md: clean up

---

docs/storage.md

- drop a duplicate colon
- fix the type spec of two yaml code blocks
Visual inspection of the diff

docs/storage: fix a typo and yaml formatting

---

cmd/thanos/rule.go
docs/components/rule.md

Since now alertmanager url is auto parse into url.URL, the scheme should exist and not empty, or would parse warn:
```
thanos rule --alertmanagers.url=localhost:9093 --rule-file=rule.yaml --query=localhost:19999
...
level=warn ts=2019-12-04T03:45:28.597397054Z caller=alert.go:342 msg="sending alerts failed" alertmanager= numAlerts=2 err="send request to \"localhost:///api/v1/alerts\": Post 
localhost:///api/v1/alerts: unsupported protocol scheme \"localhost\""
```
Without scheme, this warn is error indeed since can not send alerts forever.

comment url scheme

---

CHANGELOG.md
go.mod
go.sum

This version includes https://github.com/minio/minio-go/commit/d18cd1c3fde63effb2eb789120abdc73da4a5610, which adds functionality I would like to use with Thanos.

deps: bump minio-go to v6.0.44

---

CHANGELOG.md
pkg/receive/tsdb.go

We are running thanos receive in production with 1w retention. When the receiver starts up it consumes about 20% memory on each of our 32 nodes. After the initial WAL flush the memory footprint progressively grows over time. I originally reported this in CNCF Slack. I initially tried to delete the WAL and restart the nodes but that didn’t solve the issue. The only solution was to clear out some TSDB blocks
Potentially fixes #1855 
Close the DBReadOnly connection after `FlushableStorage.Flush()`
I’ve not been able to verify this just yet. I’ll try to build the image with this patch and see if I see an improvement.

receive: close DBReadOnly after flushing

---

docs/components/compact.md
pkg/compact/downsample/downsample.go

Previous doc was not fully correct: https://github.com/thanos-io/thanos/blob/825f119982dd2db4b9a3b4fe0a4b652331670ff2/cmd/thanos/downsample.go#L225

Be clear about downsampling process.

---

pkg/rule/api/v1.go

Ref: https://github.com/prometheus/prometheus/pull/5582
```
curl localhost:10906/api/v1/rules | jq
{
"status": "success",
"data": {
"groups": [
{
"name": "test-alert-group",
"file": "valid.yaml",
"rules": [
{
"name": "test",
"query": "1",
"duration": 0,
"labels": {
"key": "value"
},
"annotations": {
"key": "value"
},
"alerts": [
{
"labels": {
"alertname": "test",
"key": "value"
},
"annotations": {
"key": "value"
},
"state": "firing",
"activeAt": "2019-12-11T10:07:10.851171763-05:00",
"value": "1e+00",
"partial_response_strategy": "WARN"
}
],
"health": "ok",
"type": "alerting",
"partial_response_strategy": "WARN"
}
],
"interval": 5,
"partial_response_strategy": "WARN"
}
]
}
}
```

fix /api/v1/rules value

---

pkg/alert/alert.go

add user-agent in http header.

add user-agent in http header.

---

pkg/store/storepb/custom_test.go

Add benchmark merge seriesset

---

docs/components/query.md

Refer to CHANGELOG.md:376:
```
- [#970](https://github.com/thanos-io/thanos/pull/970) Deprecated `partial_response_disabled` proto field. Added `partial_response_strategy` instead. Both in gRPC and Query API.
No `PartialResponseStrategy` field for `RuleGroups` by default means `abort` strategy (old PartialResponse disabled) as this is recommended option for Rules and alerts.
```

fix wrong defalut value

---

CHANGELOG.md
cmd/thanos/receive.go

As pointed out by a user on the CNCF Slack, the receiver is currently
uploading to object storage as the sidecar.
cc @metalmatze @brancz 

cmd/thanos/receive: dont upload as sidecar

---

docs/getting-started.md
examples/dashboards/dashboards.md
mixin/thanos/README.md

This PR fixes broken links references `thanos-mixin`.
A follow up to #1760.

Fix broken doc links

---

pkg/discovery/cache/cache.go
pkg/discovery/cache/cache_test.go

Multiple groups of addresses may have duplicates

deduplicate addresses.

---

docs/components/compact.md
docs/quick-tutorial.md
docs/service-discovery.md
pkg/objstore/oss/oss.go

Based on #1801, finish format and lint for current codes and docs.
- clean up all white noise calling `make docs`
- fix comment issue calling `make format`:
```
>> checking Go comments trailing periods
./pkg/objstore/oss/oss.go:
func (b *Bucket) ObjectSize(ctx context.Context, name string) (uint64, error) {
// https://github.com/aliyun/aliyun-oss-go-sdk/blob/cee409f5b4d75d7ad077cacb7e6f4590a7f2e172/oss/bucket.go#L668
m, err := b.bucket.GetObjectMeta(name)
Error: Found comments without trailing period. Comments has to be full sentences.
```

Clean up white noise and format all codes

---

pkg/query/storeset.go

repeat timeout:
https://github.com/thanos-io/thanos/blob/2f29975982e25632a3eaccaf47d2401dcbfeef4b/cmd/thanos/query.go#L299-L303
update grpc timeout:
https://github.com/thanos-io/thanos/blob/2f29975982e25632a3eaccaf47d2401dcbfeef4b/pkg/query/storeset.go#L406
the `grpc timeout` should be lower than `repeat timeout`.

bugfix: adjust the timeout.

---

cmd/thanos/sidecar.go

@bwplotka
Adds a flag that allows users to disable the requirement that their Prometheus instances have equal min/max block durations if they have enabled block upload. 
As discussed on slack; because only uncompacted blocks are uploaded, in the event of an upload failure or network issues that last longer than 4h there is the potential for data loss (in the bucket storage) if blocks are compacted by Prometheus during that time
Signed-off-by: Callum Styan <callumstyan@gmail.com>
cc @gouthamve @beorn7

sidecar: don't require Prometheus min/max block durations to be equal

---

pkg/store/tsdb_test.go
scripts/build-check-comments.sh

The script always exited with `0` so the CI never detected when comments didn't follow the guidelines.

scripts/build-check-comments.sh: fix exit code

---

Makefile

Those errors didn't trigger a CI failure because `quay.io/thanos/thanos-ci` (or rather `circleci/golang`) uses `sh` as the interpreter which doesn't fail on incorrect test expressions.
```
$ if [[ ! ls ezae; ]]; then echo yes; fi
/bin/sh: 14: [[: not found  
/bin/sh: 14: ]]: not found  
$ echo $?
0
$ ps 
PID TTY          TIME CMD 
1 pts/0    00:00:00 sh 
7457 pts/0    00:00:00 ps
$ bash
circleci@47ec4d9adda4:/go/thanos$ if [[ ! ls ezae; ]]; then echo yes; fi
bash: conditional binary operator expected
bash: syntax error near `;'
circleci@47ec4d9adda4:/go/thanos$ echo $?
2
```

Makefile: fix lint and check-docs targets

---

CHANGELOG.md
cmd/thanos/rule.go
cmd/thanos/rule_test.go
docs/components/rule.md
docs/service-discovery.md
pkg/alert/alert.go
pkg/alert/alert_test.go
pkg/alert/client.go
pkg/alert/client_test.go
pkg/discovery/dns/provider.go
scripts/cfggen/main.go
test/e2e/rule_test.go
test/e2e/spinup_test.go

Closes #606 
This change adds support for authentication with basic auth, client
certificates and bearer tokens. It also enables to configure TLS
settings for the Alertmanager endpoints.
Most of the work leverages the existing Prometheus configuration format
and code. In particular TLS certificate files are automatically reloaded
whenever they change.
End-to-end tests added to cover various HTTP client configurations (TLS, authentication) and file SD integration.

*: support authentication and TLS for Alertmanager

---

CHANGELOG.md
pkg/store/gate.go

The `thanos_bucket_store_series_gate_duration_seconds` metric is currently measured as nanoseconds and not seconds, so every measurement basically ends up in the `+Inf` bucket. This PR fixes it.
- Fixed the gate duration metric unit
Manual tests.

Fixed the gate duration metric unit

---

cmd/thanos/rule.go

Left over from #1838, the metric isn't used anywhere.

cmd/thanos/rule: remove unused metric

---

pkg/alert/client.go
pkg/alert/client_test.go
pkg/http/http.go
test/e2e/rule_test.go

This change moves the HTTP client code (including configuration) to a separate package so it can be easily reused for implementing TLS and authentication for queries in Thanos Ruler.
Unit and e2e tests should pass.

pkg/alert: factorize HTTP client code into separate package

---

CONTRIBUTING.md
Makefile
docs/storage.md
pkg/objstore/objtesting/foreach.go

Still by default run all. Making it more difficult to skip makes sure we don't forget to run those.

Simplify running tests with excluding certain providers.

---

Makefile
scripts/cleanup-white-noise.sh
scripts/genflagdocs.sh

OSX's `sed` has the `-i` flag which is not compatible with GNU `sed`, causing commands like `make docs` to fail on OSX. A popular option for OSX users is to install `gsed` via `brew`.
In this PR I'm suggesting to:
1. Use `gsed` when available, falling back to `sed`
2. Always use `find .`  to get it working on OSX too
These changes should be safe for Linux users.
- Makefile: use gsed on OSX to keep GNU sed compatibility
Manual tests.

Makefile: use gsed on OSX to keep GNU sed compatibility

---

pkg/query/api/v1.go

We should support both GET and POST method in /api/v1/labels.

support post method in /api/v1/labels

---

Makefile

Fix below issue:
```
[root@test thanos]# LICHE=/deploy/go/bin/liche make check-docs 
all modules verified
>> building binaries /deploy/go/bin
>   thanos
which: no gsed in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
which: no gsed in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
```

Fix sed issue

---

Makefile

We don't check so often and it's very flaky on our CI.

Exclude couchdb.apache from link checking.

---

pkg/discovery/cache/cache_test.go

fix flaky test cache addresses

---

cmd/thanos/compact.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/compact/compact_test.go

In Cortex, we're currently working on an experimental TSDB-storage layer based on Thanos 🎉❤️. The next step would be introducing the Thanos compactor in Cortex too, but to do that we would need a way to allow vertical compaction (due to how the replication works, in Cortex we have overlapping blocks).
According to our experiments, enabling vertical compaction is just a matter of disabling the checks done by Thanos to make sure blocks don't overlap. In this PR I'm suggesting to introduce an internal option (not exposed to Thanos users) to allow Cortex enabling it.
- Introduce an internal option to enable vertical compaction
Manual tests.

Introduce an internal option to enable vertical compaction

---

CHANGELOG.md
pkg/compact/compact.go

There are conditions under which the `BucketCompactor.Compact()` returns no error even if an error occurred.
This happens when the number of groups left to compact is <= the concurrency. In this scenario, all jobs have been pushed to workers, so the code executions moves to [`wg.Wait()`](https://github.com/thanos-io/thanos/compare/master...pracucci:fix-bucket-compactor-error-handling#diff-921a1164068d3a04217b2d85714b16adR1146) and any subsequent error is not catched and then returned.
- Fixed the compactor successfully exiting when actually an error occurred while compacting a blocks group
Manual tests.

Fixed the compactor successfully exiting when actually an error occurred while compacting a blocks group

---

CHANGELOG.md
cmd/thanos/store.go
docs/components/store.md
go.mod
go.sum
pkg/cacheutil/jump_hash.go
pkg/cacheutil/memcached_client.go
pkg/cacheutil/memcached_client_test.go
pkg/cacheutil/memcached_server_selector.go
pkg/cacheutil/memcached_server_selector_test.go
pkg/gate/gate.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/cache/cache.go
pkg/store/cache/cache_test.go
pkg/store/cache/factory.go
pkg/store/cache/inmemory.go
pkg/store/cache/inmemory_test.go
pkg/store/cache/memcached.go
pkg/store/cache/memcached_test.go
pkg/store/cache/units.go
pkg/store/cache/units_test.go
scripts/cfggen/main.go

This PR proposes to introduce memcached support for the index cache. Few reasons why memcached may make sense:
1. Do not wipe out the index cache on thanos store restarts/redeploys
2. Scale the cache size above the single thanos store memory limits (ie. a cluster of memcached nodes)
3. _Use it in Cortex, where we're experimenting a TSDB storage based on some Thanos components and we currently have the "bucket store" replicated across different nodes and a shared cache may benefit_
**Open questions**:
- Should `MaxGetMultiBatchConcurrency` be global (like right now) or a per `MultiGet()` call limit? I would be more lean towards the latter (see TODO in `pkg/cacheutil/memcached_client.go`)
- Moved index cache key struct outside of the file containing the in-memory cache backend because …

Add memcached support to index cache

---

CHANGELOG.md
pkg/block/block_test.go
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/compact/compact_e2e_test.go
pkg/extprom/tx_gauge.go
pkg/extprom/tx_gauge_test.go
pkg/objstore/objtesting/acceptance_e2e_test.go
pkg/objstore/objtesting/foreach.go
pkg/shipper/shipper_e2e_test.go
pkg/store/bucket_e2e_test.go

This is meant to replace least 5 inconsistent meta.json syncs places across components.
Usage of those will be done in follow up chained PRs.
In the first commit: Transactional gauge allowing to have atomic gauge across different labels.

Added block.MetaFetcher logic for resilient sync of meta files.

---

pkg/discovery/cache/cache_test.go

Make sure that the returned slice is sorted consistently.
`go test -count 100 ./pkg/discovery/cache/.` returns successfully with this PR while a few instances fail on master.

pkg/discovery: fix unit tests

---

CHANGELOG.md
cmd/thanos/store.go
docs/components/store.md
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go

Fixes: https://github.com/thanos-io/thanos/issues/1874
Depends on: https://github.com/thanos-io/thanos/pull/1934
* Corrupted disk cache for meta.json is handled gracefully.
* Synchronize was not taking into account deletion by removing meta.json.
* Prepare for future implementation of https://thanos.io/proposals/201901-read-write-operations-bucket.md/
* Better observability for syncronize process.
* More logs for store startup process.
TODO in separate PR:
* More observability for index-cache loading / adding: e.g duration time. 
* Unit + e2e tests.

Use block.MetaFetcher in Store Gateway.

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main_test.go
docs/components/compact.md
pkg/block/fetcher.go
pkg/compact/clean.go
pkg/compact/clean_test.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/compact/compact_test.go
pkg/compact/downsample/streamed_block_writer.go
pkg/compact/retention.go
pkg/compact/retention_test.go

Fixes: https://github.com/thanos-io/thanos/issues/1335
Fixes: https://github.com/thanos-io/thanos/issues/1919
Fixes: https://github.com/thanos-io/thanos/issues/1300
Depends on https://github.com/thanos-io/thanos/pull/1934
* Clean up of meta files are now started only if block which is being uploaded is older than 2 days (only a mitigation).
* Blocks without meta.json are handled properly for all compactor phases.
* Prepare for future implementation of https://thanos.io/proposals/201901-read-write-operations-bucket.md/
* Added metric for partialUploadAttempt deletions and delayed it.
* More tests.
* Unit tests + e2e tests.

Use block.MetaFetcher in Compactor.

---

.circleci/config.yml

Fixes https://github.com/thanos-io/thanos/issues/1942
Master container images were built with Go 1.12 ):

Unify all CI base images to be built with Go 1.13.

---

docs/proposals/201909_thanos_sharding.md
docs/proposals/201912_thanos_binary_index_header.md

Some verifications in TODO, otherwise. Feedback welcome.
Definitely not a silver bullet here, but rather change in a good direction (:

Added proposal for moving to index-header binary format.

---

pkg/store/bucket.go

`stats` is being accessed from the goroutines inside this function so it
needs to be protected here in the same way with `mtx`. Move the house
keeping out of the inner loop into the outer one to reduce the number of
times we will need to lock/unlock the mutex.

store: fix a small house-keeping data race

---

cmd/thanos/rule.go

https://github.com/thanos-io/thanos/blob/f5b7bacf762197c5fa8ec728257bbca264072e35/cmd/thanos/rule.go#L745
function `removeDuplicateQueryAddrs`  does not modify `addrs` but return the deduplicated value.  It may be a bug.
If it only logs the number of duplicated addresses, it's better to change the name of the function.

rule: fix bug that ignore deduplicate addrs.

---

pkg/receive/hashring.go

This commit simplifies the receive/hashring.go file a bit. Most
significantly it changes two sequential `if`s that can never both be
true, to an `if/else`.

pkg/receive: simplify hashring file

---

CHANGELOG.md
cmd/thanos/receive.go
cmd/thanos/rule.go
docs/components/rule.md

Add a WAL compression option in rule and receive

Add a wal compression flag in rule and receive

---

cmd/thanos/rule.go

This commit changes the querier address deduplication logic so that we
only iterate over the input once, rather than twice.
Noticed this while reviewing a PR today

cmd/thanos/rule.go: simplify deduplication

---

CHANGELOG.md
cmd/thanos/sidecar.go
docs/components/sidecar.md
pkg/exthttp/transport.go
pkg/store/prometheus.go
pkg/store/prometheus_test.go

Allow custom connection pool size for Thanos sidecar to prevent excessive tcp connections on machines with very high load. More details are laid out in #1953 
A build from my fork is currently running in production on our machines and handling ~1700 RPS with very little connection cycling.
```
$ netstat -a | awk '{ print $6 }' | grep -P '[A-Z]' | sort | uniq -c | sort -r
951 ESTABLISHED
166 TIME_WAIT
146 CONNECTED
133 CLOSE_WAIT
129 FIN_WAIT2
53 STREAM
12 LISTEN
4 FIN_WAIT1
1 SEQPACKET
1 I-Node
1 Foreign
```
HTTP connections

sidecar: allow custom http con pool size fix #1953

---

CHANGELOG.md
cmd/thanos/receive.go

Allow enabling local TSDB compaction. For some setups uploading is disabled and local compaction saves a good amount of disk space and query times. 
Running a local build

receive: allow local tsdb compaction

---

CHANGELOG.md
pkg/cacheutil/memcached_server_selector.go
pkg/cacheutil/memcached_server_selector_test.go

Fixes https://github.com/thanos-io/thanos/issues/1974
Unit tests.

Fixed crash in the memcached servers selector when there's only 1 server

---

cmd/thanos/rule.go
pkg/alert/alert.go

Running Thanos Ruler on master generates warnings in the logs because the tracer isn't passed down to `Sender.Send()`:
```
level=warn ts=2020-01-10T11:24:49.434277378Z caller=http.go:57 msg="Tracer not found in context."
```
Pass the tracer in the context and generate spans when calling the Alertmanager API endpoint.
No more warning in the logs.

*: fix tracing for alerts

---

cmd/thanos/store.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go
test/e2e/spinup_test.go

Depends on: https://github.com/thanos-io/thanos/pull/1952

Enabled index-header under experimental flag.

---

cmd/thanos/bucket.go
pkg/verifier/duplicated_compaction.go
pkg/verifier/index_issue.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/verify.go

Issue link: https://github.com/thanos-io/thanos/issues/1941
use `block.metaFetcher` in `bucket` command

bucket: use block.MetaFetcher to fetch blocks

---

CHANGELOG.md
pkg/objstore/inmem/inmem.go
pkg/store/bucket.go
pkg/store/bucket_test.go

Fixes: https://github.com/thanos-io/thanos/issues/1983
cc @pracucci as we discussed this offline at some point (:

store: Refetch series if longer than expected.

---

pkg/query/api/v1.go

Let's set `Cache-Control` to `no-store` if there were any warnings while
the query was being executed i.e. it is a partial response or we got
some other problem.
Seems like this works successfully in tandem with https://github.com/cortexproject/cortex/pull/1974.
Tested by turning off one sidecar which leads to warnings and then Cortex Query Frontend did not save anything into the cache when querying.

api/v1: add cache-control header

---

CHANGELOG.md

Some pull requests were incorrectly added to v0.10.0 while they're not released yet.

CHANGELOG.md: fix v0.10.0 entry

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
examples/dashboards/ruler.json
mixin/thanos/alerts/alerts.libsonnet
mixin/thanos/alerts/ruler.libsonnet
mixin/thanos/dashboards/ruler.libsonnet

This PR adds missing Ruler alerts to thanos-mixin.
Alerts are inspired by https://thanos.io/components/rule.md/#must-have-essential-ruler-alerts
* Adds Ruler alerts
* Adds alert queue metric panels to Thanos Rule dashboards
For rules:
* Manual tests using Query UI against running cluster.
For dashboards:
* Imported generated dashboard JSON to a Grafana with live data.

mixin: Add Thanos Ruler alerts

---

cmd/thanos/compact.go
docs/components/compact.md

(This is a docs-only change - does it need to go in the changelog? If so, I'm more than happy to add it in 🙂)
I was confused by the wording around 0d rerentions in the docs - does 0d retention mean that samples aren't retained at all, or that they're not evicted? - so I went through the code, and as far as I can tell, 0d retention means that samples aren't evicted.
I went through the docs and the CLI help text, and added explanations that 0d retention means that samples are never evicted.
- Ran `make build`, and then `./thanos compactor -h`, verifying the the new help text was there
- Ran `make web`, then opened up `website/public/components/compact.md/index.html`, and verified that the text I'd added to the docs was present

compactor: Clear up wording around 0d retention times in docs

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/querier.libsonnet

This PR fixes wrong querier metric name.
* Rename `thanos_query_store_apis_dns_failures_total` to `thanos_querier_store_apis_dns_failures_total`
1. `make examples-lint`
1. Manuel test using promdash.

mixin: Fix wrong querier metric name

---

pkg/model/timeduration.go
pkg/store/prometheus.go
pkg/store/prometheus_test.go

Fixes #2011
cc @IKSIN  @GiedriusS 
I have already tested both in Grafana and local API request.
```
curl -g 'http://localhost:10908/api/v1/series?' -d 'match[]={__name__="up"}'
{"status":"success","data":[{"__name__":"up","instance":"localhost:9090","job":"prometheus","replica":"test"},{"__name__":"up","instance":"localhost:9091","job":"prometheus","replica":"test"}]}
curl -g 'http://localhost:10908/api/v1/series?' -d 'match[]={__name__="up"}' -d 'start=1579551916'   
{"status":"success","data":[{"__name__":"up","instance":"localhost:9091","job":"prometheus","replica":"test"}]}
```

Fix invalid start/end params in series api

---

pkg/alert/config.go
pkg/alert/config_test.go

Regression introduced in #1982. `BuildAlertmanagerConfig()` didn't set the API version to use resulting in bad URL (e.g. `http://example.com:9093/api/alerts` instead of `http://example.com:9093/api/v1/alerts`).

pkg/alert: fix configuration from "legacy" flags

---

CHANGELOG.md
cmd/thanos/query.go
pkg/store/proxy.go
pkg/store/proxy_test.go

This adds a metric to track how often we do requests that end up in empty responses. Related to #1611.
Did queries that stores didn't have data for, and verified that indeed the `/metrics` endpoint reflects this.
@bwplotka @squat @GiedriusS

pkg/store: Expose metric about empty stream responses in proxy store

---

CHANGELOG.md
cmd/thanos/query.go
cmd/thanos/rule.go

I guess we need `_total` in counter metrics

Add _total suffix to two counter metrics

---

cmd/thanos/query.go
docs/components/query.md

fix https://github.com/thanos-io/thanos/issues/703

add flag max query samples

---

CHANGELOG.md
go.mod
go.sum

Bump to the minio-go library to support Web Identity providers for IAM credentials for AWS EKS - Fixes #1494 
Have built a new docker image with the updated library and confirmed that when deployed on EKS with a service account, it correctly uses the service account's IAM role to grant access to S3.

Bumped minio-go library to v6.0.45

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/ruler.libsonnet

Similarly to Thanos querier, we've got metrics about DNS resolutions attemps/failures that we can use for alerting.

mixin/thanos: add DNS alerts for Thanos Ruler

---

pkg/ui/templates/alerts.html

Fixes https://github.com/thanos-io/thanos/issues/2024
In https://github.com/thanos-io/thanos/pull/1854, I mistakenly changed the click behavior of the alerts section in Ruler UI.
Now change back to `queryURL` and it works now. I have already tested in my local env

Fx ruler ui alerts click

---

pkg/compact/compact.go
pkg/verifier/overlapped_blocks.go

Use a variable to keep the group key instead of calculating it multiple times

Don't calculate compact group key multiple times

---

pkg/shipper/shipper.go

This PR improves help text of `thanos_shipper_dir_syncs_total`, `thanos_shipper_uploads_total` and `thanos_shipper_upload_failures_total` metrics.
I did not test this 😱 [but it's a trivial change]

pkg/shipper: Improve help text for shipper metrics.

---

CHANGELOG.md
docs/tracing.md
pkg/tracing/elasticapm/elastic_apm.go

This is a patch to address thanos-io/thanos#2039.
Tracing every request can be quite expensive. By introducing a sample rate (similar to what stackdriver and jaeger already support), the overhead and trace storage cost can be controlled.
This patch adds sampling for Elastic APM tracing.
* tracing: Support sampling on Elastic APM with new `sample_rate` setting
* I still need to run a proper integration test. Is there a standalone-ish way of running thanos locally that would enable such testing?
* Since the default value for sample rate is `0`, this will break anyone currently using the elastic APM backend. It might make sense to have a proper default value of `1` -- this applies to various settings on other tracing backends.

tracing: Support sampling on Elastic APM

---

.github/stale.yml

* Updated mark stale info
* No way to label issue/pr in a way that it will get ignored by stale bot.
cc @daixiang0

Updated stale bot as agreed offline on #thanos-dev.

---

SECURITY.md

This commit cleans up the grammar in the SECURITY.md file for better
readability.

SECURITY.md: clean up doc

---

docs/components/compact.md
examples/alerts/alerts.md
examples/alerts/alerts.yaml
examples/dashboards/overview.json
mixin/thanos/alerts/compactor.libsonnet
mixin/thanos/dashboards/compactor.libsonnet

This PR renames `compact` to `compactor` in mixin and docs.
As discussed in https://github.com/thanos-io/thanos/issues/1871
* `make docs`
* `make check-docs`

mixin, docs: Rename Compact -> Compactor

---

netlify.toml

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src thanos.io". Either the 'unsafe-inline' keyword, a hash ('sha256-3qFt4qPvMCWVUpjUxP5X57GBKae6RHYZ0rMjn9WuNF4='), or a nonce ('nonce-...') is required to enable inline execution.`
Fixed by not restricting by domain, just TLS.

Lower restriction for website scripts.

---

Makefile

Fix following error:
```
find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
xargs -n 1 -- jsonnetfmt -n 2 --max-blank-lines 2 --string-style s --comment-style s -i
xargs: jsonnetfmt: No such file or directory
```

Makefile: optimize jsonnet-format target

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/querier.libsonnet

This PR fixes querier store DNS query failures promQL issue. 
https://github.com/thanos-io/thanos/pull/2027 brought this to my attention.
cc @metalmatze @simonpasquier 
* Fix querier alert ratio calcualtion.
* Fix querier alert messages.

mixin: Fix querier store DNS query alert

---

cmd/thanos/main_test.go
pkg/block/block_test.go
pkg/block/index_test.go
pkg/block/indexheader/header_test.go
pkg/compact/compact_e2e_test.go
pkg/promclient/promclient_e2e_test.go
pkg/query/api/v1_test.go
pkg/shipper/shipper_e2e_test.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go
pkg/store/prometheus_test.go
pkg/store/tsdb_test.go
pkg/testutil/e2eutil/copy.go
pkg/testutil/e2eutil/port.go
pkg/testutil/e2eutil/prometheus.go
pkg/testutil/e2eutil/sysprocattr.go
pkg/testutil/e2eutil/sysprocattr_linux.go
pkg/testutil/testorbench.go
pkg/testutil/testorbench_test.go
test/e2e/spinup_test.go
test/e2e/store_gateway_test.go

testutil: Moving all e2e utils to separate package, added TB union.

---

Makefile

Fix below error:
```
>> Compiling and generating thanos-mixin
docker run --rm -u="0:0" -v "/root/.cache/go-build:/.cache/go-build" -v "/deploy/go/src/git
hub.com/thanos-io/thanos:/go/src/github.com/thanos-io/thanos:Z" -w "/go/src/github.com/than
os-io/thanos" -e USER=deadbeef -e GO111MODULE=on quay.io/coreos/jsonnet-ci make  JSONNET_BU
NDLER='/go/bin/jb' jsonnet-vendor
rm -rf mixin/vendor
/go/bin/jb install --jsonnetpkg-home="mixin/vendor"
GET https://github.com/grafana/grafonnet-lib/archive/69bc267211790a1c3f4ea6e6211f3e8ffe22f987.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/f4c59f64f80442f871a06c91edf74d014b82acaf.tar.gz 200
CLEAN mixin/vendor/.tmp
CLEAN mixin/vendor/github.com
CLEAN mixin/vendor/github.com/grafana
CLEAN …
```

Makefile: fix quay.io/coreos/jsonnet-ci image tag

---

mixin/thanos/README.md

I fixed broken links in `mixin/thanos/README.md` doc.
- link to `examples` directory 
- link to renamed file:  `defaults.jsonnet` -> `defaults.libsonnet`
Manually.

mixin: Fix broken links in docs

---

pkg/block/indexheader/binary_reader.go
pkg/block/indexheader/json_reader.go
pkg/gate/gate.go
pkg/pool/pool.go
pkg/pool/pool_test.go
pkg/query/api/v1_test.go
pkg/store/bucket.go
pkg/store/bucket_test.go
pkg/store/cache/memcached_test.go
pkg/store/limiter.go
pkg/testutil/e2eutil/prometheus.go

*  Added ExpandedPostingsMatchers benchmarks. This function and only this
will be affected by index-header changes.
* Added store Series test. This can be later expanded for tests for different StoreAPIs not only Store GW.
* Added few interfaces to improve testability to Store GW bucket struct.
* Fixed time filtering edge case. Now request mint=0, maxt=0 should succeed.
Script for running those:
```
#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${DIR}/../
RUN="${1}-exppostings"
mkdir -p ${DIR}/bench_outs/${RUN}
for TEST in BenchmarkBucketIndexReader_ExpandedPostings/binary_header BenchmarkBucketIndexReader_ExpandedPostings/index_json
do
echo "Running ${TEST} run ${RUN}"
go test -bench=${TEST} -run=^$ -benchmem -memprofile …
```

store: Added benchmarks for .Series and expanded matchers.

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/sidecar.libsonnet

Fix #544
- This metrics has removed by #599, so remove this alert.
- Add new alert

Mixin: Update sidecar alert

---

CHANGELOG.md
pkg/alert/alert.go

https://github.com/thanos-io/thanos/issues/2100
Fixes #2100
Signed-off-by: Kevin Hellemun <17928966+OGKevin@users.noreply.github.com>

Register thanos_alert_sender_errors_total metric.

---

docs/release-process.md

I'm happy  to shepard the v0.11.x release this month. 
For the next v0.12 release I simply added 6 weeks to the current date - which is April 1st.
/cc @thanos-io/thanos-maintainers

Add metalmatze as release shepard for v0.11

---

cmd/thanos/store.go
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/block/node.go

Add Filter to filter out old blocks if new overlapping blocks found that fully submatch the old blocks
Please let me know if this is the right direction to go in terms of filtering out the old blocks

fetcher: add filter to remove old blocks if new overlapping blocks found

---

cmd/thanos/store.go
docs/components/store.md

Store: Document --chunk-pool-size better

---

pkg/query/api/v1.go

Signed-off-by: Aleksey Sin <asin@ozon.ru>
Grafana need to get variables from /series. It do not work when we have only downsampled data (we using other retentions for every resolutions).
Support downsampling for /series API method. Based on `defaultInstantQueryMaxSourceResolution`
Grafana can get data for variables.

Support downsampling for /series.

---

docs/getting-started.md

The link of the latest Banzai Cloud blog post is wrong.

Fix wrong Banzai Cloud blog post link

---

pkg/store/proxy.go

Fix #2091 
There is not only one case for query failure:
- no storeAPIs available
- no storeAPIs matched
- include all above cases
Also, querier use not only storer, but also sidecar, may be other, use storeAPIs here is better.

pkg/store/proxy.go: optimize help info

---

pkg/compact/downsample/streamed_block_writer.go

compact log line when encountering an empty chunk should be a valid JSON to avoid breaking logs parsing.
Otherwise you endup in something like this (Kibana) : 
label set is printed in the log as a single string when compact encounters empty chunks.
get proper JSON log line

compact: Avoid breaking the json log with series string

---

CHANGELOG.md
cmd/thanos/bucket.go
scripts/quickstart.sh

This PR adds missing instruction to set probe status for bucket web UI.
Fixes #2115 
*  Set state of status prober properly
* ` MINIO_ENABLED=1 ./scripts/quickstart.sh`

bucket: Set state of status prober properly

---

examples/dashboards/store.json
mixin/thanos/dashboards/store.libsonnet

Remove the redundant `_bucket` in the jsonnet file and re-generate.
Import the new dashboard to Grafana and then it works. I can see the graph.

Fix store dashboard metric name

---

Makefile

This PR fixes the error we get from `make jsonnet-fmt`:
```console
➜ make jsonnet-format
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [jsonnet-format] Error 2
```
* Fix make task.
* `make jsonnet-format`
* `make jsonnet-format-in-container`

make: Fix broken make task

---

examples/dashboards/sidecar.json
mixin/thanos/dashboards/sidecar.libsonnet

I cannot see sidecar gRPC stream metrics on the previous dashboard.
With the new dashboard:
cc @kakkoyun

Fix sidecar dashboard gRPC stream metric

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
examples/alerts/rules.yaml
examples/dashboards/compact.json
examples/dashboards/overview.json
examples/dashboards/query.json
examples/dashboards/receive.json
examples/dashboards/rule.json
mixin/thanos/README.md
mixin/thanos/alerts/absent.libsonnet
mixin/thanos/alerts/alerts.libsonnet
mixin/thanos/alerts/compact.libsonnet
mixin/thanos/alerts/query.libsonnet
mixin/thanos/alerts/receive.libsonnet
mixin/thanos/alerts/rule.libsonnet
mixin/thanos/dashboards/compact.libsonnet
mixin/thanos/dashboards/dashboards.libsonnet
mixin/thanos/dashboards/query.libsonnet
mixin/thanos/dashboards/receive.libsonnet
mixin/thanos/dashboards/rule.libsonnet
mixin/thanos/defaults.libsonnet
mixin/thanos/rules/query.libsonnet
mixin/thanos/rules/receive.libsonnet
mixin/thanos/rules/rules.libsonnet

This adapts alerting rules and dashboarding where applicable to comply to the agreed upon conventions documented in: https://github.com/thanos-io/thanos/blob/master/CONTRIBUTING.md#components-naming.
I mostly did `sed` over the repo, and reviewed it myself, but another couple of pairs of eyes reviewing this would be great :) .
Let me know if you feel this needs a changelog entry, and if so what you think it should be.
@thanos-io/thanos-maintainers @kakkoyun 
Promtool checks and tests continue to pass.

*: Adapt alerts and dashboards to naming conventions

---

CHANGELOG.md
pkg/store/prometheus.go

This patch extends tracing to include a `prometheus.query` tag for queries against the prometheus remote read API (`/api/v1/read`).
Previously there wasn't much information about the call being made, since that API uses protobuf over POST bodies. Now there is a JSON encoding of the protobuf request body in the trace.
One potential downside of this change is that there is JSON encoding and allocation overhead on every request. I wasn't able to find an easy way to make those conditional (input very welcome).
I also moved `spanReqDo.Finish()` before the error handling. I believe we want to finish the span in any case -- though if leaving it open was intentional, I'm happy to change it back.
* tracing: Add `prometheus.query` tag to `query_prometheus_request` span
I ran thanos locally with …

tracing: track query sent to prometheus via remote read api

---

cmd/thanos/bucket.go
cmd/thanos/check.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go

This PR handles received SIGHUP signals and dispatches reload events to sub-commands to handle.
Only the ruler utilizes this right now. Receiver and Ruler implement their own file watchers to reload configurations.
Fixes #1333.
* MINIO_ENABLED=1 ./scripts/quickstart.sh
- `kill -HUP <thanos-pid>`

*: Handle SIGHUP

---

cmd/thanos/compact.go
cmd/thanos/store.go
docs/components/store.md
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/testutil/e2eutil/prometheus.go
test/e2e/store_gateway_test.go

Add consistency delay in store component to fetch blocks

store: add consistency delay to fetch blocks

---

pkg/store/proxy.go
pkg/store/proxy_test.go

We want to increase stability Thanos infrastructure with many stores/sidecars (49 in our case) when some stores respond slowly.
More details in comments.

Improve store timeouts

---

Makefile

Fix following issue introduced by #2133 :
```
[root@test thanos]# make examples-in-container
>> Compiling and generating thanos-mixin
docker run --rm -u="0:0" -v "/root/.cache/go-build:/.cache/go-build" -v "/deploy/go/src/github.com/thanos-io/thanos:/go/src/github.com/thanos-io/thanos:Z" -w "/go/src/github.com/thanos-io/thanos" -e USER=deadbeef -e GO111MODULE=on quay.io/coreos/jsonnet-ci:release-0.35 make  JSONNET_BUNDLER='/go/bin/jb' jsonnet-vendor
rm -rf mixin/vendor
cd mixin && /go/bin/jb install
jb: error: failed to install packages: downloading: failed to create tmp dir: stat vendor/.tmp: no such file or directory
make: *** [Makefile:360: jsonnet-vendor] Error 1
make: *** [examples-in-container] Error 2
```

Makefile: update jsonnet-ci image

---

cmd/thanos/store.go
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/extprom/testing.go

store: Added test for consistency delay filter, defaulted to 0.

---

Makefile
go.mod
go.sum
pkg/block/fetcher.go
pkg/cacheutil/memcached_client_test.go
pkg/query/api/v1_test.go
pkg/receive/hashring.go
pkg/runutil/example_test.go
pkg/store/cache/memcached_test.go
pkg/store/storepb/custom_test.go

Fixes #2142 
(I've included a line at the bottom of the Added section)
Added failint package with the paths specified within the issue description to 'make lint'
Manual execution of the command and output verification.

Makefile: add faillint to lint target - Issue 2142

---

pkg/compact/compact.go
pkg/objstore/objstore.go

compactor: Put important compaction logs as info; init object store metrics.

---

CHANGELOG.md
pkg/ui/static/js/bucket.js
pkg/ui/templates/bucket.html

Related to:  #2149
I improved the tooltip on `bucket web`. It was reconstructed using bootstrap tools to show much more details than before:
**Before**
**After**
Visual testing only

bucket: Improve tooltip for bucket UI

---

go.mod
go.sum
pkg/store/bucket.go
pkg/store/bucket_test.go
pkg/store/proxy_test.go
pkg/testutil/testorbench.go
pkg/testutil/testorbench_test.go

This will be my baseline for further benchmarks. I think moving out of mmap would be nice as it will actually show allocations made by mmap :/ Will test in next PRs.
```
goos: linux
goarch: amd64
pkg: github.com/thanos-io/thanos/pkg/store
BenchmarkSeries/10e6SeriesWithOneSample/1of10000000-12         	       2	20763847906 ns/op	1578012024 B/op	20077109 allocs/op
BenchmarkSeries/10e6SeriesWithOneSample/10of10000000-12        	       2	19857501482 ns/op	1577936288 B/op	20076943 allocs/op
BenchmarkSeries/10e6SeriesWithOneSample/100of10000000-12       	       2	19582049218 ns/op	1578040744 B/op	20077604 allocs/op
BenchmarkSeries/10e6SeriesWithOneSample/1000of10000000-12      	       2	19267030930 ns/op	1578414776 B/op	20081687 allocs/op …
```

Expanded series benchmarks; Added OneSeriesManySamples case with 100mln samples.

---

cmd/thanos/receive.go
pkg/receive/config.go
pkg/receive/config_test.go
pkg/receive/hashring.go

This PR checks if the hashring config is empty and fails if it is.
Fixes #2160 
cc @squat @bwplotka 
* checks if the hashring config is empty and fails if it is.
* Run `REMOTE_WRITE_ENABLED=1 MINIO_ENABLED=1 ./scripts/quickstart.sh` with several modified versions of hashring file.

receive: Validate hashring at initialization

---

Makefile

Fix issue when run `make examples`:
```
find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
xargs -n 1 -- jsonnetfmt -n 2 --max-blank-lines 2 --string-style s --comment-style s -i
/gopkg/bin/jsonnet-fbde25be2182caa4345b03f1532450911ac7d1f3 mixin/thanos/alerts.jsonnet | /gopkg/bin/gojsontoyaml-e8bd32d46b3d764bef60f12b3bada1c132c4be55 > examples/alerts/alerts.yaml
/gopkg/bin/jsonnet-fbde25be2182caa4345b03f1532450911ac7d1f3 mixin/thanos/rules.jsonnet | /gopkg/bin/gojsontoyaml-e8bd32d46b3d764bef60f12b3bada1c132c4be55 > examples/alerts/rules.yaml
rm -rf examples/dashboards/*.json
/gopkg/bin/jsonnet-fbde25be2182caa4345b03f1532450911ac7d1f3 -J mixin/vendor -m examples/dashboards mixin/thanos/dashboards.jsonnet …
```

Makefile: check embedmd in examples target

---

CHANGELOG.md
go.mod
go.sum

Resolves #2181. Minio introduced a bug which prevents IAM roles from being used. This was fixed in v6.0.47.
Verified in https://github.com/thanos-io/thanos/issues/448#issuecomment-589807381

Bumped minio-go library to v6.0.49, fixing an IAM bug in v6.0.45

---

pkg/runutil/runutil.go
pkg/runutil/runutil_test.go

Check in `CloseWithLogOnErr()` if it has been closed already. If it has
been then it's certainly not a problem and can be safely ignored.
Closes: https://github.com/thanos-io/thanos/pull/1489.
Closes: https://github.com/thanos-io/thanos/issues/2082.
Tested:
* `make lint`

rununtil: do not log if already closed

---

docs/release-process.md

Just a few small things I encountered while cutting the RCs (:

Simplify and clarify small bits in the release process

---

docs/quick-tutorial.md

* Corrected all Prometheus possessives to read `Prometheus's`, this matches Prometheus's own documentation.
* Corrected `simple` to `simply` when describing compactor scanning behaviour
N/A

Typo corrections quick-tutorial.md

---

examples/dashboards/dashboards.md

Fixed links to Grafana dashboards JSON files in the documentation.
Links work now!

docs: Fixed links to Grafana dashboards json files.

---

pkg/block/block.go

We see this happening with Swift. Because the consistency of swift is eventual, swift sometimes didn't process the deletion of the meta file yet, and so it turns up in the bkt.Iter(). The second deletion then causes a 404 and compaction fails.

Skip deleting files that we just deleted

---

cmd/thanos/query.go
cmd/thanos/rule.go

This makes the handling of web.route-prefix more similar to the
behavior in Prometheus.  Correctly handles '/' and prefixes which
do not begin with a '/'.
Changed query and rule commands to preform pre-processing of web.route-prefix
Tested briefly on local system
Fixes #2207

query/rule: improve web.route-prefix handling

---

pkg/prober/intrumentation.go

Prober help message indicated that error returned a value of 1 while success returned a value of 0.  Looking at the code it is apparent this should be the other way around, so just modified the help message.
I was unsure if this should be added to the CHANGELOG or not.  Please advise.
Minor change in help message.

Fix error in component status help message

---

CHANGELOG.md
pkg/alert/alert.go
pkg/alert/alert_test.go

Fixes Issue #2204. The bug is that `alert.Queue.Push` can be called multiple times to add alerts to the queue, but it only provides a single signal on `morec` for `alert.Queue.Pop` to know that the queue has changed, i.e. there are alerts waiting. Further calls to `Push` can fill the queue and use `select` ... `default:` to skip signalling if the `morec` channel's buffer (size 1) is full. However, Pop will only remove `maxBatchSize` alerts from the queue and further calls to `Pop` block because the signal has been read. Therefore Pop fails to remove remaining alerts until `Push` has been called at least once again to restore the signal on `morec`.
This fix adds to `alert.Queue.Pop` so that if the queue is not empty after popping it restores the signal it read on the `morec` channel to …

ruler: Fix #2204 bug where alert queue is unpoppable causing full queue and dropped alerts

---

pkg/ui/static/js/bucket.js

* Allow bucket web UI to continue labeling old blocks, even if they don't match up with current labeling conventions.
This allows someone to edit their external labels, and still see all their data inside the bucket web component. Currently, the bucket web component will just throw an error (in bucket.js) since some of the data is unlabeled (assuming that you pass `--label`).
The bucket component already handles shards with and without labels, this change simply allows you to mix the two. Any unlabeled shards will be assigned a number, exactly how the component behaves when no `--label` is passed. After the unlabeled shards are listed, any labeled shards will be listed.
Tested with bucket containing some data with no external labels.
It is merged with newer data containing external …

bucket: improve shard label handling

---

cmd/thanos/bucket.go
cmd/thanos/rule.go
pkg/block/block.go
pkg/compact/downsample/streamed_block_writer.go
pkg/discovery/dns/miekgdns/lookup.go
pkg/discovery/dns/resolver_test.go
pkg/objstore/cos/cos.go
pkg/prober/http_test.go
pkg/query/api/v1.go
pkg/replicate/replicater.go
pkg/replicate/scheme.go
pkg/store/bucket.go

`%w` directive is only valid for recently introduces go native error wrapping. `pkg/errors` uses `%v`.
This PR fixes discovered issues in the code base.

*: Fix misuse of pkg/errors.Errorf and error directive

---

test/e2e/store_gateway_test.go

Fix false metric name in `test/e2e/store_gateway_test.go`.
Actually, `WaitSumMetrics` has to fail if an expected metric is not present in the scraped metrics, however apparently it is not the case, see: https://github.com/cortexproject/cortex/blob/c0b0238da2b88e64857a692fb90b43a8815f667a/integration/e2e/service.go#L536-L544
* Fix false metric name in `test/e2e/store_gateway_test.go`

test/e2e: Fix false metric name in Store GW e2e test

---

docs/components/rule.md

Using the URL format shown in the example will cause the following error:
```
Post mysite.example.com/api/v1/alerts: unsupported protocol scheme ""
```
And according to the ruler docs:
>The scheme should not be empty e.g `http` might be used.
This PR adds the http scheme to the example to avoid misunderstanding.

rule/docs: Add scheme to the alertmanagers.url in ruler example

---

CHANGELOG.md
pkg/ui/static/js/bucket.js

Sort series on bucket viewer page to better group compaction levels
Before
After

Bucket Web - Sort chunks by thanos.downsample.resolution for better grouping

---

tutorials/katacoda/thanos/1-globalview/step3.md

You would have to query `prometheus_tsdb_head_series` instead of `sum(prometheus_tsdb_head_series)` in order to get the 5 results when deduplicating.

tutorials: fix incorrect query

---

docs/sharding.md
docs/sharing.md

docs: Document Thanos Sharding

---

CHANGELOG.md
cmd/thanos/compact.go
docs/components/compact.md

Add a new `--wait-interval` flag that specifies compactor run interval.
This is helpful, especially for the end-to-end tests. See #2250 
* Add `--wait-interval` flag.
* `make build`

compactor: Add wait-interval flag

---

CHANGELOG.md
pkg/replicate/replicator.go
pkg/replicate/scheme.go
pkg/replicate/scheme_test.go

Fix replicate duplicate metrics

---

CHANGELOG.md
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/store.go
docs/components/bucket.md
docs/components/compact.md
docs/components/store.md
docs/proposals/201901-read-write-operations-bucket.md
pkg/block/block.go
pkg/block/block_test.go
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/block/metadata/deletionmark.go
pkg/block/metadata/deletionmark_test.go
pkg/compact/blocks_cleaner.go
pkg/compact/clean.go
pkg/compact/clean_test.go
pkg/compact/compact.go
pkg/compact/compact_e2e_test.go
pkg/compact/retention.go
pkg/compact/retention_test.go
pkg/shipper/shipper.go
pkg/verifier/duplicated_compaction.go
pkg/verifier/index_issue.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/safe_delete.go
pkg/verifier/verify.go

Signed-off-by: khyatisoneji <khyatisoneji5@gmail.com>
As part of this PR, we address the following:
a. Scheduling block for deletion rather than straight away deleting the block.
We do this by creating `deletion-mark.json` file for each block which signifies when the block was marked for deletion.
b.Cleaning up blocks marked for deletion after deleteDelay.
I have added `blocks_cleaner` component in compactor that checks if the blocks have been marked for deletion `deleteDelay` duration ago, and then deletes them.

store, compact, bucket: schedule block deletion by adding deletion-mark.json

---

pkg/store/cache/inmemory.go

Thanos uses `math.MaxInt64` constant for `int` parameter, which fails when building linux/arm builds. Found via vendoring Thanos in Cortex, and vendoring Cortex in Loki, which does linux/arm builds.
I've run `GOOS=linux GOARCH=arm go build ./cmd/thanos/` with this fix. Without the fix, it fails with
```
$ GOOS=linux GOARCH=arm go build ./cmd/thanos/
pkg/store/cache/inmemory.go:164:22: constant 9223372036854775807 overflows int
```

pkg/store/cache/inmemory.go: Use maxInt instead of math.MaxInt64

---

cmd/thanos/compact.go
pkg/block/block.go
pkg/objstore/objstore.go

Signed-off-by: khyatisoneji <khyatisoneji5@gmail.com>
* Since Bucket Interface already has Exists function, it is better to use `bkt.Exists` directly rather than using `objstore.Exists`. 
This should also address the CI pipeline failures seen here: https://circleci.com/gh/thanos-io/thanos/7875

Replace objstore.Exists function calls with bkt.Exists

---

pkg/cacheutil/memcached_client.go

While investigating some memcached errors I found a couple of additional logs (which I'm submitting in this PR) quite useful:
1. Size of a key on store failure
2. Number of keys (and their first key to see what's fetching) on get multi failure
- Enriched Memcached client logs
Manual tests.

Enrich Memcached client logs

---

CHANGELOG.md
pkg/store/bucket.go

This PR implements has some postings fetching optimizations:
- "ALL" postings are only fetched if they are required, and then they are fetched only once. Before this PR, "ALL" postings could have been fetched multiple times.
- label =~ ".*" is now shortcut to return ALL postings
- label !~ ".*" is now shortcut to return NO results :)
To implement this, `postingGroup` now only holds `add` and `remove` keys (labels). Postings for "Add" keys in each individual group are merged together and intersected between groups, and postings for "remove" keys are then subtracted from "added" ones. This all now happens in `ExpandedPostings`. `postingGroup` also has boolean flag `addAll`, which indicates whether "ALL" postings should be added or not. `ExpandedPostings` will only add ALL postings, if there …

store: Postings fetching optimizations

---

cmd/thanos/receive.go
pkg/receive/handler.go

Remove unused TLSClientConfig from receiver Options.
Its not used anymore since the [forwarding got moved to GRPC](https://github.com/thanos-io/thanos/pull/1970).
The TLS client settings for the GRPC client are being passed as DialOpts:
https://github.com/thanos-io/thanos/blob/master/cmd/thanos/receive.go#L197
https://github.com/thanos-io/thanos/blob/a7aa2986678309790d3fd2cc6810e42cd81603ab/pkg/extgrpc/client.go#L56
It compiles

cmd/thanos/receive: Remove unused TLSClientConfig from Options

---

pkg/receive/handler.go

Re-opening #2298
Invoke `httpSrv.ListenTLS` when a `TLSConfig` was specified.
```
curl -v -d {} http://127.0.0.1:19291/api/v1/receive
*   Trying 127.0.0.1:19291...
* Connected to 127.0.0.1 (127.0.0.1) port 19291 (#0)
> POST /api/v1/receive HTTP/1.1
> Host: 127.0.0.1:19291
> User-Agent: curl/7.69.0
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sat, 21 Mar 2020 13:01:34 GMT
< Content-Length: 22
< 
snappy: corrupt input
* Connection #0 to host 127.0.0.1 left intact
```
```
curl --insecure -v -d {} http://127.0.0.1:19291/api/v1/receive
*   Trying …
```

cmd/thanos/receive: Serve TLS when TLSConfig is given

---

CHANGELOG.md
cmd/thanos/bucket.go
cmd/thanos/compact.go
docs/components/compact.md

This commit enhances the compact component so that it runs the bucket UI
whenever the --wait flag is also passed. In order to reduce the overhead
of running the UI in addition to the compactor, this commit also
introduces an abstraction around downloading block meta files allowing
the metadata to be downloaded once and cached. This ensures that the
compactor does not unnecessarily download every metadata file twice.
Fixes: #1657
Ran the compact component with `--wait` with an objstore config against
a minio instance with blocks in it.
cc @bwplotka

cmd/thanos/compact: add bucket UI

---

CHANGELOG.md
cmd/thanos/rule.go

As discussed at #1848  we should return errors when initialization fail.
See https://github.com/thanos-io/thanos/pull/1848#discussion_r384959763
Currently, reloadRules wraps two kind of errors:
* filepath bad pattern error
* rule manager update error
Either of them contributes errors and stops ruler.

Ruler: reloadRules initlialization should fail

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/query.go
cmd/thanos/receive.go
cmd/thanos/rule.go
cmd/thanos/sidecar.go
cmd/thanos/store.go
pkg/replicate/replicator.go

Fixed inconsistent metrics naming and method

---

.github/workflows/e2e.yaml
Makefile
cmd/thanos/compact.go
pkg/block/fetcher.go
pkg/compact/compact.go
pkg/compact/compact_test.go
pkg/promclient/promclient.go
pkg/testutil/e2eutil/prometheus.go
test/e2e/compact_test.go
test/e2e/e2ethanos/services.go
test/e2e/query_test.go
test/e2e/receive_test.go
test/e2e/rule_test.go
test/e2e/store_gateway_test.go

Also:
* Reduced number of services for e2e for latency
* Fixed halting
* Improved logging.
* Improved test cases (e.g added test for compaction and halting)

e2e: Fixing compactor test flakiness.

---

CHANGELOG.md
Makefile
cmd/thanos/store.go
docs/components/store.md
pkg/cacheutil/memcached_client.go
pkg/cacheutil/memcached_client_test.go
pkg/model/units.go
pkg/model/units_test.go
pkg/store/cache/inmemory.go

While running the memcached index cache in Cortex we've find out that whenever the item size in larger than the max size allowed by memcached (defaults to 1MB, can increase with the `-I` option) the client will waste resources doing a full round-trip to memcached just to see the `Set()` operation to fail because the item size is larger than the limit.
In this PR I'm proposing to add a new option to memcached client config to allow to set the `max_item_size` so that we skip the set operation at all if the item size is greater.
Unit tests.

Added max_item_size to Memcached client

---

go.mod
pkg/testutil/testutil.go

Changed LICENSE as we no longer use version we copied back then.
Most of it was reimplemented.
Why?
* Much richer diff (inspired by testify packages
* Consistent API
* Less indentation.

tesutil: Enchanced testutil, refactored for our needs.

---

.circleci/config.yml
Makefile

This PR adds a new make task and CI step to check if example alert and rules properly generated and error-free.
* Add check-examples make task
* Add CI step
* `make check-examples`

make, ci: Check example alerts and rules in CI

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/bucket_replicate.libsonnet
mixin/thanos/alerts/query.libsonnet
mixin/thanos/alerts/receive.libsonnet
mixin/thanos/alerts/store.libsonnet

This PR changes tail latecy alert behaviour to alert on the rate of change rather than absolute value.
cc @brancz @metalmatze 
* Fix latency alerts.

mixin: Fix latency alerts

---

test/e2e/compact_test.go

Sorry, was late when we merged the fix. Funny bug: It would start to fail exactly 12h AFTER 25.03 8:00 GMT
Should be fine now... and in future until changed ;p

Fixed e2e.

---

CHANGELOG.md
cmd/thanos/store.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go
pkg/store/postings_codec.go
pkg/store/postings_codec_test.go

This PR introduces ability to compress postings before storing them into cache (in memory or shared cache). It reencodes postings to use more efficient encoding (diff + varint) and then uses snappy to compress it even more. It typically reduces original postings size to about 1/10th. New flag is disabled by default.
- unit tests for encoding/decoding postings
- manual testing hitting the code paths in `fetchPostings` method, and stepping through it in debugger

store: added option to reencode and compress postings before storing them to the cache

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/bucket_replicate.libsonnet
mixin/thanos/alerts/compact.libsonnet
mixin/thanos/alerts/query.libsonnet
mixin/thanos/alerts/receive.libsonnet
mixin/thanos/alerts/rule.libsonnet
mixin/thanos/alerts/store.libsonnet

This PR makes error threshold values for alerts parametric to enable end-user to configure alerts.
* Make alert threshold values parametric

mixin: Make alert threshold values parametric

---

docs/components/_index.md
docs/operating/_index.md
docs/proposals/_index.md
website/layouts/_default/list.html

Fix `404 Not Found` errors on various sections like `/proposals` and `/components`
Preview: https://deploy-preview-2328--thanos-io.netlify.com/proposals/
Fixes #2261 
- Add missing template `list.html` in `website/layouts/_default`. It is required to render the lists of items instead of giving a `404`
- Add `_index.md` to section folders inside /docs.

website: fix 404 on root of sections

---

CHANGELOG.md
cmd/thanos/store.go
test/e2e/e2ethanos/services.go

Based on the feedback we got binary header is outperforming old method in almost everything and it's stable for few months now. It has been running on Production on many setups we are aware of. Also, see offline discussion: https://cloud-native.slack.com/archives/CL25937SP/p1585297836078500
Let's claim production readiness:+1: 

store: Binary index header is now production ready and enabled by default

---

website/layouts/partials/_default/sidemenu.html
website/static/expand.svg
website/static/main.css

Made the Side menu sections collapsible. This was done using CSS only so the website remains functional without JS :smile: 
Preview: https://deploy-preview-2336--thanos-io.netlify.com/getting-started.md/
Fixes #2335 
- Made the side menu collapsible
- Current section stays open by default, achieved using Hugo's page variables
I tested the website build manually and verified everything's working as expected.

website: Collapsible menu sections

---

CHANGELOG.md
pkg/query/storeset.go
pkg/query/storeset_test.go
pkg/ui/templates/stores.html

We need to update `LastCheck` only if the error is non-nil. That field
is used in the cleanup function to know when to remove the StoreAPI from
the UI. If we always update it, even if an error has happened, that
means that `--store.unhealthy-timeout` is never respected.
*But* this only affects the UI part.
* Local testing;
* Amended unit tests
Funnily enough, https://github.com/thanos-io/thanos/pull/2337 will have to probably be modified a bit because the UI AFAICT will continuously remove/add nodes specified via `--store-strict` if they go down.

ui: fix store never removed from /stores page bug

---

CHANGELOG.md
cmd/thanos/query.go
docs/components/query.md
docs/proposals/202001_thanos_query_health_handling.md
pkg/discovery/dns/provider.go
pkg/discovery/dns/provider_test.go
pkg/query/storeset.go
pkg/query/storeset_test.go
pkg/store/postings_codec.go

Replaces: https://github.com/thanos-io/thanos/pull/2252.
Add a new flag called `--store-strict` as agreed per
https://thanos.io/proposals/202001_thanos_query_health_handling.md/
I have updated the proposal to reflect the reality.
Third time's the charm, I believe it :-)
Now the flag is called `--store-strict` which only accepts statically
defined nodes. I guess the code is even simpler now.
I have also fixed one small issue where `%w` was used in
`errors.Errorf`. Couldn't compile Thanos locally with Go 1.14 without
this fix.
Tested with unit tests + ad-hoc local testing.

query: add --store-strict flag

---

pkg/server/grpc/grpc.go

This PR fixes unregistered gRPC metrics issues that accidentally introduced with https://github.com/thanos-io/thanos/pull/2228.
cc @bwplotka 
* Register metrics.
* `MINIO_ENABLED=1 ./scripts/quickstart.sh`
* Check local prometheus

pkg/server/grpc: Fix Unregister gRPC prometheus middleware metrics

---

cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main_test.go
cmd/thanos/store.go
go.mod
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/compact/clean_test.go
pkg/compact/compact_e2e_test.go
pkg/compact/retention_test.go
pkg/replicate/replicator.go
pkg/replicate/scheme_test.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go
pkg/ui/bucket.go
pkg/verifier/duplicated_compaction.go
pkg/verifier/index_issue.go
pkg/verifier/overlapped_blocks.go
pkg/verifier/verify.go

Fixed https://github.com/thanos-io/thanos/issues/2349
Fixed races (we were reusing fetcher by both bucket UI and compaction syncs...
Fixed logging
Added singleflight to ensure we don't synchronize too often.
cc @squat Would be awesome to merge this before release as it's a major race :/ That might interact with what compact sees.

fetcher: Made metaFetcher go routine safe; Fixed multiple bucket UI +fetcher issues.

---

test/e2e/query_test.go

Add timestamps to e2e log output. I found this helpful a couple of times while debugging e2e tests, so I thought I may as well not just have it in a local branch as it's probably helpful for others.
Checked that e2e tests print timestamps.

test/e2e: Add timestamp to e2e test log output

---

CHANGELOG.md
cmd/thanos/bucket.go
cmd/thanos/compact.go
cmd/thanos/query.go
cmd/thanos/rule.go
cmd/thanos/store.go
pkg/block/fetcher.go
pkg/block/fetcher_test.go
pkg/ui/bucket.go
pkg/ui/query.go
pkg/ui/rule.go
pkg/ui/ui.go
test/e2e/compact_test.go
test/e2e/store_gateway_test.go

store & compact: For components that operates on blocks - expose the UI on /loaded-blocks

---

CHANGELOG.md
cmd/thanos/rule.go
pkg/query/config.go
pkg/query/config_test.go

- Fixes issue #2281 bug in ruler with parsing query addr with path prefix
Note: Right now `querySDFiles` will be added as new element to `query.Config` slice as suggested in https://github.com/thanos-io/thanos/issues/2281#issuecomment-600546052.
I have added unit test for parsing config, however I haven't tested it live. Is there and easy way of doing it?

rule: fix query addr parsing

---

mixin/thanos/alerts/bucket_replicate.libsonnet
mixin/thanos/alerts/compact.libsonnet
mixin/thanos/alerts/query.libsonnet
mixin/thanos/alerts/receive.libsonnet
mixin/thanos/alerts/rule.libsonnet
mixin/thanos/alerts/sidecar.libsonnet
mixin/thanos/alerts/store.libsonnet

Remove jobPrefix from the thanos mixin, as it's not used anywhere.
After removing the field from the libs I did a `grep -r 'jobPrefix' mixin/thanos/alerts` to confirm it's really not used anywhere.
---
Not sure if this needs a CHANELOG entry? 🤔

mixin: Remove unused jobPrefix field

---

pkg/objstore/s3/s3.go

Due to https://github.com/golang/go/issues/13801 Connection reuse currently seems not to work as expected. This also got fixed for Prometheus in https://github.com/prometheus/prometheus/pull/3592 and for Cortex in https://github.com/cortexproject/cortex/pull/2268, since Cortex is now using the implementation of object store of thanos i may hit this behaviour.
I am not sure how to test this, if someone could help to test, this would be great.
See above

Allow more connection reuse than the default of 2

---

Makefile

We got booted from the GCS account, so skip this in CI for now.

Ignore GCS in CI

---

Makefile

This reverts commit 8591434856ced5803e399b4d9d1bf2d1459c0ee0.
No need, I updated the GCS project, should work now against new account.

Revert "Makefile: ignore GCS in CI (#2368)"

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/rule.libsonnet

mixin: Added critical Rules alerts.

---

docs/storage.md

The link for the AWS Region Endpoint Mappings for S3 was out of date, this PR updates it to point to the new location.
Updated S3 Endpoint Mapping link in the documentation.
Link is rendered correctly in https://deploy-preview-2377--thanos-io.netlify.com/storage.md/#s3.

docs: Update S3 endpoint mapping link

---

pkg/block/indexheader/binary_reader.go

Cherry pick of https://github.com/thanos-io/thanos/pull/2371
With an added commit to ensure filewriter is flushed and file is synced before renaming the file.
cc @bwplotka @GiedriusS

Fix2213 0.12

---

pkg/receive/handler.go
pkg/receive/writer.go

This commit adds a tracing span around the writing of remote-write
requests into TSDB. This will help us differentiate between the
latencies in the forwarding of requests around the hashring and the
latencies of appending to the database.
This commit also removes the `thanos_` prefix from the forwarding span
to better align with the span naming in the rest of the project.

pkge/receive: trace TSDB ingestion

---

cmd/thanos/compact.go
cmd/thanos/downsample.go
cmd/thanos/main_test.go
pkg/block/block.go
pkg/block/block_test.go
pkg/block/fetcher.go
pkg/compact/blocks_cleaner.go
pkg/compact/clean.go
pkg/compact/clean_test.go
pkg/compact/compact.go
pkg/compact/retention.go
pkg/compact/retention_test.go
pkg/verifier/safe_delete.go

Also:
* Changed order: Now BestEffortCleanAbortedPartialUploads is before DeleteMarkedBlocks.
* Increment markedForDeletion counter only when we actually uploaded block.
* Fixed logging issues.

compact: Made MarkForDeletion less strict; Added more debugability to block deletion logic, made meta sync explicit.

---

.github/stale.yml

Based on the discussion in #2262, we want to add a [reminder bot](https://github.com/probot/reminders) to mark stale issues for a customized time period. 
This PR just adds a `reminder` label to stale bot config, after this is merged, we can install [reminder bot](https://github.com/probot/reminders) and see if it fulfills our requirements.

Add reminder label to stale bot config

---

docs/sharding.md

- Update the promtail link
- We also support the default `replace` relabel action
- Fix the markdown style issue in the website
Before: https://thanos.io/sharding.md/
After: https://deploy-preview-2379--thanos-io.netlify.com/sharding.md/

Fix markdown docs style and link in the sharding doc

---

CHANGELOG.md
cmd/thanos/store.go
pkg/block/indexheader/binary_reader.go
pkg/block/indexheader/header_test.go
pkg/store/bucket.go
pkg/store/bucket_e2e_test.go
pkg/store/bucket_test.go

Spotted by @mkabischev! Thanks to you and @d-ulyanov as well! Epic finding :+1: :muscle: 
Test output before fix:
```go
testutil.Equals(t, 1, br.version)
testutil.Equals(t, 2, br.indexVersion)
testutil.Equals(t, &BinaryTOC{Symbols: headerLen, PostingsOffsetTable: 66}, br.toc)
testutil.Equals(t, int64(626), br.indexLastPostingEnd)
testutil.Equals(t, 8, br.symbols.Size())
testutil.Equals(t, map[string]*postingValueOffsets{
"": {
offsets:       []postingOffset{{value: "", tableOff: 4}},
lastValOffset: 392,
},
"a": {
offsets: []postingOffset{
{value: "1", tableOff: 9},
{value: "11", tableOff: 16},
{value: "12", tableOff: 24},
{value: "2", tableOff: 32},
{value: "3", tableOff: 39},
{value: "4", tableOff: 46},
{value: "5", tableOff: 53},
{value: "6", tableOff: 60},
{value: "7", tableOff: 67}, …
```

store: Fixed binary header bug that was causing all postings to be kept in memory instead of 1/32 as we meant.

---

CHANGELOG.md
pkg/block/indexheader/binary_reader.go
pkg/block/indexheader/header_test.go

The reason, why we could not reproduce it locally, was that for most of non-existing values, we were lucky that buffer was still long enough and we could read and decode some (malformed) variadic type. For certain rare cases, the buffer was not long enough or varint was failing.
Fixed and spotted thanks to amazing @mkabischev!
* Added more regression tests for the binary header.
Without the fix it fails with:
```
header_test.go:154: header_test.go:154:
exp: range not found
got: get postings offset entry: invalid size
```

store: Fixed critical bug, when certain not-existing values queried was causing "invalid size" error inside binary index-header

---

examples/alerts/alerts.md
examples/alerts/alerts.yaml
mixin/thanos/alerts/rule.libsonnet

This change makes the critical (typically paging) alert more symptom
based, rather than observing data written to disk. Additionally after
this change the alert will only fire if there are actually rules loaded.
Additionally to no rules loaded the previous alert was also prone to rules that legitimately are not writing data.
Fixes https://github.com/thanos-io/thanos/issues/2391
Verified against an incident we had, plus verified that this doesn't fire against a Thanos Rule instance that does not have any rules loaded.
@thanos-io/thanos-maintainers @lilic

mixin: Change critical rule alert to be symptom based

---

scripts/genproto.sh
scripts/insecure_grpcurl_series.sh

TODO in next PR: Add to contributing doc info about it. 
cc @SuperQ this should help you give us more data straight from StoreAPIs from CLI (: Just port forward queried StoreAPI (querier data for start would be good because all sample iterations are done on top of that Querier gRPC)

scripts: Added grpcurl script useful for Thanos debugging.

---

docs/components/bucket.md

and follow formatting of the other bucket commands

bucket docs: fix "thanos downsample" remnant

---

CHANGELOG.md
cmd/thanos/bucket.go

Fixes #2414 
The compare function used for sorting only checks if the string is `Time` type which causes wrong sorting if the string is `TimeDuration` type.
Added extra check to compare `time Duration` type values.
Manually tested the compare function with different type of strings

bucket: "inspect --sort-by" doesn't work in all cases

---

examples/dashboards/compact.json
examples/dashboards/query.json
examples/dashboards/receive.json
examples/dashboards/rule.json
examples/dashboards/sidecar.json
examples/dashboards/store.json
mixin/thanos/dashboards/store.libsonnet
mixin/thanos/lib/thanos-grafana-builder/builder.libsonnet

Signed-off-by: John Belmonte <john@neggie.net>
Use bytes unit in grafana dashboards
Fixes #2392 
dashboard json files were regenerated with `make examples`
CI has coverage with `make check-examples`

use bytes unit where appropriate on grafana dashboards

---

docs/components/bucket.md

added note to `bucket verify` docs about disabling the compactor when using `--repair`

bucket verify: document that compactor should be disabled

---

MAINTAINERS.md

As voted by Thanos Team, @pracucci is now part of our team! :heart: 
Also, reordered list alphabetically.

Added Marco as Thanos Maintainer

---

CHANGELOG.md
pkg/store/proxy.go
pkg/store/proxy_test.go

Closes: https://github.com/thanos-io/thanos/issues/2314
Running `THANOS_ENABLE_STORE_READ_TIMEOUT_TESTS=1 /usr/local/go/bin/go test -v -timeout 60s github.com/thanos-io/thanos/pkg/store -run '^(TestProxyStore_SeriesSlowStores)$'` gives us:
```
=== RUN   TestProxyStore_SeriesSlowStores
=== RUN   TestProxyStore_SeriesSlowStores/partial_response_disabled;_1st_errors_out_after_some_delay;_2nd_store_is_fast
panic: test timed out after 1m0s
goroutine 29 [running]:
testing.(*M).startAlarm.func1()
/usr/local/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
/usr/local/go/src/time/sleep.go:168 +0x44
goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc000262400, 0x1a2dff4, 0x1f, 0x1ac4b80, 0x48c301)
/usr/local/go/src/testing/testing.go:961 +0x377 …
```

store: proxy: fix queries never timing out bug

---

docs/contributing/coding-style-guide.md

docs: fixed typo in coding style guide

---

docs/release-process.md

In general, I think it is easier for users of guides when shell commands
are listed without a preceeding `$`, otherwise the commands cannot be
directly copied and pasted into a terminal.

docs/release-process: make shell command copyable

---

docs/contributing/coding-style-guide.md

This commit makes some small grammar fixes to the coding style
guide.

docs/contributing: clean up style guide grammar

---

.circleci/config.yml

We were not using the latest thanos-ci image tag for every part of the
CI pipeline: we were using 0.3.0 for tests but 0.2.0 for all builds.
fixes: https://github.com/thanos-io/thanos/pull/2025#issuecomment-613969516

.circleci: use consistent ci image tags

---

CHANGELOG.md

The changelog in the release-0.12 branch is correct, but somewhere in
the merge back into master, the changelog was mangled. This puts the
fixes in their correct places.

CHANGELOG.md: fix changelog

---

CHANGELOG.md
pkg/store/proxy.go
pkg/store/proxy_test.go

This PR cherry-picks @GiedriusS changes from #2411 into the release-0.12 branch so that we can make v0.12.1
* store: proxy: add test for deadlocking problem
* store: proxy: add fix for timeouts
Checking here if the series context has ended is the correct fix here.
We want to check it because if any of the other Series() calls error out
then the context is canceled. So, it is equal to checking for errors
"downstream", in `mergedSeriesSet`.
Also, `handleErr()` here is the correct function to use because in such
a case we want to set `s.err` -- if `io.EOF` still hasn't been received
then it means that StoreAPI still has some data that it wants to send
but hasn't yet.
With this, the previously added test passes.
Signed-off-by: …

store: proxy: fix queries never timing out bug (#2411)

---

docs/proposals/202004_embedd_cortex_frontend.md
docs/proposals/_index.md

proposal: Added proposal for new Thanos component: Thanos Frontend.

---

CHANGELOG.md
go.mod
pkg/store/bucket.go
pkg/store/bucket_test.go
pkg/store/opts.go
pkg/store/opts_test.go

This PR adds "regex set" optimization that's already available in Prometheus to Thanos. If label matcher is in form label=~"a|b", then we can simply get postings for label=a and label=b. This is especially useful for labels with high cardinality (as used in benchmark).
Extended unit test and benchmark to cover this case.
```
name                                                                 old time/op    new time/op    delta
BucketIndexReader_ExpandedPostings/n="1"-4                             4.14ms ± 3%    4.15ms ± 2%     ~     (p=0.853 n=10+10)
BucketIndexReader_ExpandedPostings/n="1",j="foo"-4                     32.7ms ± 1%    33.6ms ± 1%   +2.75%  (p=0.000 n=9+8)
BucketIndexReader_ExpandedPostings/j="foo",n="1"-4                     44.6ms ±56%    34.2ms ± 2%     ~     (p=0.165 …
```

store: Added regex-set optimization to ExpandedPostings

---

docs/operating/troubleshooting.md

This PR aims to add a section of the documentation of beginner issues that users might make while they are new to thanos / prometheus / golang development. 
#
Added a new file `docs/operating/beginner_issues.md`
Not required :stuck_out_tongue:

Added a page for documenting beginner issues

---

CHANGELOG.md
pkg/block/fetcher.go

Fixes: #2471
This commit fixes an issue where multiple goroutines in the block
fetcher filtering were concurrently accessing the same map. The
goroutines were concurrently writing AND reading to the shared metas
map. This commit guards this concurrent access by giving the
DeduplicateFilter struct a mutex.

pkg/block/fetcher: fix concurrent map usage

---

CHANGELOG.md
cmd/thanos/compact.go
pkg/compact/clean.go
pkg/compact/clean_test.go
test/e2e/compact_test.go

Fixes https://github.com/thanos-io/thanos/issues/2459 (quick fix).
This keeps the logic from the 0.11.0 which was good enough.
Some improvement for future: https://github.com/thanos-io/thanos/issues/2470
Let's merge this to master once 0.12.1 is released.

Reverted addition of deletion mark for partial uploads.

---

CHANGELOG.md
pkg/store/bucket.go

This PR removes shortcuts for `label=~".*"` and `label!~".*"` matchers. Unless default in Prometheus changes such that `.` matches newline as well, these optimizations are not correct. See https://github.com/prometheus/prometheus/pull/6996#issuecomment-616473253
Only removes shortcuts for specific matchers. Nothing else is changed.

Remove optimizations for label=~".*" and label!~".*".

---

CHANGELOG.md
cmd/thanos/query.go
cmd/thanos/rule.go

Fixes #2483 
The web route prefix is registered twice.
Cherr-pick of https://github.com/thanos-io/thanos/pull/2484 for release-0.12

fix thanos web route prefix register twice

---

CHANGELOG.md
pkg/query/querier.go
pkg/store/proxy.go
pkg/store/proxy_test.go

Following up the discussion we had in #2479, in this PR I'm proposing to gracefully handle additional `oneof` fields we may add in the future to `SeriesResponse`, without assuming that it either contains warnings or series (may also contain new fields an older client doesn't known).
(Already existing)  tests.

Gracefully handle additional oneof fields in SeriesResponse

---

pkg/cacheutil/memcached_client.go

Depending on the memcached client configuration, particularly `MaxGetMultiBatchSize` and `MaxItemSize`, Memcached operation duration varies; hence this PR adjusts buckets to cover more latency classes.
https://github.com/thanos-io/thanos/blob/45a6bc4ed39e7f7b14f99fedbc62ac414b745bb4/pkg/cacheutil/memcached_client.go#L35-L45
cc @brancz @pracucci @pstibrany 
* Adjust `thanos_memcached_operation_duration_seconds ` metric histogram buckets.
* `make build`
* `MINIO_ENABLED=1 ./scripts/quickstart.sh`
* Check `curl localhost:10906/metrics`

Adjust memcached operation buckets

---

CHANGELOG.md
pkg/query/storeset.go

This change removes the `thanos_store_node_info` metric which has been made obsolete in [v0.8.1](https://github.com/thanos-io/thanos/blob/master/CHANGELOG.md#v081---20191014).
Tests should pass.

pkg/query: remove obsolete 'thanos_store_node_info' metric

---

pkg/block/fetcher.go
pkg/block/fetcher_test.go

Removed `incompleteView` from fetcher response type.  It was never set to anything else than false, and its value was only passed to `MetadataFilter` and `MetadataModifier` implementations, but none of them actually used it.
Compiling the code and running the unit tests.

Remove incompleteView field from fetcher response.

---

CHANGELOG.md
Dockerfile.multi-stage

Reformatting `Dockerfile.muti-stage` to leverage the Docker Layer Caching, it reduces the build time up to 30% for recurring builds. First-time build will take the same time.

Dockerfile: Leveraging docker layer caching

---

CHANGELOG.md
cmd/thanos/sidecar.go
pkg/reloader/example_test.go
pkg/reloader/reloader.go
pkg/reloader/reloader_test.go

The reloader package didn't expose any metrics. This PR adds a few:
* `thanos_sidecar_reloader_reloads_failed_total`
* `thanos_sidecar_reloader_reloads_total`
* `thanos_sidecar_reloader_watch_errors_total`
* `thanos_sidecar_reloader_watch_events_total`
* `thanos_sidecar_reloader_watches`

*: add metrics to the reloader package

---

docs/components/query.md
docs/components/store.md
docs/proposals/201909_thanos_sharding.md
docs/quick-tutorial.md

currently setting up Thanos and came across a couple of broken links. also ran the docs/ dir through link checker and updated any broken ones while at it.
N/A 
N/A

docs: fixed broken links in documentation

---

CHANGELOG.md
pkg/block/fetcher.go
pkg/compact/compact_e2e_test.go

This PR fixes problem with duplicate blocks field not being cleared at the beginning of Filter.
If not cleared, such blocks are then reused between runs. Once deleted due to deletion delay, deletion markers are recreated, and on next meta sync, they are deleted again (as partial blocks).
Added unit test.
Closes issue #2459.
To be merged into release-0.12 as suggested by @bwplotka

Clear duplicateIDs at the beginning of Filter.

---

CHANGELOG.md
cmd/thanos/rule.go
test/e2e/rule_test.go

Let's make `/-/reload` accessible again by not wrapping the router with the prefix twice. Add a simple test-case to automatically check whether this works.
* Do not wrap `/-/reload` with the prefix twice
`make test-e2e`

cmd: rule: do not wrap reload endpoint with prefix twice

---

CHANGELOG.md
go.mod
go.sum

Bumped minio-go sdk library v6.0.53 to fix sts url to `https://` for Web Identity Provider for IAM credential, AWS EKS. (issue https://github.com/minio/minio-go/pull/1263) 
I built a new docker image with v6.0.53 and checked that it works correctly when deployed in AWS EKS with service account IAM credential to access S3 bucket (docker.io/alicek106/thanos:bumped-minio-v6.0.53).

Bumped minio-go library to v6.0.53

---

pkg/query/api/v1.go
pkg/query/api/v1_test.go

Signed-off-by: darshanime <deathbullet@gmail.com>
Thanos currently does not support `delete_series` api, see https://github.com/thanos-io/thanos/issues/415. This PR adds a skeleton endpoint explicitly mentioning the api is not supported yet as [suggested earlier](https://github.com/thanos-io/thanos/issues/415#issuecomment-403399284).
We will eventually implement the API by adding in functionality in the handler. 
- return `400 Bad Request` on `delete_series` API
```
curl -X POST "http://thanos_querier:10902/api/v1/delete_series?match[]=scrape_duration_seconds"  -v
*   Trying 172.24.0.5...
* TCP_NODELAY set
* Connected to thanos_querier (172.24.0.5) port 10902 (#0)
> POST /api/v1/delete_series?match[]=scrape_duration_seconds HTTP/1.1
> Host: thanos_querier:10902
> User-Agent: curl/7.60.0
> …
```

Add deleteSeries skeleton to return bad request

---

docs/community.md

Fixed the URL for the timezone in `docs/community.md`.
The timezone entry of the [community](https://thanos.io/community.md/#thanos-community-meeting) page contains an invalid URL, so I have fixed it.

Fixed the timezone url of Community page in docs

---

.circleci/config.yml
.github/workflows/cross-build.yaml
.github/workflows/e2e.yaml
.promu.yml
CHANGELOG.md
Dockerfile.multi-stage
Dockerfile.thanos-ci

- Update golang to 1.14.2
- Generate thanos-ci:go1.14.2-node
This is a manual process that requires one of the maintainers to run the following:
```
make docker-ci DOCKER_CI_TAG=go1.14.2-node
```
~~Sadly `circleci/golang:1.14.0` is not yet available, so this PR would be on hold until it becomes available, hopefully sometime in the next few days.~~
Go 1.14 highlights:
- [Embedding interfaces with overlapping method sets ](https://golang.org/doc/go1.14#language)
- [Improved defer performance](https://golang.org/doc/go1.14#runtime)
- [Goroutines are asynchronously preemptible](https://golang.org/doc/go1.14#runtime)
- [The page allocator is more efficient](https://golang.org/doc/go1.14#runtime)
- [Internal timers are more efficient](https://golang.org/doc/go1.14#runtime)
[Go 1.14 …

Updated to golang v1.14.2

---

Makefile
cmd/thanos/receive.go
go.sum
pkg/receive/handler.go
pkg/receive/handler_test.go
pkg/receive/multitsdb.go
pkg/receive/writer.go
pkg/server/grpc/grpc.go
pkg/store/multitsdb.go
scripts/quickstart.sh
test/e2e/query_test.go
test/e2e/receive_test.go

This PR adds multi TSDB support for the receive component.
Tested manually and e2e tests.

receive: Add support for TSDB per tenant
