thanos-io/thanos

- cmd/thanos/receive.go
- test/e2e/e2ethanos/services.go
This adds automatic migration of legacy storage to multi-tsdb disk layout, where the existing storage is migrated to the default tenant.
This builds on top of https://github.com/thanos-io/thanos/pull/2012, so until that merges, this includes those changes, but only the latest commit is relevant.
Tried upgrading locally from a legacy TSDB disk layout.
@bwplotka @squat @metalmatze @krasi-georgiev @blockloop
> Multitsdb migration

- pkg/receive/multitsdb.go
Use read locks where possible to read tenants in multitsdb.
Ran tests.
@bwplotka @squat @metalmatze @kakkoyun @krasi-georgiev
> receive: Use read locks where possible to read tenants

- CHANGELOG.md
- pkg/query/storeset.go
- pkg/query/storeset_test.go
Do not close the gRPC connection if establishing a connection has
succeeded but we have failed to get a response to a Info() call. Without
this and with strict mode in such a case, we will always keep around a
closed connection that won't work anymore unless the whole Thanos Query
process will be restarted.
It does not close the gRPC connection of strict nodes if the Info() call fails. Without it the `grpc.ClientConn` variables are kept around forever in this state and Thanos Query never tries to establish that connection again.
Updated unit tests to cover this case. Without these changes they fail.
> query/storeset: do not close the connection if strict mode enabled

- pkg/compact/compact.go
Since when we introduced the deletion marker, the `thanos_compact_garbage_collected_blocks_total` metric tracks the number of blocks marked for deletion and not the ones effectively deleted.
N/A
> Fixed thanos_compact_garbage_collected_blocks_total metric help

- CHANGELOG.md
- cmd/thanos/store.go
- docs/components/store.md
- pkg/cache/cache.go
- pkg/cache/memcached.go
- pkg/cache/memcached_test.go
- pkg/extflag/hidden.go
- pkg/store/cache/caching_bucket.go
- pkg/store/cache/caching_bucket_factory.go
- pkg/store/cache/caching_bucket_test.go
- pkg/store/cache/factory.go
This PR implements chunks caching as described in ["Caching in Thanos"](https://docs.google.com/document/d/1knNXQfDJlQDA9Dr9R9OVFvdWS83sXd0kLEFdv21IxCM/edit#) document.
Chunks caching is done at Bucket level. Since bucket doesn't really know about chunks, and Thanos simply uses GetRange call on Bucket to fetch chunks, this implementation splits such requests into smaller "blocks" (with size of 16000 bytes), and stores each block into cache individually.
To enable chunks caching, one needs to configure `store` to use caching bucket using `--experimental.caching-bucket.config=store_cache.yaml` option. File looks like this:
```yaml
backend: memcached
backend_config:
addresses:
- localhost:11211
caching_config:
chunk_block_size: 16000
max_chunks_get_range_requests: 3
```
Only memcached client …
> Chunks caching at bucket level

- pkg/compact/compact.go
Following up the feedback received in #2572, in this PR I've reworded comments and logs in the compactor to actually match the fact blocks are no more immediately deleted, but marked for deletion.
N/A
> Reword block deletion comments and logs in compactor

- scripts/quickstart.sh
The subcommand is called now `tools bucket web` after the recent
changes.
Without this, the quickstart script outputs:
```
Error parsing commandline arguments: expected command but got "bucket"
thanos: error: expected command but got "bucket"
```
Edited `./scripts/quickstart.sh` to include the "tools" prefix which is needed after the recent renames.
`./scripts/quickstart.sh` brings up Thanos Bucket Viewer on `http://localhost:10933/`
> quickstart: fix bucket web after recent changes

- cmd/thanos/config.go
- cmd/thanos/flags.go
- cmd/thanos/sidecar.go
Introduce config structs for sidecar component.
As per #2248  - this change parses flags into structs before passing into the sidecar run func
> Refactor of commands and flag parsing

- pkg/ui/react-app/package.json
- pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx
- pkg/ui/react-app/src/pages/graph/Graph.test.tsx
- pkg/ui/react-app/src/pages/graph/Panel.test.tsx
- pkg/ui/react-app/src/pages/graph/PanelList.tsx
- pkg/ui/react-app/src/pages/targets/__snapshots__/TargetLabels.test.tsx.snap
- pkg/ui/react-app/yarn.lock
Update the react dependencies by porting these commits via a three-way merge:
https://github.com/prometheus/prometheus/commit/24ecae995691dabf782a6b4a7464f7aab561b554
https://github.com/prometheus/prometheus/commit/65a19421a42c69e16241eec24c66b98e4c8fa5da
Updated new UI dependencies by using commits from Prometheus. I had to revert one change before the first patch applied successfully. Also, moved the Thanos-specific props a bit up so they would not appear in the diff's context.
Should solve the security warnings that appeared after the introduction of the new UI.
```
make assets
make build
./thanos query
```
And played around with the new UI, it seems like nothing broke.
> react: update deps

- Makefile
Found out that there is some weird interaction between `jest --coverage`
and `babel-plugin-istanbul`. Maybe related to:
https://github.com/facebook/jest/issues/6827.
From my testing, removing `--coverage` makes this work again. Probably
worth investigating in the future why that happens.
Also, this is really not needed during CI because we do not use the
coverage data anywhere anyway.
`docker run --user 1000 -v "$(pwd):/src" -it --rm quay.io/thanos/thanos-ci:go1.14.2-node` and then:
```bash
cd /src
make react-app-test
```
Passes the tests as it is supposed to.
> Makefile: remove --coverage from test run

- .circleci/config.yml
- .github/workflows/react-test.yml
Add a GH actions workflow to test the React UI on nodejs v10 and v12
Remove `react-app-test` from CircleCI config
I tested it by creating a dummy PR on my clone and the GH action wrokflow seems to work as expected.
> ci: use GitHub Actions to test React UI

- pkg/receive/handler_test.go
- pkg/receive/multitsdb.go
- pkg/receive/multitsdb_test.go
- pkg/receive/tsdb_test.go
> Added receiver multidb unit tests for basic cases.

- Dockerfile
- Makefile
- docs/components/compact.md
- docs/components/store.md
- scripts/genflagdocs.sh
cc @Harshitha1234 @PhilipGough  this is what I mean (:
> Fixed make docs 

- pkg/store/cache/caching_bucket.go
- pkg/store/cache/caching_bucket_config.go
- pkg/store/cache/caching_bucket_factory.go
- pkg/store/cache/caching_bucket_test.go
This PR does several things at once:
- Adds caching to more methods in `CachingBucket` (Get, Exists, Iter, ObjectSize)
- Makes caching bucket fully configurable: caching for each operation is configured via `Cache<OperationName>` method. This takes config name (used as label in metrics), cache, matcher function that is used to match object names, and configuration used for matching objects.
- Factory configures caching bucket to support:
- Chunks caching: via `GetRange` method
- Meta files caching (meta.json, deletion mark) via `Get` and `Exists` method
- Caching of `Iter` for root directory
- Caching of index files via `GetRange` and `ObjectSize` (this is mostly an example how to do it. We can discuss whether to do it now, or we wait)
Factory uses user-supplied configuration to configure …
> Metadata caching in bucket

- cmd/thanos/store.go
- docs/components/store.md
store: Improve help of --data-dir flag. #2435
Updated the help message for --data-dir flag
> Updated the help message for --data-dir flag

- CHANGELOG.md
- cmd/thanos/rule.go
- pkg/rule/rule.go
- pkg/rule/rule_test.go
Note: The commits were taken from this PR https://github.com/thanos-io/thanos/pull/1439, as that PR was closed too early but the bug still exists and we hit it in our setup. I added the original author as the co-commiter, as they were not responsive on the original PR.
From original PR:
> Thanos rule loading alerts about out-of-sync rule files
Specifically, the following scenario:
Rule file rule. Yaml, which contains some rules, through the reload command, thanos rule load rules.
If you clear the contents of rule. Yaml, but leave the file in, the old rules in thanos rule will not be cleared.
This bug leads to a common situation (all rules in one file)
If thanos rule has 100 rules, it can only clear 99 rules at most.
Note this also fixes when you have one rule loaded only, and you delete …
> rule: Fix bug when rules were out of sync

- CHANGELOG.md
- pkg/store/bucket.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
- pkg/store/storepb/custom.go
- pkg/store/storepb/custom_test.go
- pkg/store/storepb/rpc.pb.go
- pkg/store/storepb/rpc.proto
Blocked by: https://github.com/thanos-io/thanos/pull/2548
Partially fixes: https://github.com/thanos-io/thanos/issues/2303
It should make certain calls where we have overlapped data from StoreAPIs much faster and more efficient.
* Cases like overlapped data from store and sidecar and 1:1 duplicates are now optimized by removal of exact duplicates as soon as it's possible, on proxy level (fanout receive). This case was highly visible on GitLab repro data and exists in most of the Thanos setups. cc @SuperQ 
* Also this adds logic for merging the same series together on proxy level instead of `select`. This allows for better dedup efficiency.
> store/proxy: Deduplicate chunks on StoreAPI level. Recommend chunk sorting for StoreAPI.

- CHANGELOG.md
- docs/components/store.md
This PR adds CHANGELOG entry and documentation for PR #2579.
> Documentation and CHANGELOG.md entry for #2579.

- cmd/thanos/compact.go
- cmd/thanos/config.go
Introduce config structs for sidecar component.
As per #2248  - this change parses flags into structs before passing into the compact run func
> Cleanup flags for compact component

- CHANGELOG.md
- pkg/tracing/elasticapm/elastic_apm.go
Disable Elastic APM Default Tracer that would otherwise gather metrics
and send them on localhost even if no tracing backend was specified.
Fix thanos-io/thanos#2610
I don't think the change is relevant as I don't see anyone using the default metric gatherer without enabling tracing. However feel free to edit it if you think the new behavior is considered breaking changes.
The worse case scenario is: someone is using the default gatherer to gather Go Metrics without having tracing enabled. As far as I understand it, this is undocumented and unsupported.
Disable Elastic APM default tracer on initialization 
Start `thanos` with `ELASTIC_APM_LOG_LEVEL=debug` and `ELASTIC_APM_LOG_FILE=stdout`. Elastic APM does not try to gather and send metrics anymore.
> .*: pkg/tracing: Disable Elastic APM default tracer

- docs/components/store.md
- pkg/store/cache/caching_bucket_factory.go
Relevant discussion #2575 
Signed-off-by: Ranjith Kumar <ranjith.dakshana2015@gmail.com>
1. Rename caching bucket YAML fields from backend to type, backend_config to config 
2. Update docs to reflect the change in YAML fields
Verified documentation using `make web-serve` .
Caching at bucket level was not part of an earlier release. So, this shouldn't update changelog, right?
> Rename caching_bucket yaml fields

- CHANGELOG.md
- cmd/thanos/query.go
- cmd/thanos/rule.go
- pkg/cacheutil/memcached_client.go
- pkg/discovery/dns/provider.go
- pkg/discovery/dns/provider_test.go
- pkg/http/http.go
This PR addresses the issue  #2404 
I had run the changes, and the Query component also logs the failure of the dns resolution. Earlier, only the `provider.go` logged the issue, now both are logging the error.
```
yash@kmaster  thanos-io/thanos   query-component-issue  ./thanos query --store.sd-dns-resolver=miekgdns --store=dnssrv+_grpc._tcp.thanos-store-grpc.default.svc.cluster.local
level=info ts=2020-04-26T08:10:36.149858286Z caller=main.go:152 msg="Tracing will be disabled"
level=info ts=2020-04-26T08:10:36.150778772Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-04-26T08:10:36.151007023Z caller=query.go:408 msg="starting query node"
level=info …
```
> Added logging for dns resolution error in the Query component as well

- CHANGELOG.md
- cmd/thanos/receive.go
- pkg/receive/handler.go
- pkg/receive/handler_test.go
- pkg/receive/writer.go
This patch modifies receive replication slightly, in that it doesn't
always wait for all requests to complete anymore. If quorum amount of
replication requests were successful it now does not wait for the
remaining request to finish as it's not necessary to reach quorum
anymore. In error cases where quorum is not reached, it still continues
to wait for all requests to finish in an attempt to return a quorum
error.
Additionally this patch moves log lines printed in the parallelize
requests function to debug logging. Calling functions already print the
resulting error(s), so this was previously just noise, even in cases
where requests actually succeeded.
Let me know if you think there should be a changelog entry for this, in reality there is not really a user noticable change, other than …
> receive: Only wait for write quorum

- pkg/compact/compact.go
If the compactor group key check fails, it currently wraps an error which is actually `nil` and this causes a panic. This PR fixes it.
Manual tests.
> Fixed panic in compactor

- docs/components/store.md
- pkg/store/cache/caching_bucket_factory.go
* Change memcached BucketCacheProvider constant type to `MEMCACHED` to be consistent with index cache backend.
https://github.com/thanos-io/thanos/blob/8bdd15e032c24fb98ed9ec69fa42f16376a9101e/pkg/store/cache/factory.go#L18-L23
* Make it case-insensitive to prevent future issues.
cc @pstibrany
> store: Fix inconsistent cache backend types

- CHANGELOG.md
- pkg/compact/compact.go
- pkg/compact/compact_test.go
Just like in IsHaltError(), let's unwrap the given error to see if is
`terrors.MultiError`. This lets us detect the retryable errors as well:
* `BucketCompactor.Compact` returns `terrors.MultiError` of wrapped
errors;
* `compactMainFn` wraps the previously returned error again.
So, we need to unwrap it at the beginning, iterate over it, and then
unwrap again which is what the code does with this change.
`IsRetryError()` now detects wrapped `terrors.MultiError` which is what happens in some (if not all) cases.
Amended unit tests.
> compact: unwrap the original error as well

- docs/operating/troubleshooting.md
- scripts/thanos-block.jq
This PR adds `scripts/thanos-block.jq` script that I find useful when inspecting `meta.json` files. It mostly just translates timestamps to human-readable form. Example:
```
$ cat ./thanos-tsdb/01E6K1KY8N748AE90M68TZGSEP/meta.json | thanos-block.jq 
{
"ulid": "01E6K1KY8N748AE90M68TZGSEP",
"minTime": "2020-03-19T00:00:00Z",
"maxTime": "2020-03-28T20:00:00Z",
"stats": {
"numSamples": 18417487,
"numSeries": 2455,
"numChunks": 227913
},
"thanos": {
"labels": {
"prometheus_instance": "localhost"
},
"downsample": {
"resolution": 0
},
"source": "compactor"
},
"compaction": {
"level": 4,
"sources": [
"01E3RE3Y560AH99QJEV2D7D0KH",
"01E4NRW2PEVMRXEDDD046CDEBX"
],
"sourcesCount": 113, # not found in original meta.json, but I find it useful
"parents": [
{
"ulid": "01E45Z17PVM72TDGF19WC5ZV02", …
```
> Added thanos-block.jq script and mention in troubleshooting doc.

- CHANGELOG.md
- pkg/cacheutil/memcached_client.go
- pkg/cacheutil/memcached_client_test.go
This PR fixes issue when user tries to configure both caching bucket and index cache at the same time. That creates two independent memcached clients, which try to create same metrics into the same registry, which failed before. This PR fixes that.
Unit test that fails on master. Also manually tested by configuring Thanos store to use both caches -- it fails with master build, but works with this patch.
/cc @kakkoyun (since you reported it to me)
> Allow using multiple memcached clients at the same time.

- Dockerfile.multi-stage
* Fix multi-stage builds (reflect changes after modification to `make build`)
* `make docker-multi-stage`
> Fix failing docker multistage builds

- cmd/thanos/store.go
- pkg/cache/tracing_cache.go
- pkg/objstore/client/factory.go
- pkg/objstore/tracing.go
- pkg/store/cache/caching_bucket.go
- pkg/store/cache/caching_bucket_factory.go
- pkg/tracing/tracing.go
This PR adds bucket and cache interactions to the traces.
This PR also fixes bug in Thanos tracing code, which first finished the span and only then called the function with given span.
Tested manually, see screenshot with small part of example trace.
> 2020 05 tracing bucket

- Makefile
Fixes dependency name discrepancies between `.bingo/Variables.mk` and `Makefile`.
* Fixes dependency name discrepancies between `.bingo/Variables.mk` and `Makefile`.
* `make install-deps`
> Makefile: Fix broken Make action dependencies

- pkg/receive/handler.go
We have observed increase in forward error rate, even though no increase in incoming error rates.
This happens because we cancel the request as soon as we reach the quorum.
This PR lets forward requests run for replication until it actually timeouts.
* Cancel request context only an error occurred and let it optimistically run until it timeouts.
cc @brancz @squat
> receive: Let forward requests run until timeout

- CODE_OF_CONDUCT.md
There is nothing wrong with current code of conduct a part from being a bit outdated. So I propose instead of having our own code of conduct, we "import" CNCF and add additional information about enforcement.
I believe it's easier for our users to learn/read one Code of Conduct.
This is similar to what other has done (Prometheus, Cortex).
https://github.com/prometheus/prometheus/blob/master/code-of-conduct.md
https://github.com/cortexproject/cortex/blob/master/code-of-conduct.md
> change code of conduct to CNCF

- cmd/thanos/compact.go
- cmd/thanos/downsample.go
- cmd/thanos/main_test.go
- pkg/compact/compact.go
- pkg/compact/compact_e2e_test.go
- pkg/compact/compact_test.go
- pkg/verifier/overlapped_blocks.go
In Cortex we're experimenting a different grouping logic, in order to be able to concurrently compact blocks belonging to non-overlapping time ranges. So far we've got a good result and we would like to move it upstream.
In order to continue to use the great Thanos `BucketCompactor`, we would need to inject a custom blocks grouping logic.
In this PR I'm proposing to extract the syncer grouping logic into a dedicated component (`Grouper`), moving the syncer `Groups()` logic to a `DefaultGrouper` implementation. Logic and metrics haven't changed (if they did, it's a bug).
/cc @pstibrany 
> Refactoring to extract blocks grouping logic out of syncer

- pkg/store/storepb/rpc.proto
After a brief [discussion on public Slack](https://cloud-native.slack.com/archives/CL25937SP/p1590491672334400) and after a look at the `Series()` implementation, I think we can safely document that response series labels are guaranteed to be sorted by name.
N/A
> Document series labels sorting in SeriesResponse

- pkg/cacheutil/memcached_client.go
- pkg/cacheutil/memcached_client_test.go
* Allow using multiple memcached clients at the same time.
Signed-off-by: Peter Štibraný <peter.stibrany@grafana.com>
* Added unit test to verify that we can have multiple clients.
Signed-off-by: Peter Štibraný <peter.stibrany@grafana.com>
* Added CHANGELOG.md entry.
Signed-off-by: Peter Štibraný <peter.stibrany@grafana.com>
* Remove unused argument.
Signed-off-by: Peter Štibraný <peter.stibrany@grafana.com>
> Allow using multiple memcached clients at the same time. (#2648)

- docs/contributing/onboarding-dev.md
This PR adds a placeholder for writing up a dev-docs from scratch. Some content has been written up here in a [doc](https://docs.google.com/document/d/1hluKPDKsSdOqcCpOnzr7-4PxLnUtrCl5d4-TVGch_D4/edit)
> Add a placeholder for devdocs

- CHANGELOG.md
- go.mod
- go.sum
Upgrade Prometheus to current master which has a couple of fixes related to m-mapping chunks.
> Upgrade Prometheus to master

- pkg/ui/static/js/graph.js
Fixes #2578 
We now use per panel `key` to store the state in `localStorage`. This keeps the states separate and provides a more consistent experience.
Tested locally by inspecting requests and localStorage.
> ui: Fix UI state being shared

- CHANGELOG.md
- pkg/query/iter.go
- pkg/store/bucket.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
- pkg/store/storepb/custom.go
- pkg/store/storepb/custom_test.go
- pkg/store/storepb/rpc.pb.go
- pkg/store/storepb/rpc.proto
Actually do properly the https://github.com/thanos-io/thanos/issues/2546
This is a rebased version of https://github.com/thanos-io/thanos/pull/2603 - It was wrongly merged to chained, already merged PR. + small fix to avoid `.String()`
This also has to be cherry picked to 0.13
> store/proxy: Deduplicate chunks on StoreAPI level. Recommend chunk sorting for StoreAPI + Optimized iter chunk dedup.

- CHANGELOG.md
- pkg/query/iter.go
- pkg/store/bucket.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
- pkg/store/storepb/custom.go
- pkg/store/storepb/custom_test.go
- pkg/store/storepb/rpc.pb.go
- pkg/store/storepb/rpc.proto
Cherry picked: https://github.com/thanos-io/thanos/pull/2710
* Deduplicate chunk dups on proxy StoreAPI level. Recommend chunk sorting for StoreAPI.
Also: Merge same series together on proxy level instead select. This allows better dedup efficiency.
Partially fixes: https://github.com/thanos-io/thanos/issues/2303
Cases like overlapped data from store and sidecar and 1:1 duplicates are optimized as soon as it's possible.
This case was highly visible on GitLab repro data and exists in most of Thanos setup.
* Optimized algorithm to combine series only on start.
* Optimized chunk comparision for overlaps.
* Optimized deduplication …
> store/proxy: Deduplicate chunks on StoreAPI level. Recommend chunk sorting for StoreAPI + Optimized iter chunk dedup. (#2710)

- CHANGELOG.md
- go.mod
- go.sum
This PR is a cherry-pick of #2705, which updates the minio-go dependency to [v6.0.56](https://github.com/minio/minio-go/tree/v6.0.56). This essentially adds two new region endpoints for AWS S3.
Would it be possible for this change to be included in the `0.13.0` release?
We are planning to switch over to the newly added regions in AWS S3, but until the dependency is added, we are stuck using on-prem storage.
> deps: Updated minio-go dependency to v6.0.56 to add two region endpoints

- CHANGELOG.md
- pkg/query/querier.go
See related discussion: https://cloud-native.slack.com/archives/CL25937SP/p1590408991325100
cc @SuperQ 
> (release branch) query: `irate` and `resets` use now counter downsampling aggregations.

- pkg/ui/ui.go
This commit simplifies the SanitizePrefix func to remove an unecessary
call to `strings.HasSuffix`. The `strings.TrimSuffix` func internally
calls `strings.HasSuffix`, so there is an unneeded, extra call.
cc @prmsrswt @GiedriusS
> pkg/ui: simplify SanitizePrefix func

- CHANGELOG.md
- CONTRIBUTING.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
> Moved to allowlist naming; added contributing naming rule about potentially offensive terminology.

- cmd/thanos/receive.go
- docs/components/query.md
- docs/components/receive.md
- docs/components/sidecar.md
- docs/operating/multi-tenancy.md
- scripts/genflagdocs.sh
* Add documentation for `receive` command
* Add documentation for multi-tenancy
* `make docs`
* `make check-docs`
cc @brancz @squat
ref: https://github.com/thanos-io/thanos/issues/1093
> docs: Add receive command docs

- go.mod
Upgrade Prometheus to include the merge adapter bug fix https://github.com/prometheus/prometheus/pull/7369, introduced in Thanos by https://github.com/thanos-io/thanos/pull/2596.
This bug shouldn't affect Thanos (reason why I haven't opened a PR against the `0.13` branch) but it's safer to upgrade the vendored Prometheus. The reason why this bug shouldn't affect Thanos is because `storage.NewMergeSeriesSet()` is only used by the series API, but the resulting `SeriesSet` is iterated sequentially (the bug is triggered when the result of an iteration is retained).
_Existing tests_
> Upgrade Prometheus to fix merge adapter bug

- pkg/compact/compact.go
- test/e2e/compact_test.go
Let's leave the compactDir if a HaltError occurs to aid in debugging
problems. Without this, it is impossible to inspect the state on disk
after a HaltError occurs.
Added a named return for the error in a function. Checked if it is not a halting error before trying to delete `compactDir`.
e2e test improvements that fail without this change.
> compact: do not delete compact dir if halt error occurs

- pkg/block/fetcher_test.go
This WIP PR intends to add benchmarking tests to **Thanos** for the `deduplication filter`.
Currently, I have used some ideas from this PR #2118 
Fixes #2174 
* Added a benchmarking test in `fetcher_test.go`.
Some details of the benchmarking result after I ran them - 
```
goos: linux
goarch: amd64
pkg: github.com/thanos-io/thanos/pkg/block
BenchmarkDeduplicateFilter_Filter/Block-10/#00-4     	   16364	     77193 ns/op	    3544 B/op	      48 allocs/op
BenchmarkDeduplicateFilter_Filter/Block-10/#01-4     	    8421	    155745 ns/op	    9502 B/op	     134 allocs/op
BenchmarkDeduplicateFilter_Filter/Block-100/#00-4    	     126	   8885819 ns/op	   31375 B/op	     356 allocs/op
BenchmarkDeduplicateFilter_Filter/Block-100/#01-4    	      74 …
```
> Added some benchmarking tests for deduplicate filter

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/receive.libsonnet
* Improve readability for `ThanosReceiveHighForwardRequestFailures` while increasing `for` value to prevent flappy alerts.
* Promote `ThanosReceiveNoUpload` to critical while increasing `for` value to prevent flappy alerts.
cc @brancz
> mixin: Improve receive alerts

- pkg/shipper/shipper.go
- pkg/shipper/shipper_test.go
> Minor readability fix for shipper tests.

- test/e2e/compact_test.go
- test/e2e/e2ethanos/helpers.go
- test/e2e/e2ethanos/services.go
- test/e2e/query_test.go
- test/e2e/receive_test.go
- test/e2e/rule_test.go
- test/e2e/rules_api_test.go
- test/e2e/store_gateway_test.go
As it pointed out, https://github.com/thanos-io/thanos/pull/2742#issuecomment-642172122,
cleaning up e2e test files.
Fixes `2587`.
* Introduce a new e2e test helper to clean up the files after scenario is done.
> test/e2e: Make sure clean test files cleaned

- pkg/rules/manager.go
Currently, the original file field is a private field.
This causes it to render in the Thanos Rules UI.
This fixes it by making that field public.
- Exposed original file field in `pkg/rules.Group` struct.
Screenshot before this change shows that Rules are not being rendered:
Additionally the following warn error message is rendered in log files:
```
level=warn ts=2020-06-15T11:05:16.146463886Z caller=ui.go:152 component=rules msg="template expansion failed" err="template: :82:26: executing \"content\" at <.OriginalFile>: can't evaluate field OriginalFile in type rules.Group"
```
Screenshot with this change applied:
/cc @bwplotka @brancz
> pkg/rules/manager: expose original file field in groups

- pkg/cacheutil/memcached_client.go
- pkg/gate/gate.go
- pkg/query/api/v1.go
- pkg/query/api/v1_test.go
- pkg/store/bucket.go
- pkg/store/bucket_test.go
Changes will be useful for https://github.com/thanos-io/thanos/pull/2657 to track gate metrics for queries that has multiple selects.
* Refactor gate to enable to track metrics for multiple gates
* Add an interface that conforms prometheus/gate as well to use interchangeably 
* `make test`
> pkg/gate: Refactor gate to enable to track metrics for multiple gates

- pkg/receive/handler.go
- pkg/store/multitsdb.go
- pkg/store/tsdb.go
```
.
└── "receive_http"
└── "receive_fanout_forward"
├── "receive_replicate"
│   ├── "receive_replicate"
│   ├── "receive_tsdb_write"
│   └── "receive_forward"
├── "receive_tsdb_write"
└── "receive_forward"
```
```
.
└── "receive_grpc"
└── "receive_fanout_forward"
├── "receive_replicate"
│   ├── "receive_replicate"
│   ├── "receive_tsdb_write"
│   └── "receive_forward"
├── "receive_tsdb_write"
└── "receive_forward"
```
```
.
├── "multitsdb_series"
│   └── "multitsdb_tenant_series"
├── "multitsdb_label_names"
└── "multitsdb_label_values"
```
* Add more tracing spans for the life-cycle of a receive request.
* Add tracing spans for storeAPI read path.
* `make build`
> receive: Add more tracing spans for the life-cycle of requests

- CHANGELOG.md
- cmd/thanos/query.go
- docs/components/query.md
- pkg/query/api/v1_test.go
- pkg/query/iter.go
- pkg/query/querier.go
- pkg/query/querier_test.go
- pkg/tracing/tracing.go
Enable Querier to dissect a query into pieces and execute concurrently.
xref: https://github.com/prometheus/prometheus/pull/7251
depends: https://github.com/thanos-io/thanos/pull/2748
* `maka test-local`
> querier: Execute Selects concurrently per query

- examples/dashboards/bucket_replicate.json
- examples/dashboards/compact.json
- examples/dashboards/overview.json
- examples/dashboards/query.json
- examples/dashboards/receive.json
- examples/dashboards/rule.json
- examples/dashboards/sidecar.json
- examples/dashboards/store.json
- mixin/dashboards/defaults.libsonnet
Various tools in the SRE space use UTC as the default to make it
effortless during incidents to not have to calculate between timezones.
The Thanos query UI also defaults to this just like Prometheus.
Changed the default timezone to UTC to follow best practices.
Re-generated the examples and the values changed.
> mixin: Default dashboards to UTC

- pkg/query/api/v1.go
- pkg/ui/react-app/src/App.tsx
- pkg/ui/react-app/src/thanos/pages/errorBoundary/ErrorBoundary.module.css
- pkg/ui/react-app/src/thanos/pages/errorBoundary/ErrorBoundary.tsx
- pkg/ui/react-app/src/thanos/pages/index.tsx
- Add a error boundary to the React UI. Now in case of an irrecoverable error, users would see a "Something went wrong" page instead of a blank screen.
- Fix the crash when there is no store connected to the Querier. The crash was because the API response for `/api/v1/label/__name__/values` was
```json
{
"status": "success",
"data": null
}
```
Here, the UI expects `data` to be an array.
Fixed this by sending an empty array (`[]`) instead of `null`
Tested locally by emulating error conditions.
> ui: Add error boundary in the React UI

- pkg/receive/handler.go
- pkg/server/http/middleware/request_id.go
* Add request-id middleware and use it for remote writes.
* Add tenant context to logs.
* Add missing endpoint to logs.
* `MINIO_ENABLED=1 REMOTE_WRITE_ENABLED=1 ./scripts/quickstart.sh`
> receive: Improve receive error logging

- CHANGELOG.md
- go.mod
Update Prometheus mod to pull in prometheus/prometheus#7414
Passing tests.
> go.mod: Update Prometheus mod to pull in prometheus/prometheus#7414

- CONTRIBUTING.md
- docs/contributing/coding-style-guide.md
- docs/contributing/onboarding-dev.md
Removed all the `table-of-content` links which were created manually as per pull request #2689 
Build successful locally
> Removing manually created TOC in Thanos docs

- docs/proposals/202005_scalable-rule-storage.md
Add proposal for scalable rule storage.
When I started writing this, I actually thought it would be much more intricate, but it still changes the architecture of the rule component pretty significantly in the long term, so I still think it's important to have as a proposal first, and if accepted, then for people to understand the changes that have happened over time in the future.
> proposal: Add scalable rule storage proposal

- CHANGELOG.md
- pkg/store/bucket.go
I'm investigating `BucketStore` memory allocations and I've noticed that, in our context (Cortex), most of the memory is allocated by `readIndexRange()` (see profile below). Investigating it further, I've noticed the use of `ioutil.ReadAll()` which is quite bad when it comes to memory allocations if the length of the reader is known in advance (like this case), so I've tried to optimise it preallocating the buffer with the right size in advance.
My old laptop has quite bad consistent CPU performances, so I wouldn't focus too much on CPU +/- (different benchmark runs showed different results). Moreover, from a CPU perspective, nothing should be worse.
```
benchmark                                                                        old ns/op     new ns/op     delta …
```
> Reduced memory allocations in readIndexRange()

- docs/components/compact.md
Add some verbiage that explains when exactly do the blocks get deleted.
Closes #2782.
> docs: compact: add blurb about how retention policy works

- CHANGELOG.md
- cmd/thanos/compact.go
- docs/components/compact.md
Thanos compact currently does metadata sync every minute if `--wait` is
active. Thanos store has a equivalent flag named `sync-block-duration`.
This commit introduces `--wait-sync-block-duration` to be able to
configure the interval via a flag.
Resolves #2642 
Signed-off-by: Schlotter, Christian <christi.schlotter@gmail.com>
* added flag `--wait-sync-block-duration` to compact command
* used value of flag instead of hardcoded time.Minute
Run it in production
> compact: introduce flag --wait-sync-block-duration

- pkg/store/bucket.go
- pkg/store/bucket_test.go
- pkg/store/postings_codec.go
- pkg/store/postings_codec_test.go
This PR modifies `diffVarintSnappyEncode` method to preallocate output buffer based on number of passed postings. This helps to avoid reallocations.
```
name                      old time/op    new time/op    delta
EncodePostings/10000-4       114µs ± 1%     106µs ± 1%   -6.55%  (p=0.009 n=3+9)
EncodePostings/100000-4     1.11ms ± 1%    1.05ms ± 0%   -5.39%  (p=0.007 n=3+10)
EncodePostings/1000000-4    11.6ms ± 2%    10.7ms ± 0%   -7.21%  (p=0.009 n=3+9)
name                      old alloc/op   new alloc/op   delta
EncodePostings/10000-4      48.5kB ± 0%    13.6kB ± 0%  -71.98%  (p=0.000 n=3+10)
EncodePostings/100000-4      506kB ± 0%     131kB ± 0%  -74.08%  (p=0.000 n=3+10)
EncodePostings/1000000-4    5.86MB ± 0%    1.25MB ± 0%  -78.62%  (p=0.000 n=3+10)
name                      old …
```
> store: Preallocate output buffer when encoding postings.

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/receive.libsonnet
Old query on the left and new query on the right. One can clearly see how the old query is still alerting on the long gone Pods, while we filter those on the right side and the number of NoUpload instances decreases while restarting Pods.
> Improve ThanosReceiveNoUpload to only alert on current instances

- pkg/receive/multitsdb.go
NOTE: Those are minor fixes, this does not fix any issue we see with CPU usage or cut block.
* startTimeMargin and StartTime is used only by Prometheus remote read, Thanos does not use it.
* Fixed following race:
```
=== RUN   TestMultiTSDB/run_on_existing_storage
==================
Read at 0x00c00073ae80 by goroutine 69:
github.com/prometheus/prometheus/tsdb.validateOpts()
/home/bwplotka/Repos/thanosgopath/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200609165731-66dfb951c4ca/tsdb/db.go:510 +0x55
github.com/prometheus/prometheus/tsdb.Open()
/home/bwplotka/Repos/thanosgopath/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200609165731-66dfb951c4ca/tsdb/db.go:502 +0x61
github.com/thanos-io/thanos/pkg/receive.(*MultiTSDB).getOrLoadTenant.func1() …
```
> receive: Fixed small options race; Removed unused StartTime feature.

- CHANGELOG.md
When I submitted the PR https://github.com/thanos-io/thanos/pull/2613 I forgot to mention the config change in the CHANGELOG.
/cc @pstibrany 
N/A
> Added missing CHANGELOG entry for PR 2613

- CHANGELOG.md
- pkg/query/storeset.go
- pkg/query/storeset_test.go
While testing out the new React UI, I have found out that some errors
return empty dicts when marshalled into the JSON format. The response
looks like this:
```
{..., "lastError": {}}
```
And then, obviously, the UI fails to parse that. Add a
`stringifiedError` type with tests which ensures that we always get a
string.
Add a small, new type which ensures that we always get strings in the `lastError` field of `/api/v1/stores`.
Unit tests.
> Query: always return a string in the `lastError` field

- cmd/thanos/receive.go
- pkg/receive/handler_test.go
- pkg/receive/multitsdb.go
- pkg/receive/multitsdb_test.go
Reason: Missing (), probably we need linter for this.
> receive: Added more observability, fixed leaktest, to actually check leaks ):

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/receive.libsonnet
Right now the alert actually fires in wrong conditions.
We select all sum(instances  == 0) which is always 0...
Instead we want to sum(instances) == 0
Thanks for finding this @krasi-georgiev
> Update ThanosReceiveNoUpload to select sum == 0

- .circleci/config.yml
- Makefile
Fix failed crossbuild CI job: https://app.circleci.com/pipelines/github/thanos-io/thanos/2008/workflows/f96cefcb-e91c-4f73-8eca-5c1c20b2ac46/jobs/10115
For context: https://cloud-native.slack.com/archives/CL25937SP/p1593613071221800
> ci: Manually download promu in crossbuild stage

- CHANGELOG.md
It should go under the unreleased section.
> CHANGELOG: move changelog item

- CHANGELOG.md
- pkg/query/api/v1_test.go
- pkg/rules/rulespb/custom.go
- pkg/rules/rulespb/custom_test.go
Currently, alert state is rendered as upper case.
In Prometheus it is lower case.
This fixes it.
Fixes #2830
- the web /apiv1/rules endpoint renders alert states now in lowercase to retain compatibility with the Prometheus API.
- Changed unit tests
- Verified manually in a local setup:
```
$ curl -s localhost:32775/api/v1/rules | jq .
{
"status": "success",
"data": {
"groups": [
{
"name": "example_abort",
"file": "/shared/rules/rules-0.yaml",
"rules": [
{
"state": "inactive",
"name": "TestAlert_AbortOnPartialResponse",
"query": "absent(some_metric)",
"duration": 0,
"labels": {
"replica": "rule1",
"severity": "page"
},
"annotations": {
"summary": "I always complain, but I don't allow partial response in query."
},
"alerts": [], …
```
> Query: Fix rendered JSON state value for rules and alerts should be in lowercase

- pkg/query/storeset.go
- pkg/query/storeset_test.go
Fixes: https://github.com/thanos-io/thanos/issues/2846
Passing nil error to updateStoreStatus causes a panic. This is displayed to the user in the Stores ui when the Store is healthy
Added higher level unit test to catch this, and hopefully clarified existing test.
> Query: correctly marshal errors to JSON and ignore if nil

- .circleci/config.yml
- CONTRIBUTING.md
- Makefile
Added Swift CI tests as suggested in https://github.com/thanos-io/thanos/issues/2829
I'm not sure if it should run for every test? I'm not sure if we are somehow limited in the CircleCI usage.
From time perspective it does not significantly prolong the test stage in CI.
> chore: enable Swift CI tests

- docs/storage.md
Added by https://github.com/thanos-io/thanos/pull/2838.
> docs: note that Swift is tested in CI

- .golangci.yml
- cmd/thanos/config.go
- pkg/objstore/oss/oss.go
- pkg/objstore/swift/swift.go
- pkg/objstore/swift/swift_test.go
- pkg/receive/writer.go
- pkg/store/cache/caching_bucket_test.go
- pkg/store/prometheus.go
- pkg/tracing/jaeger/config_yaml.go
* Enabled  `unparam`, `unused` and `varcheck`
* Applied fixes accordingly
* Added notes for more complicated or critical ones for now
* `make go-lint`
> ci: Enable a set of linters to catch unused code

- CHANGELOG.md
- pkg/store/bucket_test.go
- pkg/store/multitsdb.go
- pkg/store/multitsdb_test.go
- pkg/store/postings_codec_test.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
- pkg/store/storepb/testutil/series.go
- pkg/store/tsdb.go
- pkg/store/tsdb_test.go
Similar to store GW Series but for proxy.
Also: * Fixed minTime for TSDB and Receiver. Now checks head block min Time as well. 
> storetestutil: Added shared series helpers on BucketSeries; added ProxySeries and MultiTSDB Series benchmarks.  

- .golangci.yml
* Remove redundant linters and sort them alphabetically
* `make go-lint`
> ci: Remove redundant linters and sort them alphabetically

- CHANGELOG.md
- pkg/receive/multitsdb.go
- pkg/store/multitsdb.go
- pkg/store/multitsdb_test.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
Fixes: https://github.com/thanos-io/thanos/issues/2823
TestTenantSeriesSetServert_NotLeakingIfNotExhausted was showing leaks:
```
TestTenantSeriesSetServert_NotLeakingIfNotExhausted/cancelled,_not_exhausted_StoreSet: leaktest.go:132: leaktest: timed out checking goroutines
TestTenantSeriesSetServert_NotLeakingIfNotExhausted/cancelled,_not_exhausted_StoreSet: leaktest.go:150: leaktest: leaked goroutine: goroutine 84 [chan send]:
github.com/thanos-io/thanos/pkg/store.(*tenantSeriesSetServer).Send(0xc000708360, 0xc0003104c0, 0x0, 0x0)
/home/bwplotka/Repos/thanos/pkg/store/multitsdb.go:141 +0x13e
github.com/thanos-io/thanos/pkg/store.(*mockedStoreServer).Series(0xc0004e6330, 0xc0007083c0, 0x20ac2c0, 0xc000708360, 0x5116a0, 0x0)
/home/bwplotka/Repos/thanos/pkg/store/multitsdb_test.go:173 +0x76 …
```
> receive: Fixed leak on receive and querier proxying Store API Series, which was leaking on errors.

- CHANGELOG.md
- cmd/thanos/query.go
- pkg/query/api/v1.go
- pkg/ui/query.go
- pkg/ui/react-app/src/pages/status/Status.tsx
- pkg/ui/react-app/src/thanos/Navbar.tsx
- Implement API endpoints `/status/runtimeinfo` and `/api/buildinfo`
- Enable the `Runtime & Build Information` page in react UI
Tested locally using both production and development build.
> ui: react: Add runtime and build info page

- pkg/store/multitsdb_test.go
- pkg/store/prometheus.go
- pkg/store/prometheus_test.go
- pkg/store/tsdb.go
- pkg/store/tsdb_test.go
This is to have a unified chunk size and should reduce the load on queriers.
This also will be much more comparable when a chunk iterator will be done.
See following benchmark results for Receive (multiTSDB):
```
benchstat -delta-test none _dev/bench_outs/0-receiveseries/benchBenchmarkMultiTSDBSeries.out _dev/bench_outs/1-receiveseries/benchBenchmarkMultiTSDBSeries.out
name                                                                                                  old time/op    new time/op    delta
MultiTSDBSeries/1000000SeriesWith1Samples/headOnly/4_TSDBs_with_1_samples,_250000_series_each-12         6.41s ± 0%     6.16s ± 0%   -3.85%
MultiTSDBSeries/1000000SeriesWith1Samples/blocksOnly/4_TSDBs_with_1_samples,_250000_series_each-12       5.77s ± 0%     6.16s ± 0%   +6.61% …
```
> ruler,receive,sidecar: StoreAPI Series encodes chunks to 120 samples instead of single, big one.

- Makefile
- pkg/receive/handler.go
This PR makes the best-effort fan-outs more explicit by detaching the fan-out context requests' context from the incoming request context. 
* Detach the fan-out context requests' context from the incoming request context. Make the best-effort fan-outs more explicit.
* Removed redundant `govet` call, `golangci-lint` already runs it 0f5b22556a7827f4246435a4145e8c311b278cb3
* `make test`
> receive: Detach fanout context from request context

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/rules.yaml
- examples/dashboards/receive.json
- mixin/alerts/receive.libsonnet
- mixin/dashboards/receive.libsonnet
- mixin/rules/query.libsonnet
- mixin/rules/receive.libsonnet
- mixin/rules/store.libsonnet
- pkg/receive/handler.go
- pkg/rules/rules_test.go
This PR adds a new metric to track replication behaviour. Previously, `thanos_receive_forward_requests_total` was used. However, that metric is now misleading because we have recently changed how replication behaves (https://github.com/thanos-io/thanos/pull/2621).
* Add a new metric to track replicated request `thanos_receive_replications_total` https://github.com/thanos-io/thanos/pull/2852/commits/fd0497105ab76fdc2cbcfd0c74f4a642f389ec45
* Add alerts and dashboards for the new metric https://github.com/thanos-io/thanos/pull/2852/commits/0aa495da1bb6e44c56c2653c55e8c4bc70b1e62c
* Modify alerts for the `thanos_forward_requests_total` https://github.com/thanos-io/thanos/pull/2852/commits/0aa495da1bb6e44c56c2653c55e8c4bc70b1e62c
* `make …
> receive: Track replications

- pkg/reloader/reloader.go
- pkg/reloader/reloader_test.go
Fixes: https://github.com/thanos-io/thanos/issues/2622
E.g https://app.circleci.com/pipelines/github/thanos-io/thanos/1545/workflows/851eeb7a-8e4c-4b7e-b7c4-5e63582004a0/jobs/9566/steps
Reason for flakiness: We expected exact number of reloads. It can happen that there were more reloads than asserting go routine was waiting for, which is ok, test was not expecting that.
> reloader: Fixed test flakiness.

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/compact.libsonnet
max is aggregating across series. We need to aggregate something across time as well as series due to rollout.
Alert was flaky on every rollout essentially as last time is 0 in reset case.
> alerts: Fixed compactor alert to use correct aggregation function.

- pkg/query/api/v1_test.go
- pkg/rules/rulespb/custom.go
- pkg/rules/rulespb/custom_test.go
Go's `encoding/json` turns nil slices into `null` instead of `[]`. This
is problematic for consumers expecting that the `alerts` field is a JSON
array. The same is true for empty rule groups.
The solution is to enforce that nil slices are converted to zero-length
slices when encoding.
I've updated the unit tests to cover the issue.
> pkg/rules/rulespb: fix JSON marshaling for nil slices

- CHANGELOG.md
- cmd/thanos/downsample.go
`thanos_compact_downsample_total` metric was not incremented for ResLevel1
> compact: fix increment of thanos_compact_downsample_total counter

- CHANGELOG.md
- cmd/thanos/store.go
- docs/components/store.md
- pkg/store/bucket.go
- pkg/store/bucket_e2e_test.go
- pkg/store/bucket_test.go
- pkg/store/limiter.go
- pkg/store/limiter_test.go
- pkg/store/prometheus.go
- pkg/store/tsdb.go
In this PR I've changed the `--store.grpc.series-sample-limit` implementation to apply the limit to the sum of "samples" fetched across all queried blocks instead of individually apply the limit to each block.
Few notes:
- Internally implemented as a chunks limiter (because that's what we limit on)
- Introduced `ChunksLimiterFactory` to not pass a static limit to `NewBucketStore` because I would like to use it in Cortex too and in Cortex we have dynamic limits (limits can be reloaded live, without restarting the process)
Fixes #2845.
Existing + new unit tests.
> Fixed --store.grpc.series-sample-limit

- pkg/objstore/clientutil/parse.go
- pkg/objstore/clientutil/parse_test.go
- pkg/objstore/cos/cos.go
- pkg/objstore/oss/oss.go
Fixed time format for Last-Modified header when parsing oss/cos attributes.
Signed-off-by: Sabaping <bbq.yuki@outlook.com>
[COS api doc reference](https://intl.cloud.tencent.com/document/product/436/7729)
[OSS api doc reference](https://www.alibabacloud.com/help/doc-detail/31985.htm)
1. `clientutil.ParseLastModified` function accepts optional format parameter
2. `Bucket.Attributes` function, for cos/oss object storage, passes additional `time.RFC1123` when calls `clientutil.ParseLastModified`.
Unit test.
> Fixed time format for Last-Modified header

- CHANGELOG.md
- cmd/thanos/receive.go
- pkg/receive/multitsdb.go
- pkg/server/grpc/grpc.go
- pkg/server/http/http.go
* Add more logs for receive start and shutdown sequence.
* Merge uploader routines (on-demand and recurring).
* Receive now fails if initial upload fails.
* `MINIO_ENABLED=1 REMOTE_WRITE_ENABLED=1 ./scripts/quickstart.sh`
> receive: Overhaul start up sequence

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/downsample.go
- pkg/receive/handler.go
- pkg/replicate/replicator.go
- pkg/store/bucket.go
> compact, receive, store: Init all labeled counter and histogram metrics

- CHANGELOG.md
- cmd/thanos/receive.go
- cmd/thanos/rule.go
- docs/components/receive.md
- docs/components/rule.md
- pkg/receive/multitsdb.go
This PR attempts to prevent any concurrent access to TSDB directories on a single session.
* Lock TSDB dir for Receiver
* Lock TSDB dir for Ruler
* Introduce a flag or a default mode to clean up flags, in case of a dirty shutdown in the next startup.
> receive, rule: Lock TSDB directories 

- go.mod
- pkg/receive/handler.go
This PR will help to reduce unnecessary forward requests and noisy logs while rolling out new versions for Thanos Receive.
*  [x] Change is not relevant to the end-user.
* Implement exponential backoffs for forwarding requests when nodes are unavailable.
* `MINIO_ENABLED=1 REMOTE_WRITE_ENABLED=1 ./scripts/quickstart.sh`
> receive: Forward Request exponential back-off for unavailable nodes

- pkg/store/prometheus.go
Added a http header to the remote_read request.
While Prometheus itself doesn't care about this header, for some third party remote_read compatible api, it is required.
The version match the one made by Prometheus when performing a remote read (see https://github.com/prometheus/prometheus/blob/v2.20.0-rc.1/storage/remote/client.go#L237) .
Manually tested again a third party API (Cortex)
> .*: Add header for remote read version

- CHANGELOG.md
- cmd/thanos/receive.go
Updated code that configures the local endpoint if --receive.local-endpoint is not specified.
Tested on a 3 node cluster in GKE using a StatefulSet deployment. In this case the node upon startup will use local hostname which includes the StatefulSet pod index, e.g: thanos-receive-us-west2-1. The GRPC port is appended and this lines up with the hash ring configuration. All nodes in hash-ring then begin to correctly participate in replication of time series.
> Receive: Fixing auto-configuration of --receive.local-endpoint

- CHANGELOG.md
- pkg/block/fetcher.go
- pkg/block/fetcher_test.go
> Fix ReplicaLabelRemover panic when replicaLabels are not specified

- docs/getting-started.md
Add blog post from Beat which uses Thanos to monitor kubernetes
clusters and AWS resources.
Add blog post from Beat
> docs: Add blog post from Beat

- pkg/rules/manager.go
The following panic can be observed when calling `/api/v1/rules` without
this change when the TZ is _not_ UTC:
```
2020/07/22 21:44:22 http: panic serving 127.0.0.1:49368: merger not found for type:int
goroutine 529 [running]:
net/http.(*conn).serve.func1(0xc00029e640)
/usr/lib/go-1.14/src/net/http/server.go:1772 +0x139
panic(0x1e0a400, 0xc000368c30)
/usr/lib/go-1.14/src/runtime/panic.go:975 +0x3e3
github.com/gogo/protobuf/proto.(*mergeInfo).computeMergeInfo(0xc0008b8780)
/home/gstatkevicius/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_merge.go:662 +0xfc6
github.com/gogo/protobuf/proto.(*mergeInfo).merge(0xc0008b8780, 0xc0007447a0, 0xc00057bb00)
/home/gstatkevicius/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_merge.go:113 +0x4a2 …
```
> rules: manager: avoid panic when cloning when TZ != UTC

- Makefile
Tried to build mixins using `make examples-in-container`
```
>> Compiling and generating thanos-mixin
docker run --rm -u="1000:1000" -v "/home/yeya24/.cache/go-build:/.cache/go-build" -v "/home/yeya24/hub/gowork/thanos:/go/src/github.com/thanos-io/thanos:Z" -w "/go/src/github.com/thanos-io/thanos" -e USER=deadbeef -e GO111MODULE=on quay.io/coreos/jsonnet-ci:release-0.36 make  JB='/go/bin/jb' jsonnet-vendor
(re)installing /go/bin/jb-v0.4.0
flag provided but not defined: -modfile
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [.bingo/Variables.mk:77: /go/bin/jb] Error 2
make: *** [Makefile:301: examples-in-container] Error 2
```
We are using bingo and it requires go 1.14+. So I update the …
> Bump jsonnet-ci container image to latest release with go 1.14

- docs/contributing/coding-style-guide.md
fixed typo in coding-style-guide.md, where string slice is declared using `[]string{}` rather than `[]string`
> Fix typo in coding-style-guide.md

- cmd/thanos/rule.go
- cmd/thanos/sidecar.go
- docs/components/sidecar.md
- pkg/receive/multitsdb.go
- pkg/reloader/reloader.go
- pkg/shipper/shipper.go
- pkg/shipper/shipper_e2e_test.go
- pkg/shipper/shipper_test.go
shipper.NewWithCompacted function is kind of duplicate. This pr removes it and updates shipper.New function.
> Cleanup shipper NewWithCompacted function

- pkg/cache/memcached.go
- pkg/cacheutil/memcached_client.go
- pkg/store/cache/memcached.go
* Change the log level for async buffer full error.
* Add a label to track the occurrence of the error.
cc @pstibrany
> store/memcached: Mitigate bloating logs when async buffer is full

- CHANGELOG.md
- pkg/store/bucket.go
- pkg/store/bucket_test.go
This PR fixes issue with fetching chunks that are bigger than 16000 bytes. Under some circumstances it is possible to come across chunks like that, and under some conditions Thanos may currently fail to fetch such chunks. This PR adds fetching of remaining chunk data from the bucket.
Added unit test. Also tested manually against real block found in our test cluster.
Fixes issue https://github.com/thanos-io/thanos/issues/2945.
> Fetching large chunks

- CHANGELOG.md
- docs/components/query.md
- pkg/api/query/v1.go
- pkg/query/querier.go
- pkg/query/querier_test.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
Solves the api part of #2919
Add a new parameter on the API to pass an allow list of stores.
Only stores matching this list will be able to be used for the query.
WIP: manual testing and partial unit tests
> Query: Allow passing a `storeMatcher[]` to select matching stores when debugging the querier

- CHANGELOG.md
- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
Fixes: #2971
Use same fix like https://github.com/prometheus/prometheus/pull/4941
1. Add a test case in `TestParseTime` and run it.
2. Run `make` via ci.
> Query: Better rounding for incoming query timestamps.

- cmd/thanos/main.go
- scripts/quickstart.sh
Fixes: #2986 
Changes in `quickstart.sh`:
* `MINIO_ENABLED` is disabled by default
* `S3_ENDPOINT` is empty by default and filled in only when minio is enabled, hence [thanos does not run store](https://github.com/thanos-io/thanos/blob/master/scripts/quickstart.sh#L168)
* thanos arguments are parsed correctly (no empty arguments `OBJSTORECFG`, and `STORES`)
* thanos arguments are dumped in console on parse error. **NOTE** please object if you think it might be a security issue - i'll remove it
I didn't add anything to the changelog, since the last ~10 commits to the quickstart.sh are not reflected there.
Verified manually by running `PROMETHEUS_EXECUTABLE=~/go/src/github.com/prometheus/prometheus/prometheus THANOS_EXECUTABLE=~/go/bin/thanos MINIO_ENABLED="" ./scripts/quickstart.sh`.
log …
> Fix quickstart

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/query.go
- cmd/thanos/rule.go
- cmd/thanos/tools_bucket.go
- docs/components/query.md
- docs/components/rule.md
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/blocks/v1.go
- pkg/api/query/v1.go
- pkg/api/rule/v1.go
- pkg/logging/http.go
- pkg/logging/options.go
- pkg/server/http/utils.go
* Initialised a HTTP Middleware to log all details of the request
* Added options for enabling logging and custom level of logging based on http response status code
* Added interface and types for the custom options in the logging middleware
Fixes #2844 
The current logging looks like this - 
```powershell
level=debug name=query-0 ts=2020-07-27T08:55:01.712803436Z caller=http.go:45 protocol=http http.component=server  http.start_time="2020-07-27 14:25:01.712671672 +0530 IST m=+7.688823783" msg="started call"
level=debug name=query-0 ts=2020-07-27T08:55:01.715027845Z caller=proxy.go:295 msg="store Addr: 127.0.0.1:10901 LabelSets: [name:\"prometheus\" value:\"prom-0\" ] Mint: 0 Maxt: 9223372036854775807 queried;store Addr: …
```
> Initial setup for Request Logging in HTTP in the server side

- pkg/promclient/promclient.go
- pkg/promclient/promclient_e2e_test.go
This pr adds a query range API in promclient, which can be used in the query frontend E2E test.
An E2E test is added.
> Add query range API in promclient

- pkg/cacheutil/memcached_client.go
- pkg/cacheutil/memcached_client_test.go
Add more metrics for memcached to benchmark the performance.
* Add an info metric to expose memcached client configuration
* Record expected errors (especially timeout errors) in failure metric
* Change log level to debug since cache writes are best effort and we have a metric for it
* Add a metric to track the size of the values stored in the cache.
> memcached: Add more metrics for memcached client

- CHANGELOG.md
Signed-off-by: Max Neverov <neverov.max@gmail.com>
Deduplicate changelog. Fixes: #2856
I used the following command to find duplicates: 
```
awk '/\[.?[0-9]+\]/ {print $2}' CHANGELOG.md | sort | uniq -d
[#1362](https://github.com/thanos-io/thanos/pull/1362)
[#1770](https://github.com/thanos-io/thanos/pull/1770)
[#1838](https://github.com/thanos-io/thanos/pull/1838)
[#2166](https://github.com/thanos-io/thanos/pull/2166)
[#2526](https://github.com/thanos-io/thanos/pull/2526)
[2603](https://github.com/thanos-io/thanos/pull/2603)
[#2667](https://github.com/thanos-io/thanos/pull/2667)
[#2671](https://github.com/thanos-io/thanos/pull/2671)
[#2705](https://github.com/thanos-io/thanos/pull/2705)
```
Most of these PRs are mentioned both in `Added` and `Changed`, except 2166, 2603, 2705
> Deduplicate changelog

- CHANGELOG.md
- cmd/thanos/config.go
- cmd/thanos/sidecar.go
- docs/components/sidecar.md
- pkg/reloader/example_test.go
- pkg/reloader/reloader.go
- pkg/reloader/reloader_test.go
Fixes: #2873
Log error when applying changes in the prometheus config instead of stopping the sidecar.
Add new metric `reloader_config_errors_total` to reflect config readings errors.
Add new flags `--reloader.retry-interval` and `--reloader.watch-interval` to tweak corresponding configs for the reloader.
**NOTE** 
I found [prometheus.ready_timeout flag](https://github.com/thanos-io/thanos/blob/master/cmd/thanos/config.go#L67) with underscore, which seems to be a typo. Please, let me know if it should be changed to `prometheus.ready-timeout` in this PR (breaking change?).
To verify it manually add the following flags to the [quickstart.sh](https://github.com/thanos-io/thanos/blob/master/scripts/quickstart.sh#L160):
```
--reloader.config-file=data/prom"${i}"/prometheus.yml \ …
```
> Apply error in loop should not kill the sidecar

- Makefile
~~Update the Makefile `test-e2e` target to depend on the `docker-multi-stage` instead of `docker` target. This ensures people running on Mac OS X will be able to run the integration tests easily.~~
I updated the `make docker` command to run as normal if the OS is linux and the Arch is x86_64. Otherwise `make docker` will default to `make docker-multi-stage`. 
Ran `make test-e2e`
**Note**: This does not change the fact that images built using `make docker` will not work on Mac OS X. Also if other Mac users are not experiencing this issue, I would be interested to know if there is something misconfigured with my local environment causing this to fail.
Fixes: #2803
> change: change test-e2e target to depend on docker-multi-stage

- pkg/cacheutil/memcached_client.go
- pkg/objstore/objstore.go
- pkg/store/bucket.go
- pkg/store/bucket_test.go
I would like to expose bucket fetch operation durations to fine-tune caching layer for store.
* Add metrics to expose already collected fetch durations.
* `make build`
> store: Expose bucket index operation duration histogram

- CHANGELOG.md
- cmd/thanos/query.go
- go.mod
- go.sum
- pkg/rules/manager.go
- pkg/rules/manager_test.go
- pkg/store/storepb/testutil/series.go
- pkg/store/tsdb.go
- pkg/store/tsdb_test.go
Finally some first tests of chunk iterator :heart: 
Benchmarks to come.
Depends on: https://github.com/prometheus/prometheus/pull/7069
> receive,ruler: Upgraded TSDB and used ChunkIterator in Series TSDB Store.

- Makefile
- docs/contributing/coding-style-guide.md
- scripts/build-react-app.sh
- scripts/genflagdocs.sh
- scripts/genproto.sh
- scripts/websitepreprocess.sh
Fixes for https://github.com/thanos-io/thanos/pull/2969/files#r464896752
* Fix issue with partial matches
* `make proto`
* `make docs`
* `make web-pre-process`
* `make assets`
> ci: Make sure conditions work for all platforms

- go.mod
- go.sum
- pkg/store/bucket_test.go
xref: https://github.com/prometheus/prometheus/pull/7772
> Updated TSDB to include atomic delete fix.

- pkg/cacheutil/memcached_client.go
A minor left-over of #3019 
* Initialize metric with the new label.
> memcached: Initialize forgotten label for failure metric

- CHANGELOG.md
- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/tests.yaml
- mixin/alerts/sidecar.libsonnet
The alert was giving the wrong information as the $value contained
the number of pods that failing to send heartbeat instead of the actual
number of seconds that each sidecar was being unhealthy.
Also the 5 minute interval is probably too low as on large deployments
prometheus could take much longer to come up online and for sidecar to
become actually useful.
As such, we can simply subtract the timestamp of the last heartbeat from
the current time and fire if we are lagging for more than 10 minutes.
This is also consistent with the current unit tests.
Improve alert for sidecar to provide correct information and not fire too soon
Deployed locally and did a prometheus update and it did not fire anymore
> mixin: Fix alert about unhealthy sidecar

- CHANGELOG.md
- docs/proposals/202003_thanos_rules_federation.md
- pkg/rules/rules.go
- pkg/rules/rules_test.go
- pkg/rules/rulespb/custom.go
Fixes #3017
Currently only the group name is considered for group deduplication.
However prometheus uses also the group file according to [1].
This fixes it.
[1] https://github.com/prometheus/prometheus/blob/ce838ad6fcbd14b0cf9971a4d093ad672e1469fe/rules/manager.go#L1047-L1055
Tests have been modified
> pkg/rules: consider group name and file for deduplication

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/tests.yaml
- mixin/alerts/absent.libsonnet
- mixin/alerts/bucket_replicate.libsonnet
- mixin/alerts/compact.libsonnet
- mixin/alerts/query.libsonnet
- mixin/alerts/receive.libsonnet
- mixin/alerts/rule.libsonnet
- mixin/alerts/sidecar.libsonnet
- mixin/alerts/store.libsonnet
Monitoring mixins guidelines: https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations
* replaced `message` annotation field with `description`
* added simple `summary` field
Running `make examples/alerts/alerts.yaml` and `make example-rules-lint` seems to produce correct results.
/cc @kakkoyun @metalmatze
> mixin: Adhere to monitoring mixins annotation guidelines

- cmd/thanos/query-frontend.go
- docs/components/query-frontend.md
This pr adds instrument middleware to query frontend handler, including logging and tracing.
The tracing middleware is important because we don't have a start span before query range tripperware. So range query starts from step_align span and there are no spans for other queries.
Before
After
Query parameters are also logged in the first span.
Other queries are also working.
> Add instrumentation middlewares to query frontend

- pkg/cacheutil/memcached_client.go
- pkg/cacheutil/memcached_client_test.go
Add two more validations to Memcached client config.
1. If `dns_provider_update_interval` <= 0, it will panic in https://github.com/thanos-io/thanos/blob/master/pkg/cacheutil/memcached_client.go#L525.
2. if `max_async_concurrency` <= 0, `SetAsync` never works.
> Add more validations for memcached client config

- CHANGELOG.md
- docs/components/query.md
The correct usage of setting store matchers is to set `storeMatch[]` param and this pr updates the wrong usage in the doc and changelog.
> Update the usage of storeMatch[] param

- pkg/ui/query.go
Fixes #3043 
When using the UI via `query-frontend` we were getting redirected from `/new/` to `/new/` itself, which causes an infinite loop.
We had a redirect from `/new` to `/new/` (notice the trailing slash) and I suspect this the reason why we are getting this problem. The Query Frontend passes all requests other than `query_range` directly to upstream but I think that it is removing the trailing slash somehow. So when we request `/new/` the query frontend requests `/new` from upstream and get a 302 Redirection from upstream for `/new/` resulting in an infinite loop.
> ui: Fix "too many redirects" when using query frontend

- examples/dashboards/overview.json
- examples/dashboards/rule.json
- mixin/dashboards/rule.libsonnet
In #2398 we added a ThanosNoRuleEvaluations alert which is really helpful and signaling a symptom of unavailability of the Thanos Ruler. Sadly we don't surface these underlying metrics on the Thanos Ruler dashboard.
Add some panel to the Thanos Ruler dashboard.
Deployed the new Thanos Ruler dashboard on Grafana and check against our datasource :)
> Add Rule Group Evaluations to Ruler dashboard in mixin

- CHANGELOG.md
- docs/storage.md
- pkg/objstore/s3/s3.go
- pkg/objstore/s3/s3_test.go
Adds S3 SSE via a `sse_config` block. It's a reimplementation of #2170 since it looks like it was abandoned. It solves #946. 
There are 3 types of SSE you can use: [SSE-S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html), [SSE-KMS](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html), and [SSE-C](https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html).
```
sse_config:
enabled: false
kms_key_id: ""
kms_encryption_context: {}
encryption_key: ""
```
I can verify if this works when I get back to work. We're currently running into 403 errors from not providing a KMS key ID, so when we don't get 403s I'll know it works.
> Adds SSE-KMS and SSE-C config to S3 Objstore

- docs/getting-started.md
- pkg/store/bucket_test.go
- pkg/store/multitsdb.go
- pkg/store/multitsdb_test.go
- pkg/store/proxy_test.go
- pkg/store/storepb/testutil/series.go
- pkg/store/tsdb.go
- pkg/store/tsdb_test.go
- pkg/testutil/testutil.go
Fixed https://github.com/thanos-io/thanos/issues/3013
Also:
* Fixed other quite big issue with reusing chunk slice.
* Fixed framing - previously it was wrongly sending single-chunk frames, taking
huge amount of time.
Fix: We deletage closer now to ensure multitsdb operate on valid data.
> receive/rule: Fixed Segfault issue; Added tests & benchmarks for TSDB Store, fixed multitsdb benchmarks.

- pkg/queryfrontend/cache_splitter.go
- pkg/queryfrontend/cache_splitter_test.go
- pkg/queryfrontend/codec.go
- pkg/queryfrontend/codec_test.go
- pkg/queryfrontend/request.go
- pkg/queryfrontend/roundtrip.go
- pkg/queryfrontend/roundtrip_test.go
1. Handle `max_source_resolution=auto` correctly.
2. Generating cache key based on resolution level instead of time
> Correctly handle auto downsampling in codec

- website/layouts/_default/baseof.html
Made docsearch attribute reflect the version of the page
Works on local
> made docsearch attribute reflect version of page

- CHANGELOG.md
- pkg/rules/manager.go
- pkg/rules/manager_test.go
This bug was already fixed in https://github.com/thanos-io/thanos/pull/2615 but it got lost when we merged https://github.com/thanos-io/thanos/pull/2200.
A unit test has been added.
> Rule: update manager when all rule files are removed

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- pkg/api/blocks/v1.go
- pkg/ui/bucket.go
- pkg/ui/react-app/src/App.tsx
- pkg/ui/react-app/src/thanos/Navbar.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
- pkg/ui/templates/bucket_menu.html
- pkg/ui/ui.go
Fixes #3093
- Modified the Blocks API to serve loaded blocks and global blocks
- Fix Block Viewer not working because of incorrect handling of the external prefix.
Tested locally for Bucket web, Compactor, and Store using docker-compose setup.
> ui: Fix Block Viewer for Compactor and Store

- CHANGELOG.md
- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
This pr makes maxSourceResolution overwritable when auto downsampling is enabled. For more context, please check https://cloud-native.slack.com/archives/CL25937SP/p1598839574028300
> querier: Fix overwriting maxSourceResolution when auto downsampling is enabled

- CHANGELOG.md
- cmd/thanos/query.go
- docs/components/query.md
- pkg/query/iter.go
closes: https://github.com/thanos-io/thanos/issues/3001
Promql has a default 5m look back delta so if the penalty causes the
duration between the samples to be greater than 5m this will show as
gaps in the visualisation and when using the count function returns a
lower number then expected.
For example:
time is in mins
series 1
```
itA  t1 0.1  t3 0.3
itB  t1 0.1  t3 0.3 t4 0.4  t9 0.9
```
`it.penB = 2 * (ta - it.lastT), 2 * (3 - 1) = 4 `
```
merged t1 0.1  t3 0.3  t9 0.9
```
t4 is missing because the it.penB is 4 so it skips it.
When the time between  `t3 0.3`  and  `t9 0.9` is more then 5min(the default look
back) so when visualizing this it shows as gaps in the graph.
~When the penalty is resolution based the seek for itB always advances NO
more then the requested time so doesn’t skip …
> querier: bugfix - data gaps when switching iterators

- pkg/queryfrontend/roundtrip_test.go
Fix #3084 
In the previous test case, I used `counter` to mock HTTP handler and check how many times the handler is being called.
``` go
func counter() (*int, http.Handler) {
count := 0
var lock sync.Mutex
return &count, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
lock.Lock()
defer lock.Unlock()
count++
})
}
```
But this mock handler doesn't return a meaningful result to query frontend so it might cause other requests canceled at the same time, which causes the flaky.  https://github.com/cortexproject/cortex/blob/master/pkg/querier/queryrange/limits.go#L104
So if we return promql response which is valid for query frontend, then the test case should work.
Used the function below to test it works as expected.
``` go
func …
```
> Fix flaky query frontend split interval unit test

- cmd/thanos/sidecar.go
- pkg/reloader/example_test.go
- pkg/reloader/reloader.go
- pkg/reloader/reloader_test.go
The `reloader` package doesn't care whether the watched directories
contain rule files or something else. This change removes the references
to "rule directories" and uses "watched directories" instead.
The motivation is that prometheus-operator use 2 reloaders:
* [prometheus-config-reloader](https://quay.io/repository/prometheus-operator/prometheus-config-reloader) that watches the Prometheus configuration file, it leverages the `github.com/thanos-io/thanos/pkg/reloader` package
* [configmap-reload](https://hub.docker.com/r/jimmidyson/configmap-reload) that watches Prometheus rule files and Alertmanager configuration files, it is a separate project and implements its own logic to detect file changes.
Eventually we may consolidate and have only one reloader instance (presumably …
> pkg/reloader: remove mention of rule directories

- mixin/README.md
Updated documentation to have the correct path for `jb install`
Fixes #3126 
- Updated README to update the mixin install command.
Ran the command `jb install github.com/thanos-io/thanos/mixin@master` and it works
> docs: mixin docs install path

- docs/getting-started.md
Add Query Frontend HTTP port service for single node deployments.
Adds default port for Query Frontend HTTP service for single node deployments.
> Add HTTP port for Query Frontend service

- website/layouts/_default/baseof.html
- website/layouts/index.html
We have some 404s in the links to the contributing docs, e.g.
contributing.md and community.md. This commit fixes those links.
> website/layouts: fix links to contributing docs

- CHANGELOG.md
- pkg/reloader/example_test.go
- pkg/reloader/reloader.go
- pkg/reloader/reloader_test.go
When watching for changes in directories, the reloader used to rely only
on the watch interval and not on the inotify events. This commit implements
a more efficient detection of changes for watched directories.
The change also adds a new `DelayInterval` option that allows to delay
the config reload after no additional event are received.
Finally a new metric,
`thanos_sidecar_reloader_config_apply_operations_total`, is added and
`thanos_sidecar_reloader_config_apply_errors_total` has been renamed
to `thanos_sidecar_reloader_config_apply_operations_failed_total` for
consistency.
I've modified the unit test to validate that the reloader reacts on file changes (without the periodic watch). I've added a unit test to validate that the reloader's periodic watch detects a change in case it …
> pkg/reloader: improve detection of directory changes

- pkg/ui/react-app/src/thanos/Navbar.tsx
Fixes #3160 
Added `key` prop in `UncontrolledDropdown` & `DropdownItem` components of `Navigation` so that React can handle the minimal DOM change.
The warnings shown in #3160 disappeared.
> added key prop in Navigation

- cmd/thanos/query.go
- cmd/thanos/store.go
- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
- pkg/cacheutil/memcached_client.go
- pkg/gate/gate.go
- pkg/query/querier.go
- pkg/query/querier_test.go
- pkg/ui/query.go
The metrics on the gates for concurrent selects were exposed without a prefix (e.g. `gate_queries_in_flight` and `gate_duration_seconds`) unlike the gate metrics for the query API. The first commit 60950ff adds the `thanos_query_concurrent_selects_` prefix.
After more thinking, I felt that exposing the number of in-flight queries doesn't make much sense for concurrent selects because each query creates a new gate. Thus we can have (max number of concurrent selects per query x max number of concurrent queries) selects in flight and it doesn't tell whether a query is blocked on too many selects or not. I've added another commit 
722181c that removes the `thanos_query_concurrent_selects_gate_queries_in_flight` metric.
The following metrics have also been added to record the maximum number of …
> pkg/gate: Prefix gate metrics for selects

- CHANGELOG.md
> CHANGELOG.md: include #3154 changes

- pkg/ui/react-app/src/components/withStatusIndicator.tsx
- pkg/ui/react-app/src/pages/graph/DataTable.test.tsx
- pkg/ui/react-app/src/pages/graph/DataTable.tsx
- pkg/ui/react-app/src/pages/graph/GraphTabContent.test.tsx
- pkg/ui/react-app/src/pages/graph/GraphTabContent.tsx
- pkg/ui/react-app/src/pages/graph/Panel.tsx
- pkg/ui/react-app/src/pages/graph/PanelList.tsx
- pkg/ui/react-app/src/pages/rules/RulesContent.tsx
- pkg/ui/react-app/src/pages/targets/EndpointLink.test.tsx
- pkg/ui/react-app/src/pages/targets/EndpointLink.tsx
- pkg/ui/react-app/src/pages/targets/ScrapePoolList.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
- pkg/ui/react-app/src/thanos/pages/stores/Stores.test.tsx
- pkg/ui/react-app/src/thanos/pages/stores/Stores.tsx
Replaces `reactstrap` Alert Component in the react-app with the UncontrolledAlert. This makes the alerts rendered on the UI dismissable, meaning the alerts now have an 'x' button which can be used to close the alerts.
Fixes #3168 
Thanos `package/ui/react-app`
Replaced the Alert component with UncontrolledAlert component in all the relevant files
Made relevant changes to the affected tests
Ran the `yarn run test` command and all the test suites passed.
@prmsrswt
> React-UI: Replace Alert components with UncontrolledAlert

- CHANGELOG.md
- cmd/thanos/sidecar.go
- pkg/store/prometheus.go
- pkg/store/prometheus_test.go
I've found that when requesting many series (in the order of ten
thousands), the Thanos sidecar spends half of its time computing the
number of received series. To calculate the number of series, it needs
to build a label-based identifier for each chunked series and compare it
with the previous identifier. Eventually this number is only used for
logging and tracing so it doesn't feel like it's worth the penalty.
This change adds an histogram metric,
`thanos_sidecar_prometheus_store_received_frames`, which tracks the number
of frames per request received from the Prometheus remote read API
(buckets: 10, 100, 1000, 10000, 100000). It can be used to evaluate
whether expensive Series requests are performed.
CPU profile before this PR (half of the time is spent in `prompb.(*Label).String`)
CPU …
> *: improve latency when streaming series from Prometheus

- website/layouts/_default/single.html
The correct term is `Table of Contents` in plural. This commit fixes the
title for the TOC.
cc @thisisobate
> website/layour: fix TOC title

- CHANGELOG.md
- pkg/logging/options.go
Fixes #3174
Handled logging for return codes 3xx at Info level. Initially the responses were logged as error
@yashrsharma44 @yeya24 Please let me know if it should be handled in any other way.
> *: Handling query logging for code 3xx

- pkg/ui/react-app/src/pages/alerts/Alerts.tsx
Fixes linter warning about `statsCount` prop being overwritten.
Fixes #3172 
Moved `statsCount` prop after the spread `response.data` object.
Ran `yarn run test` and all the test suites passed
> react-app: Fixes `statsCount` prop being overriten by spread `response.data` object in `src/pages/alerts/Alerts.tsx`

- CHANGELOG.md
- cmd/thanos/config.go
Signed-off-by: Daksh Sagar <daksh.sagar@yahoo.com>
Fix web.prefix-header to use `&wc.prefixHeaderName` instead of `&wc.externalPrefix`
Fixes #3156 
`cmd/thanos/config.go` in `registerFlag` method, make cmd.Flag("web.prefix-header", "...", "...") use the `prefixHeaderName`  field instead of `externalPrefix`
> Compact: Fix web.prefix-header to use &wc.prefixHeaderName

- CHANGELOG.md
- pkg/objstore/objstore.go
Signed-off-by: Jarod Watkins <jarod@42lines.net>
Resolves #3149 
If a request is cancelled or times out we will no longer increment the ops failure counter.
> Store: If request ctx has an error we do not increment opsFailures counter

- pkg/queryfrontend/roundtrip.go
Signed-off-by: Oghenebrume50 <raphlbrume@gmail.com>
Changed the check on the exact matching part for the URL to a match on a specified suffix
I queried the API using this `curl "http://localhost:9093/thanos/api/v1/query_range?query=time()&dedup=true&partial_response=true&start=1600269819.107&end=1600273419.107&step=14&max_source_resolution=0s&_=1600273386626"` and got an okay response. 
I am not exactly sure if this is the correct solution for this but I am open to better clarification
> change from switch case to if else with a check on the url path suffix

- docs/components/query-frontend.md
query-frontend: Add the documentation about the in memory cache config in  `docs/components/query-frontend.md`
Fixes #3189 
Update documentation for the in-memory cache config.
ran `make web-serve` locally
> query-frontend: Update documentation for query-fronted in-memory cache

- CHANGELOG.md
- cmd/thanos/query.go
- cmd/thanos/query_frontend.go
- docs/components/query.md
- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
- pkg/testutil/e2eutil/prometheus.go
WIP
Ref #3119
Fixes #1811 
* Add `query.metadata.default-time-range` flag to specify the default look-back duration for retrieving labels through Labels APIs when time range parameters are not specified.
> querier: Add a flag to limit time range for metadata APIs (Labels and Series)

- pkg/objstore/s3/s3.go
The reason for this change was to provide a bit more control over the transport level of this client. I noticed that the default Minio transport has diverged significantly from this implementation. Instead of exposing more values as HTTPConfigs or introducing changes to the default config, I thought it made more sense to give the package caller extra control over the client.
- Create a `DefaultTransport` function that generates an `*http.Transport` from the Config as it currently exists. This function was made public since it allows a caller to generate a Transport that respects the provided config but then tweak values within the transport.
- Add a `Transport http.Roundtripper` field to the `s3.Config` struct that will replace the default transport if set
I am assuming no unexpected …
> feat: Allow callers to the minio objstore to inject a RoundTripper

- pkg/store/bucket.go
- pkg/store/proxy.go
- pkg/store/proxy_test.go
TSDB block time range is half open, which is [b.meta.MinTime, b.meta.MaxTime). So when checking whether a block time is  overlapped with a time range, we can include the max time case. Added a `overlapsClosedInterval` method for the block which is the same as https://github.com/prometheus/prometheus/blob/b521612042/tsdb/block.go#L615.
> chore: Include half-open block maxtime for labels API

- docs/getting-started.md
- go.mod
Signed-off-by: Max Neverov <neverov.max@gmail.com>
go version update was done in #3022 and `go.mod` file wasn't updated. Tests for reloader were failing when run with go1.14
> Update go version to 1.15 in go.mod

- cmd/thanos/query.go
- cmd/thanos/receive.go
- cmd/thanos/rule.go
- cmd/thanos/sidecar.go
- cmd/thanos/store.go
- pkg/rules/proxy.go
- pkg/server/grpc/grpc.go
- pkg/server/grpc/option.go
- pkg/store/proxy.go
- pkg/store/tsdb.go
This decouples the grpc server package from specific gRPC servers.
Previously there was tight coupling and leaking of specific server
implementations into a "generic" instantiation of an opinionated gRPC
server.
Running e2e tests (through this PR) and (hopefully) everything still works.
> *: Refactor gRPC server registration

- CHANGELOG.md
- pkg/ui/ui.go
- Fix UI not working when using `--web.prefix-header` to set external prefix. Fixes #3226 
This was caused by incorrect handling of the prefix value we got from the header. If the header had `/` as a suffix, we were still adding another `/` as a suffix to it, resulting in `//prefix` which translates to an external network request.
Tested it using a reverse proxy with prefix-stripping and the header `X-Forwarded-Prefix` set.
> ui: Fix assets not loading when `--web.prefix-header` is used

- cmd/thanos/query.go
Signed-off-by: aribalam <arib.alam.iitkgp@gmail.com>
Fixes #3180 
The details of the approach are given in [this comment](https://github.com/thanos-io/thanos/issues/3180#issuecomment-696401479).
Setup: 
```
$ thanos query --http-address=127.0.0.1:9092 --web.route-prefix=thanos --web.external-prefix=thanos
$ thanos query-frontend --http-address=127.0.0.1:9093 --query-frontend.compress-responses --query-frontend.downstream-url=http://127.0.0.1:9092 --query-range.split-interval=24h --query-range.max-retries-per-request=5
```
The following request was made -
```
$ curl -iL --max-redirs 3 http://localhost:9093/thanos
TTP/1.1 302 Found
Content-Length: 36
Content-Type: text/html; charset=utf-8
Date: Mon, 21 Sep 2020 22:04:28 GMT
Location: /thanos/graph
Vary: Accept-Encoding
Vary: Accept-Encoding …
```
> Handling of bare path prefix in Querier

- pkg/ui/react-app/src/thanos/pages/stores/StoreLabels.tsx
- pkg/ui/react-app/src/thanos/pages/stores/__testdata__/testdata.ts
- pkg/ui/react-app/src/thanos/pages/stores/store.ts
- pkg/ui/react-app/yarn.lock
- pkg/ui/templates/stores.html
#2783 modified the `LabelSets` field of struct `StoreStatus` in `/pkg/query/storeset.go`, which broke the `stores.html` template for old UI and it also changed the structure of it's marshaled JSON, which resulted in the crashing of Stores page in new UI as well.
- Update the Stores page in both old UI and new UI to match the modified struct.
All React unit tests passed with the new response. Also tested manually.
> ui: Fix labelSets in Stores page

- cmd/thanos/compact.go
- cmd/thanos/main.go
- cmd/thanos/query.go
- cmd/thanos/receive.go
- cmd/thanos/rule.go
- cmd/thanos/sidecar.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- pkg/extkingpin/flags.go
Extract common flag registrations into package for reuse elsewhere.
It compiles and e2e tests pass.
> cmd/thanos: Extract common flag registrations for reuse

- examples/dashboards/dashboards.md
The file name updated in https://github.com/thanos-io/thanos/pull/2781 and the doc should be updated as well.
Caught by our markdown checker.  https://github.com/thanos-io/thanos/pull/3245/checks?check_run_id=1177044878
> Fix bucket replicate file path in dashboards doc

- pkg/store/bucket.go
I found the description of the new metrics in the bucket store a bit difficult to understand. Does this change help to clarify it in your opinion?
N/A
> Clarify new bucket store metrics

- CHANGELOG.md
- pkg/block/block.go
- pkg/block/index.go
- pkg/block/metadata/meta.go
- pkg/compact/compact.go
- pkg/compact/compact_e2e_test.go
- pkg/compact/downsample/streamed_block_writer.go
- pkg/objstore/objstore.go
- pkg/shipper/shipper.go
- pkg/shipper/shipper_e2e_test.go
- pkg/shipper/shipper_test.go
- pkg/store/bucket.go
- pkg/testutil/e2eutil/prometheus.go
This PR adds `segment_files` field into `meta.json` file (Thanos section), which lists all segment files for a block. This helps to avoid call to storage to get this list. This small optimization helps to reduce amount of LIST operations in clusters with many created blocks.
- Added unit test for shipper, added check in compactor test
- Verified that new code path in `store/bucket.go` is hit by existing tests.
> Segment files

- pkg/server/grpc/grpc.go
This is useful to have the gRPC server to be self describing. This could
for example be used to discover what capabilities a server has.
Add reflection API to grpc server instantiation.
Ran
```
$ grpcurl -plaintext -v 127.0.0.1:10903 list
grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection
thanos.Rules
thanos.Store
```
Against a local querier.
> pkg/server/grpc: Register gRPC replection API

- cmd/thanos/store.go
- docs/components/store.md
> store: Fix typo in Thanos store documentation

- website/layouts/_default/baseof.html
- website/layouts/index.html
Signed-off-by: Marvin Javier <mjavier2k@gmail.com>
fixes issue #3270 
- update maintainers links to /tip/thanos/maintainers.md
- update contributing links to /tip/contributing/contributing.md
- updated links works on live site
> Fix broken links for community and contributing in landing page

- pkg/query/storeset.go
- pkg/query/storeset_test.go
Currently, a rule client for a store reference is only created if a rules spec has been discovered at the time of the discovery of a store spec.
If a rules spec has been discovered after a store reference has been already created, the rules spec is being ignored. The effect is that we sometimes have discovered StoreAPI endpoints without underlying RulesAPI endpoints.
This fixes it.
Fixes #3244
I added a unit test.
cc @bwplotka @kakkoyun @lilic @simonpasquier
> pkg/query: eventually update rules client 

- CONTRIBUTING.md
Signed-off-by: Kartik Ramesh <kartikx2000@gmail.com>
Fixes issue #3283 
* Made changes to `Reporting a Vulnerability Process`, `proposal` and `CLI tools` links in `Contributing.md` to point to the correct files in the Thanos GitHub repo.
I tested the website on localhost and the links now direct to the desired pages.
> Fix broken links on Contributing Page

- CONTRIBUTING.md
Just a minor fix in docs - #thanos-prs was archived in June 2020, so there seems to be no point in leading people there.
Signed-off-by: Vladimir Kononov <krya-kryak@users.noreply.github.com>
> Actualize slack channel for contributors.

- docs/storage.md
Signed-off-by: Ricardo Ribeiro <j.ribeiro.fafe@gmail.com>
Small fix in the docs: add the missing `tools` sub command in the GCS section.
NA
> Docs: Fix thanos tools bucket command in the GCS section (Storage)

- CHANGELOG.md
- pkg/store/labelpb/label.go
Long term fix: https://github.com/thanos-io/thanos/pull/3279
> Quick fix for remote write "leak".

- pkg/shipper/shipper.go
In Cortex we would like to use `thanos.shipper.json` as source of truth to know if a specific block has been shipped to the storage. We found an edge case where `thanos.shipper.json` doesn't actually get updated with the whole list of blocks shipper and this PR should fix it.
Change is not relevant to the end user because doesn't affect Thanos.
N/A
> Fix thanos.shipper.json uploaded blocks

- CHANGELOG.md
- go.mod
- pkg/objstore/azure/helpers.go
Ever since the introduction of the deletion marker, Thanos compact has been filling the logs with Azure blob storage exceptions. As discussed in #2565, the error logging should be handled by Thanos itself, so this patch turns off standard logging from the Azure library.
However, [due to the way logging is set up in the library][1], it will always log errors to syslog, regardless of how `ShouldLog` is configured. As such, and until that can be a configurable behavior, care should be taken to handle that from the syslog side as well.
[1]: https://github.com/Azure/azure-storage-blob-go/blob/48358e1de5110852097ebbc11c53581d64d47300/azblob/zc_policy_request_log.go#L100-L102
Signed-off-by: Pedro Araujo <phcrva@gmail.com>
Disabled exception logging from the Azure Blob storage module
Compiled …
> Disable Azure blob exception logging

- pkg/queryfrontend/config.go
Make sure `dns_provider_update_interval` has a sane default, with `0s` then `query-frontend` won't start. More context at #3324 
Compile and test default config
> queryfrontend: fix invalid values for dns provider interval

- cmd/thanos/main.go
- pkg/logging/logger.go
Extract logger instantiation to the `pkg/logging` package.
Moved code, and still compiles :) 
> cmd/thanos: Extract logger instantiation to pkg/logging

- pkg/store/bucket.go
Using the similar idea of https://github.com/prometheus/prometheus/pull/8050 to only fetch labels for `/api/v1/series` API. Changes:
1. Only sort and dedup labels when there is at least one chunk in the specified time range. If no chunk is valid, then not necessary to sort labels.
2. Series query not load chunks.
> Improve store to not load chunks from obj store for Series API

- CHANGELOG.md
- pkg/objstore/azure/helpers.go
As a follow-up to #3331, this disables Azure exception logging to syslog.
Fixes #2565
Disabled Azure pipeline `ForceLog`.
Ran a build of my branch against an Azure blob storage container and confirmed no further exceptions were being sent to syslog.
> objstore/azure: Disable Azure syslog exception logging

- CHANGELOG.md
- pkg/ui/templates/rules.html
Signed-off-by: Sevag Hanssian <sevagh@protonmail.com>
This applies a similar change as the Prometheus project: https://github.com/prometheus/prometheus/pull/7865
This fixes https://github.com/thanos-io/thanos/issues/3311 - in my existing Thanos setup, without this PR the rule UI (/rules page) doesn't show the rules correctly. I have this change deployed in production currently, working fine.
> Fix Rule UI /rules endpoint bug

- pkg/store/bucket.go
It is not necessary to alloc `s.refs` and `s.chks` when we don't need to load chunks.
> Only alloc labelsets in bucket series entry when it is a Series query

- CHANGELOG.md
- docs/storage.md
- pkg/objstore/s3/s3.go
- pkg/objstore/s3/s3_test.go
Signed-off-by: Sevag Hanssian <sevagh@protonmail.com>
I added an optional config "list_objects_version: string" to the S3 configuration.
I have a bucket in production which requires ListObjectsV1 to work (I need to deploy a custom binary with minio UseV1 set to true). After making this PR, I tested "thanos bucket tools web" with the new config option and it works.
> objstore/s3: Add list_objects_version to S3 config

- pkg/server/grpc/grpc.go
- pkg/server/grpc/option.go
Allow passing arbitrary gRPC server option to server instantiation.
Still compiles :) 
> pkg/server/grpc: Allow passing arbitrary gRPC server options

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/absent.libsonnet
- mixin/alerts/alerts.libsonnet
- pkg/rules/rules_test.go
When someone excludes certain components at the downstream, this prevents generating absent alerts. This PR makes sure that those alerts are generated without any errors.
> mixin: Fix absent alerts

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/bucket_replicate.libsonnet
- mixin/alerts/store.libsonnet
This PR fixes inconsistent alert latency thresholds.
cc @metalmatze
> mixin: Fix p99 latency alerts

- pkg/queryfrontend/roundtrip_test.go
Using the real time (time.Now()) might cause flaky when splitting queries. This pr changes it to use hardcoded time.
> Use hardcoded time in query frontend test, fix flakey

- pkg/store/bucket_test.go
- pkg/store/storepb/testutil/series.go
This pr fixes and extends the benchmark tests in bucket_test.go with skip chunk option so that we can measure the performance with `/api/v1/series` queries.
Did some local benchmarks between current master and https://github.com/thanos-io/thanos/commit/2a7590f69a5ace6014ddcc932788056935f201ba, which is the commit before I introduced https://github.com/thanos-io/thanos/commit/053730c6054517186187b33b36d989069b08ad70.
Results:
```
➜  thanos git:(change-benchseries-skipchunks) ✗ benchcmp old new2 
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                                                                           old ns/op      new ns/op      delta …
```
> Extend bench bucket series with skip chunk test case

- CHANGELOG.md
- cmd/thanos/query_frontend.go
- docs/components/query-frontend.md
- pkg/queryfrontend/config.go
- pkg/queryfrontend/roundtrip.go
> Add a flag to disable step alignment middleware

- scripts/quickstart.sh
Move Thanos Ruler execution a bit earlier, before Thanos Query, so that
we could connect it to Thanos Query using the STORES variable. Also, fix
the recording rule so that it would use a more "universal" metric. On my
machine I couldn't find `http_inprogress_requests` so it didn't work
OOB.
Ran the script and was able to query the result of the recording rule via Thanos Query on http://localhost:10904/ that is connected to Thanos Ruler.
> scripts/quickstart: connect Ruler to Query, fix recording rule

- pkg/ui/react-app/src/pages/graph/ExpressionInput.test.tsx
- pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx
- pkg/ui/react-app/src/pages/graph/Panel.test.tsx
- pkg/ui/react-app/src/pages/graph/Panel.tsx
- pkg/ui/react-app/src/pages/graph/PanelList.tsx
This change adds a toggle to enable or disable the metric autocomplete
functionality. By default it is enabled.
Signed-off-by: Jarod Watkins <jarod@42lines.net>
Added toggle to enable/disable metric autocomplete functionality in the new UI.
Tested locally against production data.
> UI: Add toggle to enable/disable metric autocomplete

- CHANGELOG.md
- examples/dashboards/bucket-replicate.json
- mixin/dashboards/bucket-replicate.libsonnet
- pkg/replicate/scheme.go
In the previous implementation, we are iterating the origin bucket, and each time, we use metaFetcher to fetch all meta files. But this seems not necessary, we can just fetch meta files once at the beginning.
> Refactor replicate execution method to not iterate the origin bucket

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- pkg/block/block.go
- pkg/replicate/replicator.go
- pkg/replicate/scheme.go
- pkg/replicate/scheme_test.go
This will allow time based replication.
Its blocked by #2906 
* Added TimePartitionMetaFilter for thanos replication, this means that replicate can now be time based.
> REPLICATOR: Add TimePartitionMetaFilter to thanos replicate.

- pkg/store/bucket.go
This idea behind this pr is to check the chunk time range when decoding the series from the index. This change can benefit a lot the `skipChunk` queries because it can immediately return if it finds a valid chunk instead of decoding all the chunks in this series. 
Verification
Uses the benchmarks from https://github.com/thanos-io/thanos/pull/3366. Benchmark and compare between this pr and current master.
1. `SkipChunk` query. 
It is expected that this type of query should be much faster than before.
```
➜  thanos git:(improve-index-valid) ✗ benchcmp old new9
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                                                                           old …
```
> Check bucket series time range when decoding chunks from index

- pkg/block/block.go
- pkg/block/block_test.go
- pkg/block/fetcher.go
- pkg/block/index.go
- pkg/block/metadata/meta.go
- pkg/compact/compact.go
- pkg/compact/downsample/streamed_block_writer.go
- pkg/replicate/scheme_test.go
- pkg/shipper/shipper.go
- pkg/shipper/shipper_e2e_test.go
- pkg/shipper/shipper_test.go
- pkg/store/bucket_e2e_test.go
- pkg/testutil/e2eutil/prometheus.go
Not necessarily required, but it would be nice to have to reduce Attr API calls and have it for debugging purposes.
cc @pstibrany as I marked one meta.json field as Deprecated (although not plan to remove it yet)
> meta.json: Added meta.Thanos.Files section to meta.JSON; Added version

- CHANGELOG.md
- pkg/ui/react-app/src/pages/graph/ExpressionInput.test.tsx
- pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx
- pkg/ui/react-app/src/pages/graph/Panel.tsx
Bringing in changes suggested by Prometheus developers to keep in sync.
Also updated CHANGELOG.
Signed-off-by: Jarod Watkins <jarod@42lines.net>
> Querier UI: Updating enable/disable metric automcomplete with upstream

- pkg/api/query/v1.go
To be consistent with Prometheus API. If no label names found, return an empty array instead of nothing.
> Fix empty label names response

- CHANGELOG.md
- cmd/thanos/query_frontend.go
Set CORS to the query frontend component in order to be able
to freely access it from Grafana's living elsewhere.
Signed-off-by: Markos Chandras <markos@chandras.me>
Set `Access-Control-Allow-Origin` Header to Query Frontend
- `make test-e2e-local`
- Tested also with local grafana connected to a local Thanos frontend using our internal Thanos querier and everything worked fine. No CORS errors anymore.
> Query Frontend: Set CORS header

- pkg/queryfrontend/queryrange_codec.go
- pkg/queryfrontend/queryrange_codec_test.go
query-frontend: make POST-request to downstream url for query-range to avoid HTTP 414 request-URI too large
> query-frontend: make POST-request to downstream url for query-range

- docs/components/query-frontend.md
- docs/getting-started.md
- Fix broken helm chart link and query frontend invalid argument
Manually verified the doc fixes.
> Docs: Fix broken helm chart link and query frontend invalid argument

- CHANGELOG.md
- cmd/thanos/compact.go
- pkg/block/block.go
- pkg/block/block_test.go
- pkg/block/metadata/markers.go
- pkg/compact/planner.go
- pkg/compact/planner_test.go
- test/e2e/compact_test.go
- test/e2e/query_test.go
- test/e2e/rule_test.go
- test/e2e/rules_api_test.go
Chained with https://github.com/thanos-io/thanos/pull/3409
Fixes: https://github.com/thanos-io/thanos/issues/1424
> compact: Added index size limiting planner detecting output index size over 64GB.

- cmd/thanos/main.go
- pkg/logging/logger.go
After https://github.com/thanos-io/thanos/pull/3424, and re-reading all the surrounding code, I feel like this makes more sense, and we don't have to fiddle with the log caller if it were to ever change in go-kit, since we can use the default correctly now (again).
> *: Cleanup and simplify logging instantiation

- CHANGELOG.md
- cmd/thanos/query_frontend.go
- cmd/thanos/query_frontend_test.go
- docs/components/query-frontend.md
Signed-off-by: Neil Fordyce <neilfordyce@skyscanner.net>
1. Add `query-frontend.org-id-header` flag to specify HTTP header(s) to populate slow query log org_id field: Fixes #3177 
Executed query-frontend pointed at a local querier with this configuration
`thanos query-frontend --http-address=127.0.0.1:9093 --query-frontend.downstream-url=http://localhost:9090 --query-frontend.log-queries-longer-than="-1s" --query-frontend.org-id-header="x-grafana-user" --query-frontend.org-id-header="x-scope-orgid"`
Ran query with expected headers
```
curl --request GET \
--url 'http://localhost:9093/api/v1/query_range?query=up&dedup=true&partial_response=true&start=1594422000&end=1594508400&step=600&max_source_resolution=0s' \
--header 'x-grafana-user: grafana-username'
```
grafana-username shows in …
> query-frontend: Extract org id from from request headers

- cmd/thanos/query_frontend.go
- go.mod
- go.sum
- pkg/queryfrontend/config.go
- pkg/queryfrontend/roundtrip.go
We recently refactored the query-frontend in Cortex, in order to introduce the support for a new component (query-scheduler used by query-frontend v2). The "old" query-frontend logic (v1) has been left untouched, a part from some package refactoring. Also the v1 doesn't handle the downstream, slow query logging and response compression anymore, but they're available as pluggable middlewares.
In this PR I've upgraded Cortex and done the required changes 🤞 
_Note: this upgrade has the nice side effect that Thanos will not vendor anymore Cortex `pkg/storegateway`, thus unblocking the PR #3431._
> Upgrade Cortex into Thanos

- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- pkg/block/block.go
- pkg/block/block_test.go
- pkg/block/metadata/markers.go
- pkg/compact/compact.go
- pkg/compact/retention.go
- pkg/component/component.go
- pkg/verifier/safe_delete.go
- scripts/genflagdocs.sh
- test/e2e/compact_test.go
> tools: Added thanos bucket tool mark

- pkg/store/bucket.go
- pkg/store/bucket_test.go
The PR #3367 introduced a bug causing partial query results. The problem is: in `decodeSeriesWithReq()`, when the condition `if maxt < req.MinTime` is met, the chunk reference `ref0` is not read from the index (and `t0` not updated) and this breaks the decoding of subsequent chunks.
Unit and manual tests.
> Fix partial query results

- CHANGELOG.md
- CONTRIBUTING.md
- cmd/thanos/compact.go
- cmd/thanos/query.go
- cmd/thanos/rule.go
- docs/components/tools.md
- docs/operating/reverse-proxy.md
- docs/quick-tutorial.md
- docs/service-discovery.md
- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/rules.yaml
- examples/dashboards/query.json
- mixin/alerts/compact.libsonnet
- mixin/alerts/query.libsonnet
- mixin/alerts/rule.libsonnet
- mixin/dashboards/query.libsonnet
- mixin/rules/query.libsonnet
- pkg/api/query/v1.go
- pkg/compact/compact_e2e_test.go
- test/e2e/compact_test.go
- test/e2e/rule_test.go
:warning: This is a breaking change
Rename metrics not following the components naming convention:
- `thanos_compact_*` (from `thanos_compactor_*`)
- `thanos_rule_*` (from `thanos_ruler_*`)
- `thanos_query_*` (from `thanos_querier_*`)
Also match the naming convention in the documentation and code comments
https://thanos.io/tip/contributing/contributing.md/#components-naming
Has yet to be tested.
I feel like removing the metrics directly before any deprecation cycle has been done is a bit harsh. But before working on duplicating the two metrics, I'd like to have your opinion on this.
> *: match naming convention in metrics and documentation

- CHANGELOG.md
- cmd/thanos/store.go
- docs/components/store.md
- pkg/block/indexheader/binary_reader.go
- pkg/block/indexheader/header.go
- pkg/block/indexheader/header_test.go
- pkg/block/indexheader/lazy_binary_reader.go
- pkg/block/indexheader/lazy_binary_reader_test.go
- pkg/block/indexheader/reader_pool.go
- pkg/block/indexheader/reader_pool_test.go
- pkg/store/bucket.go
- pkg/store/bucket_e2e_test.go
- pkg/store/bucket_test.go
As discussed during the Thanos community meeting, I would like to propose to add support for lazy mmaping of index-headers in the store-gateway with the ability to automatically unload them after X time of inactivity. This PR aims to do it.
**Draft** because:
- CHANGELOG is missing
Unit tests.
> Store-gateway: add support to lazy mmap index-headers

- cmd/thanos/tools_bucket.go
- pkg/block/index.go
- pkg/compact/compact.go
- pkg/verifier/duplicated_compaction.go
- pkg/verifier/index_issue.go
- pkg/verifier/overlapped_blocks.go
- pkg/verifier/safe_delete.go
- pkg/verifier/verify.go
Was playing around a couple of statistics of real block indexes and this is crazy!
For example one customer's block from our production at Red Hat has following stats:
```
ts=2020-10-30T16:05:15.969081066Z caller=level.go:63 level=debug verifiers=index_known_issues verifier=index_known_issues stats="{TotalSeries:8377876 OutOfOrderSeries:0 OutOfOrderChunks:0 DuplicatedChunks:0 OutsideChunks:0 CompleteOutsideChunks:0 Issue347OutsideChunks:0 OutOfOrderLabels:0 SeriesMinLifeDuration:0s SeriesAvgLifeDuration:13h7m1.399s SeriesMaxLifeDuration:311h50m40.379s SeriesMinLifeDurationWithoutSingleSampleSeries:14.91s SeriesAvgLifeDurationWithoutSingleSampleSeries:13h46m22.193s SeriesMaxLifeDurationWithoutSingleSampleSeries:311h50m40.379s SeriesMinChunks:1 SeriesAvgChunks:8 SeriesMaxChunks:165 …
```
> verify: Added extra statistics for block index; Printable on debug; Interesting results

- docs/design.md
- "scaled up" -> "scaled out"
- "as approximately as" -> "approximately as"
> fix(docs): Fix two typos in design.md

- cmd/thanos/receive.go
- cmd/thanos/sidecar.go
- pkg/block/block.go
- pkg/block/fetcher.go
- pkg/block/index.go
- pkg/block/indexheader/header_test.go
- pkg/block/metadata/meta.go
- pkg/block/metadata/meta_test.go
- pkg/compact/compact.go
- pkg/compact/compact_e2e_test.go
- pkg/compact/downsample/downsample_test.go
- pkg/compact/planner_test.go
- pkg/shipper/shipper.go
- pkg/store/bucket_e2e_test.go
- pkg/testutil/e2eutil/prometheus.go
```
caller=fetcher.go:700 msg="block has no labels left, creating one" replica=deduped
panic: assignment to entry in nil map
goroutine 441 [running]:
github.com/thanos-io/thanos/pkg/block.(*ReplicaLabelRemover).Modify(0xc000b19d70, 0x2b261e0, 0xc000c16d00, 0xc0008596e0, 0xc000b1a980, 0x0, 0x0)
/remote-source/app/pkg/block/fetcher.go:701 +0x3cf
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch(0xc000d75d40, 0x2b261e0, 0xc000c16d00, 0xc000c16a40, 0xc000c16a00, 0x4, 0x4, 0xc000b0e590, 0x1, 0x1, ...)
/remote-source/app/pkg/block/fetcher.go:441 +0x65d
github.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch(0xc0002fe480, 0x2b261e0, 0xc000c16d00, 0x5528a0, 0xc000c16340, 0xc0005c6000, 0x8)
/remote-source/app/pkg/block/fetcher.go:474 +0x9f …
```
> metadata: Fixed panic when no ext labels are set; Added more tests.

- docs/components/compact.md
Updates docs about compactor's default behaviour of running to completion.
> docs compactor: add information about default run to completion

- pkg/block/metadata/meta.go
A recent refactoring in the compactor made log messages hard to read because the planned blocks are logged as pointers. This should PR fix it.
Before:
```
compaction available and planned; downloading blocks" plan="[0xc001820d20 0xc0028afb30 0xc0018cbef0 0xc00152e960 0xc001940f00 0xc001940a50 0xc0028af770 0xc00152e5a0 0xc002b2e1e0 0xc001735d10 0xc002b2e000 0xc0028af590 0xc001735b30 0xc0018cb1d0 0xc001735950 0xc0019405a0 0xc001940c30 0xc00152e3c0 0xc001940870 0xc0018caff0 0xc00152e1e0 0xc0028af2c0 0xc0017354a0 0xc0017352c0 0xc001e2fef0 0xc001e2f860 0xc0018cae10 0xc001735770 0xc001e2f680]
```
After (different set of blocks in the example log):
```
compaction available and planned; downloading blocks" plan="[01EGQB46JTK4AWAV0Y5J4RA871 (min time: 1598277600000, max time: 1598284800000) …
```
> Fixed compactor logs

- docs/release-process.md
This commit adds entries for the next two releases to the release
process schedule as well as updates the entries for the previous
releases to match the dates on which they were ultimately released.
> docs: update release schedule

- CHANGELOG.md
- cmd/thanos/main.go
Related: https://github.com/thanos-io/thanos/issues/3497
> *: Set debug.SetPanicOnFault(true) so we can recover seg faults. [for v0.17.1]

- CHANGELOG.md
- Makefile
- cmd/thanos/compact.go
- cmd/thanos/main.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- pkg/block/fetcher.go
- pkg/block/fetcher_test.go
- pkg/block/index.go
- pkg/block/metadata/meta.go
- pkg/block/metadata/meta_test.go
- pkg/block/writer.go
- pkg/compactv2/changelog.go
- pkg/compactv2/chunk_series_set.go
- pkg/compactv2/compactor.go
- pkg/compactv2/compactor_test.go
- pkg/compactv2/modifiers.go
- pkg/component/component.go
- pkg/objstore/filesystem/filesystem.go
- pkg/store/bucket_test.go
- scripts/genflagdocs.sh
Added rewrite tool:
```bash
thanos tools bucket rewrite --no-dry-run \
--id 01DN3SK96XDAEKRB1AN30AAW6E \
--objstore.config "
type: FILESYSTEM
config:
directory: <local dir>
" \
--rewrite.to-delete-config "
- matchers: \"{__name__!~\\\".*total\\\"}\"
" 
```
Not that inefficient as for first iteration. Deleting ALL gauges from 2w 8.3mln series block while gathering changelog file took ~1m30s
Head of changelog for prod block I used:
```
Deleted {To="1007c280a27d8401", __name__="alerts", _id="f10e61fd-069c-49eb-8ed9-b1633c6259de", alertname="etcdMemberCommunicationSlow", alertstate="firing", endpoint="etcd-metrics", instance="10.35.145.22:9979", job="etcd", namespace="openshift-etcd", pod="etcd-member-control-plane-1", prometheus="openshift-monitoring/k8s", …
```
> tools: Added thanos bucket tool rewrite (e.g allowing block series deletions).

- cmd/thanos/compact.go
- cmd/thanos/downsample.go
- cmd/thanos/main_test.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- pkg/block/fetcher.go
- pkg/block/fetcher_test.go
- pkg/compact/compact_e2e_test.go
In Cortex we're currently testing a cluster with 6K tenants. Among the things we've discovered, we've noticed synching metas is slower than we would have expected. Further digging into it, looks like a significant % of time is spent by `IgnoreDeletionMarkFilter.Filter()` and the reason is that there's no parallelisation compared to the metas loading.
In this PR I would like to propose to introduce a concurrency to `IgnoreDeletionMarkFilter` too, set to the same value of the meta syncer concurrency.
I've run a test and below you can see the average meta sync time per tenant: on the left this PR code, on the right `master`. Obviously this is a non issue for a low volume of tenants and/or blocks, but becomes significative when you've to sync hundred of thousands of blocks.
Unit tests.
> Add concurrency to IgnoreDeletionMarkFilter

- CHANGELOG.md
- docs/components/tools.md
- pkg/objstore/s3/s3.go
Thanos currently only supports V2 signatures when the credentials are statically specified in its configuration. This change supports using signature V2 on other credential sources, too.
The object storage appliance is not fully compatible with S3V4 signatures and we are able to run it statically configured with V2. 
As we need to roll over the used accessKey/secretKey regularly we would like to be able to configure it via the `&credentials.IAM{}` chain.
> s3: Respect SignatureV2 flag for all credential providers

- pkg/block/metadata/meta.go
- pkg/block/metadata/meta_test.go
In Cortex we have the need to parse `meta.json` from a `io.Reader`. Since Thanos already has a function for that, can we expose it, instead of duplicating it?
N/A
> Expose metadata.Read()

- cmd/thanos/query.go
While the context is passed to DNS resolver, no timeout is ever set,
which leaves us in an unpredictable state, as we wait for the resolution
indefinitely. Every interval we repeat the DNS resolution, but don't ever
cancel previous attempts even if they have not finished.
Signed-off-by: Lili Cosic <cosiclili@gmail.com>
- Adds timeout DNS resolution with refresh interval
While the context is passed to DNS resolver, no timeout is ever set,
which leaves us in an unpredictable state, as we wait for the resolution
indefinitely. Every interval we repeat the DNS resolution, but don't ever
cancel previous attempts even if they have not finished. 
Note as per https://github.com/thanos-io/thanos/pull/3508#issuecomment-734316160 this only applies to the default DNS resolver.
> cmd/thanos/query.go: Timeout DNS resolution with refresh interval

- pkg/ui/react-app/yarn.lock
This commit bumps the version of a transitive dependency to resolve a
dependabot alert for a potential UI vulnerability.
> pkg/ui: upgrade dependency to resolve alert

- cmd/thanos/query.go
c21337e5 introduced a subtle bug: when the DNS resolution context
expires, all subsequent resolutions will fail with 'operation was
canceled' because the function overwrites the global context instead of
creating child context. To make it more obvious, we use different
variable names for the parent and child contexts.
Here is a minimal reproducer:
https://play.golang.org/p/Gw9B1cU3mtL
> cmd/thanos: fix DNS resolution when ctx is canceled

- CHANGELOG.md
- pkg/queryfrontend/split_by_interval.go
Verified same way bug report #3526 was tested. When passing start/end with the same value, results are now returned.
```
❯ http --follow "http://localhost:19090/api/v1/query_range?query=up&start=$(gdate +%s)&end=$(gdate +%s)&step=120" | jq '.data.result | length'
14
❯ http --follow "http://localhost:19090/api/v1/query_range?query=up&start=$(gdate --date='5 minutes ago' +%s)&end=$(gdate +%s)&step=120" | jq '.data.result | length'
14
```
> query-frontend: inclusive results when start/end are the same

- pkg/queryfrontend/labels_codec.go
- pkg/queryfrontend/queryrange_codec.go
- pkg/store/labelpb/label.go
- pkg/store/labelpb/label_test.go
Fixes #3515 
The bug is originated from that I got the label pair length using `Size()` method, it is a stupid mistake :-1:  because it doesn't return the number of label pairs.
Added one test case to ensure no panic for comparing the same label sets.
However, we deduplicate the series before sorting them so the case shouldn't happen. Still investigating the root cause and trying to reproduce this from the query frontend side.
> fix index out of bound bug when comparing ZLabelSets

- pkg/store/bucket.go
**Key rationales: The majority of query latency comes from symbols.Lookup.**
Also cleaned up the code.
Baseline:
```
/tmp/___BenchmarkTelemeterRealData_Series_in_github_com_thanos_io_thanos_pkg_store -test.v -test.bench ^\QBenchmarkTelemeterRealData_Series\E$ -test.run ^$ -test.benchtime=1m -test.benchmem
goos: linux
goarch: amd64
pkg: github.com/thanos-io/thanos/pkg/store
BenchmarkTelemeterRealData_Series
Built index header; Starting
BenchmarkTelemeterRealData_Series/alerts2w/01DN3SK96XDAEKRB1AN30AAW6E
BenchmarkTelemeterRealData_Series/alerts2w/01DN3SK96XDAEKRB1AN30AAW6E-12         	      43	1866550478 ns/op	395648807 B/op	 4348808 allocs/op
BenchmarkTelemeterRealData_Series/alerts15s/01DN3SK96XDAEKRB1AN30AAW6E
BenchmarkTelemeterRealData_Series/alerts15s/01DN3SK96XDAEKRB1AN30AAW6E-12 …
```
> store: Optimized common cases for time selecting smaller amount of series. Avoid looking up symbols.

- .circleci/config.yml
Add CircleCI orb for Go, use go mod download caching.
Signed-off-by: Ben Kochie <superq@gmail.com>
> Add CircleCI Go orb

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/absent.libsonnet
- mixin/alerts/bucket_replicate.libsonnet
- mixin/alerts/compact.libsonnet
- mixin/alerts/query.libsonnet
- mixin/alerts/receive.libsonnet
- mixin/alerts/rule.libsonnet
- mixin/alerts/sidecar.libsonnet
- mixin/alerts/store.libsonnet
- pkg/rules/rules_test.go
Removed `.rules` suffix from alert groups in thanos mixin. This is similar to how node_exporter handles alert groups.
Run `make examples` and look at output.
Fixes #3347
/cc @kakkoyun
> mixin/alerts: remove .rules suffix from alert groups

- CHANGELOG.md
- cmd/thanos/compact.go
- test/e2e/compact_test.go
Do not clean up blocks on boot because in some very bad cases there could
be thousands of blocks ready-to-be deleted and doing that makes Thanos
Compact exceed `initialDelaySeconds` on k8s.
* Removed cleanup on boot; added another metric which shows how many loops were performed. Used that metric in tests.
Updated e2e tests that pass.
Fixes #3395.
> compact: do not cleanup blocks on boot

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/main.go
- cmd/thanos/query_frontend.go
- docs/operating/cross-cluster-tls-communication.md
- pkg/queryfrontend/labels_codec.go
- pkg/queryfrontend/labels_codec_test.go
- pkg/queryfrontend/queryrange_codec.go
- pkg/store/labelpb/label.go
- pkg/store/labelpb/label_test.go
- test/e2e/compact_test.go
- test/e2e/query_frontend_test.go
- test/e2e/query_test.go
- tutorials/katacoda/thanos/1-globalview/courseBase.sh
- tutorials/katacoda/thanos/1-globalview/step2.md
- tutorials/katacoda/thanos/1-globalview/step3.md
- tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
- tutorials/katacoda/thanos/7-multi-tenancy/step1.md
- tutorials/katacoda/thanos/7-multi-tenancy/step2.md
Merge `release-0.17` back into `master`.
Please let me know if I rebased things correctly @yeya24 @GiedriusS.
> Merge release-0.17 branch back

- CHANGELOG.md
- docs/storage.md
- go.mod
- go.sum
- pkg/objstore/swift/swift.go
- pkg/objstore/swift/swift_test.go
- scripts/cfggen/main.go
Resolves #2678 
Closes #2665 
As described in the issue, switch to new library to communicate with swift which supports large file types.
I also changed the maintainer of the swift integration to me since if this would be accepted, there would be not much of the old codebase left so it felt fair not to leave the burden on @sudhi-vm.
It supports also working with the large objects which was limit of the previous library.
- switched to new library for Swift API
- added support for large files (description in docs)
- added timeouts for Swift API 
All tests are passing, tried running it as a sidecar, compactor and store for now on real workload.
Works well but will continue testing it with higher load and  bigger blocks. 
Eventually would like to migrate production on it.
> objstore/swift: use ncw/swift and support large files for OpenStack Swift

- CHANGELOG.md
- cmd/thanos/query_frontend.go
Instead of using the cache config from the query-range.
Fixed a bug in which the cache config from the query frontend's query range cache was passed to the label cache. This made it impossible to use a label cache on its own, because invalid empty yaml (from the query range cache) would be passed to the label cache config builder.
Any users who are attempting to use separate label and query range caches today should find that the query range one is being used for both. If this is merged and upgraded to, it will cause the label cache to become used instead.
I've only done some very basic testing, by running the thanos binary locally and verifying whether the different config combinations cause an error on startup with or without this fix.
The error I see from master is:
``` …
```
> query-frontend: Allow separate label cache

- pkg/block/indexheader/binary_reader.go
- pkg/store/bucket.go
Apply the same improvement as the upstream Prometheus pr https://github.com/prometheus/prometheus/pull/8265.
The benchmark result is great comparing to the current master.
```
name                                                             old time/op    new time/op    delta
TelemeterRealData_Series/alerts2w/01EPXBGA0413QZMTF4XQ0M4Q3E        16.7s ± 0%     11.8s ± 0%  -29.31%
TelemeterRealData_Series/alerts15s/01EPXBGA0413QZMTF4XQ0M4Q3E       3.95s ± 0%     3.93s ± 0%   -0.53%
TelemeterRealData_Series/subssyncs2w/01EPXBGA0413QZMTF4XQ0M4Q3E     2.44s ± 0%     1.18s ± 0%  -51.63%
TelemeterRealData_Series/subs2w/01EPXBGA0413QZMTF4XQ0M4Q3E          14.3s ± 0%      6.3s ± 0%  -56.04%
TelemeterRealData_Series/subs15s/01EPXBGA0413QZMTF4XQ0M4Q3E …
```
> Use direct cache in index reader for symbol values

- Dockerfile
- Dockerfile.multi-stage
- Makefile
- cmd/thanos/rule.go
- pkg/promclient/promclient.go
- pkg/receive/multitsdb.go
- pkg/rules/prometheus.go
- pkg/store/bucket.go
- pkg/store/bucket_test.go
- pkg/store/labelpb/label.go
- pkg/store/labelpb/label_test.go
- pkg/store/prometheus.go
- pkg/store/proxy.go
- pkg/store/storepb/prompb/types.pb.go
- pkg/store/storepb/prompb/types.proto
- pkg/store/tsdb.go
```
name                old time/op    new time/op    delta
InjectExtLabels-12    2.16µs ± 4%    0.85µs ± 0%  -60.77%
name                old alloc/op   new alloc/op   delta
InjectExtLabels-12      736B ± 0%      704B ± 0%   -4.35%
name                old allocs/op  new allocs/op  delta
InjectExtLabels-12      2.00 ± 0%      1.00 ± 0%  -50.00%
```
Overall store benchmarks are not great, something is wrong.
```
benchstat -delta-test=none _dev/bench/store_symb_dbefore.txt _dev/bench/store_symb_d.txt
name                                                                old time/op    new time/op    delta
TelemeterRealData_Series/alerts2w/01DN3SK96XDAEKRB1AN30AAW6E-12        841ms ± 0%    1414ms ± 0%  +68.19%
TelemeterRealData_Series/alerts15s/01DN3SK96XDAEKRB1AN30AAW6E-12       284ms ± 0% …
```
> storegw: Optimized inject label stage of index lookup.

- pkg/store/bucket.go
This is a speculative change that came up when reading the code
while trying to install the pool. We should also move the check
before potentially allocating anything.
Signed-off-by: Holger Hans Peter Freyther <holger@freyther.de>
It seems there is an error path that doesn't return the byte slice into the pool. This could lead to a pool being considered full and all Queries failing.
TODO
> bucket: Fix unbalanced chunkPool get/put

- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
- pkg/promclient/promclient.go
- pkg/store/prometheus.go
- test/e2e/query_frontend_test.go
- test/e2e/query_test.go
Fixes #3351 
Add `match[]` param for LabelNames and LabelValues queries.
Now this is implemented via the `Series` matching. We can do matchers push down to improve this later.
TODO: query frontend also needs `matchers` type for Label names and label values query. Will add them in the next pr.
Add unit tests and E2E tests for this feature.
> Support label matchers in labels API

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- mixin/alerts/sidecar.libsonnet
- pkg/rules/rules_test.go
Metric was removed on PR 2002 accidentally. fix #3005 
- reintroduce alert `thanos_objstore_bucket_operation_failures_total` which was deleted by mistake
tested with make example-rules-lint
> mixin: Reintroduce thanos_objstore_bucket_operation_failures_total alert

- pkg/receive/handler.go
- pkg/receive/handler_test.go
The Receiver has a couple of similar error modes that could be originated from different resources (i.e local tsdb, forward requests for other peers in the ring), this PR attempts to unify how errors are returned from those paths and how the errors handled, especially for the nested errors, in order to provide consistent fail mode behaviour and make the code easier to follow.
One other reason was, for some cases because of the wrapped errors, it was wrongly categorising the root cause of the errors, this PR also attempts to fix it.
* Unify error handling paths for fan-out forward requests.
> receive: Unify error handling

- pkg/discovery/dns/provider.go
fixes #3187
Amended the comment.
Verified from the official docs which states that it returns error for non-SRV prefix, when a port is not supplied.
While for SRV prefixes there is no need to specify a port, as the one from the SRV query results will be used.
> comment amendment in dns/provider.go

- CHANGELOG.md
- pkg/block/block.go
- pkg/block/block_test.go
Under certain conditions, when upload of `meta.json` file fails, it will actually appear on the bucket eventually. S3 has been observed to behave like this when it reports 503 "SlowDown" error. Currently `block.Upload` calls `cleanUp` to delete partially uploaded block, but if `meta.json` can still appear in the bucket later, this actually creates invalid block – with `meta.json` file only, but no index or chunks.
This PR removes call to `cleanUp` if only `meta.json` upload fails. If `meta.json` has really failed, this will result into partial block (without `meta.json`) and be eventually removed by other components, or upload will be retried by Shipper. But at least it won't generate corrupted blocks.
For more details, see discussion at …
> Blocks upload: Don't do cleanUp when meta.json fails to upload.

- scripts/quickstart.sh
Add an external label for Thanos Rule akin to Thanos Receive:
```
--label 'receive="true"' \
```
In the same fashion, let's add `rule=true`. This enables uploading
blocks for Thanos Rule as Thanos blocks must have at least one external
label.
`./scripts/quickstart.sh` works as expected
> scripts/quickstart: add external label for Thanos Rule

- pkg/block/block.go
- pkg/replicate/scheme.go
Fixes #3470. 
`bytes.Reader` type is not supported when guessing the file size.
> Use bytes.Buffer to detect file size when uploading files

- CHANGELOG.md
- cmd/thanos/receive.go
- docs/components/receive.md
- pkg/extflag/pathorcontent.go
- pkg/receive/config.go
- pkg/receive/hashring.go
- scripts/cfggen/main.go
- scripts/quickstart.sh
- test/e2e/e2ethanos/services.go
- test/e2e/receive_test.go
Fixes #3026.
* Added `--receive.hashrings` alternative to `receive.hashrings-file` flag (lower priority). Content of JSON file that contains the hashring configuration.
> receive: Add ability to consume contents of the hashrings file directly

- docs/proposals/deletions_object_storage.md
Design proposal for delete series #1598
> Proposal: Delete series for object storage

- CHANGELOG.md
- pkg/discovery/dns/godns/resolver.go
- pkg/discovery/dns/miekgdns/lookup.go
- pkg/discovery/dns/miekgdns/resolver.go
- pkg/discovery/dns/provider.go
- pkg/discovery/dns/resolver.go
- pkg/discovery/dns/resolver_test.go
The rule will crash due to alert managers restart, same with https://github.com/thanos-io/thanos/pull/3257 but I use `dnssrv+`/`dnssrvnoa+`.
Maybe we should make [this line](https://github.com/thanos-io/thanos/blob/3908812e60d1baabf0ba38cd8bf6edf78206d7ab/cmd/thanos/rule.go#L803) fault-tolerant rather than make changes in [pkg/discovery/dns](https://github.com/thanos-io/thanos/tree/master/pkg/discovery/dns).
> rule: prevent rule crash from no such host error

- CHANGELOG.md
- examples/dashboards/compact.json
- mixin/dashboards/compact.libsonnet
This PR adds a new row to the Thanos Compact Dashboard. This row contains:
- The rate at which blocks are deleted from S3: This is useful as it avoids reading logs or manually querying the metric. In 0.15, the deletion is done after downsampling so it allows us to monitor whether it is actually called or not. In 0.16, this process is done concurrently thanks to #3115 . This graph then allows us to monitor if the async context is doing its job.
- The error rate when trying to delete from S3
- The rate at which blocks are marked for deletion, not only from GC but also from retention policy
Our compactor isn't deleting anything at the moment so the graphs are empty.
**Notes**
Metrics will need to be renamed following #3309 as they use the `thanos_compact_*` format.
> mixin: Add block deletion panels for compactor dashboard

- CHANGELOG.md
This small commit fixes the changelog entry for release v0.16.0 so that
the section title includes a link to the actual release.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com
> CHANGELOG.md: add v0.16.0 link

- pkg/block/block.go
- pkg/block/block_test.go
In Cortex, we have an extra protection to delete partial blocks only when the `deletion-mark.json` exists (reason is that we don't expect any partial block unless an issue). However, if the block deletion fails, we may end up in a situation where `meta.json` as been deleted (correct), `deletion-mark.json` deleted but few other files still left in the bucket (eg. `index`).
In this PR I'm proposing to delete `deletion-mark.json` at last. The only downside is that we're adding an extra `HEAD object` call to check for existence, but I'm planning to improve in a follow up PR (I would like to propose to change objstore clients `Delete()` contract to be idempotent, but that's a separate discussion https://github.com/thanos-io/thanos/issues/3662).
Unit tests.
> Delete deletion-mark.json at last when deleting a block

- tutorials/katacoda/thanos/2-lts/step1.md
- tutorials/katacoda/thanos/2-lts/step3.md
Fixed two broken links in the 2-lts tutorial for katacoda, one in step 1 when opening the graph and another in step 3 when opening the New UI.
I pushed to my own katacoda environment and manually checked the links.
> tutorials: fixed some broken links in the lts tutorial

- CHANGELOG.md
- pkg/block/indexheader/binary_reader.go
- pkg/block/indexheader/header_test.go
The symbols cache introduced in https://github.com/thanos-io/thanos/pull/3557 also introduced a subtle race condition, because `LookupSymbol()` may be called concurrently.
In this PR I'm proposing to introduce a lock. With a lock it's obviously slower, but benchmarks show it may not be much significative compared to not having a cache at all (it's late, maybe I'm missing something, so be critic on this please).
```
benchmark                                                    old ns/op     new ns/op     delta
BenchmarkBinaryReader_LookupSymbol/num_series_=_1024-12      3288          13786         +319.28%
BenchmarkBinaryReader_LookupSymbol/num_series_=_10240-12     1850285       1996616       +7.91%
benchmark                                                    old allocs     new allocs …
```
> Fix race condition in BinaryReader.LookupSymbol()

- CHANGELOG.md
- pkg/ui/static/js/bucket.js
Make the old bucket viewer UI work with vanilla Prometheus blocks by
checking whether the `Thanos` part exists before formatting the HTML.
Only changing the old UI here to solicit responses on whether we should
change the API not to return the `thanos` key if it does not exist. IMHO
we should keep it as is and add checks as in this PR.
Screenshot:
Built Thanos and ran it with the `FILESYSTEM` bucket on a local Prometheus directory.
> ui: make old bucket viewer UI work with vanilla blocks

- cmd/thanos/query_frontend.go
- docs/components/query-frontend.md
this is a minor PR fix I just fund out when doing some exploratory usage of thanos.
The text is copied from upstream documentation, feel free to suggest changes if you think it could be improved. :sake: 
- add more text description for the command
```
query-frontend [<flags>]
query frontend
```
```
query-frontend [<flags>]
query frontend command implements a service that can be put in front of Thanos Queriers to improve the read path. It is based on the Cortex Query Frontend component so you can find some common features like Splitting and Results
Caching. Query Frontend is fully stateless and horizontally scalable.
```
> Query-frontend: use detailed text description for cmd

- cmd/thanos/query_frontend.go
- go.mod
- go.sum
- pkg/objstore/swift/swift.go
Today we upgraded Thanos in Cortex, so in this PR I'm upgrading Cortex in Thanos and removing the `swift.SwiftConfig` which is no more required (because we moved to `swift.Config` in Cortex too).
> Upgrade Cortex and remove SwiftConfig

- docs/storage.md
- pkg/objstore/s3/s3.go
The http.Transport is not auto-tuning and one size does not seem to fit
all cases. In order to respond to a query a store gateway might need to
fetch a large (thousands) of postings, series and chunks.
While the number of idle connections has been increased recently it can
still be too low or expose bursty (opening, closing) behavior. Allow to
tune most of the http.Transport parameters. I considered embedding the
full Transport but there is already a Transport member.
Signed-off-by: Holger Hans Peter Freyther <holger@freyther.de>
I manually started thanos store and used fmt.Printf to see the options, e.g. that MaxIdleConns's default is taken.
> store: Make more S3 http.Transport settings configurable.

- docs/components/store.md
- docs/design.md
- docs/operating/troubleshooting.md
- docs/storage.md
Fixes https://github.com/thanos-io/thanos/issues/3627
- Update store.md
- Update design.md
- Update storage.md
- Update troubleshooting.md
> added definiton of chunk and referenced it in the docs

- CHANGELOG.md
- pkg/rules/proxy.go
- pkg/rules/proxy_test.go
Currently, if we receive an error from the underlying client stream,
we continue with trying to receive additional data.
This causes a hotloop as we will receive the same error again.
This fixes it by returning in the error case and adds a unit test for the proxy logic.
Fixes #3717
> pkg/rules/proxy: fix hotlooping when receiving client errors

- CHANGELOG.md
This commit fixes the order of the changelog to properly reflect a
recent change.
cc @thanos-io/thanos-maintainers @s-urbaniak
> CHANGELOG.md: fix changelog to incorporate new fix

- docs/proposals/210701_endpoint_discovery.md
Add the proposal for unified endpoint discovery as per discussion in https://github.com/thanos-io/thanos/issues/2600.
I highlighted two options, but again up to the maintainers which one you choose, happy to work on any of the ones that we agree! 🎉 
I was not sure what to put under work plan and there was no fixed format for proposals that I could find, might have missed it? I copied from some existing ones if there is anything missing let me know! 🙂
> api: Added Proposal for Discovery Endpoint idea (InfoAPI)

- cmd/thanos/compact.go
- cmd/thanos/downsample.go
- cmd/thanos/main_test.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- docs/components/compact.md
- docs/components/store.md
- pkg/block/fetcher.go
Signed-off-by: Johannes Frey <johannes.frey@daimler.com>
This PR makes the meta fetcher concurrency configurable for the end user by introducing a corresponding flag for `compact` and `store`. Furthermore it moves the fetcherConcurrency const close to the fetcher code of the block package.
The reason for this PR is to have a way to control how many goroutines are started in parallel to fetch meta data from object storage. Especially with S3 this leads to many parallel HEAD requests which might provoke rate-limiting. This mostly affects `store` as there currently happens an initial sync which does not use memcached.
Furthermore, it seems that the flag `block-sync-concurrency` of `compact` is passed but not used in the `Syncer`. So I'm actually not sure where this value should be used or if …
> Introduce "block-meta-fetch-concurrency" flag for compact and store

- CHANGELOG.md
- cmd/thanos/query_frontend.go
- docs/components/query-frontend.md
- pkg/queryfrontend/config.go
- pkg/queryfrontend/downsampled.go
- pkg/queryfrontend/roundtrip.go
Signed-off-by: Vladimir Kononov <krya-kryak@users.noreply.github.com>
- [#2641](https://github.com/thanos-io/thanos/issues/2641) Query Frontend: Added `--query-range.request-downsampled` flag enabling additional queries for downsampled data in case of empty or incomplete response to range request.
This is needed to zoom into past, where raw and/or 5m datapoints could be lacking due to retention policies.
Q: Why query-frontend instead of query?
A: Query currently has no concept of modifying queries, while query-frontend does. Secondly, at the moment query seems to have no cortex dependencies, and cortex's matrix merger is a convenient thing.
Here are screenshots for the same queries made against the very same underlying thanos-query. Please excuse the quality. For those struggling to make …
> Add `--query-range.request-downsampled` flag to Query Frontend (#2641)

- Makefile
> Pinned to newer busybox on quay.

- CHANGELOG.md
- pkg/block/indexheader/lazy_binary_reader.go
- pkg/block/indexheader/lazy_binary_reader_test.go
- pkg/block/indexheader/reader_pool.go
The `LazyBinaryReader` can be unloaded at any time. When it gets unloaded, the values returned by its functions (eg. `LabelValues()`) are no more valid because they're yolo strings whose underlying buffer is released (and file unmmaped) on `unload()`.
I would guess this not to be a real issue assuming a long enough idle timeout. For example, if the idle timeout is 20 minutes, the values returned by the `LazyBinaryReader` needs to be around for 20 minutes before it panics, which is currently not the case.
However, the combination of `ReaderPool` and `LazyBinaryReader` doesn't guarantee that `unload()` is always executed on idle readers. It may happen that a reader which is idle gets returned by `ReaderPool.getIdleReaders()` and gets used right before calling `LazyBinaryReader.unload()`, …
> Fix panic on concurrent index-header lazy reader usage and unload

- pkg/compact/compact.go
The planner doesn't work anymore on directories, but just on metas. Because of this, I've updated the comment.
N/A
> Fixed Planner.Plan() description

- CHANGELOG.md
- pkg/block/indexheader/lazy_binary_reader.go
- pkg/block/indexheader/lazy_binary_reader_test.go
We've found a panic that may occur when the index-header lazy loading is enabled. The panic happens because of an edge case happening between when the `load()` releases the write lock and re-acquires the read lock. We've been able to sistematically reproduce it with a unit test and this PR should fix it.
Unit test.
> Fixed panic on concurrent index-header lazy load / unload

- CHANGELOG.md
- pkg/compact/planner.go
- pkg/compact/planner_test.go
Pad the index size check in the compaction planner by 15% to avoid
situations where the sum of index bytes bloats to be larger than the
sum of the original index sizes.
* https://github.com/thanos-io/thanos/issues/3724
* https://github.com/thanos-io/thanos/issues/3750
Signed-off-by: Ben Kochie <superq@gmail.com>
> Pad compaction planner size check

- pkg/server/http/http.go
- pkg/server/http/option.go
This allows to pass a specific mux from the outside that the internal server is added on top of.
Nothing really changes.
> pkg/server/http: Allow passing http.ServeMux with a server option

- docs/components/query.md
Signed-off-by: Junyoung, Sung <junyoung.sung@navercorp.com>
Fix typo in query component documentation.
Previous page is not found because it is relative path for docs
> Fix typo in query component documentation for store api link

- test/e2e/query_test.go
Signed-off-by: Abhishek357 <abhisheksinghchauhan357@gmail.com>
Fixes: #3412
Tests are retried using the Retry function in runutil which executes the function(which makes it flaky) every interval until timeout or no error is returned.
Tested Locally
> e2e: Resolved Flaky tests

- CHANGELOG.md
- docs/components/store.md
- go.mod
- go.sum
- pkg/cache/inmemory.go
- pkg/cache/inmemory_test.go
- pkg/cache/memcached_test.go
- pkg/store/cache/caching_bucket_factory.go
- pkg/store/cache/inmemory_test.go
For #5 (Add in-memory bucket caching) in #3408 
Wrote a new test case.
> in memory cache for caching bucket

- CHANGELOG.md
- cmd/thanos/receive.go
- docs/components/receive.md
This change enables the "allow-overlapping-blocks" flag to be passed down to the TSDB on the Thanos Receive component. 
This overlap can occur where there is a backlog of metrics waiting to be pushed to Thanos and a compaction event happens. The Receiver TSDB will write out the WAL to a TSDB block and start a new block. If the first metric has a time that is earlier than the end of the previous block, these blocks will overlap and cause issues when the next compaction event happens. 
By adding and enabling this flag it allows the receive component to vertically compact these blocks and deal with the overlap. 
This is related to: https://github.com/prometheus/prometheus/issues/8055 
I built the image and observed vertical compaction happening on the receivers when the overlap issue …
> Introduce "allow overlapping blocks" flag for Thanos receiver

- CHANGELOG.md
- pkg/store/bucket.go
- pkg/store/bucket_test.go
We're running the Cortex blocks storage at an increasingly large scale. We're currently investigating how to reduce the memory utilisation in the store-gateway and a low hanging fruit I've noticed is that `bucketBlock.readChunkRange()` waste memory allocations to grow the buffer if the requested length is larger than the largest bucket in the chunk pool (which is 32MB):
The reason is that to ensure that `io.Copy()` doesn't grow the buffer, the buffer needs to be at least `bytes.MinRead` larger than the actual size to write.
This PR fixes it.
I've also added a benchmark, comparing it with `master`:
```
benchmark                                  old ns/op     new ns/op     delta
BenchmarkBucketBlock_readChunkRange-12     89789         70651         -21.31%
benchmark …
```
> Reduce memory allocations in bucketBlock.readChunkRange()

- pkg/objstore/s3/s3.go
- pkg/objstore/s3/s3_test.go
In this PR I'm proposing to introduce a context key to allow downstream projects (Cortex in this case) to inject custom SSE config on a per-request basis.
Fixes #3781.
Unit test.
> Allow to customise S3 SSE on a per-request basis

- cmd/thanos/store.go
- pkg/pool/pool.go
- pkg/store/bucket.go
- pkg/store/bucket_e2e_test.go
- pkg/store/bucket_test.go
In Cortex we have 1 bucket store for each tenant. Given the chunks bytes pool is created in the `NewBucketStore()` we're currently inefficiently reusing byte slices across different tenants.
In this PR I'm doing a little refactoring to pass `pool.BytesPool` to `store.NewBucketStore()` so that we can re-use it across different tenants.
> Refactoring: allow to pass BytesPool to store.NewBucketStore()

- pkg/store/bucket.go
- pkg/store/bucket_e2e_test.go
- pkg/store/bucket_test.go
In https://github.com/thanos-io/thanos/pull/3802 I've exposed `Partitioner` to let Cortex trying to experiment with a different algorithm (in case we find anything interesting we'll upstream it to Thanos then). But `part` is still unexposed, which makes impossible to customise it.
N/A
> Allow downstream projects to customise the Partitioner

- Makefile
Sometimes `make assets` command does not regenerate static assets of react app, so those changes are not reflected during testing the ui.
`shell find` seems to solve this issue.
> Fix command to find react source files

- pkg/reloader/reloader_test.go
This is a fix of the `TestReloader_DirectoriesApply` test's
flakiness. I have been able to spot the problem locally after
introducing a few more tests on the metric values.
I have noticed that sometimes I'd get different `inotify` events.
For example here are two different runs:
```
"/tmp/TestReloader_DirectoriesApply249640168/001/rule2.yaml": CREATE
"/tmp/TestReloader_DirectoriesApply249640168/001/rule2.yaml": WRITE
"/tmp/TestReloader_DirectoriesApply249640168/001/rule1.yaml": WRITE
"/tmp/TestReloader_DirectoriesApply249640168/001/rule1.yaml": WRITE
"/tmp/TestReloader_DirectoriesApply249640168/001/rule3.yaml": CREATE
"/tmp/TestReloader_DirectoriesApply249640168/001/rule3.yaml": CREATE
"/tmp/TestReloader_DirectoriesApply249640168/001/rule-dir/rule4.yaml": WRITE …
```
> reloader: fix test's flakiness

- pkg/ui/react-app/src/App.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/SourceView.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/block.ts
- pkg/ui/react-app/src/thanos/pages/blocks/helpers.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/helpers.ts
Fixes #3709 
Now each block is clickable/selectable. 
Unit tests added.
> Block Viewer: Move overlapping blocks to separate rows

- .github/stale.yml
This PR adds an exempt label to stalebot to ignore the issue with active PRs. 
To mark the issue that has an active PR, maintainers should add a specific label: [`state: someone-working-on-it`](https://github.com/thanos-io/thanos/labels/state%3A%20someone-working-on-it)
The idea triggered in https://github.com/thanos-io/thanos/issues/3456
What do you think?
> stalebot: Add an exempt label to ignore issue that has a PR

- CHANGELOG.md
- Makefile
- cmd/thanos/query.go
- docs/components/query.md
- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
- pkg/ui/react-app/src/pages/flags/Flags.tsx
- pkg/ui/react-app/src/pages/graph/Panel.tsx
- pkg/ui/react-app/src/pages/graph/PanelList.tsx
- pkg/ui/static/js/graph.js
Fixes : #3651 
This PR Adds a new flag `query.default-step` which allows to set step for range queries. This cli flag will be overwritten when step is provided in request parameter.
> Api: Add flag to set default step

- CHANGELOG.md
- pkg/receive/handler.go
If an empty write request is passed into `fanoutForward`, no messages will be sent on the error channel (`ec`) causing the return value to be an empty/default initialised `MultiError`. The error is translated into an "internal server error" at the http handler.
This patch checks that the incoming time series contains data and if not returns immediately.
As to why newer prometheus versions have this behaviour, I'm not currently sure. I believe this will help with #3772.
We've been running this in our staging environment for a week or so and we no longer see the internal error message being logged and in its place the info message instead.
> Receive: Improve handling of empty time series from clients

- pkg/promclient/promclient.go
Use the provided `method` in the error messages. I got scared reading
the logs that the requests are still being sent using GET instead of
POST which I had specified.
Fixed error messages to use the actual passed HTTP method.
Still builds.
> promclient: fix error's message

- CHANGELOG.md
- go.mod
- go.sum
- pkg/objstore/gcs/gcs.go
- pkg/objstore/gcs/gcs_test.go
- pkg/objstore/s3/s3_test.go
From time to time we hear issues which looks be caused by a truncated response got from S3 or S3-compatible backends. An example is https://github.com/thanos-io/thanos/issues/2805.
I've added a unit test to S3 and GCS to check how the client behaves if the HTTP response body contains less data than the size reported in the `Content-Length`. Surprise surprise... GCS client returns `io.ErrUnexpectedEOF` while S3 client (Minio) returns no error.
I know this is not something we should fix in Thanos (I guess should be fixed in Minio) but this test should prove it.
I've tried to upgrade Minio to `7.0.8` (latest minor available) and the behaviour doesn't change. I've opened a [Minio issue](https://github.com/minio/minio-go/issues/1451) to hear some feedback from maintainers.
Unit test.
> Truncated S3 "get object" response is reported as error

- pkg/objstore/cos/cos.go
- pkg/objstore/gcs/gcs.go
- pkg/objstore/inmem.go
- pkg/objstore/oss/oss.go
- pkg/objstore/swift/swift.go
- pkg/store/bucket_e2e_test.go
https://app.circleci.com/pipelines/github/thanos-io/thanos/5120/workflows/efd2a21d-13b7-4035-99e3-cb1af8023694/jobs/13809
This fail is only visible for anyone from Thanos Team proposing PR, due
to extra tests against bucket providers.
Bug: https://github.com/thanos-io/thanos/pull/3823/files#r583476067
> Fixed TestBucketStore_ManyParts_e2e

- pkg/block/fetcher.go
- pkg/compact/compact.go
- pkg/compact/compact_test.go
- pkg/errutil/multierror.go
- pkg/receive/handler.go
- pkg/receive/handler_test.go
Previous multi-error implementation could cause very ugly bug of returnig empty multi-error
that should be treated as success not error by API, but if .Err() is not invoked it will be
used as non nil error.
Once we merge this, we can do cleaner solution that slighly change nesting behaviour: https://github.com/thanos-io/thanos/pull/3833
There were 9 places where we had this bug in handler due to MultiError lib allowing to do so.
> Reinforcing errutil and fixed ugly bug which caused empty []error to be treated as error

- pkg/block/fetcher.go
- pkg/block/fetcher_test.go
In Cortex we're experimenting with a [per-tenant bucket index](https://cortexmetrics.io/docs/proposals/blocks-storage-bucket-index/) which is a single json indexing blocks and deletion marks, so that queriers and store-gateway only need to periodically fetch the bucket index to discover new/deleted blocks instead of running "list objects" operations. If turns out to work well, it's a pattern we may consider backporting to Thanos too.
To implement it in the Cortex store-gateway, we're writing our own custom `MetadataFetcher` (working with the bucket index instead of scanning the bucket). Would be nice to expose the same metrics in the custom implementation too, so I'm wondering what's the sentiment to export `FetcherMetrics`, so that it could be reused by Cortex too.
N/A
> Export metadata fetcher metrics

- pkg/api/query/v1.go
- pkg/block/fetcher.go
- pkg/pool/pool.go
- pkg/pool/pool_test.go
- pkg/query/query_test.go
- pkg/query/test.go
- pkg/store/bucket.go
- pkg/store/bucket_e2e_test.go
- pkg/store/bucket_test.go
- test/e2e/e2ethanos/services.go
> store: Cleaned up API for test/benchmark purposes.

- pkg/block/fetcher.go
In the PR #3660 I've exported `FetcherMetrics` to be reusable by Cortex. That PR was opened back in Dec and in the meanwhile our usage has slightly changed. In this PR I'm proposing two changes:
1. Expose `Submit()` and `ResetTx()` (this was a mistake in the original PR)
2. Allow to inject extra init labels for the transaction metrics (this is something that has changed in the meanwhile)
N/A
> Allow Cortex to fully reuse FetcherMetrics

- cmd/thanos/downsample.go
Ensure that we have a consistent order of blocks that we are going to
downsample. `range` over maps doesn't enforce any particular order on
purpose.
This is needed for https://github.com/thanos-io/thanos/pull/3031/files.
ATM in that PR before downsampling we delete all directories which do
not match blocks ULIDs in the remote object storage. Ideally, we should
only keep around the files of a block which we are about to downsample.
It is impossible to do that properly ATM if during another iteration
we'd start from a different block. Thus, let's have a consistent order.
Added sorting for block ULIDs before attempting to possibly downsample them.
Tests still pass.
> downsample: ensure consistent order

- cmd/thanos/query.go
- cmd/thanos/rule.go
Signed-off-by: Stéphane Brillant <stephane.brillant@jive.com>
Fixes: https://github.com/thanos-io/thanos/issues/3837#issuecomment-786385400
> [Fix] Replace unsupported %v macro in logs

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docs.yaml
- .github/workflows/go.yaml
- .github/workflows/react.yml
- scripts/website/contentpreprocess.sh
- scripts/website/websitepreprocess.sh
Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>
- Fixed CircleCI and GitHub workflows to work with `main` branch
- Fixed some bash scripts to account for the branch name change
> CI: Fix CI configs and scripts to work with main branch

- CHANGELOG.md
Missed from: https://github.com/thanos-io/thanos/pull/3860
> Fixed missed changelog comments.

- CHANGELOG.md
- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/tests.yaml
- mixin/alerts/sidecar.libsonnet
- mixin/runbook.md
During prometheus updates the alert was firing because the metric was
initialized with a value of '0' before the first heartbeat was sent. As
such, the evaluation of the alert results into actually taking just the
value of time() into consideration which led to misleading information
about the health of the sidecar.
As the thanos_sidecar_last_heartbeat_success_time_seconds metric is
effectively just a timestamp that resets on new deployments, we can
simply wrap it around the timestamp() function which should return
almost the same value of the metric itself with the added benefit that
heartbeat resets will be ignored.
Signed-off-by: Markos Chandras <markos@chandras.me>
> mixin: Use sidecar's metric timestamp for healthcheck

- mixin/alerts/bucket_replicate.libsonnet
- mixin/alerts/compact.libsonnet
- mixin/alerts/query.libsonnet
- mixin/alerts/receive.libsonnet
- mixin/alerts/rule.libsonnet
- mixin/alerts/sidecar.libsonnet
- mixin/alerts/store.libsonnet
- mixin/dashboards/bucket_replicate.libsonnet
- mixin/dashboards/compact.libsonnet
- mixin/dashboards/query.libsonnet
- mixin/dashboards/receive.libsonnet
- mixin/dashboards/rule.libsonnet
- mixin/dashboards/sidecar.libsonnet
- mixin/dashboards/store.libsonnet
Allow excluding individual components alerts/dashboards through mixin configuration.
Since by default all should still be included I tested that this is the case by re-generating the examples that are checked into this repo.
@kakkoyun @metalmatze
> mixin: Allow excluding individual components through configuration

- pkg/compactv2/compactor_test.go
- pkg/compactv2/modifiers.go
Fixes #3885.
For all matchers in a single deletion request, we should use `AND` between matchers instead of `OR`.
One test case added.
> Tools: rewrite delete can delete series only if it matches all matchers

- pkg/api/query/v1.go
- pkg/metadata/metadata.go
- pkg/metadata/metadatapb/custom.go
- pkg/metadata/metadatapb/rpc.pb.go
- pkg/metadata/metadatapb/rpc.proto
- pkg/metadata/prometheus.go
- pkg/metadata/prometheus_test.go
- pkg/metadata/proxy.go
- pkg/promclient/promclient.go
- test/e2e/metadata_api_test.go
This PR renames the Metadata RPC to `MetricMetadata`.
This change is consistent with the naming from Prometheus and helps with the new target metadata we want to add https://github.com/thanos-io/thanos/issues/3870.
> Rename Metadata API to MetricMetadata API

- CHANGELOG.md
- cmd/thanos/receive.go
- docs/components/receive.md
Currently, the thanos Receiver infers whether it should use TLS for
the gRPC clients that forwards time series to other receivers based on
whether the remote-write HTTP server uses TLS. This is not correct, as
the HTTP server may use TLS without the gRPC server using TLS. This
commit fixes the inference.
Longer-term, this will be taken care of by the receive/router split.
Fixes: https://github.com/thanos-io/thanos/issues/3898
> cmd/thanos/receive.go: Receive client infers TLS

- pkg/compactv2/compactor_test.go
- pkg/compactv2/modifiers.go
Follow-up of #3886.
Require full matchers matching when processing deletion requests. Only partial match or empty label is not allowed.
Let's say a deletion request is `{a="1", b="2"}`, so the series we want to delete must at least matches `{a="1", b="2"}`. It can contain other unrelated labels and it doesn't matter.
We don't want to delete series that have an empty label value of the matchers like `{c="1"}` or series that only has partial matches like `{a="1"}` or `{b="2"}`.
> tools: Fix partial and empty matchers in rewrite

- pkg/store/tsdb.go
- pkg/store/tsdb_test.go
Fixes Task 1: `Add matchers support to TSDB store` of #3779 
This change improves the performance of the label-values lookup when matchers are specified. With this change, the Queriers won't need to fetch & sort & de-duplicate all the metrics, because they can directly call the `.LabelValues()` method and pass the matchers parameter.
Added unit tests.
> Added matchers support to TSDB store

- CHANGELOG.md
- pkg/store/bucket.go
- pkg/store/bucket_e2e_test.go
This change allow to return a different/custom GRPC code - other than the generic `Aborted` - when the limits are hit via `SeriesLimiter` or `ChunksLimiter`.
The reason for this change is that it is hard for the caller to differentiate when the error returned by [Series](https://github.com/thanos-io/thanos/blob/main/pkg/store/bucket.go#L893) method was generated by a `limiter` or if it was a generic/transient error. Propagating the error code generated by the limiter will create the possibility to return any GRPC code on those cases.
* If the error generated by the `SeriesLimiter` and `ChunksLimiter` is a GRPC error, the [Series](https://github.com/thanos-io/thanos/blob/main/pkg/store/bucket.go#L893) will return a GRPC error with the same errorcode.
* Unit tests
> Returning custom grpc code when reaching series/chunk limits

- .bingo/Variables.mk
- .bingo/variables.env
Aligned versions in .bingo for protoc-gen-gogofast to match #3853
```bash
$ make proto
(re)installing /Users/adrian/go/bin/goimports-v0.0.0-20200526224456-8b020aee10d2
go: downloading golang.org/x/tools v0.0.0-20200526224456-8b020aee10d2
>> fetching protoc@3.4.0
>> installing protoc@3.4.0
>> produced /Users/adrian/go/bin/protoc-3.4.0
(re)installing /Users/adrian/go/bin/protoc-gen-gogofast-v1.3.2
generating code
~/go/src/thanos/pkg ~/go/src/thanos
~/go/src/thanos/pkg/store/storepb ~/go/src/thanos/pkg ~/go/src/thanos
~/go/src/thanos/pkg ~/go/src/thanos
~/go/src/thanos/pkg/store/storepb/prompb ~/go/src/thanos/pkg ~/go/src/thanos
~/go/src/thanos/pkg ~/go/src/thanos
~/go/src/thanos/pkg/store/labelpb ~/go/src/thanos/pkg ~/go/src/thanos
~/go/src/thanos/pkg ~/go/src/thanos …
```
> Aligns versions of protoc-gen-gogofast

- pkg/ui/react-app/package.json
- pkg/ui/react-app/src/components/withStatusIndicator.tsx
- pkg/ui/react-app/src/pages/graph/GraphControls.test.tsx
- pkg/ui/react-app/src/pages/graph/Panel.test.tsx
- pkg/ui/react-app/src/pages/graph/TimeInput.test.tsx
- pkg/ui/react-app/yarn.lock
#3892
Fixes `make assets` command, which failed earlier due to a `react-scripts` issue. Currently `pkg/ui/react-app` uses `react-scripts` version `3.4.4`. This leads to a `typescript` version [issue](https://github.com/facebook/create-react-app/issues/9515) which causes the command to fail during building the react app with the following error,
```
./src/utils/index.ts
Line 0:  Parsing error: Cannot read property 'map' of undefined
error Command failed with exit code 1.
```
Downgrading to `typescript` version `3.9.9` fixes this issue. Upgrading `react-scripts` is not feasible at the time due to the caveats mentioned [here](https://github.com/thanos-io/thanos/pull/3813).
`make assets` now runs smoothly,
```
$ react-scripts build
Creating an optimized production build...
Compiled …
```
> Fix make assets 

- docs/components/compact.md
- docs/components/query-frontend.md
- docs/components/query.md
- docs/components/receive.md
- docs/components/rule.md
- docs/components/sidecar.md
- docs/components/store.md
- docs/components/tools.md
- pkg/extflag/pathorcontent.go
The help text stated that both flags could be defined at the same time
with higher priority for the path flag while in practice, they are
mutually exclusive.
No functional change.
> pkg/extflag: clarify help for path/content flags

- CHANGELOG.md
- pkg/logging/http.go
- pkg/logging/http_test.go
Use `net.SplitHostPort` instead of `strings.Split` with a direct slice access, which caused panics when the `Host` header is not available or doesn't contain a port.
Added a unit test that without this patch paniced.
Fixes #3921
> pkg/logging: Fix HTTP logging middleware panic

- cmd/thanos/query_frontend.go
- docs/components/query-frontend.md
Follow up for #3918, I missed this component in the other PR.
> query_frontend: Allow disabling CORS

- pkg/extgrpc/client.go
- pkg/extprom/http/instrument_server.go
- pkg/server/grpc/grpc.go
Add more buckets to read path histograms, in order to track more granularly metrics for the queries that take longer than 2m.
* Change bucket layout for `grpc_client_handling_seconds`
* Change bucket layout for `http_request_duration_seconds`
* Manual verification.
> grpc/http: Add more buckets to read path histograms

- cmd/thanos/query.go
- cmd/thanos/receive.go
- docs/components/query.md
- docs/components/tools.md
- pkg/extgrpc/client.go
- pkg/tls/options.go
Signed-off-by: Srinivas Boga <bseenu@gmail.com>
Fixes: #3719 
This change allows the grpc server to run with self signed certificate or certificates which are signed by fake CA's eg: https://letsencrypt.org/docs/staging-environment/
Just adding additional flag to the query endpoint which is disabled by false, and can be enabled to skip verification of the certificate
```
bash-3.2$  docker run  quay.io/thanos/thanos:v0.18.0 query --log.level=debug --grpc-client-tls-secure --store=localhost:443
level=debug ts=2021-03-20T08:16:37.3579772Z caller=main.go:64 msg="maxprocs: Leaving GOMAXPROCS=[8]: CPU quota undefined"
level=info ts=2021-03-20T08:16:37.358575Z caller=client.go:54 msg="enabling client to server TLS"
level=info ts=2021-03-20T08:16:37.3700257Z caller=options.go:83 msg="TLS client …
```
> Allowing tls skip verify for the query component

- CHANGELOG.md
- pkg/receive/handler.go
- pkg/receive/handler_test.go
- pkg/receive/writer.go
- pkg/store/labelpb/label.go
- pkg/store/labelpb/label_test.go
Fixes: https://github.com/thanos-io/thanos/issues/3726
Baseline: 
```
benchstat -delta-test=none base.txt 2.txt
name                                                                                old time/op    new time/op    delta
HandlerReceiveHTTP/typical_labels_under_1KB,_500_of_them/OK-12                        1.54ms ± 0%    1.54ms ± 0%  -0.42%
HandlerReceiveHTTP/typical_labels_under_1KB,_500_of_them/conflict_errors-12           6.99ms ± 8%    7.55ms ± 0%  +7.99%
HandlerReceiveHTTP/typical_labels_under_1KB,_5000_of_them/OK-12                       16.9ms ± 2%    16.5ms ± 0%  -2.06%
HandlerReceiveHTTP/typical_labels_under_1KB,_5000_of_them/conflict_errors-12          69.9ms ± 4%    67.3ms ± 0%  -3.76%
HandlerReceiveHTTP/extremely_large_label_value_10MB,_10_of_them/OK-12 …
```
> v0.19.0 patch: Added receive benchmark; Fixed Receiver excessive mem usage introduced in 0.17

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/query.go
- cmd/thanos/query_frontend.go
- cmd/thanos/rule.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- pkg/extprom/http/instrument_server.go
- pkg/receive/handler.go
Set Thanos Receive specific histogram buckets for http_duration_seconds_bucket so that we can measure Receiver latency properly. Highest bucket being 5s.
It was always 99ms during my benchmarks... 
Which is unsurprising when most requests fall within the buckets `[0.01, 0.1]`
I can see proper p99 latencies between 10ms and 100ms now. :)
> Make NewInstrumentationMiddleware buckets configurable

- docs/components/query.md
I fixed a broken link to the `service-discovery` page.
Now, when you click on that link it brings you to the correct page.
> Fix broken `service-discovery`  link

- Dockerfile.multi-stage
#3955 
Currently, the `make docker` command uses `Dockerfile` when the kernel is `linux_x86_64` and `Dockerfile.multi-stage` for everything else for e.g macOS (`darwin_x86_64`).  However, in case of the `Dockerfile.multi-stage` the `SHA` build argument goes out of scope when the first stage finishes as it's treated as part of the first stage. This results in the error below,
```
.
.
Step 7/10 : FROM quay.io/prometheus/busybox@sha256:${SHA}
invalid reference format
make: *** [docker-multi-stage] Error 1
```
By defining the build arg, `SHA`, before the first stage, we can ensure that it never goes out of scope and the docker image can be built and tagged successfully. More info can be found [here](https://docs.docker.com/engine/reference/builder/#scope) and …
> Fix `make docker`

- pkg/block/fetcher.go
We're seeing the following when querying `block_meta_sync_duration_seconds` metric:
The sync is actually taking less than 16.67s, but the displayed value is due to the bucket granularity. In this PR I'm proposing to add a couple of more buckets (5m and 10m) to have a better granularity.
N/A
> Add more granularity to block_meta_sync_duration_seconds metric

- CHANGELOG.md
- pkg/rules/rules.go
- pkg/rules/rules_test.go
Currently, if an alerting rule having the same name with different
severity labels is being returned from different replicas then they
are being treated as separate alerts.
Given the following alerts a1,a2 with severities s1,s2 returned from
replicas r1,2:
a1[s1,r1]
a1[s2,r1]
a1[s1,r2]
a1[s2,r2]
Then, currently, the algorithm deduplicates to:
a1[s1]
a1[s2]
a1[s1]
a1[s2]
Instead of the intendet result:
a1[s1]
a1[s2]
This fixes it by removing replica labels before sorting labels for
deduplication.
New unit tests have been added which failed without the fix. Existing tests have been modified to consider the changed sorting order.
> pkg/rules: fix deduplication of equal alerts with different labels

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/rules.yaml
- examples/dashboards/bucket_replicate.json
- examples/dashboards/compact.json
- examples/dashboards/overview.json
- examples/dashboards/query.json
- examples/dashboards/receive.json
- examples/dashboards/rule.json
- examples/dashboards/sidecar.json
- examples/dashboards/store.json
- mixin/README.md
- mixin/config.libsonnet
- mixin/lib/thanos-grafana-builder/builder.libsonnet
- mixin/lib/thanos-grafana-builder/grpc.libsonnet
- mixin/lib/thanos-grafana-builder/http.libsonnet
* Fix `rate(go_memstats_alloc_bytes_total{%s})` query in dashboard, range should be inside rate function.
* Add regex match to account for prefixes in thanos component names, 
so the dashboards should work for components named in the following way: `xxx-thanos-component-xxx`
* Remove hardcoded refIds from panel queries (#3959)
Yes deployed it [our instance of grafana](https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/dashboards)
Closes #3959
> Fix dashboard: query range should be inside rate function

- pkg/objstore/cos/cos.go
- pkg/objstore/gcs/gcs.go
- pkg/objstore/inmem.go
- pkg/objstore/oss/oss.go
- pkg/objstore/s3/s3.go
We have cases in Cortex where we may pass a wrapped error to `IsObjNotFoundErr()`. In this PR I'm proposing to check the error cause in `IsObjNotFoundErr()` so that it can work for wrapped errors too.
I checked all `IsObjNotFoundErr()` implementations and changed only the ones which weren't using `errors.Cause()` or `errors.Is()` yet.
N/A
> Fix IsObjNotFoundErr() for wrapped errors

- CHANGELOG.md
- cmd/thanos/query_frontend.go
- go.mod
- go.sum
- pkg/api/api.go
- pkg/extprom/http/instrument_server.go
- pkg/receive/handler.go
- pkg/server/http/http.go
The Prometheus HTTP handler now enables OpenMetrics as response format upon content negotiation. 
You can test it by running `curl -s -H 'Accept: application/openmetrics-text' localhost:10904/metrics`
This allows us to pass a `traceID` to `ObserveWithExemplar`. 
A lot of the other changes are actually changing the order of calling the middlewares.
Going forward we need to make sure to first call the tracing middleware so that by the time our monitoring/instrumentation middleware gets hit the tracing spans are already populated.
Tested locally with Jaeger and Prometheus running `--enable-feature=exemplar-storage`.
Closes #3944
> Add Exemplars for http_request_duration_seconds histogram

- examples/alerts/alerts.md
- examples/alerts/alerts.yaml
- examples/alerts/tests.yaml
- mixin/alerts/sidecar.libsonnet
- mixin/runbook.md
Cherry-pick #3204 after it has been inadvertently removed by #3856.
> Cherry-pick #3204 after it has been inadvertently removed

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- pkg/block/block.go
- pkg/block/block_test.go
Fixes #3706 
Adapt the second approach mentioned in https://github.com/thanos-io/thanos/issues/3706#issuecomment-768598478.
Add a new flag to not check Thanos external labels when uploading blocks to obj store.
Tested with a local prometheus tsdb block.
Before rewrite:
```
./promtool tsdb analyze data 01EYV86TDESNRQNT2NN0WK6QC9   --limit=100 |grep build_info
1 prometheus_build_info
```
Rewrite block with the command below:
```
thanos tools bucket rewrite --rewrite.to-delete-config-file test.yaml --id 01EYV86TDESNRQNT2NN0WK6QC9  --objstore.config-file /home/yeya24/b.yaml --no-dry-run --prom-blocks
level=info ts=2021-02-26T04:28:21.275951558Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2021-02-26T04:28:21.276586951Z …
```
> Add a flag to not check external labels using bucket rewrite

- CHANGELOG.md
- pkg/rules/rules.go
- pkg/rules/rules_test.go
Currently, if an alerting rule having the same name with different
severity labels is being returned from different replicas then they
are being treated as separate alerts.
Given the following alerts a1,a2 with severities s1,s2 returned from
replicas r1,2:
a1[s1,r1]
a1[s2,r1]
a1[s1,r2]
a1[s2,r2]
Then, currently, the algorithm deduplicates to:
a1[s1]
a1[s2]
a1[s1]
a1[s2]
Instead of the intendet result:
a1[s1]
a1[s2]
This fixes it by removing replica labels before sorting labels for
deduplication.
#	CHANGELOG.md
> Cherry-pick of pkg/rules: fix deduplication of equal alerts with different labels (#3960)

- CHANGELOG.md
- tutorials/katacoda/thanos/1-globalview/courseBase.sh
- tutorials/katacoda/thanos/1-globalview/step2.md
- tutorials/katacoda/thanos/1-globalview/step3.md
- tutorials/katacoda/thanos/2-lts/courseBase.sh
- tutorials/katacoda/thanos/2-lts/step1.md
- tutorials/katacoda/thanos/2-lts/step2.md
- tutorials/katacoda/thanos/2-lts/step3.md
- tutorials/katacoda/thanos/2-lts/step4.md
- tutorials/katacoda/thanos/6-query-caching/courseBase.sh
- tutorials/katacoda/thanos/6-query-caching/step1.md
- tutorials/katacoda/thanos/6-query-caching/step2.md
- tutorials/katacoda/thanos/7-multi-tenancy/courseBase.sh
- tutorials/katacoda/thanos/7-multi-tenancy/step1.md
- tutorials/katacoda/thanos/7-multi-tenancy/step2.md
- tutorials/katacoda/thanos/x-playground/courseBase.sh
- tutorials/katacoda/thanos/x-playground/step1.md
- tutorials/katacoda/thanos/x-playground/step2.md
> Cut v0.19.0

- pkg/runutil/runutil.go
- pkg/runutil/runutil_test.go
We're upgrading Thanos in Cortex and we noticed the compactor logs "failed deleting non-compaction group directories/files, some disk space usage might have leaked". The reason is that, under some conditions, the directory doesn't exist at all. I suggest to consider that case as a non-error.
N/A
> Fix DeleteAll() on non-existing directory

- go.mod
- go.sum
Previous versions of the module are affected by CVE-2021-22133 [1]. My assumption is that the vulnerability has a low severity and it's ok to for the fix to land in v0.20.0. Happy to open the change against the release-0.19 branch if the maintainers think differently.
[1] https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-22133
No functional change.
> go.mod: bump go.elastic.co/apm to v1.11.0

- pkg/query/storeset.go
- pkg/query/storeset_test.go
We want queries with ?partial_response=0 to be sound and complete.
Unfortunately today many queries can succeed without an error while the
system is heavily degraded.
Make strict stores cover a long time range by default until the right
time range has been discovered. We might need to extend this to labels
too. Also on many consecutive Metadata failures we should revert to a
default minTime and maxTime.
StoreSet
* Initialize storeRef maxTime to the maximum possible value
* The first time we set the status, initialize minTime and maxTime to the provided values. This is for initializing with an error case.
go test ./pkg/query only so far
> query: Be pessimistic about strict stores

- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- pkg/ui/templates/bucket_menu.html
- test/e2e/e2ethanos/services.go
- test/e2e/tools_bucket_web_test.go
Fixes [#3211](https://github.com/thanos-io/thanos/issues/3211)
Added the missing route-
1. prefix flag in tools bucket web.
2. External-prefix is handled properly.
1. Tested locally without reverse proxy.
2. Tested behind a reverse proxy using caddy.
3. Wrote 3 e2e test.
1. Test External Prefix without Reverse Proxy.
2. Test External Prefix with Reverse Proxy.
3. Test External Prefix and Route Prefix with Reverse Proxy.
> Block Viewer: Add the missing `--web.route-prefix` flag

- CHANGELOG.md
- pkg/cacheutil/memcached_client.go
- pkg/cacheutil/memcached_client_test.go
Relates to: #3667 
Created a build but have not run e2e. Tested runtime of store.
> Store: Adds the name of the instantiated memcached client to log info

- pkg/ui/react-app/src/pages/targets/TargetLabels.test.tsx
- pkg/ui/react-app/src/pages/targets/TargetLabels.tsx
- pkg/ui/react-app/src/pages/targets/__snapshots__/TargetLabels.test.tsx.snap
Fixes a subissue `Fix styling bug for target labels with special names.` in #3541
> UI: Fix styling bug for target labels with special names 

- pkg/reloader/reloader.go
- pkg/reloader/reloader_test.go
Fix https://github.com/prometheus-operator/prometheus-operator/issues/3061#issuecomment-619812179
Manually tested. Working on unit tests.
> Apply once when WatchInterval == 0 

- CHANGELOG.md
- cmd/thanos/query.go
- pkg/api/query/v1.go
- pkg/api/query/v1_test.go
Adds a range query histogram that tracks the distribution
of range queries. This can be useful for determining storage
retention requirements.
- Adds a range query histogram to the query component.
> Query: range query histogram

- pkg/reloader/reloader.go
- pkg/reloader/reloader_test.go
Related to https://github.com/prometheus-operator/prometheus-operator/pull/3955 when trying to fix https://github.com/prometheus-operator/prometheus-operator/issues/3061#issuecomment-619812179
- Skip make reload request when --watch-interval equals zero; which avoid retrial error when :9090/-/-reload is not ready
Updated unit test by checking reload atom equals 0 for reload request skipped.
> Skip making reload request when `--watch-interval` == `0`

- CHANGELOG.md
- mixin/dashboards/compact.libsonnet
This change will remove the dependency between the rule dashboard and the compact dashboard mixins to be able to only generate the compact dashboard without defining the rule dashboard.
The compact dashboard has been generated and imported to Grafana with and without the included change. No visible differences found.
> Mixin: Remove dependency on the rule dashboard from compact dashboard

- pkg/metadata/prometheus_test.go
- pkg/promclient/promclient_e2e_test.go
- pkg/rules/prometheus_test.go
- pkg/shipper/shipper_e2e_test.go
- pkg/targets/prometheus_test.go
- pkg/testutil/e2eutil/prometheus.go
- test/e2e/metadata_api_test.go
Fixes #4012
Refactor the metadata E2E test and use `metadataEqual` function to compare the two responses instead of just using reflect.DeepEqual.
In `metadataEqual` function, each entry in the metadata response is first sorted and then compare. This fixes the problem mentioned in https://github.com/thanos-io/thanos/issues/4012#issuecomment-812542755
Update: I also rewrite the unit tests of metadata API.
> Fix the metadata API flaky tests

- pkg/ui/react-app/yarn.lock
This removes the is-svg dependency (cssnano no longer depends on it),
which was affected by CVE-2021-28092.
Upgrade cssnano package to v4.1.11
All tests pass when running `yarn test`
Output from `npm list is-svg` before this change:
```
`-- react-scripts@3.4.4
`-- optimize-css-assets-webpack-plugin@5.0.3
`-- cssnano@4.1.10
`-- cssnano-preset-default@4.0.7
`-- postcss-svgo@4.0.2
`-- is-svg@3.0.0
```
Output from `npm list is-svg` after this change:
```
`-- (empty)
```
For reference, the output from `npm list postcss-svgo` after this change:
```
`-- react-scripts@3.4.4
`-- optimize-css-assets-webpack-plugin@5.0.3
`-- cssnano@4.1.11
`-- cssnano-preset-default@4.0.8
`-- postcss-svgo@4.0.3
```
> UI: Upgrade cssnano from v4.1.10 to v4.1.11 to address CVE-2021-28092

- CHANGELOG.md
- pkg/logging/http.go
- pkg/logging/http_test.go
Fix the HTTP logger so that it would take a look at the `url.URL` as
well if `r.Host` is empty. Without this, the logging functionality doesn't quite work
as Cortex uses `url.URL`:
https://github.com/cortexproject/cortex/blob/faf92e8f3dbedfa769fbd6a3ff6e0fbd127694f5/pkg/frontend/downstream_roundtripper.go#L16-L23
Add a test to ensure that this works as expected in both ways.
Without this, the user only sees in the logs:
```
level=error ts=2021-04-09T10:22:05.3319924Z caller=http.go:44 protocol=http http.component=server msg="failed to parse host port for http log decision" err="address foo.bar: missing port in address"
```
> logging: fix the HTTP logger

- pkg/ui/react-app/package.json
- Some dependencies were present in both `dependencies` and `devDependencies` section. I kep them in `devDependencies` (since both of them are related to tests) to avoid conflicts.
- I also explicitly added `lezer` as a dependency since it is required as a peer dependency by `codemirror-promql`.
`yarn test`
> UI: Fix conflicts in dependencies

- pkg/ui/static/js/graph.js
Attempts to fix #4004. With this fix, new window graph panels don't start from `id` 0 but from the last recorded index in `localStorage`. This ensures there is no mismatch between query result and the options selected even with multiple windows open.
For e.g, browser tab A is opened and 3 graph panels are added then `localStorage` is,
Then browser tab B is opened and 2 graph panels are added, resulting in the following `localStorage`,
> ui: Fix state sharing between windows

- pkg/ui/react-app/src/vendor/flot/jquery.flot.stack.js
Fixes a subissue `Fix react UI bug with series going on and off` in #3541.
> UI: Fix react UI bug with series going on and off

- CHANGELOG.md
- docs/components/compact.md
- docs/components/query-frontend.md
- docs/components/query.md
- docs/components/receive.md
- docs/components/rule.md
- docs/components/sidecar.md
- docs/components/store.md
- docs/components/tools.md
- go.mod
- go.sum
- pkg/extkingpin/app.go
Relates to https://github.com/thanos-io/thanos/issues/4034
It sorts the flags alphabetical
The latest release of the kingpin package is from 17 Dec 2017. It was missing any method to do some funky stuff to get this done. That is, unless we want to manually order all flags in the code. So;
* Replaced v2.2.6 of kingpin with latest commit on their master branch so `UsageFuncs` becomes available
* Used the default template with an extra function call before the flag output 
* Added a function that does a sort on flag name
I think this might fall under "it's not stupid if it works" but this change felt nasty lol. Open for review anyway, LMK.
Locally tested. 
Will update further if this is the way to go...
> Sort flags alphabetically

- cmd/thanos/config.go
- cmd/thanos/rule.go
- docs/components/compact.md
- docs/components/rule.md
Signed-off-by: Michael Okoko <okokomichaels@outlook.com>
- Refactor `runRule` arguments into a config struct which can then be passed to the function instead.
- Create new config structs for flags that are in the same "namespace" e.g `query.*` and `alertmanagers.*`. (As per #2248 and similar to #2267).
> Refactor flag parsing and runRule arguments for ruler

- CHANGELOG.md
- docs/components/query-frontend.md
- pkg/queryfrontend/config.go
Fixes #3895
This pr upgrades Cortex and support `max_item_size` in query frontend Memcached config.
> Support max_item_size for query frontend memcached cache

- cmd/thanos/compact.go
- pkg/compact/compact.go
Follow the pattern used for IgnoreDeletionMarkFilter but instead
of stopping early completely drain the channel and report any of
the errors that occurred.
Synced metadata in prod (but we didn't have no compact marked blocks)
> compact: Add concurrency to GatherNoCompactFilter

- pkg/receive/handler_test.go
- pkg/receive/hashring.go
- pkg/receive/writer.go
```
benchstat -delta-test=none ../_dev/thanos/2021/receive2/impr5-go1.16.3.txt ../_dev/thanos/2021/receive2/errimpr1-go1.16.3.txt
name                                                                                old time/op    new time/op    delta
HandlerReceiveHTTP/typical_labels_under_1KB,_500_of_them/OK-12                        1.22ms ± 0%    1.05ms ± 0%  -13.97%
HandlerReceiveHTTP/typical_labels_under_1KB,_500_of_them/conflict_errors-12           5.84ms ± 0%    1.26ms ± 0%  -78.46%
HandlerReceiveHTTP/typical_labels_under_1KB,_5000_of_them/OK-12                       12.8ms ± 0%    11.3ms ± 0%  -11.54%
HandlerReceiveHTTP/typical_labels_under_1KB,_5000_of_them/conflict_errors-12          59.4ms ± 0%    12.8ms ± 0%  -78.39%
HandlerReceiveHTTP/extremely_large_label_value_10MB,_10_of_the …
```
> receive: Improved Performance for err path.

- mixin/README.md
- mixin/config.libsonnet
- mixin/dashboards/defaults.libsonnet
This keeps the default timezone for dashboards to 'UTC' but allows to override it in an easier way.
> Mixin: make timezone dynamic

- pkg/server/grpc/grpc.go
Signed-off-by: wander1024 <yawhua1024@gmail.com>
due to panic and recover atribute
we met the issue as #4080
> fixed grpc.ServerOption order to catch panic

- docs/design.md
- Fixed grammatical mistakes.
- Formated markdown file.
> docs: Updated design document page

- cmd/thanos/store.go
Refactors store cmd
- adds store config struct which contains all required params for store
- replaces all params from runStore method and passes storeConfig as single conf param
Related Issue: #2248
> Store command flag parsing and run args refactoring

- pkg/pool/pool.go
We're reviewing #3937 and we found a race condition introduced in `pool.BucketedBytes.Put()`. If the input buffer is larger than the largest bucket size, then `p.usedTotal` is modified outside the lock.
In this PR I'm rolling back the change done in #3937 which I think was unnecessary. Before the lock only `p.sizes` and `p.buckets[i]` are accessed: `p.sizes` doesn't change and `p.buckets[i]` (which is a `sync.Pool`) is thread safe.
N/A
> Fix race condition in pool.BucketedBytes

- cmd/thanos/query_frontend.go
- go.mod
- go.sum
- pkg/queryfrontend/roundtrip_test.go
End-to-end tests are broken, apparently due to a change in GitHub actions (looks like hosts are now running with IPv6 enabled). I've fixed it in Cortex and in this PR I'm upgrading Cortex into Thanos to bring in the change.
CI tests.
> Fix E2E tests

- pkg/objstore/objstore.go
- pkg/objstore/objstore_test.go
- pkg/objstore/tracing.go
- pkg/store/cache/caching_bucket.go
This PR makes following changes:
- Add `ReaderWithSize` interface that extends Reader with support to report the size of object directly
- Make `tracingReadCloser` implement `ReaderWithSize`.
- Also added `NopCloserWithSize` that can be used instead of `ioutil.NopCloser`.
- Support for `*bytes.Reader` when getting size.
Especially `ReaderWithSize` should make it simpler to avoid warnings with unknown object size during uploads.
> Add ReaderWithSize that allows readers to report size of object directly

- docs/proposals/202012_receive_split.md
👋🏽 @Chans321 @brancz @GiedriusS @kakkoyun @squat @yashrsharma44 @metalmatze 
Sorry for not paying attention to the past proposal, but when we revisited and tried to review  https://github.com/thanos-io/thanos/pull/3845 and https://github.com/thanos-io/thanos/pull/3580  with @kakkoyun we found the potentially easier idea that might be more cleaner for users and maintainers. Feel free to give feedback!
First of all, thanks for all of your hard work on this, and experimental implementations in PR 🤗 We only want to propose different configuration really, but the idea stays exactly the same.
Some learnings for the future:
1. Let's not merge things prematurely. The previous proposal was missing some important parts:
* Goals were stating implementation goals, not the usage goals. We should focus …
> Proposal: Modification of Receive Split proposal.

- test/e2e/targets_api_test.go
The `TestTargetsAPI_Fanout` is flaky (see issue https://github.com/thanos-io/thanos/issues/4069) and is currently blocking some PRs from being merged. I would suggest to temporarily skip it to gain more time to investigate and fix it.
CI
> Temporarily skip flaky test TestTargetsAPI_Fanout

- CHANGELOG.md
- cmd/thanos/query.go
- pkg/exemplars/exemplarspb/custom.go
- pkg/exemplars/proxy.go
- pkg/exemplars/proxy_test.go
- pkg/query/storeset.go
Fixes #4116 
Add logic of matching external labels in the exemplars API proxy.
The matching part is a little bit complex because the input is a query, which might contain multiple vector selectors.
We need to match each vector selector separately and construct the final query after all matches are processed.
Tested locally and one unit test.
We don't have an E2E test for exemplars now so no E2E test added.
> match external labels in exemplars API

- docs/proposals/202101_endpoint_discovery.md
1. Added status and owner.
2. Fixed typos.
3. Used Info Service instead of Info API in the main solution.
4. Removed alternative solutions because both main and alternative solutions were similar as discussed [here](https://github.com/thanos-io/thanos/discussions/4003).
4. Added a new alternative solution which proposes to add Info method in all services (eg. Rule, Targets...). Also added possible disadvantages of this approach.
> Enhance unified endpoint discovery proposal

- cmd/thanos/testdata/rules-files/valid_1.yaml
- cmd/thanos/testdata/rules-files/valid_2.yaml
- cmd/thanos/tools.go
- cmd/thanos/tools_test.go
Adds glob check for filepaths provided via cli. Checks for each matching file path and throws `Matching file not found` error if no file matches the pattern.
fixes #4082 
Added a basic unit test
> Adds glob support for filepath in tools command

- pkg/logging/grpc.go
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
fix [staticcheck lint errors ](https://console.muse.dev/result/thanos-io/thanos/01F4RM4HGH6KVXTB0DQX8N2QY8?t=CustomTool%20%22Staticcheck%22%7CST1005) in Incorrectly formatted error string
> Fix staticcheck lint errors in error strings

- CONTRIBUTING.md
Bonus, remove reference to GOROOT, which does not need to be referenced:
https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really.
xref: #4142 
cc @GiedriusS
> CONTRIBUTING.md: follow up GO* variable cleanup

- pkg/reloader/reloader.go
- pkg/testutil/e2eutil/copy.go
```go
defer f.Close()
```
to
```go
defer runutil.CloseWithErrCapture(&err, f, "close file")
```
Fixes G307
> (bugsbash) Fix deferring unsafe method "Close" on type "*os.File" to adhere to styleguide

- pkg/logging/options.go
Fixes ST1005 : Error string should not be capitalized and should not end with punctuation or a newline
> (bugsbash) Error string should not be captilazed in options.go

- cmd/thanos/tools.go
- pkg/block/indexheader/binary_reader.go
- pkg/block/metadata/hash.go
- pkg/block/metadata/meta.go
- pkg/objstore/filesystem/filesystem.go
- pkg/objstore/objstore.go
- pkg/query/test.go
- pkg/receive/config.go
gosec was showing the following warning "Potential file inclusion via variable". This is because we are trying to open files using dynamic variables. Hence, I've cleaned the bad file paths using filepath.Clean()
Another observation, most of the file paths for which the ```gosec``` was showing a warning, they will never have user-inputted filenames, so I think it is sufficient to remove bad file paths. If it is a user inputted file path, having a basePath joined to the incoming path would be better. 
References
[filePath.Clean()](https://golang.org/pkg/path/filepath/#Clean)
[Stackoverflow](https://stackoverflow.com/questions/52320708/how-to-handle-gosec-linter-warning-potential-file-inclusion-via-variable)
> (bugsbash)fixes gosec warning potential file inclusion via variable

- pkg/queryfrontend/labels_codec.go
```go
log, ctx := spanlogger.New(ctx, "ParseQueryResponse")
```
to
```go
log, _ := spanlogger.New(ctx, "ParseQueryResponse")
```
Fixes SA4006
> (bugsbash)value of ctx is never used

- pkg/promclient/promclient.go
* [x ] Change is not relevant to the end user.
Fixes ST1019 : package "github.com/prometheus/prometheus/pkg/labels" is being imported more than once
> (bugsbash)Package "prometheus/prometheus/pkg/labels" imported twice

- CHANGELOG.md
- Dockerfile
- Dockerfile.multi-stage
Updates busybox image to latest (via sha hash)
Fixes: https://github.com/thanos-io/thanos/issues/4167
> Updates busybox to latest

- cmd/thanos/downsample.go
- cmd/thanos/receive.go
- pkg/block/block.go
- pkg/block/indexheader/binary_reader.go
- pkg/block/writer.go
- pkg/compact/compact.go
- pkg/compact/downsample/downsample.go
- pkg/objstore/filesystem/filesystem.go
- pkg/objstore/objstore.go
- pkg/receive/multitsdb.go
- pkg/reloader/reloader.go
- pkg/shipper/shipper.go
- pkg/store/bucket.go
- scripts/copyright/copyright.go
- test/e2e/e2ethanos/services.go
Minor fix by changing file and directory permissions, Copy of #4150 since messed up the rebase in the previous one
> Modified permissions of file [Bug-bash] 

- .github/dependabot.yml
- Dockerfile
- Dockerfile.multi-stage
- Makefile
> Updated busybox sha; Added dependabot.

- pkg/extprom/http/instrument_server.go
Fixes: #4186 
If a trace is not sampled, then it is unnecessary to create an exemplar.
```
if ok && spanCtx.IsSampled() 
```
> Checking sampled traces to create exemplar

- cmd/thanos/tools_bucket.go
Example:
```
xs = append(xs, 1)
xs = append(xs, 2)
```
should be written as:
```
xs = append(xs, 1, 2)
```
> appends clubbed into a single call

- docs/contributing/how-to-contribute-to-docs.md
- docs/contributing/mentorship.md
- docs/design.md
- docs/operating/use-cases.md
- docs/release-process.md
- docs/storage.md
- Fixed broken links
- Ensured that links are working in GitHub markdown files as well as the Thanos documentation website
**Note**: Rest of the broken links are due to different directory structure in GitHub and in the Thanos website which will be fixed by #3081 and this PR is not a fix for that.
Manual checking of all links
> Docs: fix broken links in website and github

- CHANGELOG.md
- cmd/thanos/config.go
- cmd/thanos/rule.go
- docs/components/rule.md
- pkg/alert/alert.go
- pkg/alert/alert_test.go
- pkg/alert/config.go
Signed-off-by: Christian Schulz <trutty3@gmail.com>
Fixes https://github.com/thanos-io/thanos/issues/4122
Add Prometheus' alert relabelling features to Thanos Rule.
Add command line flag to supply the configuration via YAML or file.
Tested locally with a unit test.
The relabelling logic itself is also tested within Prometheus.
> Add alert relabelling for Thanos Rule based on Prometheus' logic

- pkg/api/query/v1.go
- pkg/rules/manager.go
- pkg/rules/proxy.go
- pkg/rules/rules.go
Signed-off-by: Matsumoto <toshi.matsumoto.3n@gmail.com>
Add tracing for federated rules API.
Closes #4131 
- `make build`
- `make test-local`
> Add tracing spans for rules API

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/config.go
- cmd/thanos/downsample.go
- cmd/thanos/query.go
- cmd/thanos/query_frontend.go
- cmd/thanos/receive.go
- cmd/thanos/rule.go
- cmd/thanos/sidecar.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- docs/components/compact.md
- docs/components/query-frontend.md
- docs/components/query.md
- docs/components/receive.md
- docs/components/rule.md
- docs/components/sidecar.md
- docs/components/store.md
- docs/components/tools.md
- docs/operating/https.md
- go.mod
- go.sum
- pkg/extkingpin/flags.go
- pkg/replicate/replicator.go
- pkg/server/http/http.go
- pkg/server/http/option.go
This PR adds in TLS and basic auth to Thanos HTTP APIs using [exporter-toolkit](https://github.com/prometheus/exporter-toolkit). Configuration follows a similar pattern to Prometheus, where a file containing [TLS configuration](https://github.com/prometheus/prometheus/blob/main/docs/configuration/https.md) is provided using `http-tls-config` flag.
Addresses issue #4168 
> Add TLS and basic auth

- pkg/objstore/swift/swift.go
Resolves #3958
As per NCW Swift's [ObjectCreate():](https://pkg.go.dev/github.com/ncw/swift/v2?utm_source=godoc#Connection.ObjectCreate)
> You MUST call Close() on it and you MUST check the error return from Close().
Signed-off-by: Benjamin Charron <benjamin.charron@ubisoft.com>
Report failures during Upload() back to the caller so that it can retry the operation
- Manual testing with TestObjStore_AcceptanceTest_e2e
> Report errors to caller when Close() fails

- pkg/replicate/replicator.go
The ready status prober is missing for bucket tool replicate.
> Set replicate status prober to ready

- cmd/thanos/receive.go
Moved all the flags for registration for the receiver to a new struct, for improving readability and reduce cognitive load.
Let's wait for the CI to turn green :)
Related Issue: #2248
> receiver: Move the Flags for receiver to a separate struct

- .github/dependabot.yml
- Dockerfile
- Dockerfile.multi-stage
- Makefile
- pkg/ui/bucket.go
- pkg/ui/query.go
- pkg/ui/rule.go
- pkg/ui/ui.go
- Server React UI index page on request to `/` instead of figuring out the path to redirect to. This fixes #4128 
- Append `/` prefix to other redirects. Without this the location is interpreted as relative and we end up doing weird redirections like `/prefix/new/prefix/...`.
Tested Querier, Ruler, and Block Viewer UI locally with and without external prefixes
> UI: Fix infinite redirection loop on /

- test/e2e/receive_test.go
Signed-off-by: Abhishek357 <abhisheksinghchauhan357@gmail.com>
Fixes #4257 
Changed the network name for `hashring with config watcher` e2e test for receive.
The network name for two tests (`hashring` and `hashring with config watcher`) for receive are same.
`go test -run TestReceive/hashring ./test/e2e/...`
> Receiver: e2e test

- mixin/rules/bucket_replicate.libsonnet
- mixin/rules/query.libsonnet
- mixin/rules/receive.libsonnet
- mixin/rules/store.libsonnet
Following on from #3883, if a components is excluded via configuration you can't create rules for it. Resolves #4260
Tested it locally by turning off `receive` via our own mixins (using thanos as a mixin library). Since `receive`'s object is now `null` there are no `dimensions` or `selector`s variables and we get an error during generation:
```
RUNTIME ERROR: Not enough values to format: 1, expected more than 1
std.jsonnet:710:15-103  thunk <val>
std.jsonnet:715:27-30   thunk <val>
std.jsonnet:585:22-25   thunk <a>
std.jsonnet:36:17
std.jsonnet:36:8-19     thunk <a>
std.jsonnet:36:8-31     function <anonymous>
std.jsonnet:36:8-31     function <anonymous>
std.jsonnet:585:9-26    function <format_code>
std.jsonnet:715:15-60   thunk <s>
std.jsonnet:720:24      thunk <str>
... …
```
> Mixin: exclude rule generation if component has been excluded

- pkg/ui/react-app/src/hooks/useFetch.ts
Currently, if any request fails the loading spinner still appears, which gives a false notion that the request is still in the processing state. So I have made the loading spinner hidden if the request fails.
**Before:**
**After:**
Start the React frontend without starting the backend of Thanos
```js
yarn start
```
> UI: fix loading spinner component

- pkg/ui/react-app/package.json
- pkg/ui/react-app/yarn.lock
This PR is increasing the version of codemirror-promql and lezer-promql.
It provides the following interesting (for Prometheus) fixes and enhancements:
* Autocomplete `NaN` and `Inf`
* Fetch series using the HTTP POST method. (The switch was done because some users are reaching the URL limit, which I thought wasn't really possible in the context of this lib)
* Fix the parsing of metric names starting with `Inf` / `NaN` like `infra`
Complete release note is available [here](https://github.com/prometheus-community/codemirror-promql/releases/tag/0.16.0)
> bump codemirror-promql to v0.16.0

- pkg/info/infopb/rpc.proto
- scripts/genproto.sh
This is the protofile for the Info service we are planning to add as part of [unified endpoint discovery](https://thanos.io/tip/proposals/202101_endpoint_discovery.md/) proposal.
1. Can there be disjoint labelsets (i.e. different external labels for different APIs) for the components exposing multiple APIs?
2. Is there any other metadata for any API?
> Add Protofile for info service

- CHANGELOG.md
- pkg/exemplars/exemplars.go
- pkg/exemplars/exemplars_test.go
- pkg/exemplars/exemplarspb/custom.go
- pkg/exemplars/prometheus.go
Fixes #4222 
This pr removes the step of adding replica labels to exemplars. Only adding replica labels to exemplars' series labels.
> Don't add replica labels to exemplar labels, only to its series labels

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- pkg/block/fetcher.go
- pkg/block/metadata/meta.go
- pkg/compactv2/chunk_series_set.go
- pkg/compactv2/compactor_test.go
- pkg/compactv2/modifiers.go
Fixes #3069 
Add relabel support to bucket rewrite.
Add a `RelabelModifier` for blocks relabeling. Unlike the deletion modifier which is used in a streaming way, `RelabelModifier` cannot do this and the reasons are:
1. Relabeling might add new symbols so I have to modify the symbol set and sort it before returning it. Besides, symbols can be deleted because the whole series might be dropped via relabeling.
2. Series are not ordered as relabeling might change the order of series.
These requirements mean that I have to sort almost all the things in the constructor. It is inefficient but currently I don't find a better way to solve it.
Unit tests added and manual testing.
> Support bucket rewrite relabel

- cmd/thanos/receive.go
- test/e2e/e2ethanos/services.go
- test/e2e/receive_test.go
Implementation PR for the Thanos Split Receiver proposal - https://thanos.io/tip/proposals/202012_receive_split.md/
**PR is incomplete, pushed for tracking changes and quick review**
TODO: 
> Implement the dual mode for Thanos Receiver

- test/e2e/compact_test.go
- test/e2e/e2ethanos/services.go
- test/e2e/exemplars_api_test.go
- test/e2e/metadata_api_test.go
- test/e2e/query_frontend_test.go
- test/e2e/query_test.go
- test/e2e/receive_test.go
- test/e2e/rule_test.go
- test/e2e/rules_api_test.go
- test/e2e/store_gateway_test.go
- test/e2e/targets_api_test.go
Fixes #4014 
1. Use Builder pattern for creating Thanos Querier in the E2E test
2. Add some test cases for exemplars API
> Add E2E test for exemplars

- CHANGELOG.md
- pkg/api/query/v1.go
- pkg/exemplars/exemplars.go
- pkg/exemplars/prometheus.go
- pkg/exemplars/proxy.go
Follows https://github.com/thanos-io/thanos/pull/4238 & https://github.com/thanos-io/thanos/pull/4178 - adds tracing instrumentation to the exemplar endpoints.
Closes https://github.com/thanos-io/thanos/issues/4130
Standard tests pass:
```
make build
make test-local
```
I have been trying and failing to figure out an additional unit test to verify this behaviour. 
It might be possible to setup a grpc server with a `basictracer-go` and register the exemplar APIs then verify spans are created when the API is called. Previous tracing PRs have not included this so might not be worth the effort :shrug:
> Add tracing to exemplar APIs

- pkg/reloader/reloader.go
fixes: #4307
Revert back permission change of reloader made in #4173 
Used https://github.com/users/OGKevin/packages/container/package/thanos and works as before 👌🏾
> fix: sidecar: reloader: fix output config file permission

- tutorials/katacoda/thanos/2-lts/step1.md
See issue here:
https://github.com/thanos-io/thanos/issues/4289#issue-907430212
Former:
```
- job_name: 'store_gateway'
static_configs:
- targets: ['127.0.0.1:19092']
```
Corrected:
```
- job_name: 'store_gateway'
static_configs:
- targets: ['127.0.0.1:19091']
```
> Fixed issue #4289

- test/e2e/rule_test.go
E2E tests for ruler are currently marked as skip because they're flaky. This re-enables the test with an attempt at fixing the flakiness (increasing the rule evaluation intervals so they don't oversaturate CI CPUs). 
Also, it removes the test for AlertManager HTTP client pending when we can improve on implementation
(see https://github.com/thanos-io/thanos/issues/4056).
Signed-off-by: Michael Okoko <okokomichaels@outlook.com>
- Re-enable e2e test for ruler
- Remove existing test for AlertManager HTTP client
> Re-enable e2e test for ruler

- tutorials/katacoda/thanos/7-multi-tenancy/step2.md
Fixes https://github.com/thanos-io/thanos/issues/4309:
* Updates `prom-label-proxy` image tag.
* Updates links to Querier UIs.
* Adds UI resources to `unsafe-passthrough-paths`.
Verified tutorial works in my personal katacoda account [here](https://katacoda.com/ibillett/courses/thanos/7-multi-tenancy) per the documentation [here](https://github.com/ianbillett/thanos/blob/8191ed844ea60d621b7bc02d701fbae37a069b8f/tutorials/katacoda/README.md)
> Fix Katacoda multi-tenant tutorial

- pkg/ui/react-app/src/pages/alerts/CollapsibleAlertPanel.tsx
- pkg/ui/react-app/src/pages/graph/GraphControls.test.tsx
- pkg/ui/react-app/src/pages/graph/GraphControls.tsx
- pkg/ui/react-app/src/pages/graph/Panel.tsx
- pkg/ui/react-app/src/pages/graph/TimeInput.tsx
- pkg/ui/react-app/src/pages/rules/RulesContent.tsx
- pkg/ui/react-app/src/utils/index.ts
- pkg/ui/react-app/src/utils/utils.test.ts
Signed-off-by: ajinkya359 <sajinkya359@gmail.com>
Related: #3541 
Subissue `Support new duration format in graph range input`.
Added the support for `Support new duration format in graph range input`.
> UI: Add support for new duration format in graph range input

- pkg/ui/react-app/src/pages/alerts/CollapsibleAlertPanel.tsx
- pkg/ui/react-app/src/utils/utils.test.ts
Closes #4303.
- adds display of alert duration time in Alerts UI
- new function formatDuration() as used in Prometheus project
- also displays all labels and all annotations, not just severity and summary
Tested locally with `make Quickstart` and `yarn start` for the React UI portion. Screenshot added below.
Original:
yarn test, since added new func and tests:
```
PASS  src/pages/graph/DataTable.test.tsx
PASS  src/utils/utils.test.ts
PASS  src/App.test.tsx
PASS  src/pages/targets/ScrapePoolPanel.test.tsx
PASS  src/thanos/pages/blocks/Blocks.test.tsx
PASS  src/pages/targets/ScrapePoolList.test.tsx
PASS  src/pages/graph/TimeInput.test.tsx
PASS  src/pages/graph/ExpressionInput.test.tsx
PASS  src/thanos/pages/stores/StorePoolPanel.test.tsx
PASS  src/pages/graph/GraphControls.test.tsx
PASS …
```
> ruler: fixes issue 4302, adds display of alert duration time in Alerts UI

- CHANGELOG.md
- cmd/thanos/receive.go
- docs/components/receive.md
- pkg/exemplars/exemplarspb/custom.go
- pkg/exemplars/multitsdb.go
- pkg/exemplars/proxy.go
- pkg/exemplars/tsdb.go
- pkg/exemplars/tsdb_test.go
- pkg/receive/handler.go
- pkg/receive/multitsdb.go
- pkg/receive/multitsdb_test.go
- pkg/receive/writer.go
- pkg/receive/writer_test.go
- Enable exemplar ingestion in Receive
- Add exemplars API implementation for TSDB and MultiTSDB
- Expose exemplars gRPC API from Receive
Fixes #4235 
- Local testing, modified some existing tests for ingestion. Need to add E2E tests.
> receive: Enable exemplars ingestion and querying

- CHANGELOG.md
- go.mod
- go.sum
- pkg/receive/handler.go
Use https://github.com/klauspost/compress/tree/master/s2#s2-compression
for decompressing Snappy data. I think if this pays off then we could
also try using this in Prometheus for encoding?
Benchmarks show these numbers:
```
benchmark                                                                                       old ns/op     new ns/op     delta
BenchmarkHandlerReceiveHTTP/typical_labels_under_1KB,_500_of_them/OK-16                         1139713       1071864       -5.95%
BenchmarkHandlerReceiveHTTP/typical_labels_under_1KB,_500_of_them/conflict_errors-16            1294286       1207937       -6.67%
BenchmarkHandlerReceiveHTTP/typical_labels_under_1KB,_5000_of_them/OK-16                        11613568      10849901      -6.58% …
```
> receive: use s2 when decompressing snappy data, reduce CPU usage for incoming remote write requests by ~5-7%

- .github/ISSUE_TEMPLATE/config.yml
Inspired and copy/pasta'd from jaegertracing :) 
It will look like this (but with our own text)
As discussed via slack: https://cloud-native.slack.com/archives/CL25937SP/p1622453498082200
> Adds more contact options when creating a new issue on Github

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
Fixes #4287 
Add a new `delete-blocks` flag.
> Add --delete-blocks flag to bucket rewrite tool to mark original blocks for deletion

- docs/storage.md
Signed-off-by: Blacklion14 <rkush214@gmail.com>
A small typo in /docs/storage.md [here](https://github.com/thanos-io/thanos/blob/main/docs/storage.md#how-to-our-special-config-flags)
I changed the line "How to our special config flags?" to "How to use our special config flags?"
> Fixed a typo in /docs/storage.md

- CHANGELOG.md
- pkg/receive/handler.go
Signed-off-by: Ian Billett <ibillett@redhat.com>
Fixes https://github.com/thanos-io/thanos/issues/4305
Running the integration tests from https://github.com/thanos-io/thanos/pull/4362 I see the following log:
```
11:25:28 receive-i3: level=error name=receive-i3 ts=2021-07-01T10:25:28.330239422Z caller=handler.go:261 component=receive component=receive-handler err="request replica exceeds receiver replication factor" msg="write request rejected" request_replica=2 replication_factor=1
```
> Add error log to receiver and clarify bad replica error message

- CHANGELOG.md
- pkg/ui/react-app/package.json
- pkg/ui/react-app/src/pages/flags/Flags.test.tsx
- pkg/ui/react-app/src/pages/flags/Flags.tsx
- pkg/ui/react-app/src/pages/flags/__snapshots__/Flags.test.tsx.snap
- pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx
- pkg/ui/react-app/yarn.lock
> Add sorting and filtering to flags page

- README.md
- docs/components/compact.md
This PR is for #4395 Adding Adopters list to Readme.md file
> #4395 Added Adopters list in Readme.md

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
Signed-off-by: ben.ye <ben.ye@bytedance.com>
This pr adds a new bucket tool `retention`. It simply applies the given retention policy on the bucket, same as compactor.
Because of the misconfiguration of our compactor, we have over 60k blocks left in the bucket and I am trying to scale the compactor to make blocks compactions faster.
The workflow of compactor is:
1. Grouper groups blocks into several groups
2. Apply compaction
3. Perform downsampling if enabled
4. Apply retention policy
For us, because of the large amount of blocks left in the bucket, step 2 is super slow. Also it is trying to compact blocks that are outside our retention period. For example, it is compacting blocks generated in March, however, our longest retention is only 2 months. So even the compaction succeeds, the …
> Add bucket tool retention command

- pkg/ui/react-app/src/thanos/pages/blocks/blocks.module.css
- pkg/ui/react-app/src/themes/_bootstrap_dark.scss
Signed-off-by: Blacklion14 <rkush214@gmail.com>
I changed ThIs [css](https://github.com/thanos-io/thanos/blob/main/pkg/ui/react-app/src/thanos/pages/blocks/blocks.module.css) file and added a z-index so that the blocks which were behind the container of bootstrap-dark have came to front
Also i changed this bootstrap-dark.css file a bit in order to make close Button in blocks details div to be visible clearly in dark mode. This change may not create any ambiguity because in general we will always willing to have a white contrast text colour inside a button in dark-mode . And this will change colour of only text inside button not the background colour. 
If some one wants to change colour to some other white contrast they can directly change it from here.
I ran the UI and it is running …
> Fixed Night Mode in BlocksUI

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/downsample.go
- cmd/thanos/main_test.go
- cmd/thanos/tools_bucket.go
- docs/components/compact.md
- docs/components/tools.md
Signed-off-by: ben.ye <ben.ye@bytedance.com>
Fix #4363 
Add a flag `downsample.concurrency` to specify the number of workers to use for downsampling blocks.
> Add support for downsampling concurrency

- CHANGELOG.md
Cut the CHANGELOG for release. This is the first step as per the
instructions. This reduces the risk for new PRs to add new entries to a
version that has been already released.
> CHANGELOG: cut for release

- CHANGELOG.md
- cmd/thanos/rule.go
- test/e2e/rule_test.go
Signed-off-by: Juraj Michalek <juraj.michalek132@gmail.com>
Fixed a [bug](https://github.com/thanos-io/thanos/issues/4432) when sending sighup signal to thanos ruler didn't result in loading changes.
1. Started thanos locally using `make quickstart`.
2. Modified recording rule in rules.yml created by the quickstart option
3. Sent sighup to thanos ruler
4. Looked at thanos ruler ui to check if changes were successfully loaded (they were)
5. Also added e2e test for it
> rule: fix reload signal not working

- .bingo/prometheus.mod
- CHANGELOG.md
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
- test/e2e/e2ethanos/services.go
- test/e2e/tools_bucket_web_test.go
fix #4452 
- add `min-time` `max-time` `selector.relabel-config` flag to `thanos tools bucket web`.
e2e test.
run with new flag, it works.
> Tools: Add flag `--selector.relabel-config-file` / `--selector.relabel-config` / `--max-time` / `--min-time` to filter served blocks.

- docs/components/rule.md
Advanced relabeling is possible since commit 745f0f3d. This change
updates the documentation to reflect the reality.
No functional change.
> docs: update relabeling for Thanos Ruler

- CHANGELOG.md
- pkg/ui/react-app/src/pages/alerts/AlertContents.tsx
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
Added correct escape sequence \&gt; to represent > from html.
Manual, refer the attached screen shots,
> fix: incorrect html escape sequence used for '>' symbol

- CHANGELOG.md
- docs/storage.md
- pkg/objstore/cos/cos.go
- pkg/objstore/cos/cos_test.go
- scripts/cfggen/main.go
Fix #4479
The http.Transport is not auto-tuning and one size does not seem to fit all cases.
Add `HTTPConfig` Allow to tune most of the http.Transport parameters and `MaxIdleConnsPerHost` tune to 100.
add http_config for cos storage.
unit test .
redeploy thanos tools bucket web, no TIME_WAIT connection.
> COS: Add http_config for cos object store client

- pkg/block/metadata/meta.go
Signed-off-by: ilangofman <igofman99@gmail.com>
Hello, I mentioned this briefly in one of the community calls. Currently I am working on the adding the series deletion API in Cortex. To accomplish the task of permanently deleting the series, I would like to leverage the logic of the bucket rewrite work done inside of Thanos. To track which blocks have been rewritten, the proposed idea was to store the deletion request id inside of the `meta.json` file. Since the file is written from within Thanos, this PR will allow us to do this.  
If anyone is intrested, the proposal for the API in Cortex can be found [here](https://cortexmetrics.io/docs/proposals/block-storage-time-series-deletion/l).
Please let me know if there is any questions or concerns with this change.
Thanks
- Add a new variable …
> Add RequestID for Deletion Requests

- test/e2e/tools_bucket_web_test.go
Some linux systems support less than 64 characters for a host-name. the host name is more than 64 in this case `TestToolsBucketWebExternalPrefixAndRoutePrefix` so that the case cannot be passed:
```
06:22:50 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-08-03T06:22:50.42873554Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
```
reduce the length of scenario name
> reduce the length of scenario name

- CHANGELOG.md
- docs/components/query-frontend.md
- docs/components/store.md
- pkg/cacheutil/memcached_client.go
- pkg/discovery/memcache/provider.go
- pkg/discovery/memcache/provider_test.go
- pkg/discovery/memcache/resolver.go
- pkg/discovery/memcache/resolver_test.go
* Add a flag to enable auto-discovery for memcached
* Add a new provider/resolver for auto-discovery
* Integrated into cortex, and verified that auto-discovery is able to find scaled up nodes without having to restart pods
* Tested with [AWS ElastiCache Auto Discovery](https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/AutoDiscovery.HowAutoDiscoveryWorks.html), but should work with [Google Cloud ](https://cloud.google.com/memorystore/docs/memcached/auto-discovery-overview)too, since the protocol seem the same
I also updated the memcached config documentation so that we can close https://github.com/thanos-io/thanos/issues/3879
> query: add memcached autodiscovery support

- CHANGELOG.md
- pkg/ui/react-app/src/thanos/pages/blocks/BlockInput.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/BlockSearchInput.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/SourceView.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/SourceView.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/blocks.module.css
- pkg/ui/react-app/src/thanos/pages/blocks/helpers.ts
This PR is part of LFX Mentorship project (issue: #3112). We want to add Search Block by ID.
When we haven't search anything yet:
Example search block by ID:
Tested on local using `make quickstart`
> ui: Add search block UI

- CHANGELOG.md
- cmd/thanos/query.go
- pkg/cacheutil/memcached_client.go
ref: https://github.com/thanos-io/thanos/issues/4204
I saw the same issue exists in version 0.22 in OCP 4.8. 
If I understand correctly, `Miekg resolver was working fine for everyone, but Go native not`. so have this PR to use Miekg as default resolver.
> Switch to use Miekg by default

- CHANGELOG.md
- cmd/thanos/downsample.go
- pkg/block/fetcher.go
- pkg/compact/compact.go
Currently the logged lines contain a `duration` field that is encoded as a string with varying units. When ingesting these structured logs into a logging system (eg. elasticsearch), the field is parsed as a string which doesn't allow for range queries.
Example from v0.19.0:
```json
{
"ts": "2021-08-02T11:38:26.928570654Z",
"cached": 23731,
"duration": "2.09562852s",
"tier": "sv",
"stage": "main",
"returned": 1567,
"type": "monitoring",
"component": "block.BaseFetcher",
"msg": "successfully synchronized block metadata",
"caller": "fetcher.go:476",
"level": "info",
"partial": 0
}
```
Adding a dedicated `duration_ms` integer field solves this problem.
Example:
```json
{
"duration": "2.09562852s",
"duration_ms": "2095",
}
```
In order to avoid schema conflicts and introducing a breaking …
> adds duration_ms in int64 to the logs

- pkg/discovery/memcache/provider_test.go
* Fix flaky test (https://github.com/thanos-io/thanos/issues/4523)
> Fix flaky test introduced by memcached autodiscovery

- pkg/ui/react-app/src/pages/graph/CMExpressionInput.tsx
This PR is removing the inner search tool that you have when you press CTRL-F when having the focus in the PromQL 
Which is not really helpful in the usage of writing PromQL query.
It also to be synchronized with Prometheus: https://github.com/prometheus/prometheus/pull/9184
> remove search keymap from new expression editor

- CHANGELOG.md
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/SourceView.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/SourceView.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/helpers.ts
This PR is part of LFX Mentorship project to improve Block Viewer UI (issue: #3112). We want to add feature so user can find overlapping blocks easily.
When we haven't enable find overlapping block yet:
Example `enable find overlapping block`:
Tested on local using `make quickstart`
cc: @onprem @squat
> ui: Add find overlap block UI

- CHANGELOG.md
- cmd/thanos/compact.go
- pkg/block/index.go
- pkg/block/index_test.go
- pkg/block/metadata/markers.go
- pkg/compact/compact.go
- pkg/compact/compact_e2e_test.go
- pkg/query/querier.go
- pkg/testutil/testutil.go
Signed-off-by: Yang Hu <yhuz@amazon.com>
- add a check for OOO chunks in block index, and mark such block for no compaction, and continue on with the compaction
- add testutil to generate an index with OOO chunks
- verified the exepected behavior with `compact_e2e_test.go`
Addresses: #3442 
cc: @yeya24 @alvinlin123 @roystchiang
> skip blocks with out-of-order chunk during compaction

- pkg/block/indexheader/reader_pool.go
- pkg/block/indexheader/reader_pool_test.go
- pkg/store/bucket.go
- pkg/store/bucket_test.go
I'm working on some improvements to reduce the Cortex store-gateway memory allocations on clusters with large number of tenants.
Long story short, we have a known issue caused by metrics collection (https://github.com/cortexproject/cortex/issues/3697) and, as a first step, I would like to be able to share the metrics passed to `indexheader.ReaderPool`.
> Allow to share indexheader.ReaderPool metrics

- cmd/thanos/compact.go
- pkg/compact/compact.go
- pkg/compact/compact_e2e_test.go
The PR https://github.com/thanos-io/thanos/pull/4469 was just merged but I've the feeling it's not correct. The problem is that when the skip is **disabled** it should still be a critical error while right now the error is ignored at all (see comment annotation in the PR).
Also, from a design perspective, I don't think it's the responsibility of the grouper to know if skipping is enabled or not, so I've moved that config to the `BucketCompactor`.
> Fix -compact.skip-block-with-out-of-order-chunks

- go.mod
- go.sum
- pkg/objstore/azure/azure.go
Supersedes https://github.com/thanos-io/thanos/pull/4502
I'm trying to update `azure-pipeline-go` and `azure-storage-blob-go` in `grafana/loki` which vendors Thanos. Because of this I'll also try to update those two dependencies in Thanos. 
Since this PR is only updating dependencies, I figured it would not require filling out the usual sections. If otherwise please just let me know.
- Bumps `azure-pipeline-go` dependency form v0.2.2 to v0.2.3
- Bumps `azure-storage-blob-go` dependency from v.0.8.0 to v0.13.0
- Addresses library changes under `pkg/objstore/azure/azure.go`
- Run repository tests
> Bump azure-storage-blob-go to v0.13.0

- cmd/thanos/query.go
- cmd/thanos/receive.go
- docs/components/query.md
- docs/components/receive.md
- go.mod
- go.sum
- pkg/extkingpin/flags.go
- pkg/server/grpc/grpc.go
- pkg/server/grpc/option.go
- pkg/tls/options.go
- test/e2e/tls_test.go
This PR implements the second part of this [proposal](https://github.com/thanos-io/thanos/blob/main/docs/proposals-accepted/202106-automated-per-endpoint-mTLS.md), i.e. 
> Adding a new `--grpc-server-max-connection-age` CLI option which takes time as input and controls how often to re-do the tls handshake and re-read the certificates. This in reality is controlled by the keepalive’s MaxConnectionAge option (which will close the connection after every (e.g. 15m) inputted time duration) so when the connection is closed it requires a new tls handshake.
While reading the cert_file on each handshake we can improve the performance by keeping track of it’s modification time. We should re-load the certificates only if they are actually rotated and there is some change in their modification time …
> Automatic certificate rotation without restart

- pkg/query/storeset_test.go
> pkg/query: Improve readability of StoreSet test by not escaping quotes

- pkg/query/storeset.go
It might be nicer to have an embedded interface where it's the same for all of them.
I started deleting the interfaces like TargetSpec, MetadataSpec etc but I do think they improve readability in other places, so I decided to still keep them around.
Tests
> pkg/query: Embed new StoreAddrSpec in other interfaces for consistency

- pkg/compact/compact.go
Change the spelling of the blocksMarkedForNoCompact variable.
Compilation: `make build`
> compactor: Change the spelling of blocksMarkedForNoCompact variable

- pkg/queryfrontend/cache.go
- pkg/queryfrontend/cache_test.go
- pkg/queryfrontend/labels_codec.go
- pkg/queryfrontend/labels_codec_test.go
- pkg/queryfrontend/request.go
- pkg/queryfrontend/roundtrip_test.go
Signed-off-by: Sandeep Raveesh <crsandy@gmail.com>
Fixes https://github.com/thanos-io/thanos/issues/4580
This PR adds the support for match[] parameter for labels api in query frontend
I added the required tests to verify this.
> match support for labels api in query frontend

- CHANGELOG.md
- cmd/thanos/downsample.go
Signed-off-by: Anugrah Vijay <anugrah.vijay@gmail.com>
- Registers and implements downsampleDuration histogram. 
- New var for downsample duration to avoid recomputing time.Since across logs/metric. 
- Local validation of compactor with local minIO bucket
> compactor: adds downsample duration histogram

- pkg/store/storepb/custom.go
- pkg/store/storepb/custom_test.go
Do not forget to check the length of a slice returned by sync.Pool.
Annotate the whole function with comments to aid understanding of it.
Cover the case with a test that fails on `main`.
Fixes https://github.com/thanos-io/thanos/issues/4591.
cc @yeya24 as you've noticed this too
> store: fix marshaling with sync.Pool

- cmd/thanos/rule.go
- pkg/extprom/http/instrument_client.go
- pkg/http/http.go
This pr add `pkg/extprom/http/instrument_client.go` with code to instrument an HTTP client.
The approach is to add metrics clients to the HTTP config.
Not sure if this is the right approach or if another clever design can be used, this was the most obvious and backward compatible way I could come up with.
fixes: https://github.com/thanos-io/thanos/issues/4545
Signed-off-by: Kevin Hellemun <17928966+OGKevin@users.noreply.github.com>
```
thanos_rule_query_http_client_in_flight_requests 0
thanos_rule_query_http_client_request_duration_seconds_bucket{le="0.005"} 0
thanos_rule_query_http_client_request_duration_seconds_bucket{le="0.01"} 1
thanos_rule_query_http_client_request_duration_seconds_bucket{le="0.025"} 2
thanos_rule_query_http_client_request_duration_seconds_bucket{le="0.05"} 2 …
```
> Improvement: add metrics to prom client

- pkg/objstore/azure/azure.go
- pkg/objstore/azure/helpers.go
- pkg/objstore/azure/helpers_test.go
The changes made in #4607  was missing a token refresh as I expected that to be done by the client. This was not the case and after leaving things running over the weekend the token eventually expired and everything stopped working. This change adds a token refresh function which renews the token before it expires.
Have tested a build of this branch in an AKS cluster, and it works. I will leave it running for another day just to make sure that the token refresh actually works.
> .*: Fix Azure MSI token refresh

- pkg/ui/react-app/src/pages/graph/Panel.tsx
Signed-off-by: Nishidha Sri <nishidhasri@gmail.com>
Fixes #4301
Changed state change to null after discarding the error in src/pages/graph/Panel.tsx
Tested it by manually firing a wrong query and then discarding it and firing the wrong query again. Did it several times.
> UI: Fix error only appearing once for failing queries

- CHANGELOG.md
- cmd/thanos/query_frontend.go
- docs/components/query-frontend.md
- pkg/queryfrontend/config.go
Make the HTTP downstream tripper configurable so that it would be
possible to set the number of maximum idle connections per host to more
than 2 so that HTTP keep-alive connections could be used on higher
loads.
Solves https://github.com/thanos-io/thanos/issues/4571.
> query-frontend: make HTTP downstream tripper configurable

- pkg/store/prometheus.go
- pkg/store/prometheus_test.go
Handle older Prometheus versions that do not support `match[]`. Add
tests that cover new code. The new code is largely modeled after the
LabelValues() code.
It fixes https://github.com/thanos-io/thanos/pull/4586#discussion_r700735487 and unblocks the release.
> store: add handling code for older Prometheus versions

- pkg/query/endpointset.go
- test/e2e/compact_test.go
- test/e2e/e2ethanos/services.go
- test/e2e/exemplars_api_test.go
- test/e2e/metadata_api_test.go
- test/e2e/query_frontend_test.go
- test/e2e/query_test.go
- test/e2e/receive_test.go
- test/e2e/rule_test.go
- test/e2e/rules_api_test.go
- test/e2e/store_gateway_test.go
- test/e2e/targets_api_test.go
> query: Added tests for compatiblity for old components without InfoAPI.

- CHANGELOG.md
- docs/release-process.md
> Cut release 0.23.0-rc.0

- test/e2e/query_frontend_test.go
Small fix for what seems to be an incorrect condition - in the check func, we should be returning error if there are no results, not when there are results available. This seems to currently always make the E2E test fail.
Run tests locally - :heavy_check_mark:
> Tests: Query Frontend - Fix incorrect check in E2E tests

- go.mod
- go.sum
- pkg/objstore/cos/cos.go
Change to official COS object store SDK.
Fix objstore e2e test invalid test bucket name.
Fix setRange when off>0.
Hi all, 
The COS objstore support is implement via `github.com/mozillazg/go-cos` at 2019 year,
the `mozillazg/go-cos` is unfficial and not actively update now, it's latest tag version date is 2019-09-18.
the official sdk `github.com/tencentyun/cos-go-sdk-v5` which based on `mozillazg/go-cos` is keeping actively update, the latest tag date is `2021-09-07`.
It should be change to official SDK to get more support. I fix testing bucket name bug and setRange bug, then it has passed the e2e objectore test. 
thanks to @jojohappy and mozillazg/go-cos author. 
1. Change to official COS object store SDK. 
2. Fix objstore e2e test invalid …
> COS: Change to official COS object store SDK.

- CHANGELOG.md
- docs/storage.md
- go.mod
- go.sum
- pkg/objstore/azure/azure.go
- pkg/objstore/azure/azure_test.go
- pkg/objstore/azure/helpers.go
Adds support for [user-assigned managed identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview#managed-identity-types).
When using the `user_assigned_id` the change does not require setting `msi_resource` it defaults to `https://<storage account name>.<endpoint>` unless the config explicitly sets the `msi_resource`.
Tested against Azure.
> Azure: Support authentication using user-assigned managed identity

- pkg/compact/compact_test.go
- pkg/objstore/testing.go
> compact: Add benchmark for #4084

- pkg/promclient/promclient.go
- pkg/promclient/promclient_e2e_test.go
- test/e2e/e2ethanos/services.go
> Sidecar: Fix process external label on promethues v2.28+ use units.Bytes config type

- pkg/exemplars/proxy.go
- pkg/metadata/proxy.go
- pkg/targets/proxy.go
Fix #4676.
This PR base on #4680.
grpc doc say https://github.com/grpc/grpc-go/blob/v1.40.0/stream.go#L123
```
// RecvMsg blocks until it receives a message into m or the stream is
// done. It returns io.EOF when the stream completes successfully. On
// any other error, the stream is aborted and the error contains the RPC
// status.
```
if gRPC bid-stream response error, `return`.
test in #4676
> Query: Fix (*Stream).receive infinite loop when target response Unimplemented error (#4676)

- scripts/insecure_grpcurl_series.sh
Running `scripts/insecure_grpcurl_series.sh` yields the following error:
```
no required module provides package github.com/fullstorydev/grpcurl/cmd/grpcurl; to add it:
go get github.com/fullstorydev/grpcurl/cmd/grpcurl
```
This PR resolves it by adding the `@latest` prefix to the go install argument
* Modify `scripts/insecure_grpcurl_series.sh` to install `github.com/fullstorydev/grpcurl/cmd/grpcurl@latest` instead of `github.com/fullstorydev/grpcurl/cmd/grpcurl`
I ran `scripts/insecure_grpcurl_series.sh` locally.
> scripts: Install grpcurl@latest when querying a store API

- .mdox.validate.yaml
Most of the time `cloud.baidu.com` is unreachable from CI servers. Lets
ignore it to avoid flakiness during CI validations.
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> docs: ignore cloud.baidu.com from mdox validation

- pkg/promclient/promclient.go
- pkg/store/acceptance_test.go
- pkg/store/prometheus.go
- pkg/store/prometheus_test.go
- pkg/store/tsdb.go
- pkg/store/tsdb_test.go
- test/e2e/query_test.go
It was super inconsitent. 
There might be still inconsistencies across other store APIs but fixing sidecar and receive first 🤗
> sidecar, receive: Fixed label matching using matchers + external labels; unify tests and behaviour.

- CHANGELOG.md
- pkg/cache/cache.go
- pkg/cache/inmemory.go
- pkg/cache/memcached.go
- pkg/cache/tracing_cache.go
- pkg/store/cache/caching_bucket_test.go
With multiple caches, this change lets you see clearly which spans relate to which cache.
Added a name member to caches, add this as a tag when tracing.
Left as an exercise.
> Query: Put cache name on tracing spans

- pkg/model/timeduration.go
- pkg/model/timeduration_test.go
Signed-off-by: Jimmiehan <hanjinming@outlook.com>
before this fix, set --min-time or --max-time negative value will be empty at page. beacuse prometheus/common model.Duration does not support negative. https://github.com/prometheus/common/blob/main/model/time.go#L236
fixed:
`func (tdv *TimeOrDurationValue) String()` support negative.
Unit test.
> Store: Fix (*model.TimeOrDurationValue).String() when value is negative

- cmd/thanos/query.go
Signed-off-by: Jimmiehan <hanjinming@outlook.com>
fix panic on stop application.  the  `(*Discovery).refresh` may send the channel after close channel. https://github.com/prometheus/prometheus/blob/v2.30.0/discovery/file/file.go#L343
logs 
```
ts=2021-09-19T08:24:41.135548308Z caller=log.go:168 level=debug msg="Stopping file discovery..." paths="[/etc/thanos-query/thanos-store-api-targets.yaml /etc/thanos-query/thanos-sidecar-targets.yaml]"
ts=2021-09-19T08:24:41.135746869Z caller=log.go:168 level=debug msg="File discovery stopped"
panic: send on closed channel
goroutine 307 [running]:
github.com/prometheus/prometheus/discovery/file.(*Discovery).refresh(0xc0000b2960, 0x2159ca8, 0xc0002d33c0, 0xc0001090e0)
/Users/jimmiehan/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210720123808- …
```
> Store: fix panic on stop application

- pkg/server/grpc/grpc.go
It was quite common to hit receive limit using large remote write requests. In this PR I remove limits as we did not have them for send anyway. Probably proper way is to allow users to configure them via flags. Right now no use cases like this so let's consider configurability for the future.
```
observatorium-thanos-receive-default-9observatorium-thanos-receive-default-0 thanos-receive level=error ts=2021-09-24T18:13:03.444687849Z caller=handler.go:366 component=receive component=receive-handler err="10 errors: replicate write request for endpoint observatorium-thanos-receive-default-1.observatorium-thanos-receive-default.monitoring.svc.cluster.local:10901: quorum not reached: 3 errors: forwarding request to endpoint observatorium-thanos-receive-default-2.observatorium-thanos-receive-defa …
```
> .*: Removed limit for received message size through gRPC.

- CHANGELOG.md
- pkg/query/endpointset.go
- pkg/query/endpointset_test.go
In #4699 it was discovered that users might be receiving 'false' reports due to increase in number of `Unimplemented` error, caused by attempting to obtain metadata via gRPC service, which is not yet implemented.
The fix proposed here is to remove info client for now and instead always fall back to using store API to obtain metadata. After https://github.com/thanos-io/thanos/pull/4282 we should be able to switch back to using info client.
The PR also adjusts the tests accordingly and fixes some discrepancies (e.g. the mocked rule component was not exposing store API)
Resolves #4699
Updated tests.
> Endpointset: Do not use info client to obtain metadata (for now)

- cmd/thanos/tools_bucket.go
Signed-off-by: 4molybdenum2 <tathagatapaul7@gmail.com>
Fixed Bucket Tools such that it supports Dry Run with multiple block ID's (#4713)
- Changed the code such that when dry run mode is enabled for multiple id's the function doesn't return nil after first iteration of the loop and instead continues to the next iteration.
- Updated logger to log the block ID for each such block in dry run.
> Fix bucket tools to dry run with multiple block ID's

- pkg/block/index.go
- pkg/compact/compact.go
Signed-off-by: metonymic-smokey <ahuja.aditi@gmail.com>
Fixes #4470 
The debug log on compaction when an unhealthy index is found now mentions the series in the out of order index too. Earlier, only the proportion of such series was logged.
> Add series label for unhealthy index debug log

- test/e2e/compact_test.go
- test/e2e/e2ethanos/services.go
- test/e2e/store_gateway_test.go
- Extended newStoreGW services to accept caching bucket config.
- Added Memcached in Store Gateway e2e test.
- Added a separate test for Store Gateway with Memcached.
The tests passed after the changes.
> e2e: Add memcached as cache in store-gateway test

- pkg/queryfrontend/labels_codec_test.go
- pkg/queryfrontend/queryrange_codec_test.go
As a part of working on query frontend performance related task (https://github.com/thanos-io/thanos/issues/4571), I'm adding benchmarks to query frontend packages for codecs.
Results:
``` bash
queryfrontend ❯ go test -bench=.                                                                     query-frontend-benchmarks
goos: linux
goarch: amd64
pkg: github.com/thanos-io/thanos/pkg/queryfrontend
cpu: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
BenchmarkLabelsCodecEncodeAndDecodeRequest/SeriesRequest-12               217172              5070 ns/op            3496 B/op         44 allocs/op
BenchmarkLabelsCodecEncodeAndDecodeRequest/LabelsRequest-12               165806              7023 ns/op            3937 B/op         57 allocs/op
BenchmarkLabelsCodecDecodeResponse/SeriesResponse-12 …
```
> Query frontend: Add benchmarks for labels codec and query range codec

- pkg/metadata/metadata.go
- pkg/metadata/proxy_test.go
- pkg/rules/proxy_test.go
- pkg/rules/rules.go
- pkg/targets/proxy_test.go
- pkg/targets/targets.go
Relevant #4805.
Signed-off-by: Jimmiehan <hanjinming@outlook.com>
1. write a unit test, go test -race to reproduce it .
2. add `sync.Mutex` to `*metadataServer/*rulesServer/*targetsServer`.
`go test -race -run TestProxyDataRace -v`
> Query: Fix metadataServer/rulesServer/targetsServer data race

- pkg/ui/react-app/src/hooks/useFetch.ts
- pkg/ui/react-app/src/pages/graph/Panel.tsx
- pkg/ui/react-app/src/pages/targets/EndpointLink.tsx
This PR fixes the Store Filter select menu text color to be more legible in dark mode.
Before fix:
After fix:
Note: Had to type annotate `catch` blocks due to errors when running `make assets`, but is unrelated to PR.
> Fix store filter select menu color in dark mode

- docs/release-process.md
This PR updates release procedure to include merging of release branch to `main` (after each release). This makes the latest version tags reachable from `main`, which is important for Go modules to not get confused about which version to use when trying to use branch names. This is only important for projects (eg. Cortex) that depend on Thanos. 
For example:
```
$ go get github.com/thanos-io/thanos@main
go get: github.com/thanos-io/thanos@main (v0.19.1-0.20211012092857-7dee6fa15682) requires github.com/thanos-io/thanos@v0.22.0, not github.com/thanos-io/thanos@main (v0.19.1-0.20211012092857-7dee6fa15682)
```
This happens because latest reachable tag from `main` branch is `v0.19.0` and not `v0.23.1`.
> Add step for merging release branch back to main.

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/store.go
- cmd/thanos/tools_bucket.go
- pkg/api/blocks/v1.go
- pkg/api/blocks/v1_test.go
- pkg/ui/react-app/src/thanos/pages/blocks/BlockDetails.tsx
This is part of LFX mentorship project (issue: #3112). We want to add mark deletion and no compaction button in block details UI.
- Add `/block/mark` endpoint for trigger marking block API
- Add button for mark deletion and no compaction in UI, with modal for asking the detail/reason
Tested in local using `make quickstart`
Example of mark deletion:
Result of mark deletion:
Example of mark no compaction:
Result of mark no compaction:
cc: @squat @onprem
> block (UI and API): Add mark deletion and no compaction UI

- pkg/store/proxy.go
Defer in for loop will lead too many timer in heap.
here is the pprof log:
```
[*]* ./go tool pprof  *:19192/debug/pprof/heap
Fetching profile over HTTP from http://*:19192/debug/pprof/heap
Saved profile in *pprof.thanos.alloc_objects.alloc_space.inuse_objects.inuse_space.011.pb.gz
File: thanos
Type: inuse_space
Time: Nov 3, 2021 at 2:41pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 153.80MB, 84.79% of 181.38MB total
Dropped 76 nodes (cum <= 0.91MB)
Showing top 10 nodes out of 111
flat  flat%   sum%        cum   cum%
50.52MB 27.85% 27.85%    54.52MB 30.06%  github.com/thanos-io/thanos/pkg/store/storepb.(*Series).Unmarshal
36.01MB 19.86% 47.71%    36.01MB 19.86%  google.golang.org/grpc.(*parser).recvMsg
17.72MB …
```
> Query: fix streamSeriesSet defer in for loop

- docs/components/query-frontend.md
> Fix flag name in query frontend doc

- pkg/ui/react-app/src/thanos/Navbar.tsx
With https://github.com/thanos-io/thanos/pull/4282 merged, it is time to
unhide these very useful pages from the navigation bar. :tada:
Checked those pages via the quickstart script after changes.
> ui: unhide previously hidden pages

- test/e2e/info_api_test.go
This PR fixes `TestInfo` method in `info_api_test` which calls `NewPrometheusSidecar` with too few arguments and breaks linter and e2e test as shown [here](https://github.com/thanos-io/thanos/runs/4161586199?check_suite_focus=true).
> Fix `info_api_test` for linter

- go.mod
For some reason, the `go.mod` for `github.com/efficientgo/tools/core` points to an invalid git commit (it does not exist on any branch), which causes error:
```
thanos ❯ go get github.com/efficientgo/tools/core@421d0828c9a6                                                       
go get: github.com/efficientgo/tools/core@421d0828c9a6: invalid version: unknown revision 421d0828c9a6
```
Resolves #4806.
Go get works for
> go.mod: Fix invalid reference to github.com/efficientgo/tools/core

- CHANGELOG.md
- cmd/thanos/query.go
- docs/components/query.md
- pkg/ui/query.go
Pass `queryURL` to the UI to have proper URLs in the React UI. Without
this, all URLs are set to `http://localhost:10902` i.e. the default
value set in `config.ts`.
Started Thanos via the quickstart script and checked that http://localhost:10904/rules, for example, has proper, clickable URLs.
> query: pass queryURL along to the UI

- cmd/thanos/compact.go
- docs/components/compact.md
1. Only enable progress metrics if `wait` mode is enabled
2. Make the interval configurable instead of hardcoded 5m
3. Remove the original `progress-metrics` bool flag. Now to disable progress metrics, just set interval to 0.
> Make progress metrics interval configurable

- CHANGELOG.md
- cmd/thanos/query.go
- docs/components/query.md
This PR completes 3rd task from [this](https://github.com/thanos-io/thanos/issues/2600#issuecomment-967241095) list.
- Added `--endpoint-strict` flag (similar to `--store-strict`) which can be used to add statically configured endpoints.
> query: add `--endpoint-strict` flag to statically configure endpoints

- cmd/thanos/rule.go
Thanks to the version update in https://github.com/thanos-io/thanos/pull/4882, we can bring https://github.com/prometheus/prometheus/pull/9623 in to support the no lock option in the agent DB.
> Add no lock option for stateless rule agent DB

- docs/components/rule.md
- docs/proposals-done/202005-scalable-rule-storage.md
This pr adds the missing document for Thanos Ruler stateless mode.
> Add doc for thanos rule stateless mode

- pkg/httpconfig/http.go
I'm upgrading Thanos in Loki and the arm build fails because it detects an int overflow:
```
vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:94:28: constant 90000000000 overflows int
vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:95:28: constant 10000000000 overflows int
vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go:97:28: constant 10000000000 overflows int
```
This PR should fix it.
N/A
> Fixed int overflow in HTTP config

- .mdox.yaml
> Make hyperlinks work

- pkg/store/bucket.go
- pkg/store/bucket_test.go
The queryStats log is very useful to debug query in thanos-store.
But currently the duration field is unexported so that `fmt.Printf("%+v", stats)` print a number for time.Duration.
Before: <details>
<p>
level=debug msg="stats query processed" stats="&{blocksQueried:1 postingsTouched:102 postingsTouchedSizeSum:1122 postingsToFetch:0 postingsFetched:1 postingsFetchedSizeSum:404 postingsFetchCount:1 postingsFetchDurationSum:162905 cachedPostingsCompressions:1 cachedPostingsCompressionErrors:0 cachedPostingsOriginalSizeSum:404 cachedPostingsCompressedSizeSum:18 cachedPostingsCompressionTimeSum:29569 cachedPostingsDecompressions:101 cachedPostingsDecompressionErrors:0 cachedPostingsDecompressionTimeSum:65901 seriesTouched:100 seriesTouchedSizeSum:1229 seriesFetched:54 …
> Store: Make queryStats log with human-readable format.

- docs/components/query.md
* Include `auto` in the list of options.
* Improve wording.
* Add backticks around the values.
Signed-off-by: SuperQ <superq@gmail.com>
> Improve auto downsampling query param docs

- CHANGELOG.md
- pkg/tracing/http.go
- pkg/tracing/jaeger/jaeger.go
This is replacement for stale PR https://github.com/thanos-io/thanos/pull/4018 by @conorevans
Make baggage key lowercase for Jaeger support. Per Jaeger documentation:
>Limitation: since HTTP headers don’t preserve the case, Jaeger recommends baggage keys to be lowercase-kebab-case, e.g. my-baggage-key-1.
Not sure if it's easy to test. As original author, I'm not sure if spinning Jaeger and Thanos worth to test that.
> Fixing force tracing with Jaeger

- pkg/query/endpointset.go
- pkg/query/endpointset_test.go
Avoid RLock()ing twice as described here:
https://github.com/thanos-io/thanos/issues/4766#issuecomment-948743455
(due to
https://stackoverflow.com/questions/30547916/goroutine-blocks-when-calling-rwmutex-rlock-twice-after-an-rwmutex-unlock/30549188).
Fix it by removing HasClients() and simply changing it with `er.clients != nil`.
> backport (query: fix deadlock in endpointset (#4795))

- docs/components/query-frontend.md
- docs/components/store.md
- go.mod
- go.sum
- pkg/cache/memcached.go
- pkg/cache/redis.go
- pkg/cache/redis_test.go
- pkg/cacheutil/memcached_client.go
- pkg/cacheutil/redis_client.go
- pkg/cacheutil/redis_client_test.go
- pkg/queryfrontend/cache.go
- pkg/queryfrontend/cache_test.go
- pkg/queryfrontend/config.go
- pkg/store/cache/caching_bucket_factory.go
- pkg/store/cache/factory.go
- pkg/store/cache/memcached.go
- pkg/store/cache/memcached_test.go
- scripts/cfggen/main.go
Hi, I am attempt to add redis cache support,  like cortex does.
First. i will make it a draft PR.
1. add redis support for bucket-cache/index-cache/query-frontend
1. unit test.
2. continning test in production deployment.
> Cache: support redis cache backend

- CHANGELOG.md
- pkg/objstore/azure/helpers.go
`getContainerURL` was creating a new `http.Client` within `HTTPSender`.
This increased memory pressure on components making requests to Azure.
Move `http.Client` creation out of `HTTPSender`, only creating it once
per call to `getContainerURL`.
Signed-off-by: Andrew Seigner <andrew@sig.gy>
In objstore/azure, move `http.Client` creation out of `HTTPSender`, only creating it once
per call to `getContainerURL`.
We observed a 2x~4x memory increase in our alertmanager, compactor, ruler during an upgrade from Cortex [v1.10.0](https://github.com/cortexproject/cortex/blob/v1.10.0/go.mod#L57) to [v1.11.0](https://github.com/cortexproject/cortex/blob/v1.11.0/go.mod#L85), and tracked it down to a change in `getContainerURL`.
Memory usage of alertmanager, compactor, ruler with Cortex …
> objstore/azure: Only create an http client once

- cmd/thanos/rule.go
- docs/components/rule.md
- test/e2e/e2ethanos/services.go
- test/e2e/rule_test.go
This is mainly for non surprising remote write YAML format, but also for ability
to add more targets, similar to agent supported model.
> rule: Added ability to specify multiple remote write targets.

- pkg/discovery/dns/resolver.go
- I've improved the log when an A record of part of a SRV record fails to resolve to include which A record did not resolve.
- None, this feels fairly low risk.
I'm hoping this is fairly uncontroversial, but happy to take advice on naming. I didn't think this was worth raising an issue about, but we've had problems where A records didn't resolve as part of a SRV record and only outputting the SRV record in the log.
> resolver: Improve logs when A record does not resolve from SRV record set

- CHANGELOG.md
- cmd/thanos/compact.go
- docs/components/compact.md
> Compactor support time filter (#4884)

- .circleci/config.yml
- .dockerignore
- CHANGELOG.md
- Dockerfile.multi-arch
- Makefile
> support build docker images for arm64 arch

- CHANGELOG.md
- docs/tracing.md
- pkg/tracing/jaeger/config_yaml.go
The OpenTelemetry jaegerreceiver always write 128bit traceID to backend https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.41.0/pkg/translator/jaeger/jaegerthrift_to_traces.go#L95 , with leading zero. 
like '00000000000000007aeab04b2badb0bd',  but jaeger query will parse it to 64bit traceid to search https://github.com/jaegertracing/jaeger/blob/main/model/ids.go#L51.
One of solution is make jaeger client use 1238bit traceID.
1. add `traceid_128bit` field to tracing config, align to same field in  jaeger config .
> Tracing: add `traceid_128bit` support for jaeger

- CHANGELOG.md
- cmd/thanos/sidecar.go
- test/e2e/query_test.go
Set Sidecar to not be ready when Prometheus is unavailable. This avoids
problems when Prometheus is replaying WAL and Sidecar is "up" but then
Query hangs while waiting for a response from Prometheus/Sidecar. Also,
it gets shown as UP in the Stores page with no ext. labels during this
time that is confusing.
Improved e2e tests which pass.
> sidecar: not ready when Prometheus is unavailable

- Makefile
It seems like recent changes to Prometheus BusyBox image have been reverted (https://github.com/prometheus/busybox/pull/47) and the SHA of the images changed again - E2E tests are currently not passing because of this. This PR updates the images' SHA again.
Waiting on green CI :tumbler_glass:
> *: Update BusyBox image sha

- CHANGELOG.md
- pkg/verifier/index_issue.go
Only the first block is parsed. This commit fixes this issue to parse all blocks present in the bucket.
Fix issue #4878 .
Signed-off-by: Aymeric <aymeric.daurelle@cdiscount.com>
* Split the function `VerifyRepair` in two dedicated functions `verify` and `repair`.
* Replace **return** statement by **continue** to go to the next iteration. This allow to parse all blocks from a bucket.
* Added a log in debug level to just say when a block has no issue :
```
level=debug ts=2021-11-19T11:50:37.47465883Z caller=index_issue.go:56 verifiers=index_known_issues verifier=index_known_issues msg="no issue" id=01FMVXMZABF699W6HC8HA2B0E3
```
Tested locally. 
<details>
<p>
```
$ thanos tools bucket verify --objstore.config-file=/etc/default/thanos-storage-a01-dc1.yml -i index_known_issues …
```
> bucket verify: fix to parse all blocks

- CHANGELOG.md
- pkg/cacheutil/redis_client.go
- pkg/queryfrontend/cache.go
- pkg/store/cache/caching_bucket_factory.go
- pkg/store/cache/memcached.go
1. docs: add changelog about redis cache.
2. fix code review in #4888.
> docs: add changelog about redis cache

- CHANGELOG.md
- cmd/thanos/downsample.go
- cmd/thanos/main_test.go
Fix deadlock that occurs if there is some backlog of blocks to be
deduplicated, and an error occurs. For this to trigger, there needs to
be at least `downsampleConcurrency + 2` blocks in the backlog.
Add test to cover this regression. Affected versions 0.22.0 - 0.23.1.
Fixes https://github.com/thanos-io/thanos/issues/4960.
> downsample: fix deadlock if error occurs

- CHANGELOG.md
- docs/storage.md
- pkg/objstore/s3/s3.go
- pkg/objstore/s3/s3_test.go
use prometheus common tls_config to connect with s3 object store so that we can pass the certificate in.
part of thanos-io/thanos#4820
> Add custom certificate CA support for s3

- CHANGELOG.md
- docs/storage.md
- pkg/objstore/azure/azure.go
- pkg/objstore/azure/azure_test.go
- pkg/objstore/azure/helpers.go
- pkg/objstore/s3/s3.go
- pkg/objstore/tlsconfig.go
use tls_config to connect with azure object store so that we can pass the certificate in.
part of #4820
>  Add custom CA support for azure

- pkg/store/prometheus.go
Use the appropriate function `labelpb.ExtendSortedLabels` to extend the
labelset in `queryPrometheus` with external labels. It maintains the
invariant that labelset is a sorted set of labels. Otherwise, random
errors might occur with pushdown enabled:
`Error executing query: vector cannot contain metrics with the same labelset`
I have triggered this with a weird query `max_over_time(up[5m])` & with
HA pairs.
> store: fix label extending

- docs/proposals-accepted/202108-more-granular-query-performance-metrics.md
Signed-off-by: Moad Zardab mzardab@redhat.com
Related to https://github.com/thanos-io/thanos/issues/4895
> New metric for measuring query duration proposal

- cmd/thanos/compact.go
Filters will execute by order,  the time-filter is more cheaper than deduplicate-filter.
1. Unit test.
2. Real deployment test.
> compactor: make time filter take first

- pkg/block/indexheader/lazy_binary_reader.go
In Cortex we've noticed that the 99th percentile computed on`indexheader_lazy_load_duration_seconds` is always capped to 5s even if the average can be way higher. Reason is that the largest histogram bucket is 5s but lazy loading can take way longer than that (mostly depending on index size and the disk speed).
In this PR I proposes to add more buckets to the metric, to have a better estimation of 99th percentile on high durations.
> Change is not relevant to the end user.
Is it? Do you track such changes in CHANGELOG?
N/A
> Increase indexheader_lazy_load_duration_seconds buckets

- CHANGELOG.md
- docs/storage.md
- pkg/objstore/cos/cos.go
- pkg/objstore/cos/cos_test.go
1.  Add `endpoint` field to COS object store config.
2. Add document and validate test.
1. Unit test.
2. Real depoyment test.
> objectstore/cos: add `endpoint` field for config vpc internal endpoint

- website/layouts/index.html
- website/static/main.css
> [Website] fixed overflow company images and hero section logo 

- pkg/api/query/v1.go
Signed-off-by: Paul Grave <paul@stomer.net>
Fixes #5011 
I replaced calls to `cortexutil.ParseTime` with `parseTimeParam` in `NewExemplarsHandler` since the later allows default times to be set.
I removed the `cortexutil` since the above change made it redundant.
The impact is that this behaviour mirrors Prometheus’ behaviour and allows exemplars to be displayed in Grafana.
I effected some functional tests. I ran my own container (paulgrave/thanos:0.24.1) on my cluster and validated that exemplars are now displayed in Grafana.
Executed `curl -v -d query=test http://localhost:10902/api/v1/query_exemplars` to validate that a) API doesn’t error b) returns a 200 instead of a 400.
Executed `curl -v -d query='my_requests_total{app="prom-py"}' -d start=1640770731.689 -d end=(date +%s) …
> query: set default times for query_exemplars API

- Makefile
Fixed the `docker-build` target, which currently fails always with:
```
Sending build context to Docker daemon  295.7MB
Step 1/7 : ARG BASE_DOCKER_SHA="97a9aacc097e5dbdec33b0d671adea0785e76d26ff2b979ee28570baf6a9155d"
Step 2/7 : FROM quay.io/prometheus/busybox@sha256:${BASE_DOCKER_SHA}
invalid reference format
make: *** [Makefile:190: docker-build-amd64] Error 1
```
Presumably caused as a side-effect of https://github.com/thanos-io/thanos/pull/4965. This PR fixes the target to correctly obtain the relevant SHA.
This currently causes `publish_main` job to fail as well, meaning no images are being published.
Run `docker-build` locally and was able to get pass the problematic step.
> *: Fix docker-build target

- website/layouts/_default/baseof.html
- website/static/main.css
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>
> [Website] Fixed `footer` items alignment

- cmd/thanos/store.go
Just a small fix: add bkt closing to the run group instead of closing it
at the of the function that only sets things up. In practice, this
didn't cause a bug because Close() is a noop. But as good Go
programmers, let's Close() the bucket properly at the end of Thanos
Store's lifetime.
> store: close bkt properly

- Makefile
Added an extra Makefile option that only checks for .md files that are actually changed. Removing the need to iterate over the entire project (takes minutes!).
Locally tested.
> Feature/quick docs - only check docs that are changed for quick dev work

- pkg/extkingpin/app.go
This intends to improve error reporting in k8s. Before this change
thanos would print the error, followed by the usage. The latter part
would fill up a container status message (in say `kubectl describe`)
with the usage, hiding the actual error.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> cli: print usage before error when argument parsing causes an error

- pkg/query/querier.go
- test/e2e/query_test.go
Fix querying when some data has been pushed down and some - hasn't.
Since `max_over_time` and `min_over_time` remove `__name__` from the
results either way, let's do that inside Select() to have a unified form
of data.
Add test to cover this case.
Without this code, the test fails:
```
level=error ts=2022-01-06T16:28:37.959956685Z msg="function failed. Retrying in next tick" err="read query instant response: expected 2xx response, got 422. Body: {\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"vector cannot contain metrics with the same labelset\"}\n"
```
Closes https://github.com/thanos-io/thanos/issues/5033.
> query: fix querying with interleaved data

- CHANGELOG.md
- pkg/prober/intrumentation.go
Issue: https://github.com/thanos-io/thanos/issues/5036
Remove constant spam of "changing probe status" if status of the probe was set to the same value as before
I ran `make quickstart` without my changes and saw that `"changing probe status"` messages are spammed even though probe status was set to the same value as before. Then I added my changes, ran `make quickstart` again and got certain that these kind of logs do not repeat if probe status does not change to different value than before.
> prober: Remove spam of changing probe status

- pkg/cache/groupcache.go
- pkg/cache/groupcache_test.go
- test/e2e/store_gateway_test.go
Fix peer loading by specifying the proper route to `router`. Add a test
for this.
Also, let's add a benchmark for loading data via galaxycache.
> cache: add benchmark + fix peer loading

- pkg/objstore/s3/s3_e2e_test.go
- test/e2e/compact_test.go
- test/e2e/e2ethanos/services.go
- test/e2e/info_api_test.go
- test/e2e/query_test.go
- test/e2e/store_gateway_test.go
- test/e2e/tools_bucket_web_test.go
Enable e2e connect MinIO with TLS enabled：
- Generate certs for MinIO TLS
- Update S3 Configure to have `tls_config` field
part of #4820
> start minio server with tls

- MAINTAINERS.md
Signed-off-by: Wiard van Rij <wvanrij@roku.com>
> Change company for Wiard

- pkg/objstore/cos/cos.go
Change is not relevant to the end-user.
add NewBucketWithConfig func for cos.
I am importing objstore/cos package from thanos in other projects. Hoping to use NewBucketWithConfig as in s3 package rather than NewBucket() which only support byte slice parameter.
> add NewBucketWithConfig for cos objstore

- .circleci/config.yml
This PR attempts to fix current issue on CI - #5077 - which causes the `publish_*` jobs not to pass on the CircleCI.
The first attempt is to update the remote Docker engine version (see: https://circleci.com/docs/2.0/building-docker-images/#docker-version)
Temporarily, the job has been allowed on all branches but pushing images has been commented out, we just need to make sure we pass the `docker-test` step
Waiting on CI to pass
> *: Attempt to fix multiarch builds by updating remote Docker engine version

- CHANGELOG.md
- cmd/thanos/compact.go
- cmd/thanos/downsample.go
- cmd/thanos/main_test.go
- docs/components/compact.md
- pkg/compact/compact.go
- pkg/compact/compact_test.go
- pkg/compact/downsample/downsample.go
- test/e2e/e2ethanos/services.go
* Ran locally with e2e compactor tests with flags enabled below set retention to test flag validation 
Changes based on: https://github.com/thanos-io/thanos/issues/813 
tl;dr: For downsampling to happen, blocks must be pass a certain age for the preceding resolution. This was always the case in [Compactor](https://github.com/thanos-io/thanos/blob/c31cb08f1b0cf9ad7f23a57210812499a8fa0764/cmd/thanos/downsample.go#L265-L318) but not transparently to users. As such, it's very easy to set up retention in such a way that disrupts downsampling or leads to accidental data loss.
> Compactor: Adding minimum retention flag validation for downsampling retention

- docs/getting-started.md
Signed-off-by: fktkrt <fktkrt@gmail.com>
I added links to a blog post and a conference talk of how LastPass is using Thanos. We discussed this with @wiardvanrij on CNCF Slack's  #thanos channel.
It's just a docs change.
> Add talk and blog post of use cases at LastPass to the Getting Started section

- .github/workflows/container-version.yaml
Now the workflow is triggered by a cron job every day. But if the busybox image is updated after running the cron job that day, then the CI will be broken until the next day.
To support better control on this, I added support to trigger it manually. See doc https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch.
I am not sure if the current syntax is correct or not so would be great to have more eyes for review.
> Support triggering update sha workflow manually

- docs/components/compact.md
A missing white space is currently causing `make check-docs` to fail consistently. This is the fix.
Ran the target locally.
> *: Fix missing white space in `compactor.md`

- CHANGELOG.md
- docs/components/compact.md
- pkg/objstore/s3/s3.go
- pkg/objstore/s3/s3_test.go
The `X-Amz-Server-Side-Encryption-Context` header should be a base64 encoded string representing a string-string
map. In the case that the KMSEncryptionContext was omitted from Objstore config when SSE-KMS was being used, a nil map was being used for the header value resulting in a value of `null`. This is the issue that was causing https://github.com/thanos-io/thanos/issues/4245
I have made a change such that if no KMSEncryptionContext was passed in the config an empty map is used instead so the header value is correctly set to `{}`.
I've extended  an existing test case to cover my changes, additionally I tested this in practice as described in https://github.com/thanos-io/thanos/issues/4245 - A header value of `{}` is acceptable to the AWS API.
> S3 - Encryption context header cannot be null

- pkg/cache/groupcache_test.go
Add fixes according to the suggestions here
https://github.com/thanos-io/thanos/pull/5068#discussion_r787711237.
> cache: add os.Exit if starting HTTP fails

- mixin/README.md
Deleting link to mixin design doc (https://docs.google.com/document/d/1A9xvzwqnFVSOZ5fD3blKODXfsat5fg6ZhnKu9LK3lB4/edit#) which apparently does not exist anymore and causes the doc check to fail.
Local run of `make check-docs`
> Docs: Remove link to a deleted resource from mixin docs

- CHANGELOG.md
- pkg/block/block.go
- pkg/block/block_test.go
- pkg/shipper/shipper_e2e_test.go
Signed-off-by: Romain Dauby <romain.dauby@gmail.com>
Fix #3839 
* do not upload DebugMeta files to bucket (obj store)
Unit test, e2e tests passed locally and also in my fork with Github actions.
> Do not upload meta files to obj store

- pkg/objstore/filesystem/filesystem.go
- pkg/objstore/filesystem/filesystem_test.go
I found a race condition in the filesystem bucket client `Delete()`. The issue happen if 2 concurrent deletes occurs on different files in a subfolder containing only these 2 files. Both `Delete()` will try to delete the empty dir, but one of the two will fail with:
```
unexpected error: fdopendir /path/to/subfolder: no such file or directory
```
In this PR I propose to handle the `no such file or directory` in the `isDirEmpty()`. `isDirEmpty()` is used by Iter() and Delete(). In `Iter()` it's just used to skip empty dirs, so I think this change is fine there too.
New unit test.
> Fix race condition in filesystem bucket client Delete()

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
Most places in thanos use RFC3339 for formatting, but I noticed that `thanos tools bucket inspect` had the format hardcoded.
Built the thanos binary and tried the inspect command to verify the output
> Use time.RFC3339 in bucket inspect command for consistency

- tutorials/katacoda/thanos/2-lts/step2.md
Found a small typo in step2.md in 2-Lts katacoda tutorial.
>  Fix typo in step2.md_2-lts_katacoda-tutorial

- tutorials/katacoda/README.md
- tutorials/katacoda/thanos/2-lts/step2.md
Signed-off-by: harshita harshitakb123@gmail.com
Fix the link error in step 2 that returns 404
> Update readme katacoda

- tutorials/katacoda/thanos/1-globalview/step3.md
Signed-off-by: burntcarrot <aadhav.n1@gmail.com>
Small nit. Fixes a little typo present in the [Intro](https://katacoda.com/thanos/courses/thanos/1-globalview) Katacoda tutorial.
> fix(tutorials): fix typos in katacoda/thanos/1-globalview

- pkg/cache/groupcache.go
- scripts/quickstart.sh
Check that SelfURL also doesn't end with a slash since the galaxycache's
code checks whether the strings are equivalent when picking peers, and
peers cannot have slashes at the end so we need the same, exact format
of the URLs.
Fix quickstart script so that it wouldn't have slashes at the end.
Idea for the future: let's add smoke tests for `scripts/quickstart.sh`
to ensure smooth developer experience?
> cache: fix quickstart script, improve checking

- docs/components/query-frontend.md
- docs/components/query.md
- docs/components/receive.md
- docs/components/rule.md
- docs/components/sidecar.md
- docs/components/store.md
- docs/logging.md
- pkg/extkingpin/flags.go
> Document request logging configuration

- CHANGELOG.md
- pkg/objstore/cos/cos.go
Support multi-part upload. fix issue #5137 can not upload file more than 5GB.
e2e test.
```bash
export COS_APP_ID=*** COS_SECRET_ID=*** COS_SECRET_KEY=*** COS_REGION=ap-guangzhou  
THANOS_TEST_OBJSTORE_SKIP=AZURE,ALIYUNOSS,BOS,GCS,S3,SWIFT go test -cover -coverpkg "github.com/thanos-io/thanos/pkg/objstore/cos" -coverprofile=/tmp/test_cos.out -test.run ^TestObjStore_AcceptanceTest_e2e$ ./pkg/objstore/objtesting/...
go tool cover -html=/tmp/test_cos.out
```
result:
```
ok      github.com/thanos-io/thanos/pkg/objstore/objtesting     50.698s coverage: 68.2% of statements in github.com/thanos-io/thanos/pkg/objstore/cos
```
> objectstore/cos: support multi-part upload (#5137)

- pkg/store/prometheus.go
- test/e2e/e2ethanos/services.go
- test/e2e/exemplars_api_test.go
- test/e2e/info_api_test.go
- test/e2e/metadata_api_test.go
- test/e2e/query_frontend_test.go
- test/e2e/query_test.go
- test/e2e/rules_api_test.go
- test/e2e/targets_api_test.go
Add repro for #5069 by querying sidecar with --min-time enabled and then
checking the result equivalence.
Fix it by aligning min time with the step.
> sidecar: fix for --min-time with pushdown

- CHANGELOG.md
- pkg/ui/react-app/src/thanos/pages/blocks/Blocks.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/helpers.test.tsx
- pkg/ui/react-app/src/thanos/pages/blocks/helpers.ts
Issue: #5044 
- Added a function to filter block rows with respect to searched ULID
- Shows only the row which contains the searched block ID
- Added an edge case to show "No blocks found" if no block matches with the searched block
- Tested locally with 4 different block labels.
Attached a short video file that demonstrates my implementation.
https://user-images.githubusercontent.com/61948033/151028795-566c7bd9-8662-4a88-b861-a5f59d202ac1.mp4
> Fix: Filter block rows in bucket UI according to searched block ID

- CHANGELOG.md
- pkg/replicate/replicator.go
- pkg/replicate/scheme.go
- pkg/replicate/scheme_test.go
Even though ignoring of deleted blocks by the `tools bucket replicate`  added in https://github.com/thanos-io/thanos/pull/5117 works
It does not use the code base for filtering already prepared and that brings one additional drawback and that is it fails on reading block metadata if in process of deletion (which was also the case we were hitting)
The former implementation first read all meta files (which fails for the block that is being deleted) and only after checks for the deletion mark. The deletion mark has to be checked first, as the filtered meta fetcher does.
Sorry about that
Please, @GiedriusS and @wiardvanrij would you take a look one more time? :pray:
> fix tools bucket replicate: fix ignoring of deleted blocks

- pkg/shipper/shipper.go
- pkg/shipper/shipper_test.go
* [na] I added CHANGELOG entry for this change.
* Improve diagnostics in error from shipper.ReadMetaFile when thanos.shipper.json is invalid JSON, to help in troubleshooting
* Replace usages of ioutil in shipper tests, as it's deprecated
* Add three testcases for shipper.ReadMetaFile
I added a testcase corresponding to my change.
> shipper: better error message when thanos.shipper.json invalid

- pkg/ui/react-app/src/pages/rules/RulesContent.tsx
1. Remove white background from table cell in RulesContent table, so it's able for flexible color scheme (white/dark)
1. I didn't test it, but I'm sure about it, it seems like any other table cells now
> ui: remove white background in rules content table cell (#5024)

- pkg/store/prometheus.go
Do not divide by zero with query-pushdown by checking whether StepMillis
is not zero before using it.
Fixes the following bug:
```
goroutine 6108358 [running]:
runtime/debug.Stack()
/usr/lib/go-1.17/src/runtime/debug/stack.go:24 +0x65
github.com/thanos-io/thanos/pkg/server/grpc.New.func1({0x1a8e700, 0x32500a0})
/home/giedrius/dev/thanos/pkg/server/grpc/grpc.go:70 +0xdb
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.WithRecoveryHandler.func1.1({0x1, 0x10000000040d0e5}, {0x1a8e700, 0x32500a0})
/home/giedrius/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/recovery/options.go:33 +0x2d
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.recoverFrom({0x2160af0, 0xc00119dad0}, {0x1a8e700, …
```
> store: fix division by zero with query-pushdown

- pkg/objstore/cos/cos.go
- pkg/objstore/objstore.go
- pkg/objstore/objstore_test.go
Fix issue reported by @wu3396 (https://github.com/thanos-io/thanos/pull/5139#issuecomment-1040001559 ), pr #5139 introduce multi-part upload, it uses TryToGetSize to get the size of `reader`, but it will error when the reader is wrapped by TimingReadCloser. this pr continue to fix it.
1. Fix `TryToGetSize` error when the reader wrappered by `TimingReadCloser`, It will also fix `cos/s3/bos/swift`  get size error when use `objstore.TryToGetSize(r)`. 
2. Add size info into reader returned by `(*bucket).Get` for pass it to `(*bucket).Upload` function.
1. Implement ObjectSizer interface for timingReadCloser.
2. Add unit test.
1. unit test.
2. use `thanos tool replicate` to reproduce the issue and verify.
> COS: Fix tools replicate

- pkg/exemplars/exemplars.go
Fixes: #5189
Added a nil check for exemplar data
Did not add unit tests, since this is a rather simple method that already has no test
> fix: add null check to exemplar data

- docs/release-process.md
I recently went through the release process and I wanted to suggest a few change to make it a bit clearer, in particular:
- Split the process into few sections (prepare release branch, prepare release, tag etc.)
- Clarify which parts (do not) apply to `rc`s
- Clarify the creation of draft release and that is should happen before the release CI is finished
> Docs: Update release process doc

- go.mod
- go.sum
- test/e2e/e2ethanos/service.go
- test/e2e/e2ethanos/services.go
- test/e2e/exemplars_api_test.go
- test/e2e/query_test.go
- test/e2e/receive_test.go
- test/e2e/rule_test.go
- test/e2e/rules_api_test.go
- test/e2e/store_gateway_test.go
Bumping the `efficientgo/e2e` to the latest `main` - this includes some refactoring changes (no effect on test functionality) and using the new HTTPS readiness probe for `minio`.
Running E2E tests
> E2E Tests: Bump `efficientgo/e2e` version

- pkg/info/info.go
- pkg/store/bucket.go
- test/e2e/query_test.go
As a part of https://github.com/thanos-io/thanos/pull/5066, we have detected some data races. One of them is occurring due to concurrent write / read of bucket store's label set, excerpt:
```
12:05:39 store-gw-1: ==================
12:05:39 store-gw-1: WARNING: DATA RACE
12:05:39 store-gw-1: Read at 0x00c0001c2450 by goroutine 36:
12:05:39 store-gw-1: github.com/thanos-io/thanos/pkg/store.(*BucketStore).LabelSet()
12:05:39 store-gw-1: /go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:687 +0x3d
12:05:39 store-gw-1: main.runStore.func6()
12:05:39 store-gw-1: /go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:393 +0x1d8
12:05:39 store-gw-1: github.com/thanos-io/thanos/pkg/info.(*InfoServer).Info()
...
12:05:39 store-gw-1: Previous …
```
> Store: Fix data race in advertised label set in bucket store

- CHANGELOG.md
- cmd/thanos/rule.go
- test/e2e/rule_test.go
Fixes https://cloud-native.slack.com/archives/CK5RSSC10/p1646228262242149
For the stateless ruler mode, we still need to add the `labels` as external labels written to the remote storage.
Tested it locally and updated the E2E test.
> Append ruler labels as external labels when using stateless ruler mode

- CHANGELOG.md
- docs/components/store.md
- pkg/cache/groupcache.go
Add a timeout for groupcache's fetch operation. It is useful when there
are network errors - if loading from a peer fails then we still might
have a chance to be able to load data from remote object storage
ourselves.
Added creation of a new context with the specified deadline if it is not zero.
N/A
> cache: add timeout for groupcache's fetch operation

- CHANGELOG.md
- cmd/thanos/downsample.go
- cmd/thanos/tools_bucket.go
- docs/components/tools.md
Fixes #5074 
This makes the downsample tool run continuously and downsamples every 5m (configurable via flag).
> Run downsample tool continuously

- pkg/tls/options.go
Update TLS Min Version for Server - use TLS1.3 - better security support
> Change Server TLS Min Version to 1.3

- CHANGELOG.md
- pkg/receive/hashring.go
I removed the sort on labels before hashinf them when using an hashring. The Prometheus [remote write specification](https://docs.google.com/document/d/1LPhVRSFkGNSuU1fBd81ulhsCPR4hkSZyyBj1SZ8fWOM/edit#heading=h.3he8womg60lm) stand that:
> MUST have label names sorted in lexicographical order
So I'm wondering if it's necessary to keep the sort on the receive side tor Thanos infrastructure with two "router only" receivers. I've done a pprof and I see that the sort code is using around 8% of CPU time, so it could be a significant optimization if we can skip it:
We are using the patched version for some time on our receivers and confirmed a reduction in resource consumption. We didn't see any side-effect.
> receive: remove sort on label hashing

- CHANGELOG.md
- cmd/thanos/query_frontend.go
- docs/components/query-frontend.md
- pkg/queryfrontend/config.go
- pkg/queryfrontend/labels_codec.go
- pkg/queryfrontend/queryrange_codec.go
- pkg/queryfrontend/request.go
- pkg/queryfrontend/roundtrip.go
Add `--query-frontend.forward-header` flag to  support headers forward from  query-frontend  to downstream querier 
Tested it locally
> query-frontend: support forward-header to downstream querier

- CHANGELOG.md
- cmd/thanos/tools_bucket.go
Fixes #5228. Ignores deletion markers.
> ignore blocks with deletion markers

- Makefile
Currently the Makefile does not properly detect arm64 architecture
through uname -m. It assumes that all arm64 CPUs will be detected
as armv8.
This improves the detection by handling arm64 as a separate case.
Signed-off-by: fpetkovski <filip.petkovsky@gmail.com>
* Improve detection of `arm64` architecture in Makefile
* Use tabs instead of spaces in Makefile
Ran make commands locally.
> makefile: Fix Makefile support for arm64

- CHANGELOG.md
- cmd/thanos/rule.go
When running the Thanos ruler in stateless mode, the WAL directory that is passed to the agent is not constructed correctly. See this output when starting ruler:
```
level=info ts=2022-03-17T12:40:21.537774846Z caller=db.go:306 msg="replaying WAL, this may take a while" dir=/var/thanos/rule/wal/wal
level=info ts=2022-03-17T12:40:21.537966759Z caller=db.go:357 msg="WAL segment loaded" segment=0 maxSegment=0
```
Notice the `dir` key in the log line, which contains extra sub-directory, ending in `wal/wal`. 
The suggested fix is to provide the 'base' data directory instead of WAL directory, since the full WAL path is built by the agent.
We are also presuming this might have cause us seeing some gaps in data, since stateless ruler could not …
> Ruler: Fix WAL directory in stateless mode

- cmd/thanos/rule.go
- pkg/alert/alert.go
- pkg/alert/alert_test.go
Switch to prometheus struct `notifier.Alert` instead of maintaining the same `alert.Alert` in Thanos.
> Switch to prometheus notifier.Alert

- CHANGELOG.md
- cmd/thanos/query.go
- docs/components/query.md
Let's follow https://github.com/prometheus/prometheus/pull/10121 and
make these into stable features as well.
> query: promote negative offset and at-modifier to stable

- pkg/tracing/grpc.go
There's an extra line to print which was used for debugging and forgotten in https://github.com/thanos-io/thanos/pull/4838, now spams logs. Removing.
/
> Tracing: Remove forgotten debug line

- test/e2e/compact_test.go
Fix the compact test's flakiness by running this sub-test sequentially. The
further steps depend on this test's results so it's wrong to run it as a
sub-test.
I ran the test locally and couldn't reproduce the error anymore.
> e2e: fix compact test's flakiness

- CHANGELOG.md
- cmd/thanos/query.go
- cmd/thanos/receive.go
- cmd/thanos/rule.go
- cmd/thanos/sidecar.go
- cmd/thanos/store.go
- pkg/prober/http.go
- pkg/prober/http_test.go
Store only returns store info when its status is ready.
This is helpful in our scenario:
When a prometheus itself is down (due to storage error), the pod readiness check failed and the endpoint got removed from the service. However, because of our CNI solution, the IPVS service backend will remain for 10m(same as the pod terminationGraceSeconds) so that the Thanos Query can still connect to the sidecar for 10m, producing a lot of Query partial errors.
Once the sidecar detects that Prometheus is down, it should let the Query know that it is not available for serving any requests because it is not ready. Same for other stores.
> info: Return store info only when the service is ready

- pkg/objstore/objstore.go
- pkg/objstore/objstore_test.go
Change error cleanup in `objstore.DownloadDir` to delete files not directories: 
`dst` is always a directory. If any file after the first fails to download, the cleanup will fail because the destination already contains at least one file. This PR changes the cleanup logic to clean up successfully downloaded files one by one instead of attempting to clean up the whole dst directory.
This PR does not account for the case where there are nested directories. While we can do `os.RemoveAll` on any child directories, it's unsafe. We don't know for sure that all files in child directories were downloaded as a result of _this_ `DownloadDir` call and didn't exist before it.
> Change error cleanup in `objstore.DownloadDir` to delete files not destination dir

- pkg/discovery/dns/miekgdns/resolver.go
A mimir user reported in https://github.com/grafana/mimir/issues/1654 that since when Thanos switched memcached client from `golang` to `miekgdns`, the memcached client doesn't resolve CNAME anymore. I manually tried to switch back to `golang` and it resolves the issue.
In this PR I propose to fix `miekgdns` to recursively resolve CNAME until we get A/AAAA records (with a limit to max recursion to avoid infinite loops).
Thoughts?
Manually tested.
> Fix miekgdns resolver to work with CNAME records too

- .mdox.validate.yaml
- MAINTAINERS.md
- docs/release-process.md
- tutorials/katacoda/thanos/3-receiver/intro.md
This PR fixes the URLs for several links in the docs that are currently breaking CI.
I noticed that CI was failing [0] for PR
https://github.com/thanos-io/thanos/pull/5284 because Ian had changed
his GitHub handle from @ianbillett to @bill3tt. This PR  fixes this.
Currently, documentation generation is failing because mdox can't fetch
some GitHub documentation pages since the URLs for the help content has
changed. This commit updates the links to use the correct URLs.
[0] https://github.com/thanos-io/thanos/runs/6050355497?check_suite_focus=true#step:5:135
> docs: fix URLs preventing generation and unblock CI

- .promu.yml
- CHANGELOG.md
- Makefile
- scripts/installprotoc.sh
This is not a change content-wise, but added further functionality by providing docker images for ppc64le CPU architecture
This is relevant for the users that rely / work on ppc64le infrastructure
Checked make crossbuild, docker and docker-multi-stage
> Added support for ppc64le

- go.mod
- pkg/targets/prometheus_test.go
- pkg/targets/proxy_test.go
- pkg/targets/targets.go
> Revert "Added target API tests (+goleak)."
